/* ============================================================
   ui/crumbs.tsx: the trail across the top of a page.

   Server-rendered, from a trail the route hands it.

   ---- what this replaces, and why it was wrong ----

   `aab/src/crumbs.ts` builds the same row in the browser, after
   hydration, by reading `location.pathname` and `document.title`
   and guessing. It has to guess three things and it gets one of
   them wrong on the course pages:

     WHERE TO PUT IT. It mounts into `main > .wrap`, or into
     `main` if there is no wrap. The course shell is
     `<main class="course">` with no wrap, so the trail lands
     directly in `main`, which has no inset, and sits hard against
     the left edge of the window while every other line on the
     page starts at the content column. That is the misalignment
     in the screenshots.

     WHAT THE PAGE IS CALLED. It takes `document.title` and
     removes the site name. It used to split on U+2014, a
     character this site's own rules guarantee never appears, so
     for a while every crumb read "Course syllabus · Reiad's
     Library".

     WHERE THE PAGE SITS. It matches path segments against a
     table, so a route that moves needs an edit in a module it
     does not import.

   A route knows all three without guessing. It knows its own
   section, its own title and its own parent, so the trail is a
   prop and the row is inside the layout that everything else on
   the page is inside.

   ---- it is a nav, and the last crumb is not a link ----

   `aria-label` names it, `aria-current="page"` marks where you
   are, and the separator is generated by CSS so a screen reader
   reads the words and not a row of chevrons. `.crumbs` is the
   stylesheet's and stays: `aab/crumbs.js` still draws this row on
   the two pages that are files and cannot be routes, and two
   looks for one thing is the drift this library exists to stop.
   ============================================================ */

import type { ReactNode } from "react";

export interface Crumb {
  /** Absent for the page you are on, which is not a link. */
  href?: string;
  label: ReactNode;
}

export function Crumbs({ trail, label = "Breadcrumb" }: {
  trail: Crumb[];
  /** "পথ" on a Bangla page. */
  label?: string;
}) {
  if (trail.length < 2) return null;   // a trail of one is noise

  return (
    <nav className="crumbs" aria-label={label}>
      <ol>
        {trail.map((c, i) => {
          const last = i === trail.length - 1;
          return (
            <li key={typeof c.href === "string" ? c.href : `here-${i}`}
                aria-current={last ? "page" : undefined}>
              {c.href && !last ? <a href={c.href}>{c.label}</a> : <span>{c.label}</span>}
            </li>
          );
        })}
      </ol>
    </nav>
  );
}
