/* GENERATED by scripts/build-school-tree.mjs. Do not edit.

   The four ladders one level deep, out of content/schools.backup.json,
   for the header's tree. Half this site's routes are prerendered with
   no D1 binding, so the menu cannot ask the database for this without
   being two levels deep on some pages and one on the others.

   Refresh it with the snapshot:

     npx wrangler d1 export reiad --remote --output schools.db
     node scripts/export-schools.mjs --db schools.db
     node scripts/build-school-tree.mjs

   scripts/check-next.mjs fails if this file and the snapshot disagree. */

export interface TreeStage {
  slug: string;
  /** The stage's own name, as its hub shows it. */
  label: string;
  /** "Stufe 2", "ধাপ ৩": the short form, where the stage has one. */
  kicker?: string;
  /** How many pages are inside. */
  lessons: number;
}

export const SCHOOL_STAGES: Record<string, TreeStage[]> = {
  money: [
    { slug: "start", label: "হাতেখড়ি", kicker: "ধাপ ০", lessons: 8 },
    { slug: "basics-1", label: "শব্দগুলো শিখুন", kicker: "ভিত্তি · ধাপ ১", lessons: 18 },
    { slug: "basics-2", label: "বাজারটা পড়তে শিখুন", kicker: "ভিত্তি · ধাপ ২", lessons: 21 },
    { slug: "basics-3", label: "নিজে যাচাই করুন", kicker: "ভিত্তি · ধাপ ৩", lessons: 13 },
  ],
  deutsch: [
    { slug: "stufe-1", label: "একদম শুরু থেকে", kicker: "Stufe 1", lessons: 14 },
    { slug: "stufe-2", label: "সেতু গড়া", kicker: "Stufe 2", lessons: 14 },
    { slug: "stufe-3", label: "নদীটা খুঁজে পাওয়া", kicker: "Stufe 3", lessons: 14 },
    { slug: "stufe-4", label: "সূক্ষ্ম সুর", kicker: "Stufe 4", lessons: 14 },
  ],
  quran: [
    { slug: "dhap-1", label: "ভিত্তি", kicker: "ধাপ ১", lessons: 10 },
    { slug: "dhap-2", label: "শব্দ থেকে বাক্য", kicker: "ধাপ ২", lessons: 20 },
    { slug: "dhap-3", label: "বাক্য থেকে সূরা", kicker: "ধাপ ৩", lessons: 28 },
  ],
  english: [
    { slug: "term-1", label: "শুরু থেকে", kicker: "টার্ম ১", lessons: 13 },
    { slug: "term-2", label: "ভাব বহন", kicker: "টার্ম ২", lessons: 17 },
  ],
};
