/* ============================================================
   curriculum.js — the whole Learn tree, in one file.

   THIS IS THE ONE FILE YOU EDIT to add, rename or reorder
   anything in the Learn area. Everything else reads from it:

     /learn/index.html + hub.js   the ladder, the contents index,
                                  the resume card, the progress rings
     /learn/<stage>/index.html    generated by build-lessons.mjs
     /learn/<stage>/<lesson>.html generated by build-lessons.mjs
     /crumbs.js                   the breadcrumb trail on every page
     /content.js                  the Ctrl+K palette and the menu
     /build-meta.mjs              sitemap.xml

   ------------------------------------------------------------
   THE SHAPE

   SCHOOLS[]                a school is a subject area with its own
                            front page. Today there is one — money.
                            German, Arabic, English, cooking and the
                            rest become school #2 at their own mount
                            point, using this same code unchanged.

     .stages[]              the ladder a reader climbs. Numbered,
                            collapsible, tracked.

       .sections[]          a heading inside a stage. Never a page
                            of its own — just a grouping.

         .lessons[]         one page each.

   ------------------------------------------------------------
   LESSON URLs

   A lesson's URL is `${stage.base}${lesson.slug}.html`, where
   `base` defaults to `/learn/${stage.slug}/`. Stage `basics-1`
   overrides it to `/learn/terms/` because those eighteen pages
   were published there first and links to them exist in the wild.
   Nothing about a URL that already works is allowed to change.

   ------------------------------------------------------------
   FIELDS

   stage   slug     folder name, and the id progress is stored under
           bn/en    the name, Bangla first — matches the term cards
           kicker   the tiny label above the name ("ধাপ ২")
           icon     a key in /learn/icons.js
           who      who this stage is for, in one line
           blurb    what it teaches, two lines at most
           needs    what you should have read first (stage slugs)
           status   "live" | "soon" — "soon" stages are visible and
                    browsable, their unwritten lessons say আসছে

   lesson  slug     file name (no .html)
           bn/en    the title
           blurb    the one line on the card
           minutes  reading time
           risk     "low" | "mid" | "high" — starter steps only
           status   "live" | "soon"
   ============================================================ */

/* ------------------------------------------------------------
   STAGE 0 — হাতেখড়ি
   The steps live inline on /learn/index.html rather than on pages
   of their own: someone who has never invested should not have to
   navigate anywhere to be told what to do first. The ids below are
   the accordion ids on that page, and what progress is stored under.
   ------------------------------------------------------------ */
const STARTER_STEPS = [
  {
    slug: "money-first",
    bn: "টাকাটা আগে ঠিক করুন",
    en: "Get your money ready first",
    blurb: "বিনিয়োগ শুরুর আগে যে তিনটা জিনিস ঠিক থাকতে হয় — জরুরি তহবিল, ধার, আর কত টাকা আটকে রাখতে পারবেন।",
    minutes: 6,
    risk: "low",
    icon: "wallet",
  },
  {
    slug: "papers",
    bn: "কাগজপত্র গুছিয়ে নিন",
    en: "Get your papers in order",
    blurb: "এনআইডি, টিআইএন, ব্যাংক অ্যাকাউন্ট, ছবি, নমিনি — একবার গুছিয়ে রাখলে বাকি সব ধাপ দ্রুত হয়।",
    minutes: 5,
    risk: "low",
    icon: "id",
  },
  {
    slug: "safest-first",
    bn: "সবচেয়ে নিরাপদটা দিয়ে শুরু",
    en: "Start with the safest thing",
    blurb: "ডিপিএস, সঞ্চয়পত্র, এফডিআর — শেয়ার ছোঁয়ার আগেই যেগুলোতে হাত পাকানো যায়।",
    minutes: 7,
    risk: "low",
    icon: "shield",
  },
  {
    slug: "bo-account",
    bn: "বিও অ্যাকাউন্ট খুলুন",
    en: "Open a BO account",
    blurb: "শেয়ারবাজারে ঢোকার দরজা। ব্রোকার কীভাবে বাছবেন, খরচ কত, আর কোন কাজটা ওরাই করে দেবে।",
    minutes: 8,
    risk: "low",
    icon: "door",
  },
  {
    slug: "first-buy",
    bn: "প্রথম কেনাকাটা",
    en: "Your first purchase",
    blurb: "প্রথমেই একক শেয়ার না — কেন মিউচুয়াল ফান্ড দিয়ে শুরু করা বুদ্ধিমানের কাজ, আর অর্ডারটা আসলে কীভাবে দেয়।",
    minutes: 9,
    risk: "mid",
    icon: "cart",
  },
  {
    slug: "make-a-rule",
    bn: "নিয়ম বানান, তারপর ধৈর্য",
    en: "Make a rule, then wait",
    blurb: "প্রতি মাসে একই দিনে একই টাকা। কখন হিসাব দেখবেন, আর কখন দেখবেন না।",
    minutes: 6,
    risk: "low",
    icon: "calendar",
  },
  {
    slug: "dont-get-cheated",
    bn: "ঠকবেন না",
    en: "Don't get cheated",
    blurb: "গ্যারান্টেড রিটার্ন, ফেসবুকের টিপস, অনিবন্ধিত স্কিম — বাংলাদেশে যেভাবে মানুষ টাকা হারায়।",
    minutes: 8,
    risk: "high",
    icon: "warning",
  },
  {
    slug: "where-next",
    bn: "এরপর কোথায়",
    en: "Where to go next",
    blurb: "হাতেখড়ি শেষ। এখন শব্দগুলো শিখে নেওয়ার পালা — আর সেটা কোথা থেকে।",
    minutes: 3,
    risk: "low",
    icon: "signpost",
  },
];

/* ------------------------------------------------------------
   THE LADDER
   ------------------------------------------------------------ */
const MONEY_STAGES = [
  {
    slug: "start",
    kicker: "ধাপ ০",
    bn: "হাতেখড়ি",
    en: "Starter Guide",
    icon: "seed",
    inline: true, // the steps live on /learn/ itself, not on their own pages
    who: "যিনি কখনো বিনিয়োগ করেননি, এবং কোথা থেকে ধরবেন বুঝতে পারছেন না",
    blurb:
      "আট ধাপে বাংলাদেশে বিনিয়োগ শুরু করার পুরো পথ — কোন কাজটা আপনার, কোনটা অন্যরা করে দেবে, আর কোন ধাপে ঝুঁকি কতটা।",
    needs: [],
    status: "live",
    sections: [
      {
        id: "steps",
        bn: "আটটা ধাপ",
        en: "The eight steps",
        lessons: STARTER_STEPS.map((s) => ({ ...s, status: "live" })),
      },
    ],
  },

  {
    slug: "basics-1",
    kicker: "ভিত্তি · ধাপ ১",
    bn: "শব্দগুলো শিখুন",
    en: "Basics: Stage 1",
    icon: "book",
    base: "/learn/terms/", // published here first; the URLs stay
    who: "হাতেখড়ি শেষ, এখন কথাগুলোর মানে জানা দরকার",
    blurb:
      "বাজারের আঠারোটা শব্দ, প্রতিটার আলাদা ছোট লেখা — বন্ধুকে বোঝানোর ভঙ্গিতে। একটার ভেতরে আরেকটার লিংক।",
    needs: ["start"],
    status: "live",
    sections: [
      {
        id: "basics",
        bn: "বাজারের মূল কথা",
        en: "Market basics",
        lessons: [
          { slug: "share", bn: "শেয়ার", en: "Share / Stock", minutes: 3,
            blurb: "কোম্পানির মালিকানার ছোট্ট একটা টুকরা — শেয়ার কিনলে আপনি ওই ব্যবসার আংশিক মালিক।" },
          { slug: "dse", bn: "ঢাকা স্টক এক্সচেঞ্জ", en: "DSE", minutes: 3,
            blurb: "বাংলাদেশের সবচেয়ে বড় শেয়ারবাজার — যেখানে ক্রেতা আর বিক্রেতার অর্ডার মিলিয়ে দেওয়া হয়।" },
          { slug: "dsex", bn: "সূচক", en: "Index / DSEX", minutes: 3,
            blurb: "পুরো বাজারের হালচাল এক নম্বরে — DSEX বাড়লে বোঝায় বড় কোম্পানিগুলোর দাম মোটের ওপর বেড়েছে।" },
          { slug: "bo-account", bn: "বিও অ্যাকাউন্ট", en: "BO Account", minutes: 3,
            blurb: "শেয়ারবাজারে ঢোকার টিকিট — আপনার শেয়ার ইলেকট্রনিকভাবে জমা থাকে এই অ্যাকাউন্টে।" },
          { slug: "broker", bn: "ব্রোকার", en: "Broker", minutes: 3,
            blurb: "আপনার আর শেয়ারবাজারের মাঝখানের লাইসেন্সধারী মধ্যস্থতাকারী — অর্ডার যায় এদের মাধ্যমে।" },
          { slug: "ipo", bn: "আইপিও", en: "IPO", minutes: 3,
            blurb: "কোনো কোম্পানি প্রথমবারের মতো সাধারণ মানুষের কাছে শেয়ার বেচে বাজারে তালিকাভুক্ত হওয়া।" },
        ],
      },
      {
        id: "instruments",
        bn: "বিনিয়োগের মাধ্যম",
        en: "Ways to invest",
        lessons: [
          { slug: "mutual-fund", bn: "মিউচুয়াল ফান্ড", en: "Mutual Fund", minutes: 3,
            blurb: "অনেকের টাকা এক করে পেশাদার ম্যানেজারের হাতে বিনিয়োগ — ছোট টাকায় বড় পোর্টফোলিওর স্বাদ।" },
          { slug: "sanchayapatra", bn: "সঞ্চয়পত্র", en: "Savings Certificate", minutes: 3,
            blurb: "সরকারের কাছে টাকা ধার দেওয়া — বাংলাদেশের সবচেয়ে জনপ্রিয় নিরাপদ সঞ্চয়ের মাধ্যম।" },
          { slug: "bond", bn: "বন্ড", en: "Bond", minutes: 3,
            blurb: "কোম্পানি বা সরকারকে ধার দেওয়ার দলিল — মালিকানা না, পাওনাদারি।" },
          { slug: "fdr", bn: "এফডিআর", en: "Fixed Deposit (FDR)", minutes: 3,
            blurb: "ব্যাংকে নির্দিষ্ট মেয়াদে টাকা রেখে নির্দিষ্ট হারে মুনাফা — সহজ, পরিচিত, কিন্তু সীমিত।" },
        ],
      },
      {
        id: "analysis",
        bn: "কোম্পানি বিশ্লেষণ",
        en: "Company analysis",
        lessons: [
          { slug: "dividend", bn: "ডিভিডেন্ড", en: "Dividend", minutes: 3,
            blurb: "কোম্পানির লাভ থেকে শেয়ারহোল্ডারদের দেওয়া ভাগ — নগদ টাকায় বা বোনাস শেয়ারে।" },
          { slug: "eps", bn: "ইপিএস", en: "EPS", minutes: 3,
            blurb: "প্রতি শেয়ারে কোম্পানির আয় — কোম্পানির লাভকে শেয়ার সংখ্যা দিয়ে ভাগ করলে যা পাওয়া যায়।" },
          { slug: "pe-ratio", bn: "পিই রেশিও", en: "P/E Ratio", minutes: 3,
            blurb: "শেয়ারের দাম তার আয়ের কত গুণ — দামটা সস্তা না চড়া, তার প্রথম আন্দাজ।" },
          { slug: "nav", bn: "এনএভি", en: "NAV", minutes: 3,
            blurb: "ফান্ড বা কোম্পানির সম্পদ থেকে দায় বাদ দিলে প্রতি ইউনিটে যা থাকে — 'আসল' মূল্যের হিসাব।" },
        ],
      },
      {
        id: "risk",
        bn: "ঝুঁকি ও কৌশল",
        en: "Risk & strategy",
        lessons: [
          { slug: "risk-return", bn: "ঝুঁকি ও রিটার্ন", en: "Risk & Return", minutes: 3,
            blurb: "বেশি লাভের আশা মানেই বেশি লসের সম্ভাবনা — বিনিয়োগের সবচেয়ে সৎ নিয়ম।" },
          { slug: "diversification", bn: "ডাইভারসিফিকেশন", en: "Diversification", minutes: 3,
            blurb: "সব ডিম এক ঝুড়িতে না রাখা — এক জায়গার লস যেন অন্য জায়গার লাভে সামাল দেওয়া যায়।" },
          { slug: "inflation", bn: "মূল্যস্ফীতি", en: "Inflation", minutes: 3,
            blurb: "টাকার নীরব ক্ষয় — অঙ্ক একই থাকলেও কেনার ক্ষমতা প্রতি বছর একটু করে কমে।" },
          { slug: "compounding", bn: "চক্রবৃদ্ধি", en: "Compounding", minutes: 3,
            blurb: "মুনাফার ওপর মুনাফা — সময় যত লম্বা, টাকার বাড়া তত দ্রুত। ধৈর্যের পুরস্কার।" },
        ],
      },
    ],
  },

  {
    slug: "basics-2",
    kicker: "ভিত্তি · ধাপ ২",
    bn: "বাজারটা পড়তে শিখুন",
    en: "Basics: Stage 2",
    icon: "compass",
    who: "শব্দগুলো জানা হয়ে গেছে, এখন বাজারটা কীভাবে চলে বুঝতে চান",
    blurb:
      "দাম কেন ওঠানামা করে, কখন কিনবেন-বেচবেন-ধরে রাখবেন, কোন খাত কী, কারা নিয়ন্ত্রণ করে, আর লাইভ অ্যাপে কী দেখবেন।",
    needs: ["basics-1"],
    status: "live",
    sections: [
      {
        id: "why-move",
        bn: "বাজার কেন ওঠানামা করে",
        en: "Why markets move",
        lessons: [
          { slug: "supply-demand", bn: "চাহিদা আর জোগান", en: "Supply & demand", minutes: 6,
            blurb: "দাম আসলে একটাই জিনিসে ঠিক হয় — এই মুহূর্তে কে কত দিতে রাজি আর কে কত নিতে রাজি।" },
          { slug: "news-and-price", bn: "খবর কীভাবে দামে ঢোকে", en: "How news gets into the price", minutes: 7,
            blurb: "ভালো খবরেও দাম পড়তে পারে। কারণ বাজার খবরটা নয়, খবরটা কতটা আশা করা হয়েছিল সেটা কেনে।" },
          { slug: "interest-and-taka", bn: "সুদের হার আর টাকার মান", en: "Interest rates & the taka", minutes: 8,
            blurb: "বাংলাদেশ ব্যাংক সুদ বাড়ালে শেয়ারবাজারে কী হয়, আর ডলারের দাম বাড়লে কোন কোম্পানি চাপে পড়ে।" },
          { slug: "war-and-shocks", bn: "যুদ্ধ, দুর্যোগ আর বড় ধাক্কা", en: "War, disaster & big shocks", minutes: 8,
            blurb: "দূরের একটা যুদ্ধ কীভাবে চট্টগ্রাম বন্দর হয়ে আপনার পোর্টফোলিওতে পৌঁছায়।" },
          { slug: "crowd-behaviour", bn: "ভিড়ের আচরণ", en: "How crowds behave", minutes: 6,
            blurb: "বাবল আর ধস — দুটোই একই জিনিসের দুই পিঠ: সবাই একসাথে একই দিকে দৌড়ানো।" },
        ],
      },
      {
        id: "buy-sell-hold",
        bn: "কখন কিনবেন, কখন বেচবেন",
        en: "Buy, sell or hold",
        lessons: [
          { slug: "when-to-buy", bn: "কেনার আগে যে পাঁচটা প্রশ্ন", en: "Five questions before buying", minutes: 7,
            blurb: "দাম কম দেখলেই কেনা নয়। কেনার আগে নিজেকে যা জিজ্ঞেস করতেই হবে।" },
          { slug: "when-to-sell", bn: "বেচার তিনটা বৈধ কারণ", en: "Three good reasons to sell", minutes: 7,
            blurb: "ভয় পাওয়া এর মধ্যে নেই। বেচার কারণ আগে থেকে লিখে রাখলে হাত কাঁপে না।" },
          { slug: "why-hold", bn: "ধরে রাখাও একটা সিদ্ধান্ত", en: "Holding is a decision too", minutes: 5,
            blurb: "কিছু না করা মানে অলসতা না — কিন্তু সেটা যেন সিদ্ধান্ত হয়, এড়িয়ে যাওয়া না হয়।" },
          { slug: "cost-of-churn", bn: "বারবার কেনাবেচার দাম", en: "What churning costs you", minutes: 6,
            blurb: "কমিশন, স্প্রেড আর ভুলের সময় — ঘন ঘন হাত বদলালে যে তিনটা জায়গায় টাকা গলে।" },
        ],
      },
      {
        id: "what-exists",
        bn: "কী কী কেনা যায়",
        en: "What you can actually buy",
        lessons: [
          { slug: "sectors", bn: "খাত চিনুন", en: "Sectors explained", minutes: 9,
            blurb: "ব্যাংক, বিমা, ওষুধ, বস্ত্র, সিমেন্ট, জ্বালানি, খাদ্য — কোন খাত কীসে ভালো করে, কীসে মার খায়।" },
          { slug: "share-categories", bn: "A, B, N, Z — ক্যাটাগরি", en: "Share categories", minutes: 6,
            blurb: "ডিএসই প্রতিটা শেয়ারকে একটা অক্ষর দেয়। Z মানে কী, আর কেন নতুনদের ওদিকে না যাওয়াই ভালো।" },
          { slug: "commodities", bn: "কমোডিটি — সোনা, তেল, খাদ্যশস্য", en: "Commodities", minutes: 8,
            blurb: "সোনা কেন 'নিরাপদ আশ্রয়', তেলের দাম কাদের ভালো আর কাদের খারাপ করে।" },
          { slug: "complements-substitutes", bn: "পরিপূরক আর বিকল্প", en: "Complements & substitutes", minutes: 7,
            blurb: "চা আর চিনি একসাথে চলে; চা আর কফি একে অন্যকে খায়। এই একটা ধারণা দিয়ে অনেক দাম ব্যাখ্যা করা যায়।" },
        ],
      },
      {
        id: "institutions",
        bn: "কারা কী করে",
        en: "Who runs what",
        lessons: [
          { slug: "bsec", bn: "বিএসইসি — নিয়ন্ত্রক", en: "BSEC, the regulator", minutes: 6,
            blurb: "বাজারের পুলিশ। কী করতে পারে, কী পারে না, আর অভিযোগ করলে কোথায় করবেন।" },
          { slug: "exchanges-cdbl", bn: "ডিএসই, সিএসই আর সিডিবিএল", en: "DSE, CSE & CDBL", minutes: 6,
            blurb: "কেনাবেচা হয় এক জায়গায়, শেয়ার জমা থাকে আরেক জায়গায় — কে কোন কাজটা করে।" },
          { slug: "bangladesh-bank", bn: "বাংলাদেশ ব্যাংক", en: "Bangladesh Bank", minutes: 6,
            blurb: "সুদের হার, টাকার জোগান আর ডলার — কেন্দ্রীয় ব্যাংকের সিদ্ধান্ত সবার আগে বাজারে লাগে।" },
          { slug: "amcs-icb", bn: "অ্যাসেট ম্যানেজার আর আইসিবি", en: "Asset managers & ICB", minutes: 7,
            blurb: "আপনার ফান্ডের টাকা আসলে কারা চালায়, আর আইসিবি বাজারে ঠিক কী ভূমিকা রাখে।" },
          { slug: "choosing-a-broker", bn: "ব্রোকারেজ হাউস বাছাই", en: "Choosing a brokerage", minutes: 8,
            blurb: "কমিশন, অ্যাপের মান, মার্জিন ঋণের চাপ — কোন জিনিসগুলো আসলে দেখা দরকার।" },
        ],
      },
      {
        id: "live-market",
        bn: "লাইভ বাজার দেখা",
        en: "Reading the live market",
        lessons: [
          { slug: "reading-a-quote", bn: "একটা কোট পড়তে শিখুন", en: "How to read a quote", minutes: 8,
            blurb: "LTP, YCP, ভলিউম, সার্কিট — অ্যাপের ওই সংখ্যাগুলোর মানে এক এক করে।" },
          { slug: "apps-and-sites", bn: "কোন অ্যাপ, কোন সাইট", en: "Which apps & sites", minutes: 7,
            blurb: "ডিএসইর নিজের সাইট থেকে ব্রোকারের অ্যাপ — কোনটা কীসের জন্য, আর কোনটায় ভরসা করবেন না।" },
          { slug: "watchlist", bn: "নিজের ওয়াচলিস্ট বানান", en: "Build a watchlist", minutes: 6,
            blurb: "সারাদিন দাম দেখা নয় — সপ্তাহে একবার দেখার মতো একটা ছোট তালিকা কীভাবে বানাবেন।" },
        ],
      },
    ],
  },

  {
    slug: "basics-3",
    kicker: "ভিত্তি · ধাপ ৩",
    bn: "নিজে যাচাই করুন",
    en: "Basics: Stage 3",
    icon: "magnifier",
    who: "যিনি অন্যের কথায় না চলে নিজে একটা শেয়ার বিচার করতে চান",
    blurb:
      "বাংলাদেশে তথ্য কোথায় পাওয়া যায়, রিপোর্ট কীভাবে পড়তে হয়, আর একটা কোম্পানি নিয়ে সৎভাবে সিদ্ধান্তে আসার পদ্ধতি।",
    needs: ["basics-2"],
    status: "live",
    sections: [
      {
        id: "finding-data",
        bn: "তথ্য কোথায়",
        en: "Where the data is",
        lessons: [
          { slug: "dse-website", bn: "ডিএসইর সাইট থেকে যা পাবেন", en: "Mining the DSE website", minutes: 8,
            blurb: "কোম্পানির পাতা, মূল্য-সংবেদনশীল তথ্য, আর্কাইভ — বিনামূল্যে যা যা আছে।" },
          { slug: "annual-report", bn: "বার্ষিক প্রতিবেদন কোথায়, কীভাবে", en: "Finding the annual report", minutes: 7,
            blurb: "কোথায় নামাবেন, আর দুইশো পাতার মধ্যে আসলে কোন পাঁচটা পাতা পড়বেন।" },
          { slug: "official-sources", bn: "সরকারি সূত্র", en: "Official sources", minutes: 7,
            blurb: "বাংলাদেশ ব্যাংক, বিবিএস, এনবিআর — মূল্যস্ফীতি থেকে রপ্তানি, আসল সংখ্যাগুলো যেখানে থাকে।" },
          { slug: "keeping-records", bn: "নিজের খাতা রাখুন", en: "Keep your own records", minutes: 6,
            blurb: "একটা সাধারণ স্প্রেডশিট — কী কিনলেন, কেন কিনলেন, কত দামে। পরে এটাই সবচেয়ে দামি।" },
        ],
      },
      {
        id: "reading-statements",
        bn: "হিসাব পড়া",
        en: "Reading the numbers",
        lessons: [
          { slug: "income-statement", bn: "আয়-ব্যয়ের হিসাব", en: "The income statement", minutes: 9,
            blurb: "উপরে বিক্রি, নিচে লাভ — মাঝখানে যা যা কেটে নেয়, লাইন ধরে ধরে।" },
          { slug: "balance-sheet", bn: "স্থিতিপত্র", en: "The balance sheet", minutes: 9,
            blurb: "কোম্পানির কী আছে, কার কাছে কত দেনা, আর মালিকদের হাতে আসলে কী থাকে।" },
          { slug: "cash-flow", bn: "নগদ প্রবাহ", en: "Cash flow", minutes: 9,
            blurb: "লাভ দেখানো যায়, নগদ দেখানো যায় না। এইজন্যই এই পাতাটা সবচেয়ে সৎ।" },
          { slug: "ratios", bn: "অনুপাত দিয়ে যাচাই", en: "Checking with ratios", minutes: 9,
            blurb: "ROE, ঋণ-মূলধন, চলতি অনুপাত, মার্জিন — অল্প কয়েকটা ভাগ করেই অনেকটা বোঝা যায়।" },
          { slug: "red-flags", bn: "বিপদের চিহ্ন", en: "Red flags", minutes: 8,
            blurb: "নিরীক্ষকের আপত্তি, হঠাৎ পাল্টানো হিসাব-পদ্ধতি, উধাও নগদ — যা দেখলে সরে আসবেন।" },
        ],
      },
      {
        id: "thinking",
        bn: "সিদ্ধান্তে আসা",
        en: "Coming to a decision",
        lessons: [
          { slug: "a-thesis", bn: "নিজের যুক্তি লিখে ফেলুন", en: "Write your thesis down", minutes: 7,
            blurb: "তিন বাক্যে লিখুন কেন কিনছেন আর কী হলে ভুল প্রমাণিত হবেন। এটাই আপনাকে বাঁচাবে।" },
          { slug: "news-vs-rumour", bn: "খবর নাকি গুজব", en: "News or rumour?", minutes: 7,
            blurb: "হোয়াটসঅ্যাপের 'ইনসাইড নিউজ' যাচাই করার তিনটা ধাপ, প্রতিবারই।" },
          { slug: "case-study", bn: "একটা কোম্পানি, শুরু থেকে শেষ", en: "One company, end to end", minutes: 12,
            blurb: "উপরের সবকিছু একসাথে বসিয়ে একটা কাল্পনিক কোম্পানিকে যাচাই করে দেখা।" },
          { slug: "your-own-biases", bn: "নিজের মনের ফাঁদ", en: "Your own biases", minutes: 8,
            blurb: "যে দামে কিনেছেন সেটা আঁকড়ে ধরা, লস মানতে না চাওয়া — সবচেয়ে দামি ভুলগুলো নিজের ভেতরেই।" },
        ],
      },
    ],
  },

  {
    slug: "inter-1",
    kicker: "মাঝারি · ধাপ ১",
    bn: "বিশ্ববিদ্যালয়ের পড়া",
    en: "Intermediate 1 — Coursework",
    icon: "cap",
    who: "ফিন্যান্স, অ্যাকাউন্টিং বা অর্থনীতির স্নাতক শিক্ষার্থী",
    blurb:
      "কোর্সের বিষয়গুলো ধরে ধরে, আর অ্যাসাইনমেন্টের অঙ্ক কীভাবে ধাপে ধাপে দাঁড় করাতে হয়।",
    needs: ["basics-3"],
    status: "soon",
    sections: [
      {
        id: "core-papers",
        bn: "কোর কোর্সগুলো",
        en: "The core papers",
        lessons: [
          { slug: "corporate-finance", bn: "কর্পোরেট ফিন্যান্স", en: "Corporate finance", minutes: 12, status: "soon",
            blurb: "মূলধন কাঠামো, বাজেটিং, লভ্যাংশ নীতি — যা প্রতিটা সিলেবাসে থাকে।" },
          { slug: "valuation", bn: "মূল্যায়ন — DCF ও তুলনা", en: "Valuation: DCF & multiples", minutes: 14, status: "soon",
            blurb: "একটা কোম্পানির দাম বসানোর দুই পদ্ধতি, ধাপে ধাপে।" },
          { slug: "portfolio-theory", bn: "পোর্টফোলিও তত্ত্ব", en: "Portfolio theory", minutes: 12, status: "soon",
            blurb: "ঝুঁকি-রিটার্নের সীমানা, CAPM, বিটা — পরীক্ষায় যেভাবে আসে।" },
          { slug: "econometrics", bn: "ইকোনোমেট্রিক্স হাতেকলমে", en: "Econometrics in practice", minutes: 14, status: "soon",
            blurb: "রিগ্রেশন চালানো এক জিনিস, ফলাফল বিশ্বাস করা আরেক জিনিস।" },
        ],
      },
      {
        id: "solving",
        bn: "সমস্যা সমাধানের পদ্ধতি",
        en: "How to solve a problem",
        lessons: [
          { slug: "problem-method", bn: "যেকোনো অঙ্কের সাত ধাপ", en: "Seven steps for any problem", minutes: 10, status: "soon",
            blurb: "প্রশ্ন পড়ার পর কলম ধরার আগে যা যা করবেন।" },
          { slug: "worked-example", bn: "একটা অ্যাসাইনমেন্ট, পুরোটা", en: "A full worked assignment", minutes: 16, status: "soon",
            blurb: "একটা সত্যিকারের প্রশ্ন, শুরু থেকে জমা দেওয়া পর্যন্ত।" },
          { slug: "excel-for-coursework", bn: "কোর্সওয়ার্কের জন্য এক্সেল", en: "Excel for coursework", minutes: 12, status: "soon",
            blurb: "যে দশটা ফাংশন জানলে বাকি সব সহজ হয়ে যায়।" },
          { slug: "citing", bn: "রেফারেন্স আর নকল এড়ানো", en: "Citing & avoiding plagiarism", minutes: 8, status: "soon",
            blurb: "কোনটা উদ্ধৃতি, কোনটা নকল — সীমানাটা পরিষ্কার করে।" },
        ],
      },
    ],
  },

  {
    slug: "inter-2",
    kicker: "মাঝারি · ধাপ ২",
    bn: "গবেষণা ও অভিসন্দর্ভ",
    en: "Intermediate 2 — Dissertation",
    icon: "scroll",
    who: "যিনি থিসিস বা ডিসার্টেশন লিখছেন, বা লিখবেন",
    blurb:
      "বিষয় বাছাই থেকে জমা দেওয়া — আর স্কলারলি আর্টিকেল পড়ে কাজে লাগানোর অভ্যাস।",
    needs: ["inter-1"],
    status: "soon",
    sections: [
      {
        id: "doing-research",
        bn: "গবেষণা করা",
        en: "Doing the research",
        lessons: [
          { slug: "choosing-a-topic", bn: "বিষয় বাছাই", en: "Choosing a topic", minutes: 10, status: "soon",
            blurb: "যে প্রশ্নের উত্তর আসলে দেওয়া যায় — এবং যেটার ডেটা আছে।" },
          { slug: "literature-review", bn: "সাহিত্য পর্যালোচনা", en: "The literature review", minutes: 12, status: "soon",
            blurb: "পঞ্চাশটা পেপার পড়া নয় — একটা তর্ক দাঁড় করানো।" },
          { slug: "finding-papers", bn: "পেপার খোঁজা ও পড়া", en: "Finding & reading papers", minutes: 10, status: "soon",
            blurb: "কোথায় খুঁজবেন, কীভাবে দ্রুত পড়বেন, কীভাবে নোট রাখবেন।" },
          { slug: "methodology", bn: "পদ্ধতি নির্বাচন", en: "Methodology", minutes: 12, status: "soon",
            blurb: "প্রশ্নটাই ঠিক করে দেয় পদ্ধতি কী হবে — উল্টোটা নয়।" },
          { slug: "bd-data-for-research", bn: "বাংলাদেশের ডেটা নিয়ে কাজ", en: "Working with Bangladeshi data", minutes: 12, status: "soon",
            blurb: "ফাঁক, অসঙ্গতি আর হাতে তোলা সংখ্যা — বাস্তবে যা মোকাবিলা করতে হয়।" },
        ],
      },
      {
        id: "writing-up",
        bn: "লেখা ও জমা",
        en: "Writing it up",
        lessons: [
          { slug: "structure", bn: "কাঠামো", en: "Structure", minutes: 10, status: "soon",
            blurb: "অধ্যায় ধরে ধরে, কোনটায় কী থাকবে।" },
          { slug: "defending", bn: "ভাইভা ও প্রতিরক্ষা", en: "The viva", minutes: 8, status: "soon",
            blurb: "যে প্রশ্নগুলো আসবেই, আর সৎ উত্তর কেমন দেখায়।" },
          { slug: "publishing", bn: "প্রকাশের পথ", en: "Getting published", minutes: 10, status: "soon",
            blurb: "জার্নাল বাছাই, জমা, রিভিউ — আর প্রেডেটরি জার্নাল চেনা।" },
        ],
      },
    ],
  },

  {
    slug: "inter-3",
    kicker: "মাঝারি · ধাপ ৩",
    bn: "চাকরি ও বাস্তব কাজ",
    en: "Intermediate 3 — On the job",
    icon: "briefcase",
    who: "যিনি এই খাতে চাকরি খুঁজছেন বা সবে ঢুকেছেন",
    blurb:
      "বাজারের চাকরিগুলো আসলে কী করে, দিনটা কেমন কাটে, কী দিয়ে যাচাই করা হয়, আর কীভাবে ঢোকা যায়।",
    needs: ["inter-2"],
    status: "soon",
    sections: [
      {
        id: "the-roles",
        bn: "কাজগুলো কী",
        en: "What the jobs are",
        lessons: [
          { slug: "research-analyst", bn: "রিসার্চ অ্যানালিস্ট", en: "Research analyst", minutes: 10, status: "soon",
            blurb: "মডেল, রিপোর্ট, কল — দিনটা আসলে কীভাবে কাটে।" },
          { slug: "credit-risk", bn: "ক্রেডিট ও রিস্ক", en: "Credit & risk", minutes: 10, status: "soon",
            blurb: "ব্যাংকে ঝুঁকি মাপার কাজটা ঠিক কী।" },
          { slug: "treasury", bn: "ট্রেজারি", en: "Treasury", minutes: 10, status: "soon",
            blurb: "টাকা, ডলার আর সুদ — প্রতিষ্ঠানের ভেতর থেকে।" },
          { slug: "asset-management", bn: "অ্যাসেট ম্যানেজমেন্ট", en: "Asset management", minutes: 10, status: "soon",
            blurb: "অন্যের টাকা চালানোর দায়িত্ব কেমন।" },
        ],
      },
      {
        id: "getting-in",
        bn: "ঢোকার পথ",
        en: "Getting in",
        lessons: [
          { slug: "cv-and-interview", bn: "সিভি ও ইন্টারভিউ", en: "CV & interview", minutes: 12, status: "soon",
            blurb: "কী দেখা হয়, আর কোন উত্তরগুলো আসলে কাজ করে।" },
          { slug: "certifications", bn: "সার্টিফিকেশন — কোনটা কাজে লাগে", en: "Which certifications matter", minutes: 10, status: "soon",
            blurb: "CFA, FRM, ACCA — কার জন্য কোনটা, আর কোনটা না।" },
          { slug: "first-90-days", bn: "প্রথম তিন মাস", en: "The first 90 days", minutes: 10, status: "soon",
            blurb: "নতুন হিসেবে কী করবেন, কী করবেন না।" },
        ],
      },
    ],
  },

  {
    slug: "advanced",
    kicker: "সর্বোচ্চ ধাপ",
    bn: "গবেষণা স্তর",
    en: "Advanced — Research level",
    icon: "microscope",
    who: "গবেষক, পিএইচডি শিক্ষার্থী, এবং যিনি নিজেই প্রশ্ন তৈরি করেন",
    blurb:
      "ফ্রন্টিয়ার মার্কেট হিসেবে বাংলাদেশ — সম্পদমূল্যায়ন তত্ত্ব, বাজারের গঠন, আর মৌলিক গবেষণার কাজ।",
    needs: ["inter-3"],
    status: "soon",
    sections: [
      {
        id: "theory",
        bn: "তত্ত্ব",
        en: "Theory",
        lessons: [
          { slug: "asset-pricing", bn: "সম্পদমূল্যায়ন তত্ত্ব", en: "Asset pricing", minutes: 16, status: "soon",
            blurb: "ফ্যাক্টর মডেল থেকে শর্তসাপেক্ষ মূল্যায়ন।" },
          { slug: "market-efficiency", bn: "বাজার দক্ষতা — ফ্রন্টিয়ার প্রেক্ষাপট", en: "Efficiency in frontier markets", minutes: 14, status: "soon",
            blurb: "যে তত্ত্ব উন্নত বাজারের জন্য বানানো, সেটা এখানে কতটা খাটে।" },
          { slug: "microstructure", bn: "বাজারের গঠন", en: "Market microstructure", minutes: 14, status: "soon",
            blurb: "তারল্য, স্প্রেড আর দাম গঠনের প্রক্রিয়া।" },
        ],
      },
      {
        id: "doing-it",
        bn: "কাজটা করা",
        en: "Doing the work",
        lessons: [
          { slug: "research-design", bn: "গবেষণা নকশা", en: "Research design", minutes: 14, status: "soon",
            blurb: "পরিচয়করণ, শনাক্তকরণ কৌশল, আর দৃঢ়তা যাচাই।" },
          { slug: "replication", bn: "পুনরাবৃত্তি ও স্বচ্ছতা", en: "Replication & transparency", minutes: 12, status: "soon",
            blurb: "কোড আর ডেটা এমনভাবে রাখা, যাতে অন্যে যাচাই করতে পারে।" },
          { slug: "islamic-funds", bn: "কেস — ইসলামিক ফান্ডের ঝুঁকি", en: "Case: Islamic fund risk", minutes: 18, status: "soon",
            blurb: "একটা সত্যিকারের গবেষণা, প্রশ্ন থেকে ফলাফল পর্যন্ত।" },
        ],
      },
    ],
  },
];

/* ------------------------------------------------------------
   SCHOOLS
   One today. The second one — German from Bangla, beginner
   English, Quranic Arabic, cooking, daily checklists, travel —
   mounts at its own path and reuses every bit of this file's
   machinery. Nothing below assumes there is only one.
   ------------------------------------------------------------ */
export const SCHOOLS = [
  {
    id: "money",
    mount: "/learn/",
    bn: "টাকার পাঠশালা",
    en: "Money & markets",
    tagline: "বাংলাদেশে বিনিয়োগ — একদম শুরু থেকে গবেষণা পর্যন্ত",
    stages: MONEY_STAGES,
  },
];

/** The school a path belongs to (defaults to the first). */
export const schoolFor = (path = "/learn/") =>
  SCHOOLS.find((s) => path.startsWith(s.mount)) ?? SCHOOLS[0];

/** Every stage of the money school, in ladder order. */
export const STAGES = MONEY_STAGES;

/** A stage's folder URL. */
export const stageUrl = (stage) => `/learn/${stage.slug}/index.html`;

/** Where a stage's lessons live — `base` wins, so basics-1 keeps /learn/terms/. */
export const lessonBase = (stage) => stage.base ?? `/learn/${stage.slug}/`;

/** A lesson's URL. Inline stages (the starter guide) are hub anchors. */
export const lessonUrl = (stage, lesson) =>
  stage.inline
    ? `/learn/index.html#step-${lesson.slug}`
    : `${lessonBase(stage)}${lesson.slug}.html`;

/** Progress is stored per lesson under a stable id. */
export const lessonId = (stage, lesson) =>
  stage.slug === "basics-1" ? lesson.slug : `${stage.slug}/${lesson.slug}`;

/** Flat list of every lesson, with its stage and section attached. */
export const allLessons = () =>
  STAGES.flatMap((stage) =>
    stage.sections.flatMap((section) =>
      section.lessons.map((lesson) => ({
        ...lesson,
        stage,
        section,
        id: lessonId(stage, lesson),
        url: lessonUrl(stage, lesson),
        status: lesson.status ?? "live",
      }))
    )
  );

/** Lessons of one stage, flattened, in order. */
export const stageLessons = (stage) =>
  stage.sections.flatMap((section) =>
    section.lessons.map((lesson) => ({
      ...lesson,
      stage,
      section,
      id: lessonId(stage, lesson),
      url: lessonUrl(stage, lesson),
      status: lesson.status ?? "live",
    }))
  );

/** How many lessons a stage has, and how many are written. */
export const stageCount = (stage) => {
  const lessons = stageLessons(stage);
  return { total: lessons.length, live: lessons.filter((l) => l.status === "live").length };
};

/** Total reading time of a stage, in minutes. */
export const stageMinutes = (stage) =>
  stageLessons(stage).reduce((sum, l) => sum + (l.minutes ?? 0), 0);

/** Find a stage by slug. */
export const findStage = (slug) => STAGES.find((s) => s.slug === slug);

/** Find a lesson (and its stage) from a URL path. */
export const findByPath = (path) =>
  allLessons().find((l) => l.url === path || l.url === `${path}.html`);
