/* ============================================================
   courses.ts: the third-party course catalogue. Not this site's
   own writing: somebody else's material in a private Drive
   folder, and what this repository holds is a CATALOGUE of it,
   with no prose, no video and no copy of anything.

   NOTHING UNDER `next/` MAY IMPORT THE VALUE HALF OF THIS FILE.
   A page importing `COURSES` puts the whole admin-only catalogue
   into a bundle anybody can fetch, whatever the page then draws.
   `scripts/check-courses.ts` fails on such an import. `import
   type` is fine: TypeScript erases it before bundling. The
   catalogue reaches the browser one way, through `/api/courses`
   behind `isAdmin()`.

   `courses.data.json` beside this file is GENERATED by
   `scripts/import-courses.ts` out of the Drive folder. Do not
   edit it by hand.
   ============================================================ */

import data from "./courses.data.json" with { type: "json" };

/* ---------- what a catalogue is made of ---------- */

/** A file that hangs off a lesson: a template, a dataset, a
    slide deck. Not the lesson itself. */
export interface CourseFile {
  name: string;
  /** The extension, lower case, which is all the chip says. */
  ext: string;
  drive: string;
}

export type LessonKind = "video" | "reading" | "quiz" | "exam" | "file";

export interface CourseLesson {
  slug: string;
  title: string;
  kind: LessonKind;
  /** Which group of the module this came from. A heading in the
      sidebar, NEVER part of an address: a lesson that moves
      between groups keeps its id and its tick. */
  section: string;
  /** Where it sits in the module, counted across all groups. */
  position: number;
  /** The Drive id of the video, when there is one. */
  video?: string;
  reading?: string;
  quiz?: string;
  exam?: string;
  /** The `.en.txt`: prose, offered as a link, for reading rather
      than watching. */
  transcript?: string;
  /** The `.en.srt`: the same words with timings, which is what a
      <track> needs. Served as WebVTT, because no browser reads
      SubRip. Two files and two jobs. */
  captions?: string;
  files?: CourseFile[];
}

export interface CourseModule {
  slug: string;
  n: number;
  title: string;
  drive: string;
  lessons: CourseLesson[];
  /** No lessons yet: the Drive folder is empty or the import has
      not reached it. Said out loud, because a module missing from
      a ladder looks like a course with fewer weeks. */
  pending?: boolean;
}

export interface Course {
  slug: string;
  n: number;
  title: string;
  drive: string;
  modules: CourseModule[];
}

/** A certificate, a specialisation, a bundle: one folder holding
    a run of courses meant to be taken in order. It holds no file
    of its own, so `drive` is recorded rather than fetched. */
export interface Programme {
  slug: string;
  n: number;
  title: string;
  drive: string;
  courses: Course[];
}

export interface Catalogue {
  root: string;
  source: string;
  programmes: Programme[];
}

/** A lesson with everything the page needs to draw it. */
export interface LadderLesson extends CourseLesson {
  module: string;
  moduleTitle: string;
  id: string;
  url: string;
}

/* ---------- the catalogue ---------- */

export const CATALOGUE = data as unknown as Catalogue;
export const PROGRAMMES: Programme[] = CATALOGUE.programmes;

/** Every course of every programme, flat, for the things that do
    not care which programme a course is in. Derived rather than
    stored: a second list is a second thing to keep in step. */
export const COURSES: Course[] = PROGRAMMES.flatMap((p) => p.courses);

export const programmeOf = (slug: string): Programme | null =>
  PROGRAMMES.find((p) => p.slug === slug) ?? null;

/** A course inside a programme. Scoped to one, because two
    programmes may each hold a "Foundations". */
export const courseOf = (programme: Programme, slug: string): Course | null =>
  programme.courses.find((c) => c.slug === slug) ?? null;

/** The programme a course belongs to, for anything walking
    `COURSES` that needs an address back. NULL IS NOT AN ORDINARY
    ANSWER: it means the flat list and the tree have parted
    company. */
export const programmeFor = (course: Course): Programme | null =>
  PROGRAMMES.find((p) => p.courses.includes(course)) ?? null;

export const moduleOf = (course: Course, slug: string): CourseModule | null =>
  course.modules.find((m) => m.slug === slug) ?? null;

/* THE `.html` STRIP STAYS. This section is the one place on the
   site where an old address is TOLERATED rather than redirected:
   845 generated addresses would mean 845 rules in `_redirects`,
   regenerated every time the Drive folder changed. It costs
   nothing here, because the whole section is behind `isAdmin()`
   and `unlisted` in `shared/nav.ts`: no crawler reaches it,
   nothing links to it, and there is no canonical to split. */
export const lessonOf = (
  mod: CourseModule, slug: string
): CourseLesson | null =>
  mod.lessons.find((l) => l.slug === slug.replace(/\.html$/i, "")) ?? null;

/* ---------- where a thing lives ----------

   One function each, and everything else calls them rather than
   building a path: the sidebar, the route, the "mark complete and
   continue" button and the checks all have to agree. */

export const programmeUrl = (programme: string): string =>
  `/skills/courses/${programme}`;

export const courseUrl = (programme: string, course: string): string =>
  `/skills/courses/${programme}/${course}`;

export const moduleUrl = (programme: string, course: string, mod: string): string =>
  `/skills/courses/${programme}/${course}/${mod}`;

export const lessonUrl = (
  programme: string, course: string, mod: string, lesson: string,
): string =>
  `/skills/courses/${programme}/${course}/${mod}/${lesson}`;

/** What a tick is filed under. All three parts, because a slug
    is only unique inside its module. THE ID GOES INTO
    `courses-read`, so it is built from slugs, which are
    Coursera's own and do not move, rather than from titles or
    positions, which do. */
export const lessonId = (course: string, mod: string, lesson: string): string =>
  `${course}/${mod}/${lesson}`;

/* ---------- and the programme is NOT in it ----------

   THE ADDRESS GREW A SEGMENT AND THE TICK DID NOT, on purpose.
   `courses-read` holds these strings in real browsers and real
   accounts, and `courses-answers` holds them with two more
   segments on the end. Adding the programme here does not move
   somebody's ticks, it loses them. `lessonUrl()` above takes a
   programme; THIS MUST NOT, however much they look alike.

   THE PRICE IS THAT A COURSE SLUG HAS TO BE UNIQUE ACROSS THE
   WHOLE CATALOGUE, or two certificates each holding a
   "Foundations" share one set of ticks. `check-courses.ts` fails
   on a collision; the fix is renaming a Drive folder. */

/** Where the browser gets a lesson's bytes: THIS SITE, NOT
    DRIVE. A private Drive file cannot be embedded cross-site,
    because browsers block or partition the cookies Drive needs to
    recognise the viewer, so a `/preview` iframe answers "Unable
    to load video" and a link answers a sign-in wall. The Worker
    holds the credential and serves the bytes from this origin:
    see `functions/_lib/drive.ts`.

    No player events, and a button instead: `ended` is a guess
    that somebody who left a tab open has learnt something. */
export const fileUrl = (drive: string): string =>
  `/api/courses/file/${drive}`;

/** A reading, sanitised and rendered into the page rather than
    handed to Drive's viewer. */
export const readingUrl = (drive: string): string =>
  `/api/courses/reading/${drive}`;

/** A video's captions, converted to WebVTT on the way through.
    Separate from `fileUrl` because the bytes are REWRITTEN: the
    files in Drive are SubRip and no browser reads SubRip in a
    <track>. */
export const captionsUrl = (drive: string): string =>
  `/api/courses/captions/${drive}`;

/** Drive's own page, for the "open in Drive" link beside a file.
    Never used for playback and never framed. */
export const driveUrl = (drive: string): string =>
  `https://drive.google.com/file/d/${drive}/view`;

/* ---------- what the Worker is allowed to fetch ----------

   Every Drive id the catalogue names, and nothing else. THE
   SECOND LOCK on `/api/courses/file/<id>`, and the one doing the
   real work: `isAdmin()` alone leaves a proxy that fetches ANY id
   it is handed, which is a read-only window onto the whole of
   somebody's Drive. An id no lesson names is refused before a
   credential is loaded. Built once at module load. */

/** Every field of a lesson that holds a Drive id.

    EXPORTED BECAUSE MORE THAN ONE THING WALKS IT: a second copy
    is a lesson field some checks validate and others do not.
    `check-courses.ts` kept its own list, and when `captions` was
    added it went on reporting a clean bill of health for 298 ids
    it had never looked at. */
export const ID_FIELDS = [
  "video", "reading", "quiz", "exam", "transcript", "captions",
] as const;

const driveIds = (): Set<string> => {
  const ids = new Set<string>();
  for (const course of COURSES) {
    for (const mod of course.modules) {
      for (const lesson of mod.lessons) {
        for (const key of ID_FIELDS) {
          const id = lesson[key];
          if (id) ids.add(id);
        }
        for (const file of lesson.files ?? []) ids.add(file.drive);
      }
    }
  }
  return ids;
};

export const DRIVE_IDS: Set<string> = driveIds();

/** Is this id one a lesson actually names? */
export const isCourseFile = (id: unknown): boolean =>
  typeof id === "string" && DRIVE_IDS.has(id);

/** The lesson a Drive id belongs to, for labelling a response.
    Null when the id is not in the catalogue at all, which the
    caller should already have refused. */
export function lessonForFile(id: string): {
  programme: Programme; course: Course; mod: CourseModule; lesson: CourseLesson;
} | null {
  for (const programme of PROGRAMMES) {
    for (const course of programme.courses) {
    for (const mod of course.modules) {
      for (const lesson of mod.lessons) {
        if (lesson.video === id || lesson.reading === id || lesson.quiz === id
          || lesson.exam === id || lesson.transcript === id || lesson.captions === id
          || (lesson.files ?? []).some((f) => f.drive === id)) {
            return { programme, course, mod, lesson };
          }
        }
      }
    }
  }
  return null;
}

/* ---------- the ladder ---------- */

/** Every lesson of a course, in order, with its id and address:
    what the sidebar draws and what "continue" walks. Computed
    rather than stored, because the ordering is a fact about the
    catalogue. */
export function laddered(programme: string, course: Course): LadderLesson[] {
  return course.modules.flatMap((mod) =>
    mod.lessons.map((lesson) => ({
      ...lesson,
      module: mod.slug,
      moduleTitle: mod.title,
      /* The id has no programme in it and the url does. One of
         these is in somebody's browser, the other is a link. */
      id: lessonId(course.slug, mod.slug, lesson.slug),
      url: lessonUrl(programme, course.slug, mod.slug, lesson.slug),
    }))
  );
}

/** The ids of one module's lessons, which is what a per-module
    percentage is counted against. */
export const moduleIds = (course: string, mod: CourseModule): string[] =>
  mod.lessons.map((l) => lessonId(course, mod.slug, l.slug));

export interface CourseCounts {
  modules: number;
  lessons: number;
  videos: number;
  /** Modules whose lessons have not been imported, counted so a
      page can say so rather than looking complete. */
  pending: number;
}

export function countsOf(course: Course): CourseCounts {
  return {
    modules: course.modules.length,
    lessons: course.modules.reduce((n, m) => n + m.lessons.length, 0),
    videos: course.modules.reduce(
      (n, m) => n + m.lessons.filter((l) => l.video).length, 0),
    pending: course.modules.filter((m) => m.pending).length,
  };
}

/** What one programme adds up to. */
export const programmeCounts = (programme: Programme) =>
  programme.courses.reduce((acc, course) => {
    const c = countsOf(course);
    return {
      courses: acc.courses + 1,
      modules: acc.modules + c.modules,
      lessons: acc.lessons + c.lessons,
      videos: acc.videos + c.videos,
      pending: acc.pending + c.pending,
    };
  }, { courses: 0, modules: 0, lessons: 0, videos: 0, pending: 0 });

/** What the whole section adds up to, for the index page. */
export const catalogueCounts = () => PROGRAMMES.reduce((acc, programme) => {
  const p = programmeCounts(programme);
  return {
    programmes: acc.programmes + 1,
    courses: acc.courses + p.courses,
    modules: acc.modules + p.modules,
    lessons: acc.lessons + p.lessons,
    videos: acc.videos + p.videos,
    pending: acc.pending + p.pending,
  };
}, { programmes: 0, courses: 0, modules: 0, lessons: 0, videos: 0, pending: 0 });

/* ---------- what the browser is given ----------

   Deliberately narrower than the catalogue, which is the point of
   a function rather than answering with the row. ONE COURSE AT A
   TIME: a lesson page needs its own course's ladder and sending
   the rest hands a page Drive ids it draws none of. */
export const forBrowser = (course: Course) => ({
  slug: course.slug,
  n: course.n,
  title: course.title,
  modules: course.modules.map((mod) => ({
    slug: mod.slug,
    n: mod.n,
    title: mod.title,
    pending: mod.pending ?? false,
    lessons: mod.lessons.map((l) => ({
      slug: l.slug,
      title: l.title,
      kind: l.kind,
      section: l.section,
      position: l.position,
      video: l.video ?? null,
      reading: l.reading ?? null,
      quiz: l.quiz ?? null,
      exam: l.exam ?? null,
      transcript: l.transcript ?? null,
      captions: l.captions ?? null,
      files: l.files ?? [],
    })),
  })),
});

/** The list page's version: NO DRIVE IDS AT ALL, because the
    list draws none. Programmes with their courses nested, because
    the front door of this section is a shelf of certificates. */
export const listForBrowser = () => PROGRAMMES.map((programme) => {
  /* `courses` is dropped from the totals and sent as the LIST
     instead: spreading the counts and then writing the key again
     puts a number on the wire the next line replaces. */
  const { courses: _count, ...totals } = programmeCounts(programme);
  return {
    slug: programme.slug,
    n: programme.n,
    title: programme.title,
    ...totals,
    courses: programme.courses.map((course) => ({
      slug: course.slug,
      n: course.n,
      title: course.title,
      ...countsOf(course),
    })),
  };
});
