/* ============================================================
   research-words.ts: the Research Studio's own words.

   Its own table beside `diet-words.ts`, for that file's reason:
   `stringKeys` in the stock fixture is "every phrase the stock
   check can render" and a studio phrase there weakens the app's
   assertion for both tools.

   In `shared/` because the Android app will draw the same rooms.
   Copy is DATA by the contract at the top of `CLAUDE.md`, so a
   line reworded here is reworded on a phone at the next fetch.

   `<W k="...">` in `next/components/research/lang.tsx` reads this
   and still renders BOTH languages into the DOM, which is the
   diet pages' own arrangement: the stylesheet picks, and the page
   works with JavaScript off. Both languages are REQUIRED and the
   type is what says so.
   ============================================================ */

import type { Phrase } from "./tool-strings.ts";

export const RESEARCH_WORDS: Record<string, Phrase> = {
  /* ---- the studio itself ---- */
  "rs.name": { en: "Research Studio", bn: "গবেষণা স্টুডিও" },
  "rs.lede": {
    en: "One place to do a piece of research from the first question to the last footnote. Everything you keep here is yours, on every device you sign in on.",
    bn: "প্রথম প্রশ্ন থেকে শেষ ফুটনোট পর্যন্ত একটা গবেষণা করার এক জায়গা। এখানে যা রাখবেন সবই আপনার, আর যে ডিভাইসে সাইন ইন করবেন সেখানেই থাকবে।",
  },
  "rs.signin.head": { en: "This is yours", bn: "এটা আপনার নিজের" },
  "rs.signin.body": {
    en: "The studio keeps your sources, notes and plans on your account, so they are the same on every device. Nothing here is shared with anybody.",
    bn: "স্টুডিও আপনার উৎস, নোট আর পরিকল্পনা আপনার অ্যাকাউন্টে রাখে, তাই সব ডিভাইসে একই থাকে। এখানকার কিছুই কারও সঙ্গে ভাগ হয় না।",
  },
  "rs.signin.go": { en: "Sign in", bn: "সাইন ইন" },
  "rs.moment": { en: "One moment", bn: "এক মুহূর্ত" },
  "rs.saved": { en: "Saved", bn: "রাখা হলো" },
  "rs.saving": { en: "Saving", bn: "রাখা হচ্ছে" },
  "rs.notsaved": { en: "That did not save. Try again.", bn: "এটা রাখা যায়নি। আবার চেষ্টা করুন।" },
  "rs.conflict": {
    en: "This changed somewhere else while you were typing. Reload to see the newer copy.",
    bn: "আপনি লিখতে লিখতে এটা অন্য কোথাও বদলে গেছে। নতুন কপি দেখতে পাতাটা রিলোড করুন।",
  },
  "rs.soon.head": { en: "This room is not built yet", bn: "এই ঘরটা এখনো তৈরি হয়নি" },
  "rs.soon.body": {
    en: "It is in the plan and it is coming. Until then, the library, the notebook, the questions and the task list are open.",
    bn: "এটা পরিকল্পনায় আছে আর আসছে। ততক্ষণ লাইব্রেরি, খাতা, প্রশ্ন আর কাজের তালিকা খোলা।",
  },
  "rs.rooms": { en: "The rooms", bn: "ঘরগুলো" },
  "rs.find": { en: "Filter", bn: "ছাঁকুন" },
  "rs.new": { en: "New", bn: "নতুন" },
  "rs.delete": { en: "Remove", bn: "সরান" },
  "rs.restore": { en: "Put back", bn: "ফিরিয়ে আনুন" },
  "rs.none": { en: "Nothing here yet.", bn: "এখানে এখনো কিছু নেই।" },
  "rs.all": { en: "All", bn: "সব" },
  "rs.project": { en: "Project", bn: "প্রজেক্ট" },
  "rs.projects": { en: "Projects", bn: "প্রজেক্টগুলো" },
  "rs.noproject": { en: "No project", bn: "কোনো প্রজেক্ট নয়" },
  "rs.tags": { en: "Tags", bn: "ট্যাগ" },
  "rs.collections": { en: "Collections", bn: "সংগ্রহ" },
  "rs.updated": { en: "Updated", bn: "হালনাগাদ" },

  /* ---- the board ---- */
  "rs.board.capture": { en: "Capture", bn: "টুকে রাখুন" },
  "rs.board.capture.hint": {
    en: "A thought, a DOI, a link, a pasted reference, or a line starting with todo. The box decides what it is and says so.",
    bn: "একটা ভাবনা, একটা DOI, একটা লিংক, পেস্ট করা রেফারেন্স, বা todo দিয়ে শুরু একটা লাইন। বাক্সটা নিজেই বুঝে নেয় সেটা কী, আর বলে দেয়।",
  },
  "rs.board.today": { en: "Today", bn: "আজ" },
  "rs.board.today.empty": {
    en: "Nothing is in today's lane. Move a task here from the planner when you decide to do it.",
    bn: "আজকের লেনে কিছু নেই। যখন ঠিক করবেন কোনটা করবেন, পরিকল্পনা থেকে সেটা এখানে আনুন।",
  },
  "rs.board.resume": { en: "Pick up where you left off", bn: "যেখানে ছেড়েছিলেন" },
  "rs.board.resume.empty": {
    en: "The last things you opened will appear here, on whichever device you open them on.",
    bn: "শেষ যা খুলেছিলেন সেগুলো এখানে দেখাবে, যে ডিভাইসেই খুলুন না কেন।",
  },
  "rs.board.inbox": { en: "Inbox", bn: "ইনবক্স" },
  "rs.board.inbox.empty": {
    en: "Captures not yet filed will wait here. The inbox's job is to become empty.",
    bn: "যেসব টুকরো এখনো গোছানো হয়নি সেগুলো এখানে অপেক্ষা করবে। ইনবক্সের কাজ খালি হয়ে যাওয়া।",
  },
  "rs.board.search": { en: "Search everything", bn: "সব কিছুতে খুঁজুন" },
  "rs.board.search.empty": {
    en: "Sources, notes, questions and tasks, by any word in them.",
    bn: "উৎস, নোট, প্রশ্ন আর কাজ, তার ভেতরের যেকোনো শব্দ দিয়ে।",
  },
  "rs.board.nothing": { en: "Nothing matched.", bn: "কিছু মেলেনি।" },
  "rs.board.decided.doi": { en: "A DOI. Looked up and filed as a source.", bn: "একটা DOI। খুঁজে উৎস হিসেবে রাখা হলো।" },
  "rs.board.decided.isbn": { en: "An ISBN. Looked up and filed as a book.", bn: "একটা ISBN। খুঁজে বই হিসেবে রাখা হলো।" },
  "rs.board.decided.url": { en: "A link. Clipped and filed as a source.", bn: "একটা লিংক। ক্লিপ করে উৎস হিসেবে রাখা হলো।" },
  "rs.board.decided.bib": { en: "A reference. Parsed and filed.", bn: "একটা রেফারেন্স। পড়ে রাখা হলো।" },
  "rs.board.decided.todo": { en: "A task, in this week's lane.", bn: "একটা কাজ, এই সপ্তাহের লেনে।" },
  "rs.board.decided.note": { en: "A capture, in the inbox.", bn: "একটা টুকরো, ইনবক্সে।" },
  "rs.board.decided.dup": { en: "Already in the library. Opened it instead.", bn: "লাইব্রেরিতে আগেই আছে। সেটাই খোলা হলো।" },
  "rs.board.decided.fail": { en: "Could not look that up. Kept as a capture.", bn: "এটা খুঁজে পাওয়া যায়নি। টুকরো হিসেবে রাখা হলো।" },

  /* ---- the library ---- */
  "rs.lib.add": { en: "Add a source", bn: "উৎস যোগ করুন" },
  "rs.lib.add.hint": {
    en: "A DOI, an ISBN, a link, or a pasted BibTeX, RIS or CSL record. Or drop a .bib, .ris or .json file on the list.",
    bn: "একটা DOI, ISBN, লিংক, বা পেস্ট করা BibTeX, RIS বা CSL রেকর্ড। অথবা তালিকার উপর একটা .bib, .ris বা .json ফাইল ছেড়ে দিন।",
  },
  "rs.lib.lookup": { en: "Look up", bn: "খুঁজুন" },
  "rs.lib.import": { en: "Import a file", bn: "ফাইল আনুন" },
  "rs.lib.imported": { en: "added", bn: "যোগ হলো" },
  "rs.lib.skipped": { en: "already there", bn: "আগেই ছিল" },
  "rs.lib.empty": {
    en: "No sources yet. Paste a DOI above, drop an export from Zotero or Scholar, or pull your Zotero library from Settings.",
    bn: "এখনো কোনো উৎস নেই। উপরে একটা DOI পেস্ট করুন, Zotero বা Scholar থেকে এক্সপোর্ট ছেড়ে দিন, বা সেটিংস থেকে আপনার Zotero লাইব্রেরি টেনে আনুন।",
  },
  "rs.lib.type": { en: "Type", bn: "ধরন" },
  "rs.lib.status": { en: "Reading", bn: "পড়া" },
  "rs.lib.status.unread": { en: "Unread", bn: "পড়া হয়নি" },
  "rs.lib.status.skimmed": { en: "Skimmed", bn: "চোখ বোলানো" },
  "rs.lib.status.read": { en: "Read", bn: "পড়া হয়েছে" },
  "rs.lib.status.annotated": { en: "Annotated", bn: "নোট করা" },
  "rs.lib.status.cited": { en: "Cited", bn: "উদ্ধৃত" },
  "rs.lib.priority": { en: "Priority", bn: "অগ্রাধিকার" },
  "rs.lib.rating": { en: "Your rating", bn: "আপনার মূল্যায়ন" },
  "rs.lib.why": { en: "Why I saved this", bn: "কেন রাখলাম" },
  "rs.lib.title": { en: "Title", bn: "শিরোনাম" },
  "rs.lib.authors": { en: "Authors", bn: "লেখক" },
  "rs.lib.authors.hint": { en: "Family, Given; Family, Given", bn: "পদবি, নাম; পদবি, নাম" },
  "rs.lib.year": { en: "Year", bn: "সাল" },
  "rs.lib.container": { en: "Journal, book or publisher", bn: "জার্নাল, বই বা প্রকাশক" },
  "rs.lib.volume": { en: "Volume", bn: "খণ্ড" },
  "rs.lib.issue": { en: "Issue", bn: "সংখ্যা" },
  "rs.lib.pages": { en: "Pages", bn: "পৃষ্ঠা" },
  "rs.lib.doi": { en: "DOI", bn: "DOI" },
  "rs.lib.url": { en: "Link", bn: "লিংক" },
  "rs.lib.abstract": { en: "Abstract", bn: "সারসংক্ষেপ" },
  "rs.lib.key": { en: "Citation key", bn: "উদ্ধৃতি কী" },
  "rs.lib.key.hint": {
    en: "Made once and never regenerated: a draft's citations hold it.",
    bn: "একবারই তৈরি হয়, আর বদলায় না: খসড়ার উদ্ধৃতিগুলো এটাই ধরে রাখে।",
  },
  "rs.lib.verified": { en: "Verified record", bn: "যাচাই করা রেকর্ড" },
  "rs.lib.unverified": { en: "Unverified: check me", bn: "যাচাই হয়নি: দেখে নিন" },
  "rs.lib.via": { en: "Added via", bn: "যেভাবে এসেছে" },
  "rs.lib.reference": { en: "Reference", bn: "রেফারেন্স" },
  "rs.lib.copybib": { en: "Copy as BibTeX", bn: "BibTeX হিসেবে কপি" },
  "rs.lib.copyris": { en: "Copy as RIS", bn: "RIS হিসেবে কপি" },
  "rs.lib.notes": { en: "Notes about this", bn: "এটা নিয়ে নোট" },
  "rs.lib.note.new": { en: "Write a literature note", bn: "পড়ার নোট লিখুন" },
  "rs.lib.bin": { en: "In the bin", bn: "বিনে" },
  "rs.lib.bin.hint": {
    en: "Kept for thirty days, then gone.",
    bn: "তিরিশ দিন রাখা হয়, তারপর চলে যায়।",
  },
  "rs.lib.open": { en: "Open", bn: "খুলুন" },
  "rs.lib.merge": {
    en: "Looks like the same paper as one already here.",
    bn: "মনে হচ্ছে এখানে আগে থেকেই থাকা একটা পেপারের সঙ্গে মিলে যাচ্ছে।",
  },

  /* ---- the notebook ---- */
  "rs.notes.kind": { en: "Kind", bn: "ধরন" },
  "rs.notes.title": { en: "Title", bn: "শিরোনাম" },
  "rs.notes.empty": {
    en: "No notes yet. Press New, or capture a thought from the board.",
    bn: "এখনো কোনো নোট নেই। নতুন চাপুন, বা বোর্ড থেকে একটা ভাবনা টুকে রাখুন।",
  },
  "rs.notes.source": { en: "About a source", bn: "যে উৎস নিয়ে" },
  "rs.notes.links": { en: "Links to", bn: "যেখানে যুক্ত" },
  "rs.notes.backlinks": { en: "Linked from", bn: "যেখান থেকে যুক্ত" },
  "rs.notes.body": { en: "The note", bn: "নোট" },
  "rs.notes.daily": { en: "Today's log", bn: "আজকের খাতা" },
  "rs.notes.daily.template": {
    en: "Time spent:\nWhat I did:\nWhat I learned:\nWhat is blocking me:\nTomorrow's first task:",
    bn: "কত সময়:\nকী করলাম:\nকী শিখলাম:\nকোথায় আটকে আছি:\nকালকের প্রথম কাজ:",
  },

  /* ---- questions ---- */
  "rs.q.new": { en: "New question", bn: "নতুন প্রশ্ন" },
  "rs.q.text": { en: "The question", bn: "প্রশ্নটা" },
  "rs.q.kind": { en: "Kind", bn: "ধরন" },
  "rs.q.state": { en: "State", bn: "অবস্থা" },
  "rs.q.state.open": { en: "Open", bn: "চলছে" },
  "rs.q.state.parked": { en: "Parked", bn: "থামানো" },
  "rs.q.state.answered": { en: "Answered", bn: "উত্তর পাওয়া" },
  "rs.q.note": { en: "Where this stands", bn: "এখন কোথায় আছে" },
  "rs.q.evidence": { en: "Evidence", bn: "প্রমাণ" },
  "rs.q.evidence.add": { en: "Add a source as evidence", bn: "উৎসকে প্রমাণ হিসেবে যোগ করুন" },
  "rs.q.evidence.empty": {
    en: "Nothing speaks to this yet. Pick a source from the library and say whether it supports it, contradicts it, gives a method, or gives context.",
    bn: "এটা নিয়ে এখনো কিছু বলে না। লাইব্রেরি থেকে একটা উৎস বেছে বলুন সেটা সমর্থন করে, খণ্ডন করে, পদ্ধতি দেয়, না প্রেক্ষাপট দেয়।",
  },
  "rs.q.stance.supports": { en: "supports", bn: "সমর্থন করে" },
  "rs.q.stance.contradicts": { en: "contradicts", bn: "খণ্ডন করে" },
  "rs.q.stance.method": { en: "gives a method", bn: "পদ্ধতি দেয়" },
  "rs.q.stance.context": { en: "gives context", bn: "প্রেক্ষাপট দেয়" },
  "rs.q.children": { en: "Under this", bn: "এর নিচে" },
  "rs.q.carried": { en: "Carried from the old desk", bn: "পুরোনো ডেস্ক থেকে আনা" },
  "rs.q.empty": {
    en: "No questions yet. A research question at the top, hypotheses under it, claims under those.",
    bn: "এখনো কোনো প্রশ্ন নেই। উপরে গবেষণার প্রশ্ন, তার নিচে অনুমান, তার নিচে দাবি।",
  },

  /* ---- tasks ---- */
  "rs.tasks.new": { en: "New task", bn: "নতুন কাজ" },
  "rs.tasks.due": { en: "Due", bn: "শেষ তারিখ" },
  "rs.tasks.empty": {
    en: "Nothing in this lane.",
    bn: "এই লেনে কিছু নেই।",
  },
  "rs.tasks.move": { en: "Move to", bn: "সরান" },
  "rs.tasks.days": { en: "days", bn: "দিন" },
  "rs.tasks.waiting.since": { en: "waiting since", bn: "অপেক্ষা শুরু" },

  /* ---- settings ---- */
  "rs.set.prefs": { en: "Preferences", bn: "পছন্দ" },
  "rs.set.name": { en: "Your name on exports", bn: "এক্সপোর্টে আপনার নাম" },
  "rs.set.affiliation": { en: "Affiliation", bn: "প্রতিষ্ঠান" },
  "rs.set.orcid": { en: "ORCID", bn: "ORCID" },
  "rs.set.style": { en: "Default citation style", bn: "ডিফল্ট উদ্ধৃতি রীতি" },
  "rs.set.dense": { en: "Dense mode", bn: "ঘন সাজানো" },
  "rs.set.dense.hint": {
    en: "Less air around everything in the studio. The one place on this site a reader may ask for less.",
    bn: "স্টুডিওর সব কিছুর চারপাশে কম ফাঁকা। এই সাইটে এটাই একমাত্র জায়গা যেখানে কম চাওয়া যায়।",
  },
  "rs.set.projects.hint": {
    en: "A doctorate, a paper, a book, an application. One source or note can belong to several.",
    bn: "একটা ডক্টরেট, একটা পেপার, একটা বই, একটা আবেদন। একটা উৎস বা নোট কয়েকটার হতে পারে।",
  },
  "rs.set.project.name": { en: "Name", bn: "নাম" },
  "rs.set.project.kind": { en: "Kind", bn: "ধরন" },
  "rs.set.project.new": { en: "New project", bn: "নতুন প্রজেক্ট" },
  "rs.set.connections": { en: "Connections", bn: "সংযোগ" },
  "rs.set.connections.hint": {
    en: "What the studio can reach from here. A service that is off is a sentence on the page, never an error.",
    bn: "স্টুডিও এখান থেকে কোথায় পৌঁছাতে পারে। যে সেবা বন্ধ, পাতায় সেটা একটা বাক্য, ভুল নয়।",
  },
  "rs.set.zotero": { en: "Pull from Zotero", bn: "Zotero থেকে আনুন" },
  "rs.set.zotero.hint": {
    en: "Your numeric user id and a read-only API key from zotero.org/settings/keys. Neither is stored: they are used for this one pull and forgotten.",
    bn: "zotero.org/settings/keys থেকে আপনার সংখ্যার ইউজার আইডি আর শুধু-পড়ার API কী। কোনোটাই রাখা হয় না: এই একবার টানার জন্য ব্যবহার হয়, তারপর ভুলে যাওয়া হয়।",
  },
  "rs.set.zotero.user": { en: "Zotero user id", bn: "Zotero ইউজার আইডি" },
  "rs.set.zotero.key": { en: "API key", bn: "API কী" },
  "rs.set.zotero.go": { en: "Pull the library", bn: "লাইব্রেরি টানুন" },
  "rs.set.clipper": { en: "Save to the studio", bn: "স্টুডিওতে রাখুন" },
  "rs.set.clipper.hint": {
    en: "Drag this to your bookmarks bar. On a paper's page, press it and the paper is filed here.",
    bn: "এটা আপনার বুকমার্ক বারে টেনে নিন। কোনো পেপারের পাতায় থাকা অবস্থায় চাপলে পেপারটা এখানে রাখা হবে।",
  },
  "rs.set.on": { en: "connected", bn: "সংযুক্ত" },
  "rs.set.off": { en: "not connected", bn: "সংযুক্ত নয়" },

  /* ---- the archive ---- */
  "rs.arc.activity": { en: "Everything that happened", bn: "যা যা হয়েছে" },
  "rs.arc.activity.empty": {
    en: "Every write the studio makes is a line here, so nothing is lost and everything can be found again.",
    bn: "স্টুডিও যা লেখে তার প্রতিটি এখানে এক লাইন, তাই কিছু হারায় না আর সব আবার খুঁজে পাওয়া যায়।",
  },
  "rs.arc.export": { en: "Take a copy", bn: "একটা কপি নিন" },
  "rs.arc.export.hint": {
    en: "Every row of the studio as JSON, and the library as BibTeX and RIS beside it.",
    bn: "স্টুডিওর প্রতিটি সারি JSON হিসেবে, আর পাশে লাইব্রেরি BibTeX আর RIS হিসেবে।",
  },
  "rs.arc.versions": { en: "Versions", bn: "সংস্করণ" },
  "rs.arc.bin": { en: "The bin", bn: "বিন" },

  /* ---- the reading room ---- */
  "rs.read.queue": { en: "Up next", bn: "এরপর" },
  "rs.read.queue.hint": { en: "Every source with a file or a book to read, the important ones first. Enter opens the top one.", bn: "যেসব উৎসে ফাইল আছে বা বই পড়ার আছে, জরুরিগুলো আগে। Enter চাপলে প্রথমটা খোলে।" },
  "rs.read.queue.empty": { en: "Nothing waiting. Add a PDF to a source in the library and it will be here.", bn: "কিছু অপেক্ষায় নেই। লাইব্রেরির কোনো উৎসে PDF যোগ করলে এখানে আসবে।" },
  "rs.read.open": { en: "Open", bn: "খুলুন" },
  "rs.read.back": { en: "Back to the queue", bn: "সারিতে ফিরুন" },
  "rs.read.pages": { en: "pages", bn: "পাতা" },
  "rs.read.page": { en: "Page", bn: "পাতা" },
  "rs.read.of": { en: "of", bn: "এর মধ্যে" },
  "rs.read.nofile": { en: "No file on this source yet.", bn: "এই উৎসে এখনো কোনো ফাইল নেই।" },
  "rs.read.loading": { en: "Opening the file", bn: "ফাইল খুলছে" },
  "rs.read.failed": { en: "Could not open the file.", bn: "ফাইলটা খোলা গেল না।" },
  "rs.read.notext": { en: "This file has no text layer, so nothing can be selected. A scanned PDF needs OCR, which is a later stage.", bn: "এই ফাইলে লেখার স্তর নেই, তাই কিছু বাছাই করা যাবে না। স্ক্যান করা PDF-এর জন্য OCR লাগে, সেটা পরের ধাপে।" },
  "rs.read.keys": { en: "Select some text and press 1 to 5. j and k turn the page.", bn: "কিছু লেখা বাছাই করে ১ থেকে ৫ চাপুন। j আর k পাতা ওল্টায়।" },
  "rs.read.highlights": { en: "Highlights", bn: "হাইলাইট" },
  "rs.read.highlights.empty": { en: "Nothing marked yet.", bn: "এখনো কিছু চিহ্নিত হয়নি।" },
  "rs.read.meaning": { en: "Meaning", bn: "অর্থ" },
  "rs.read.note": { en: "A note beside it", bn: "পাশে একটা নোট" },
  "rs.read.card": { en: "Extraction card", bn: "নিষ্কাশন কার্ড" },
  "rs.read.number": { en: "Number", bn: "সংখ্যা" },
  "rs.read.unit": { en: "Unit", bn: "একক" },
  "rs.read.n": { en: "Sample size", bn: "নমুনার আকার" },
  "rs.read.method": { en: "Method", bn: "পদ্ধতি" },
  "rs.read.finding": { en: "Finding, in one line", bn: "ফলাফল, এক লাইনে" },
  "rs.read.remove": { en: "Remove", bn: "মুছুন" },
  "rs.read.goto": { en: "Go to it", bn: "সেখানে যান" },
  "rs.read.done": { en: "Mark as read", bn: "পড়া হয়েছে" },
  "rs.read.said": { en: "What did this say, in one line?", bn: "এটা এক লাইনে কী বলল?" },
  "rs.read.said.hint": { en: "It becomes the first line of the literature note. Asked once.", bn: "এটা সাহিত্য-নোটের প্রথম লাইন হয়। একবারই জিজ্ঞেস করা হয়।" },
  "rs.read.said.keep": { en: "Keep it", bn: "রাখুন" },
  "rs.read.said.skip": { en: "Not now", bn: "এখন না" },
  "rs.read.typed": { en: "From the page, typed", bn: "পাতা থেকে, টাইপ করা" },
  "rs.read.typed.hint": { en: "A book is a physical thing: type the page and the passage, and it is marked as typed.", bn: "বই একটা বাস্তব জিনিস: পাতা আর অংশটা টাইপ করুন, সেটা টাইপ-করা বলে চিহ্নিত থাকবে।" },
  "rs.read.typed.page": { en: "Page", bn: "পাতা" },
  "rs.read.typed.text": { en: "The passage", bn: "অংশটা" },
  "rs.read.typed.add": { en: "Add", bn: "যোগ করুন" },
  "rs.read.audio.start": { en: "Mark from here", bn: "এখান থেকে চিহ্ন" },
  "rs.read.audio.end": { en: "To here", bn: "এখান পর্যন্ত" },
  "rs.read.audio.hint": { en: "A highlight in audio is a time range: mark where it starts, then where it ends, then its meaning.", bn: "অডিওতে হাইলাইট মানে সময়ের একটা পরিসর: শুরু চিহ্নিত করুন, তারপর শেষ, তারপর অর্থ।" },
  "rs.read.zoom.in": { en: "Larger", bn: "বড়" },
  "rs.read.zoom.out": { en: "Smaller", bn: "ছোট" },
  "rs.read.next": { en: "Next page", bn: "পরের পাতা" },
  "rs.read.prev": { en: "Previous page", bn: "আগের পাতা" },
  "rs.read.capture": { en: "Captured page", bn: "ধরা পাতা" },
  "rs.read.data": { en: "A data file. The lab reads it in stage 8.", bn: "একটা ডেটা ফাইল। ল্যাব এটা ধাপ ৮-এ পড়ে।" },
  "rs.lib.files": { en: "Files", bn: "ফাইল" },
  "rs.lib.file.add": { en: "Add a file", bn: "ফাইল যোগ করুন" },
  "rs.lib.file.hint": { en: "A PDF, audio, a data file or a picture, up to 100 MB. Stored on your account.", bn: "PDF, অডিও, ডেটা ফাইল বা ছবি, ১০০ MB পর্যন্ত। আপনার অ্যাকাউন্টে রাখা হয়।" },
  "rs.lib.file.capture": { en: "Capture the web page", bn: "ওয়েব পাতাটা ধরে রাখুন" },
  "rs.lib.file.capture.hint": { en: "The page at this source's address, fetched and kept as it is today, so it can be read and marked here even after it changes.", bn: "এই উৎসের ঠিকানার পাতাটা আজ যেমন আছে তেমন এনে রাখা, যাতে বদলে গেলেও এখানে পড়া ও চিহ্নিত করা যায়।" },
  "rs.lib.file.remove": { en: "Detach", bn: "আলাদা করুন" },
  "rs.lib.read": { en: "Read", bn: "পড়ুন" },
  "rs.lib.uploading": { en: "Sending the file", bn: "ফাইল পাঠাচ্ছে" },
  "rs.lib.file.failed": { en: "The file was not stored.", bn: "ফাইলটা রাখা যায়নি।" },
  "rs.lib.file.quota": { en: "That would take you over the space your account has.", bn: "এতে আপনার অ্যাকাউন্টের জায়গা পেরিয়ে যাবে।" },
  "rs.set.files": { en: "Files", bn: "ফাইল" },
  "rs.set.files.hint": { en: "What the reading room holds on your account, against the space it has.", bn: "পড়ার ঘর আপনার অ্যাকাউন্টে যা রাখে, তার জায়গার তুলনায়।" },

  /* ---- finding ---- */
  "rs.findroom.q": { en: "Search every index", bn: "সব সূচিতে খুঁজুন" },
  "rs.findroom.q.hint": { en: "Words from the title, the abstract or the topic. Every index that is on is asked at once and the answers are merged.", bn: "শিরোনাম, সারাংশ বা বিষয়ের শব্দ। যেসব সূচি চালু আছে সবগুলোকে একসাথে জিজ্ঞেস করা হয়, উত্তর মেলানো হয়।" },
  "rs.findroom.go": { en: "Search", bn: "খুঁজুন" },
  "rs.findroom.save": { en: "Keep this search", bn: "এই খোঁজ রাখুন" },
  "rs.findroom.author": { en: "Author", bn: "লেখক" },
  "rs.findroom.from": { en: "From", bn: "থেকে" },
  "rs.findroom.to": { en: "To", bn: "পর্যন্ত" },
  "rs.findroom.anytype": { en: "Any type", bn: "যেকোনো ধরন" },
  "rs.findroom.oa": { en: "Free copies only", bn: "শুধু বিনামূল্যের কপি" },
  "rs.findroom.databases": { en: "Ask:", bn: "জিজ্ঞেস করুন:" },
  "rs.findroom.searching": { en: "Asking the indexes", bn: "সূচিগুলোকে জিজ্ঞেস করছে" },
  "rs.findroom.failed": { en: "The search did not answer. Try again in a moment.", bn: "খোঁজে উত্তর আসেনি। একটু পরে আবার চেষ্টা করুন।" },
  "rs.findroom.noanswer": { en: "did not answer", bn: "উত্তর দেয়নি" },
  "rs.findroom.none": { en: "Nothing found. Fewer words, or another index.", bn: "কিছু পাওয়া যায়নি। কম শব্দ, বা অন্য সূচি।" },
  "rs.findroom.empty": { en: "Type something above. A row already in your library says so, with its status.", bn: "উপরে কিছু লিখুন। লাইব্রেরিতে আগে থেকে থাকা সারি নিজেই বলবে, অবস্থাসহ।" },
  "rs.findroom.add": { en: "Add", bn: "যোগ করুন" },
  "rs.findroom.saved": { en: "Kept searches", bn: "রাখা খোঁজ" },
  "rs.findroom.saved.hint": { en: "Each one is a line of the search log a review prints. Switch the alert on and it is rerun every Monday; what is new lands in the inbox.", bn: "প্রতিটা রিভিউয়ের খোঁজ-লগের এক লাইন। সতর্কতা চালু করলে প্রতি সোমবার আবার চলে; নতুন যা আসে ইনবক্সে জমা হয়।" },
  "rs.findroom.alert.on": { en: "Alert on", bn: "সতর্কতা চালু" },
  "rs.findroom.alert.off": { en: "Alert off", bn: "সতর্কতা বন্ধ" },
  "rs.findroom.alerted": { en: "New from your alerts, filed in the inbox:", bn: "আপনার সতর্কতা থেকে নতুন, ইনবক্সে রাখা হলো:" },
  "rs.findroom.related": { en: "Related", bn: "সম্পর্কিত" },
  "rs.findroom.show": { en: "Show", bn: "দেখান" },
  "rs.findroom.citedby": { en: "Cited by", bn: "উদ্ধৃত করেছে" },
  "rs.findroom.references": { en: "References", bn: "তথ্যসূত্র" },

  /* ---- the writing desk ---- */
  "rs.write.documents": { en: "Documents", bn: "দলিল" },
  "rs.write.new": { en: "New document", bn: "নতুন দলিল" },
  "rs.write.title": { en: "Title", bn: "শিরোনাম" },
  "rs.write.kind": { en: "Kind", bn: "ধরন" },
  "rs.write.state": { en: "State", bn: "অবস্থা" },
  "rs.write.style": { en: "Citation style", bn: "উদ্ধৃতির রীতি" },
  "rs.write.budget": { en: "Word budget", bn: "শব্দের বাজেট" },
  "rs.write.empty": { en: "Nothing on the desk yet. Start a chapter, a paper or a proposal.", bn: "ডেস্কে এখনো কিছু নেই। একটা অধ্যায়, পেপার বা প্রস্তাব শুরু করুন।" },
  "rs.write.pick": { en: "Choose a document on the left, or start one.", bn: "বাঁয়ে একটা দলিল বেছে নিন, বা নতুন শুরু করুন।" },
  "rs.write.cite": { en: "Cite", bn: "উদ্ধৃত করুন" },
  "rs.write.cite.hint": { en: "Type @ in the text, or press this: pick a source, add a page, Enter.", bn: "লেখায় @ চাপুন, বা এটা: উৎস বাছুন, পাতা দিন, Enter।" },
  "rs.write.cite.find": { en: "Find a source", bn: "উৎস খুঁজুন" },
  "rs.write.cite.locator": { en: "Page", bn: "পাতা" },
  "rs.write.cite.insert": { en: "Insert", bn: "বসান" },
  "rs.write.footnote": { en: "Footnote", bn: "পাদটীকা" },
  "rs.write.footnote.hint": { en: "A marker where the caret is and a note at the foot, numbered by position. OSCOLA and Chicago notes cite here.", bn: "কার্সর যেখানে সেখানে চিহ্ন, নিচে টীকা, অবস্থান অনুযায়ী নম্বর। OSCOLA আর Chicago notes এখানেই উদ্ধৃত করে।" },
  "rs.write.quote": { en: "Quote a highlight", bn: "হাইলাইট উদ্ধৃত করুন" },
  "rs.write.render": { en: "Refresh citations", bn: "উদ্ধৃতি নতুন করে সাজান" },
  "rs.write.bibliography": { en: "Bibliography", bn: "গ্রন্থপঞ্জি" },
  "rs.write.outline": { en: "Outline", bn: "রূপরেখা" },
  "rs.write.outline.hint": { en: "The headings in the text, with the words under each. A budget on a heading fills a meter.", bn: "লেখার শিরোনামগুলো, প্রতিটার নিচের শব্দসহ। শিরোনামে বাজেট দিলে মিটার ভরে।" },
  "rs.write.outline.empty": { en: "No headings yet. Type a heading in the text and it appears here.", bn: "এখনো শিরোনাম নেই। লেখায় শিরোনাম দিন, এখানে দেখা যাবে।" },
  "rs.write.words": { en: "words", bn: "শব্দ" },
  "rs.write.minutes": { en: "min read", bn: "মিনিটে পড়া" },
  "rs.write.citations": { en: "citations", bn: "উদ্ধৃতি" },
  "rs.write.of": { en: "of", bn: "এর মধ্যে" },
  "rs.write.audit": { en: "Claims audit", bn: "দাবির হিসাব" },
  "rs.write.audit.hint": { en: "Every sentence with a number or a claim word, and whether a citation sits in it. The ones without are yours to work through.", bn: "সংখ্যা বা দাবির শব্দসহ প্রতিটা বাক্য, আর তাতে উদ্ধৃতি আছে কি না। যেগুলোতে নেই, সেগুলো আপনার কাজ।" },
  "rs.write.audit.clean": { en: "Every claim carries a citation.", bn: "প্রতিটা দাবিতে উদ্ধৃতি আছে।" },
  "rs.write.audit.uncited": { en: "without a citation", bn: "উদ্ধৃতি ছাড়া" },
  "rs.write.overlap": { en: "Overlap check", bn: "মিল পরীক্ষা" },
  "rs.write.overlap.hint": { en: "Runs of eight or more words shared with a source's abstract, a note, or another document. It reads only what the studio holds and is not a plagiarism service.", bn: "উৎসের সারাংশ, নোট বা অন্য দলিলের সাথে মিলে যাওয়া আট বা তার বেশি শব্দের টানা অংশ। এটা শুধু স্টুডিওর ভেতরের লেখা পড়ে; কুম্ভীলকতা যাচাইয়ের সেবা নয়।" },
  "rs.write.overlap.clean": { en: "No run of eight words shared with anything the studio holds.", bn: "স্টুডিওর কিছুর সাথে আট শব্দের কোনো টানা মিল নেই।" },
  "rs.write.snapshot": { en: "Snapshot", bn: "স্ন্যাপশট" },
  "rs.write.snapshot.hint": { en: "A named version, kept whatever the ten-minute rule says: sent to supervisor, submitted, before the rewrite.", bn: "নামসহ একটা সংস্করণ, দশ মিনিটের নিয়ম যা-ই বলুক রাখা থাকে: সুপারভাইজারকে পাঠানো, জমা দেওয়া, নতুন করে লেখার আগে।" },
  "rs.write.snapshot.name": { en: "Name this version", bn: "এই সংস্করণের নাম" },
  "rs.write.versions": { en: "Versions", bn: "সংস্করণ" },
  "rs.write.restore": { en: "Open this version", bn: "এই সংস্করণ খুলুন" },
  "rs.write.export": { en: "Export", bn: "রপ্তানি" },
  "rs.write.export.word": { en: "Word", bn: "Word" },
  "rs.write.export.md": { en: "Markdown", bn: "Markdown" },
  "rs.write.export.tex": { en: "LaTeX + BibTeX", bn: "LaTeX + BibTeX" },
  "rs.write.export.print": { en: "Print or PDF", bn: "ছাপা বা PDF" },
  "rs.write.author": { en: "Author", bn: "লেখক" },
  "rs.write.affiliation": { en: "Affiliation", bn: "প্রতিষ্ঠান" },
  "rs.write.conflict": { en: "Somebody else wrote first, usually you on a phone. Reload to see it.", bn: "কেউ আগে লিখেছে, সাধারণত আপনিই ফোনে। দেখতে রিলোড করুন।" },
};

/** One phrase, or a loud marker for a key nobody wrote. */
export const word = (k: string): Phrase =>
  RESEARCH_WORDS[k] ?? { en: `[${k}]`, bn: `[${k}]` };
