/* ============================================================
   research-words.ts: the Research Studio's own words.

   Its own table beside `diet-words.ts`, for that file's reason:
   `stringKeys` in the stock fixture is "every phrase the stock
   check can render" and a studio phrase there weakens the app's
   assertion for both tools.

   In `shared/` because the Android app will draw the same rooms.
   Copy is DATA by the contract at the top of `CLAUDE.md`, so a
   line reworded here is reworded on a phone at the next fetch.

   `<W k="...">` in `next/components/research/lang.tsx` reads this
   and still renders BOTH languages into the DOM, which is the
   diet pages' own arrangement: the stylesheet picks, and the page
   works with JavaScript off. Both languages are REQUIRED and the
   type is what says so.
   ============================================================ */

import type { Phrase } from "./tool-strings.ts";

export const RESEARCH_WORDS: Record<string, Phrase> = {
  /* ---- the studio itself ---- */
  "rs.name": { en: "Research Studio", bn: "গবেষণা স্টুডিও" },
  "rs.lede": {
    en: "One place to do a piece of research from the first question to the last footnote. Everything you keep here is yours, on every device you sign in on.",
    bn: "প্রথম প্রশ্ন থেকে শেষ ফুটনোট পর্যন্ত একটা গবেষণা করার এক জায়গা। এখানে যা রাখবেন সবই আপনার, আর যে ডিভাইসে সাইন ইন করবেন সেখানেই থাকবে।",
  },
  "rs.signin.head": { en: "This is yours", bn: "এটা আপনার নিজের" },
  "rs.signin.body": {
    en: "The studio keeps your sources, notes and plans on your account, so they are the same on every device. Nothing here is shared with anybody.",
    bn: "স্টুডিও আপনার উৎস, নোট আর পরিকল্পনা আপনার অ্যাকাউন্টে রাখে, তাই সব ডিভাইসে একই থাকে। এখানকার কিছুই কারও সঙ্গে ভাগ হয় না।",
  },
  "rs.signin.go": { en: "Sign in", bn: "সাইন ইন" },
  "rs.moment": { en: "One moment", bn: "এক মুহূর্ত" },
  "rs.saved": { en: "Saved", bn: "রাখা হলো" },
  "rs.saving": { en: "Saving", bn: "রাখা হচ্ছে" },
  "rs.notsaved": { en: "That did not save. Try again.", bn: "এটা রাখা যায়নি। আবার চেষ্টা করুন।" },
  "rs.conflict": {
    en: "This changed somewhere else while you were typing. Reload to see the newer copy.",
    bn: "আপনি লিখতে লিখতে এটা অন্য কোথাও বদলে গেছে। নতুন কপি দেখতে পাতাটা রিলোড করুন।",
  },
  "rs.soon.head": { en: "This room is not built yet", bn: "এই ঘরটা এখনো তৈরি হয়নি" },
  "rs.soon.body": {
    en: "It is in the plan and it is coming. Until then, the library, the notebook, the questions and the task list are open.",
    bn: "এটা পরিকল্পনায় আছে আর আসছে। ততক্ষণ লাইব্রেরি, খাতা, প্রশ্ন আর কাজের তালিকা খোলা।",
  },
  "rs.rooms": { en: "The rooms", bn: "ঘরগুলো" },
  "rs.find": { en: "Filter", bn: "ছাঁকুন" },
  "rs.new": { en: "New", bn: "নতুন" },
  "rs.delete": { en: "Remove", bn: "সরান" },
  "rs.restore": { en: "Put back", bn: "ফিরিয়ে আনুন" },
  "rs.none": { en: "Nothing here yet.", bn: "এখানে এখনো কিছু নেই।" },
  "rs.all": { en: "All", bn: "সব" },
  "rs.project": { en: "Project", bn: "প্রজেক্ট" },
  "rs.projects": { en: "Projects", bn: "প্রজেক্টগুলো" },
  "rs.noproject": { en: "No project", bn: "কোনো প্রজেক্ট নয়" },
  "rs.tags": { en: "Tags", bn: "ট্যাগ" },
  "rs.collections": { en: "Collections", bn: "সংগ্রহ" },
  "rs.updated": { en: "Updated", bn: "হালনাগাদ" },

  /* ---- the board ---- */
  "rs.board.capture": { en: "Capture", bn: "টুকে রাখুন" },
  "rs.board.capture.hint": {
    en: "A thought, a DOI, a link, a pasted reference, or a line starting with todo. The box decides what it is and says so.",
    bn: "একটা ভাবনা, একটা DOI, একটা লিংক, পেস্ট করা রেফারেন্স, বা todo দিয়ে শুরু একটা লাইন। বাক্সটা নিজেই বুঝে নেয় সেটা কী, আর বলে দেয়।",
  },
  "rs.board.today": { en: "Today", bn: "আজ" },
  "rs.board.today.empty": {
    en: "Nothing is in today's lane. Move a task here from the planner when you decide to do it.",
    bn: "আজকের লেনে কিছু নেই। যখন ঠিক করবেন কোনটা করবেন, পরিকল্পনা থেকে সেটা এখানে আনুন।",
  },
  "rs.board.resume": { en: "Pick up where you left off", bn: "যেখানে ছেড়েছিলেন" },
  "rs.board.resume.empty": {
    en: "The last things you opened will appear here, on whichever device you open them on.",
    bn: "শেষ যা খুলেছিলেন সেগুলো এখানে দেখাবে, যে ডিভাইসেই খুলুন না কেন।",
  },
  "rs.board.inbox": { en: "Inbox", bn: "ইনবক্স" },
  "rs.board.inbox.empty": {
    en: "Captures not yet filed will wait here. The inbox's job is to become empty.",
    bn: "যেসব টুকরো এখনো গোছানো হয়নি সেগুলো এখানে অপেক্ষা করবে। ইনবক্সের কাজ খালি হয়ে যাওয়া।",
  },
  "rs.board.search": { en: "Search everything", bn: "সব কিছুতে খুঁজুন" },
  "rs.board.search.empty": {
    en: "Sources, notes, questions and tasks, by any word in them.",
    bn: "উৎস, নোট, প্রশ্ন আর কাজ, তার ভেতরের যেকোনো শব্দ দিয়ে।",
  },
  "rs.board.nothing": { en: "Nothing matched.", bn: "কিছু মেলেনি।" },
  "rs.board.decided.doi": { en: "A DOI. Looked up and filed as a source.", bn: "একটা DOI। খুঁজে উৎস হিসেবে রাখা হলো।" },
  "rs.board.decided.isbn": { en: "An ISBN. Looked up and filed as a book.", bn: "একটা ISBN। খুঁজে বই হিসেবে রাখা হলো।" },
  "rs.board.decided.url": { en: "A link. Clipped and filed as a source.", bn: "একটা লিংক। ক্লিপ করে উৎস হিসেবে রাখা হলো।" },
  "rs.board.decided.bib": { en: "A reference. Parsed and filed.", bn: "একটা রেফারেন্স। পড়ে রাখা হলো।" },
  "rs.board.decided.todo": { en: "A task, in this week's lane.", bn: "একটা কাজ, এই সপ্তাহের লেনে।" },
  "rs.board.decided.note": { en: "A capture, in the inbox.", bn: "একটা টুকরো, ইনবক্সে।" },
  "rs.board.decided.dup": { en: "Already in the library. Opened it instead.", bn: "লাইব্রেরিতে আগেই আছে। সেটাই খোলা হলো।" },
  "rs.board.decided.fail": { en: "Could not look that up. Kept as a capture.", bn: "এটা খুঁজে পাওয়া যায়নি। টুকরো হিসেবে রাখা হলো।" },

  /* ---- the library ---- */
  "rs.lib.add": { en: "Add a source", bn: "উৎস যোগ করুন" },
  "rs.lib.add.hint": {
    en: "A DOI, an ISBN, a link, or a pasted BibTeX, RIS or CSL record. Or drop a .bib, .ris or .json file on the list.",
    bn: "একটা DOI, ISBN, লিংক, বা পেস্ট করা BibTeX, RIS বা CSL রেকর্ড। অথবা তালিকার উপর একটা .bib, .ris বা .json ফাইল ছেড়ে দিন।",
  },
  "rs.lib.lookup": { en: "Look up", bn: "খুঁজুন" },
  "rs.lib.import": { en: "Import a file", bn: "ফাইল আনুন" },
  "rs.lib.imported": { en: "added", bn: "যোগ হলো" },
  "rs.lib.skipped": { en: "already there", bn: "আগেই ছিল" },
  "rs.lib.empty": {
    en: "No sources yet. Paste a DOI above, drop an export from Zotero or Scholar, or pull your Zotero library from Settings.",
    bn: "এখনো কোনো উৎস নেই। উপরে একটা DOI পেস্ট করুন, Zotero বা Scholar থেকে এক্সপোর্ট ছেড়ে দিন, বা সেটিংস থেকে আপনার Zotero লাইব্রেরি টেনে আনুন।",
  },
  "rs.lib.type": { en: "Type", bn: "ধরন" },
  "rs.lib.status": { en: "Reading", bn: "পড়া" },
  "rs.lib.status.unread": { en: "Unread", bn: "পড়া হয়নি" },
  "rs.lib.status.skimmed": { en: "Skimmed", bn: "চোখ বোলানো" },
  "rs.lib.status.read": { en: "Read", bn: "পড়া হয়েছে" },
  "rs.lib.status.annotated": { en: "Annotated", bn: "নোট করা" },
  "rs.lib.status.cited": { en: "Cited", bn: "উদ্ধৃত" },
  "rs.lib.priority": { en: "Priority", bn: "অগ্রাধিকার" },
  "rs.lib.rating": { en: "Your rating", bn: "আপনার মূল্যায়ন" },
  "rs.lib.why": { en: "Why I saved this", bn: "কেন রাখলাম" },
  "rs.lib.title": { en: "Title", bn: "শিরোনাম" },
  "rs.lib.authors": { en: "Authors", bn: "লেখক" },
  "rs.lib.authors.hint": { en: "Family, Given; Family, Given", bn: "পদবি, নাম; পদবি, নাম" },
  "rs.lib.year": { en: "Year", bn: "সাল" },
  "rs.lib.container": { en: "Journal, book or publisher", bn: "জার্নাল, বই বা প্রকাশক" },
  "rs.lib.volume": { en: "Volume", bn: "খণ্ড" },
  "rs.lib.issue": { en: "Issue", bn: "সংখ্যা" },
  "rs.lib.pages": { en: "Pages", bn: "পৃষ্ঠা" },
  "rs.lib.doi": { en: "DOI", bn: "DOI" },
  "rs.lib.url": { en: "Link", bn: "লিংক" },
  "rs.lib.abstract": { en: "Abstract", bn: "সারসংক্ষেপ" },
  "rs.lib.key": { en: "Citation key", bn: "উদ্ধৃতি কী" },
  "rs.lib.key.hint": {
    en: "Made once and never regenerated: a draft's citations hold it.",
    bn: "একবারই তৈরি হয়, আর বদলায় না: খসড়ার উদ্ধৃতিগুলো এটাই ধরে রাখে।",
  },
  "rs.lib.verified": { en: "Verified record", bn: "যাচাই করা রেকর্ড" },
  "rs.lib.unverified": { en: "Unverified: check me", bn: "যাচাই হয়নি: দেখে নিন" },
  "rs.lib.via": { en: "Added via", bn: "যেভাবে এসেছে" },
  "rs.lib.reference": { en: "Reference", bn: "রেফারেন্স" },
  "rs.lib.copybib": { en: "Copy as BibTeX", bn: "BibTeX হিসেবে কপি" },
  "rs.lib.copyris": { en: "Copy as RIS", bn: "RIS হিসেবে কপি" },
  "rs.lib.notes": { en: "Notes about this", bn: "এটা নিয়ে নোট" },
  "rs.lib.note.new": { en: "Write a literature note", bn: "পড়ার নোট লিখুন" },
  "rs.lib.bin": { en: "In the bin", bn: "বিনে" },
  "rs.lib.bin.hint": {
    en: "Kept for thirty days, then gone.",
    bn: "তিরিশ দিন রাখা হয়, তারপর চলে যায়।",
  },
  "rs.lib.open": { en: "Open", bn: "খুলুন" },
  "rs.lib.merge": {
    en: "Looks like the same paper as one already here.",
    bn: "মনে হচ্ছে এখানে আগে থেকেই থাকা একটা পেপারের সঙ্গে মিলে যাচ্ছে।",
  },

  /* ---- the notebook ---- */
  "rs.notes.kind": { en: "Kind", bn: "ধরন" },
  "rs.notes.title": { en: "Title", bn: "শিরোনাম" },
  "rs.notes.empty": {
    en: "No notes yet. Press New, or capture a thought from the board.",
    bn: "এখনো কোনো নোট নেই। নতুন চাপুন, বা বোর্ড থেকে একটা ভাবনা টুকে রাখুন।",
  },
  "rs.notes.source": { en: "About a source", bn: "যে উৎস নিয়ে" },
  "rs.notes.links": { en: "Links to", bn: "যেখানে যুক্ত" },
  "rs.notes.backlinks": { en: "Linked from", bn: "যেখান থেকে যুক্ত" },
  "rs.notes.body": { en: "The note", bn: "নোট" },
  "rs.notes.daily": { en: "Today's log", bn: "আজকের খাতা" },
  "rs.notes.daily.template": {
    en: "Time spent:\nWhat I did:\nWhat I learned:\nWhat is blocking me:\nTomorrow's first task:",
    bn: "কত সময়:\nকী করলাম:\nকী শিখলাম:\nকোথায় আটকে আছি:\nকালকের প্রথম কাজ:",
  },

  /* ---- questions ---- */
  "rs.q.new": { en: "New question", bn: "নতুন প্রশ্ন" },
  "rs.q.text": { en: "The question", bn: "প্রশ্নটা" },
  "rs.q.kind": { en: "Kind", bn: "ধরন" },
  "rs.q.state": { en: "State", bn: "অবস্থা" },
  "rs.q.state.open": { en: "Open", bn: "চলছে" },
  "rs.q.state.parked": { en: "Parked", bn: "থামানো" },
  "rs.q.state.answered": { en: "Answered", bn: "উত্তর পাওয়া" },
  "rs.q.note": { en: "Where this stands", bn: "এখন কোথায় আছে" },
  "rs.q.evidence": { en: "Evidence", bn: "প্রমাণ" },
  "rs.q.evidence.add": { en: "Add a source as evidence", bn: "উৎসকে প্রমাণ হিসেবে যোগ করুন" },
  "rs.q.evidence.empty": {
    en: "Nothing speaks to this yet. Pick a source from the library and say whether it supports it, contradicts it, gives a method, or gives context.",
    bn: "এটা নিয়ে এখনো কিছু বলে না। লাইব্রেরি থেকে একটা উৎস বেছে বলুন সেটা সমর্থন করে, খণ্ডন করে, পদ্ধতি দেয়, না প্রেক্ষাপট দেয়।",
  },
  "rs.q.stance.supports": { en: "supports", bn: "সমর্থন করে" },
  "rs.q.stance.contradicts": { en: "contradicts", bn: "খণ্ডন করে" },
  "rs.q.stance.method": { en: "gives a method", bn: "পদ্ধতি দেয়" },
  "rs.q.stance.context": { en: "gives context", bn: "প্রেক্ষাপট দেয়" },
  "rs.q.children": { en: "Under this", bn: "এর নিচে" },
  "rs.q.carried": { en: "Carried from the old desk", bn: "পুরোনো ডেস্ক থেকে আনা" },
  "rs.q.empty": {
    en: "No questions yet. A research question at the top, hypotheses under it, claims under those.",
    bn: "এখনো কোনো প্রশ্ন নেই। উপরে গবেষণার প্রশ্ন, তার নিচে অনুমান, তার নিচে দাবি।",
  },

  /* ---- tasks ---- */
  "rs.tasks.new": { en: "New task", bn: "নতুন কাজ" },
  "rs.tasks.due": { en: "Due", bn: "শেষ তারিখ" },
  "rs.tasks.empty": {
    en: "Nothing in this lane.",
    bn: "এই লেনে কিছু নেই।",
  },
  "rs.tasks.move": { en: "Move to", bn: "সরান" },
  "rs.tasks.days": { en: "days", bn: "দিন" },
  "rs.tasks.waiting.since": { en: "waiting since", bn: "অপেক্ষা শুরু" },

  /* ---- settings ---- */
  "rs.set.prefs": { en: "Preferences", bn: "পছন্দ" },
  "rs.set.name": { en: "Your name on exports", bn: "এক্সপোর্টে আপনার নাম" },
  "rs.set.affiliation": { en: "Affiliation", bn: "প্রতিষ্ঠান" },
  "rs.set.orcid": { en: "ORCID", bn: "ORCID" },
  "rs.set.style": { en: "Default citation style", bn: "ডিফল্ট উদ্ধৃতি রীতি" },
  "rs.set.dense": { en: "Dense mode", bn: "ঘন সাজানো" },
  "rs.set.dense.hint": {
    en: "Less air around everything in the studio. The one place on this site a reader may ask for less.",
    bn: "স্টুডিওর সব কিছুর চারপাশে কম ফাঁকা। এই সাইটে এটাই একমাত্র জায়গা যেখানে কম চাওয়া যায়।",
  },
  "rs.set.projects.hint": {
    en: "A doctorate, a paper, a book, an application. One source or note can belong to several.",
    bn: "একটা ডক্টরেট, একটা পেপার, একটা বই, একটা আবেদন। একটা উৎস বা নোট কয়েকটার হতে পারে।",
  },
  "rs.set.project.name": { en: "Name", bn: "নাম" },
  "rs.set.project.kind": { en: "Kind", bn: "ধরন" },
  "rs.set.project.new": { en: "New project", bn: "নতুন প্রজেক্ট" },
  "rs.set.connections": { en: "Connections", bn: "সংযোগ" },
  "rs.set.connections.hint": {
    en: "What the studio can reach from here. A service that is off is a sentence on the page, never an error.",
    bn: "স্টুডিও এখান থেকে কোথায় পৌঁছাতে পারে। যে সেবা বন্ধ, পাতায় সেটা একটা বাক্য, ভুল নয়।",
  },
  "rs.set.zotero": { en: "Pull from Zotero", bn: "Zotero থেকে আনুন" },
  "rs.set.zotero.hint": {
    en: "Your numeric user id and a read-only API key from zotero.org/settings/keys. Neither is stored: they are used for this one pull and forgotten.",
    bn: "zotero.org/settings/keys থেকে আপনার সংখ্যার ইউজার আইডি আর শুধু-পড়ার API কী। কোনোটাই রাখা হয় না: এই একবার টানার জন্য ব্যবহার হয়, তারপর ভুলে যাওয়া হয়।",
  },
  "rs.set.zotero.user": { en: "Zotero user id", bn: "Zotero ইউজার আইডি" },
  "rs.set.zotero.key": { en: "API key", bn: "API কী" },
  "rs.set.zotero.go": { en: "Pull the library", bn: "লাইব্রেরি টানুন" },
  "rs.set.clipper": { en: "Save to the studio", bn: "স্টুডিওতে রাখুন" },
  "rs.set.clipper.hint": {
    en: "Drag this to your bookmarks bar. On a paper's page, press it and the paper is filed here.",
    bn: "এটা আপনার বুকমার্ক বারে টেনে নিন। কোনো পেপারের পাতায় থাকা অবস্থায় চাপলে পেপারটা এখানে রাখা হবে।",
  },
  "rs.set.on": { en: "connected", bn: "সংযুক্ত" },
  "rs.set.off": { en: "not connected", bn: "সংযুক্ত নয়" },

  /* ---- the archive ---- */
  "rs.arc.activity": { en: "Everything that happened", bn: "যা যা হয়েছে" },
  "rs.arc.activity.empty": {
    en: "Every write the studio makes is a line here, so nothing is lost and everything can be found again.",
    bn: "স্টুডিও যা লেখে তার প্রতিটি এখানে এক লাইন, তাই কিছু হারায় না আর সব আবার খুঁজে পাওয়া যায়।",
  },
  "rs.arc.export": { en: "Take a copy", bn: "একটা কপি নিন" },
  "rs.arc.export.hint": {
    en: "Every row of the studio as JSON, and the library as BibTeX and RIS beside it.",
    bn: "স্টুডিওর প্রতিটি সারি JSON হিসেবে, আর পাশে লাইব্রেরি BibTeX আর RIS হিসেবে।",
  },
  "rs.arc.versions": { en: "Versions", bn: "সংস্করণ" },
  "rs.arc.bin": { en: "The bin", bn: "বিন" },

  /* ---- the reading room ---- */
  "rs.read.queue": { en: "Up next", bn: "এরপর" },
  "rs.read.queue.hint": { en: "Every source with a file or a book to read, the important ones first. Enter opens the top one.", bn: "যেসব উৎসে ফাইল আছে বা বই পড়ার আছে, জরুরিগুলো আগে। Enter চাপলে প্রথমটা খোলে।" },
  "rs.read.queue.empty": { en: "Nothing waiting. Add a PDF to a source in the library and it will be here.", bn: "কিছু অপেক্ষায় নেই। লাইব্রেরির কোনো উৎসে PDF যোগ করলে এখানে আসবে।" },
  "rs.read.open": { en: "Open", bn: "খুলুন" },
  "rs.read.back": { en: "Back to the queue", bn: "সারিতে ফিরুন" },
  "rs.read.pages": { en: "pages", bn: "পাতা" },
  "rs.read.page": { en: "Page", bn: "পাতা" },
  "rs.read.of": { en: "of", bn: "এর মধ্যে" },
  "rs.read.nofile": { en: "No file on this source yet.", bn: "এই উৎসে এখনো কোনো ফাইল নেই।" },
  "rs.read.loading": { en: "Opening the file", bn: "ফাইল খুলছে" },
  "rs.read.failed": { en: "Could not open the file.", bn: "ফাইলটা খোলা গেল না।" },
  "rs.read.notext": { en: "This file has no text layer, so nothing can be selected. A scanned PDF needs OCR, which is a later stage.", bn: "এই ফাইলে লেখার স্তর নেই, তাই কিছু বাছাই করা যাবে না। স্ক্যান করা PDF-এর জন্য OCR লাগে, সেটা পরের ধাপে।" },
  "rs.read.keys": { en: "Select some text and press 1 to 5. j and k turn the page.", bn: "কিছু লেখা বাছাই করে ১ থেকে ৫ চাপুন। j আর k পাতা ওল্টায়।" },
  "rs.read.highlights": { en: "Highlights", bn: "হাইলাইট" },
  "rs.read.highlights.empty": { en: "Nothing marked yet.", bn: "এখনো কিছু চিহ্নিত হয়নি।" },
  "rs.read.meaning": { en: "Meaning", bn: "অর্থ" },
  "rs.read.note": { en: "A note beside it", bn: "পাশে একটা নোট" },
  "rs.read.card": { en: "Extraction card", bn: "নিষ্কাশন কার্ড" },
  "rs.read.number": { en: "Number", bn: "সংখ্যা" },
  "rs.read.unit": { en: "Unit", bn: "একক" },
  "rs.read.n": { en: "Sample size", bn: "নমুনার আকার" },
  "rs.read.method": { en: "Method", bn: "পদ্ধতি" },
  "rs.read.finding": { en: "Finding, in one line", bn: "ফলাফল, এক লাইনে" },
  "rs.read.remove": { en: "Remove", bn: "মুছুন" },
  "rs.read.goto": { en: "Go to it", bn: "সেখানে যান" },
  "rs.read.done": { en: "Mark as read", bn: "পড়া হয়েছে" },
  "rs.read.said": { en: "What did this say, in one line?", bn: "এটা এক লাইনে কী বলল?" },
  "rs.read.said.hint": { en: "It becomes the first line of the literature note. Asked once.", bn: "এটা সাহিত্য-নোটের প্রথম লাইন হয়। একবারই জিজ্ঞেস করা হয়।" },
  "rs.read.said.keep": { en: "Keep it", bn: "রাখুন" },
  "rs.read.said.skip": { en: "Not now", bn: "এখন না" },
  "rs.read.typed": { en: "From the page, typed", bn: "পাতা থেকে, টাইপ করা" },
  "rs.read.typed.hint": { en: "A book is a physical thing: type the page and the passage, and it is marked as typed.", bn: "বই একটা বাস্তব জিনিস: পাতা আর অংশটা টাইপ করুন, সেটা টাইপ-করা বলে চিহ্নিত থাকবে।" },
  "rs.read.typed.page": { en: "Page", bn: "পাতা" },
  "rs.read.typed.text": { en: "The passage", bn: "অংশটা" },
  "rs.read.typed.add": { en: "Add", bn: "যোগ করুন" },
  "rs.read.audio.start": { en: "Mark from here", bn: "এখান থেকে চিহ্ন" },
  "rs.read.audio.end": { en: "To here", bn: "এখান পর্যন্ত" },
  "rs.read.audio.hint": { en: "A highlight in audio is a time range: mark where it starts, then where it ends, then its meaning.", bn: "অডিওতে হাইলাইট মানে সময়ের একটা পরিসর: শুরু চিহ্নিত করুন, তারপর শেষ, তারপর অর্থ।" },
  "rs.read.zoom.in": { en: "Larger", bn: "বড়" },
  "rs.read.zoom.out": { en: "Smaller", bn: "ছোট" },
  "rs.read.next": { en: "Next page", bn: "পরের পাতা" },
  "rs.read.prev": { en: "Previous page", bn: "আগের পাতা" },
  "rs.read.capture": { en: "Captured page", bn: "ধরা পাতা" },
  "rs.read.data": { en: "A data file. The lab reads it in stage 8.", bn: "একটা ডেটা ফাইল। ল্যাব এটা ধাপ ৮-এ পড়ে।" },
  "rs.lib.files": { en: "Files", bn: "ফাইল" },
  "rs.lib.file.add": { en: "Add a file", bn: "ফাইল যোগ করুন" },
  "rs.lib.file.hint": { en: "A PDF, audio, a data file or a picture, up to 100 MB. Stored on your account.", bn: "PDF, অডিও, ডেটা ফাইল বা ছবি, ১০০ MB পর্যন্ত। আপনার অ্যাকাউন্টে রাখা হয়।" },
  "rs.lib.file.capture": { en: "Capture the web page", bn: "ওয়েব পাতাটা ধরে রাখুন" },
  "rs.lib.file.capture.hint": { en: "The page at this source's address, fetched and kept as it is today, so it can be read and marked here even after it changes.", bn: "এই উৎসের ঠিকানার পাতাটা আজ যেমন আছে তেমন এনে রাখা, যাতে বদলে গেলেও এখানে পড়া ও চিহ্নিত করা যায়।" },
  "rs.lib.file.remove": { en: "Detach", bn: "আলাদা করুন" },
  "rs.lib.read": { en: "Read", bn: "পড়ুন" },
  "rs.lib.uploading": { en: "Sending the file", bn: "ফাইল পাঠাচ্ছে" },
  "rs.lib.file.failed": { en: "The file was not stored.", bn: "ফাইলটা রাখা যায়নি।" },
  "rs.lib.file.quota": { en: "That would take you over the space your account has.", bn: "এতে আপনার অ্যাকাউন্টের জায়গা পেরিয়ে যাবে।" },
  "rs.set.files": { en: "Files", bn: "ফাইল" },
  "rs.set.files.hint": { en: "What the reading room holds on your account, against the space it has.", bn: "পড়ার ঘর আপনার অ্যাকাউন্টে যা রাখে, তার জায়গার তুলনায়।" },

  /* ---- finding ---- */
  "rs.findroom.q": { en: "Search every index", bn: "সব সূচিতে খুঁজুন" },
  "rs.findroom.q.hint": { en: "Words from the title, the abstract or the topic. Every index that is on is asked at once and the answers are merged.", bn: "শিরোনাম, সারাংশ বা বিষয়ের শব্দ। যেসব সূচি চালু আছে সবগুলোকে একসাথে জিজ্ঞেস করা হয়, উত্তর মেলানো হয়।" },
  "rs.findroom.go": { en: "Search", bn: "খুঁজুন" },
  "rs.findroom.save": { en: "Keep this search", bn: "এই খোঁজ রাখুন" },
  "rs.findroom.author": { en: "Author", bn: "লেখক" },
  "rs.findroom.from": { en: "From", bn: "থেকে" },
  "rs.findroom.to": { en: "To", bn: "পর্যন্ত" },
  "rs.findroom.anytype": { en: "Any type", bn: "যেকোনো ধরন" },
  "rs.findroom.oa": { en: "Free copies only", bn: "শুধু বিনামূল্যের কপি" },
  "rs.findroom.databases": { en: "Ask:", bn: "জিজ্ঞেস করুন:" },
  "rs.findroom.searching": { en: "Asking the indexes", bn: "সূচিগুলোকে জিজ্ঞেস করছে" },
  "rs.findroom.failed": { en: "The search did not answer. Try again in a moment.", bn: "খোঁজে উত্তর আসেনি। একটু পরে আবার চেষ্টা করুন।" },
  "rs.findroom.noanswer": { en: "did not answer", bn: "উত্তর দেয়নি" },
  "rs.findroom.none": { en: "Nothing found. Fewer words, or another index.", bn: "কিছু পাওয়া যায়নি। কম শব্দ, বা অন্য সূচি।" },
  "rs.findroom.empty": { en: "Type something above. A row already in your library says so, with its status.", bn: "উপরে কিছু লিখুন। লাইব্রেরিতে আগে থেকে থাকা সারি নিজেই বলবে, অবস্থাসহ।" },
  "rs.findroom.add": { en: "Add", bn: "যোগ করুন" },
  "rs.findroom.saved": { en: "Kept searches", bn: "রাখা খোঁজ" },
  "rs.findroom.saved.hint": { en: "Each one is a line of the search log a review prints. Switch the alert on and it is rerun every Monday; what is new lands in the inbox.", bn: "প্রতিটা রিভিউয়ের খোঁজ-লগের এক লাইন। সতর্কতা চালু করলে প্রতি সোমবার আবার চলে; নতুন যা আসে ইনবক্সে জমা হয়।" },
  "rs.findroom.alert.on": { en: "Alert on", bn: "সতর্কতা চালু" },
  "rs.findroom.alert.off": { en: "Alert off", bn: "সতর্কতা বন্ধ" },
  "rs.findroom.alerted": { en: "New from your alerts, filed in the inbox:", bn: "আপনার সতর্কতা থেকে নতুন, ইনবক্সে রাখা হলো:" },
  "rs.findroom.related": { en: "Related", bn: "সম্পর্কিত" },
  "rs.findroom.show": { en: "Show", bn: "দেখান" },
  "rs.findroom.citedby": { en: "Cited by", bn: "উদ্ধৃত করেছে" },
  "rs.findroom.references": { en: "References", bn: "তথ্যসূত্র" },

  /* ---- the writing desk ---- */
  "rs.write.documents": { en: "Documents", bn: "দলিল" },
  "rs.write.new": { en: "New document", bn: "নতুন দলিল" },
  "rs.write.title": { en: "Title", bn: "শিরোনাম" },
  "rs.write.kind": { en: "Kind", bn: "ধরন" },
  "rs.write.state": { en: "State", bn: "অবস্থা" },
  "rs.write.style": { en: "Citation style", bn: "উদ্ধৃতির রীতি" },
  "rs.write.budget": { en: "Word budget", bn: "শব্দের বাজেট" },
  "rs.write.empty": { en: "Nothing on the desk yet. Start a chapter, a paper or a proposal.", bn: "ডেস্কে এখনো কিছু নেই। একটা অধ্যায়, পেপার বা প্রস্তাব শুরু করুন।" },
  "rs.write.pick": { en: "Choose a document on the left, or start one.", bn: "বাঁয়ে একটা দলিল বেছে নিন, বা নতুন শুরু করুন।" },
  "rs.write.cite": { en: "Cite", bn: "উদ্ধৃত করুন" },
  "rs.write.cite.hint": { en: "Type @ in the text, or press this: pick a source, add a page, Enter.", bn: "লেখায় @ চাপুন, বা এটা: উৎস বাছুন, পাতা দিন, Enter।" },
  "rs.write.cite.find": { en: "Find a source", bn: "উৎস খুঁজুন" },
  "rs.write.cite.locator": { en: "Page", bn: "পাতা" },
  "rs.write.cite.insert": { en: "Insert", bn: "বসান" },
  "rs.write.footnote": { en: "Footnote", bn: "পাদটীকা" },
  "rs.write.footnote.hint": { en: "A marker where the caret is and a note at the foot, numbered by position. OSCOLA and Chicago notes cite here.", bn: "কার্সর যেখানে সেখানে চিহ্ন, নিচে টীকা, অবস্থান অনুযায়ী নম্বর। OSCOLA আর Chicago notes এখানেই উদ্ধৃত করে।" },
  "rs.write.quote": { en: "Quote a highlight", bn: "হাইলাইট উদ্ধৃত করুন" },
  "rs.write.render": { en: "Refresh citations", bn: "উদ্ধৃতি নতুন করে সাজান" },
  "rs.write.bibliography": { en: "Bibliography", bn: "গ্রন্থপঞ্জি" },
  "rs.write.outline": { en: "Outline", bn: "রূপরেখা" },
  "rs.write.outline.hint": { en: "The headings in the text, with the words under each. A budget on a heading fills a meter.", bn: "লেখার শিরোনামগুলো, প্রতিটার নিচের শব্দসহ। শিরোনামে বাজেট দিলে মিটার ভরে।" },
  "rs.write.outline.empty": { en: "No headings yet. Type a heading in the text and it appears here.", bn: "এখনো শিরোনাম নেই। লেখায় শিরোনাম দিন, এখানে দেখা যাবে।" },
  "rs.write.words": { en: "words", bn: "শব্দ" },
  "rs.write.minutes": { en: "min read", bn: "মিনিটে পড়া" },
  "rs.write.citations": { en: "citations", bn: "উদ্ধৃতি" },
  "rs.write.of": { en: "of", bn: "এর মধ্যে" },
  "rs.write.audit": { en: "Claims audit", bn: "দাবির হিসাব" },
  "rs.write.audit.hint": { en: "Every sentence with a number or a claim word, and whether a citation sits in it. The ones without are yours to work through.", bn: "সংখ্যা বা দাবির শব্দসহ প্রতিটা বাক্য, আর তাতে উদ্ধৃতি আছে কি না। যেগুলোতে নেই, সেগুলো আপনার কাজ।" },
  "rs.write.audit.clean": { en: "Every claim carries a citation.", bn: "প্রতিটা দাবিতে উদ্ধৃতি আছে।" },
  "rs.write.audit.uncited": { en: "without a citation", bn: "উদ্ধৃতি ছাড়া" },
  "rs.write.overlap": { en: "Overlap check", bn: "মিল পরীক্ষা" },
  "rs.write.overlap.hint": { en: "Runs of eight or more words shared with a source's abstract, a note, or another document. It reads only what the studio holds and is not a plagiarism service.", bn: "উৎসের সারাংশ, নোট বা অন্য দলিলের সাথে মিলে যাওয়া আট বা তার বেশি শব্দের টানা অংশ। এটা শুধু স্টুডিওর ভেতরের লেখা পড়ে; কুম্ভীলকতা যাচাইয়ের সেবা নয়।" },
  "rs.write.overlap.clean": { en: "No run of eight words shared with anything the studio holds.", bn: "স্টুডিওর কিছুর সাথে আট শব্দের কোনো টানা মিল নেই।" },
  "rs.write.snapshot": { en: "Snapshot", bn: "স্ন্যাপশট" },
  "rs.write.snapshot.hint": { en: "A named version, kept whatever the ten-minute rule says: sent to supervisor, submitted, before the rewrite.", bn: "নামসহ একটা সংস্করণ, দশ মিনিটের নিয়ম যা-ই বলুক রাখা থাকে: সুপারভাইজারকে পাঠানো, জমা দেওয়া, নতুন করে লেখার আগে।" },
  "rs.write.snapshot.name": { en: "Name this version", bn: "এই সংস্করণের নাম" },
  "rs.write.versions": { en: "Versions", bn: "সংস্করণ" },
  "rs.write.restore": { en: "Open this version", bn: "এই সংস্করণ খুলুন" },
  "rs.write.export": { en: "Export", bn: "রপ্তানি" },
  "rs.write.export.word": { en: "Word", bn: "Word" },
  "rs.write.export.md": { en: "Markdown", bn: "Markdown" },
  "rs.write.export.tex": { en: "LaTeX + BibTeX", bn: "LaTeX + BibTeX" },
  "rs.write.export.print": { en: "Print or PDF", bn: "ছাপা বা PDF" },
  "rs.write.author": { en: "Author", bn: "লেখক" },
  "rs.write.affiliation": { en: "Affiliation", bn: "প্রতিষ্ঠান" },
  "rs.write.conflict": { en: "Somebody else wrote first, usually you on a phone. Reload to see it.", bn: "কেউ আগে লিখেছে, সাধারণত আপনিই ফোনে। দেখতে রিলোড করুন।" },

  /* ---- the planner ---- */
  "rs.plan.board": { en: "Board", bn: "বোর্ড" },
  "rs.plan.dates": { en: "Dates", bn: "তারিখ" },
  "rs.plan.timeline": { en: "Timeline", bn: "সময়রেখা" },
  "rs.plan.sessions": { en: "Sessions", bn: "সেশন" },
  "rs.plan.week": { en: "This week", bn: "এই সপ্তাহ" },
  "rs.plan.week.review": { en: "Weekly review", bn: "সাপ্তাহিক পর্যালোচনা" },
  "rs.plan.event.new": { en: "Add a date", bn: "তারিখ যোগ করুন" },
  "rs.plan.event.title": { en: "What", bn: "কী" },
  "rs.plan.event.kind": { en: "Kind", bn: "ধরন" },
  "rs.plan.event.when": { en: "When", bn: "কবে" },
  "rs.plan.event.until": { en: "Until", bn: "পর্যন্ত" },
  "rs.plan.event.place": { en: "Where", bn: "কোথায়" },
  "rs.plan.event.done": { en: "Done", bn: "হয়েছে" },
  "rs.plan.next": { en: "Next five dates", bn: "পরের পাঁচটা তারিখ" },
  "rs.plan.past": { en: "Past", bn: "অতীত" },
  "rs.plan.none": { en: "No dates yet. A deadline, a meeting, a conference or a submission goes here.", bn: "এখনো কোনো তারিখ নেই। শেষ তারিখ, সভা, সম্মেলন বা জমা এখানে যায়।" },
  "rs.plan.meeting.agenda": { en: "Agenda", bn: "আলোচ্যসূচি" },
  "rs.plan.meeting.minutes": { en: "Minutes", bn: "কার্যবিবরণী" },
  "rs.plan.meeting.decisions": { en: "Decisions", bn: "সিদ্ধান্ত" },
  "rs.plan.meeting.actions": { en: "Actions, one a line; each becomes a task", bn: "করণীয়, প্রতি লাইনে একটা; প্রতিটা কাজ হয়ে যায়" },
  "rs.plan.meeting.people": { en: "Who", bn: "কারা" },
  "rs.plan.submission.journal": { en: "Journal", bn: "জার্নাল" },
  "rs.plan.submission.status": { en: "Status", bn: "অবস্থা" },
  "rs.plan.submission.comments": { en: "Reviewers' comments", bn: "পর্যালোচকদের মন্তব্য" },
  "rs.plan.submission.comment": { en: "Comment", bn: "মন্তব্য" },
  "rs.plan.submission.response": { en: "Response", bn: "জবাব" },
  "rs.plan.submission.change": { en: "Change made", bn: "যে বদল করা হলো" },
  "rs.plan.submission.add": { en: "Add a comment", bn: "মন্তব্য যোগ করুন" },
  "rs.plan.timeline.hint": { en: "The year's dates and documents, the present as a line, the past shaded.", bn: "বছরের তারিখ আর দলিল, বর্তমান একটা রেখা, অতীত ছায়াময়।" },
  "rs.plan.session.start": { en: "Start a session", bn: "সেশন শুরু" },
  "rs.plan.session.stop": { en: "Stop", bn: "থামুন" },
  "rs.plan.session.running": { en: "Session running", bn: "সেশন চলছে" },
  "rs.plan.session.note": { en: "What was done", bn: "কী করা হলো" },
  "rs.plan.session.hint": { en: "Twenty-five minutes by default, a bell at the end, and a line in the daily log when it stops. No count, no chart.", bn: "সাধারণত পঁচিশ মিনিট, শেষে ঘণ্টা, আর থামলে দৈনিক লগে এক লাইন। কোনো গণনা নেই, চার্ট নেই।" },
  "rs.plan.session.room": { en: "Room", bn: "ঘর" },
  "rs.plan.session.today": { en: "Today", bn: "আজ" },
  "rs.plan.minutes": { en: "min", bn: "মিনিট" },
  "rs.plan.calendar": { en: "Calendar feed", bn: "ক্যালেন্ডার ফিড" },
  "rs.plan.calendar.hint": { en: "Your dates as a subscription address for Google Calendar, Outlook or a phone. The studio holds nothing of theirs.", bn: "আপনার তারিখগুলো Google Calendar, Outlook বা ফোনের জন্য সাবস্ক্রিপশন ঠিকানা হিসেবে। স্টুডিও ওদের কিছু রাখে না।" },
  "rs.plan.calendar.make": { en: "Make the address", bn: "ঠিকানা তৈরি করুন" },
  "rs.plan.calendar.reset": { en: "New address", bn: "নতুন ঠিকানা" },
  "rs.plan.calendar.copy": { en: "Copy", bn: "কপি" },
  "rs.plan.wk.done": { en: "Done this week", bn: "এই সপ্তাহে হয়েছে" },
  "rs.plan.wk.next": { en: "Next", bn: "এরপর" },
  "rs.plan.wk.waiting": { en: "Waiting, and for how long", bn: "অপেক্ষায়, কতদিন" },
  "rs.plan.wk.read": { en: "Read this week", bn: "এই সপ্তাহে পড়া" },
  "rs.plan.wk.time": { en: "Time in sessions", bn: "সেশনে সময়" },
  "rs.plan.wk.note": { en: "The week's note", bn: "সপ্তাহের নোট" },
  "rs.plan.wk.note.hint": { en: "One box, kept as the week's daily note.", bn: "একটা বাক্স, সপ্তাহের দৈনিক নোট হিসেবে রাখা।" },
  "rs.plan.wk.save": { en: "Keep", bn: "রাখুন" },
  "rs.plan.wk.days": { en: "days", bn: "দিন" },
  "rs.plan.wk.nothing": { en: "Nothing yet.", bn: "এখনো কিছু নেই।" },

  /* ---- questions and the atlas ---- */
  "rs.atlas.graph": { en: "Graph", bn: "গ্রাফ" },
  "rs.atlas.graph.hint": { en: "Sources, notes, questions, documents and people as dots; every link, citation and evidence row as a line. A view of the rows, never edited here. Press a dot to open its page.", bn: "উৎস, নোট, প্রশ্ন, দলিল আর মানুষ বিন্দু হিসেবে; প্রতিটা লিংক, উদ্ধৃতি আর প্রমাণ একটা রেখা। সারিগুলোর একটা দৃশ্য, এখানে বদলানো হয় না। বিন্দু চাপলে তার পাতা খোলে।" },
  "rs.atlas.network": { en: "Citation network", bn: "উদ্ধৃতির জাল" },
  "rs.atlas.network.hint": { en: "Two hops out from a source with a DOI, through OpenAlex: what it cites and what cites it. Hollow dots are not in the library yet; press to add.", bn: "DOI-ওয়ালা উৎস থেকে দুই ধাপ বাইরে, OpenAlex-এর মধ্য দিয়ে: যা উদ্ধৃত করে আর যারা একে উদ্ধৃত করে। ফাঁপা বিন্দু এখনো লাইব্রেরিতে নেই; চাপলে যোগ হয়।" },
  "rs.atlas.network.pick": { en: "Start from", bn: "শুরু করুন" },
  "rs.atlas.timeline": { en: "Literature timeline", bn: "সাহিত্যের সময়রেখা" },
  "rs.atlas.timeline.hint": { en: "The library on a year axis, one dot a source, coloured by type, your tags as lanes.", bn: "বছরের অক্ষে লাইব্রেরি, প্রতি উৎস একটা বিন্দু, ধরন অনুযায়ী রং, আপনার ট্যাগ লেন হিসেবে।" },
  "rs.atlas.lanes": { en: "Lanes (tags, comma separated)", bn: "লেন (ট্যাগ, কমা দিয়ে)" },
  "rs.atlas.people": { en: "People", bn: "মানুষ" },
  "rs.atlas.people.hint": { en: "Supervisors, authors, examiners, gatekeepers. An ORCID brings what they have published.", bn: "সুপারভাইজার, লেখক, পরীক্ষক, দ্বাররক্ষী। ORCID দিলে তাঁদের প্রকাশনা আসে।" },
  "rs.atlas.person.new": { en: "Add a person", bn: "একজন যোগ করুন" },
  "rs.atlas.person.name": { en: "Name", bn: "নাম" },
  "rs.atlas.person.role": { en: "Role", bn: "ভূমিকা" },
  "rs.atlas.person.orcid": { en: "ORCID", bn: "ORCID" },
  "rs.atlas.person.email": { en: "Email", bn: "ইমেইল" },
  "rs.atlas.person.institution": { en: "Institution", bn: "প্রতিষ্ঠান" },
  "rs.atlas.person.fit": { en: "Fit", bn: "মিল" },
  "rs.atlas.person.note": { en: "Notes", bn: "নোট" },
  "rs.atlas.person.works": { en: "Published, by ORCID", bn: "প্রকাশিত, ORCID অনুযায়ী" },
  "rs.atlas.person.none": { en: "Nobody yet.", bn: "এখনো কেউ নেই।" },
  "rs.atlas.empty": { en: "Nothing to draw yet.", bn: "এখনো আঁকার কিছু নেই।" },
  "rs.atlas.kinds": { en: "Show", bn: "দেখান" },
  "rs.q.map": { en: "Argument map", bn: "যুক্তির মানচিত্র" },
  "rs.q.map.hint": { en: "Questions down the side, sources across the top, a mark where a source speaks to a question: supports, contradicts, method, context.", bn: "পাশে প্রশ্ন, উপরে উৎস, যেখানে কোনো উৎস কোনো প্রশ্ন নিয়ে বলে সেখানে চিহ্ন: সমর্থন, বিরোধ, পদ্ধতি, প্রসঙ্গ।" },
  "rs.q.gaps": { en: "Gap matrix", bn: "ফাঁকের ছক" },
  "rs.q.gaps.hint": { en: "Rows of your tags, columns of sources, and the empty cells are the gaps. Derived from the library, never maintained.", bn: "সারিতে আপনার ট্যাগ, কলামে উৎস, খালি ঘরগুলোই ফাঁক। লাইব্রেরি থেকে গড়া, আলাদা করে রাখতে হয় না।" },
  "rs.q.gaps.count": { en: "gaps", bn: "ফাঁক" },
  "rs.q.variables": { en: "Variables", bn: "চলক" },
  "rs.q.variables.hint": { en: "Every construct, how it is measured, and which source first defined it that way. The lab offers these names when a column is described.", bn: "প্রতিটা ধারণা, কীভাবে মাপা হয়, আর কোন উৎস প্রথম এভাবে সংজ্ঞা দিল। কলাম বর্ণনার সময় ল্যাব এই নামগুলো দেখায়।" },
  "rs.q.variables.measure": { en: "Measured by", bn: "মাপা হয়" },
  "rs.q.variables.new": { en: "Add a variable", bn: "চলক যোগ করুন" },
  "rs.q.tree": { en: "Tree", bn: "গাছ" },
  "rs.atlas.lanes.eg": { en: "banks, insurance, climate", bn: "ব্যাংক, বিমা, জলবায়ু" },
  "rs.evidence": { en: "Evidence", bn: "প্রমাণ" },

  /* ---- the review room ---- */
  "rs.rev.reviews": { en: "Reviews", bn: "পর্যালোচনা" },
  "rs.rev.new": { en: "Start a review", bn: "পর্যালোচনা শুরু করুন" },
  "rs.rev.title": { en: "Title", bn: "শিরোনাম" },
  "rs.rev.kind": { en: "Kind", bn: "ধরন" },
  "rs.rev.state": { en: "Stage", bn: "ধাপ" },
  "rs.rev.empty": { en: "No review yet. A systematic, scoping or narrative review starts with a protocol.", bn: "এখনো কোনো পর্যালোচনা নেই। পদ্ধতিগত, পরিধি বা বর্ণনামূলক পর্যালোচনা শুরু হয় প্রোটোকল দিয়ে।" },
  "rs.rev.pick": { en: "Choose a review on the left, or start one.", bn: "বাঁয়ে একটা পর্যালোচনা বেছে নিন, বা শুরু করুন।" },
  "rs.rev.protocol": { en: "Protocol", bn: "প্রোটোকল" },
  "rs.rev.protocol.hint": { en: "The question in a frame, the criteria with an id each, the databases, the dates and the languages. Versioned: a protocol that changed says when.", bn: "কাঠামোয় প্রশ্ন, প্রতিটার আইডিসহ মানদণ্ড, ডেটাবেস, তারিখ আর ভাষা। সংস্করণসহ: বদলানো প্রোটোকল বলে কবে বদলেছে।" },
  "rs.rev.frame": { en: "Frame", bn: "কাঠামো" },
  "rs.rev.criteria": { en: "Criteria", bn: "মানদণ্ড" },
  "rs.rev.criteria.hint": { en: "One a line. Start a line with minus for an exclusion. Each gets an id the exclusions point at.", bn: "প্রতি লাইনে একটা। বাদ দেওয়ার মানদণ্ড মাইনাস দিয়ে শুরু করুন। প্রতিটা একটা আইডি পায়, বাদগুলো সেদিকে নির্দেশ করে।" },
  "rs.rev.databases": { en: "Databases", bn: "ডেটাবেস" },
  "rs.rev.from": { en: "From", bn: "থেকে" },
  "rs.rev.to": { en: "To", bn: "পর্যন্ত" },
  "rs.rev.languages": { en: "Languages", bn: "ভাষা" },
  "rs.rev.columns": { en: "Extraction columns", bn: "নিষ্কাশনের কলাম" },
  "rs.rev.columns.hint": { en: "Comma separated: sample, country, period, method, finding, effect size.", bn: "কমা দিয়ে: নমুনা, দেশ, সময়কাল, পদ্ধতি, ফলাফল, প্রভাবের আকার।" },
  "rs.rev.appraisal": { en: "Appraisal template", bn: "মূল্যায়নের ছক" },
  "rs.rev.search": { en: "Search log", bn: "খোঁজের লগ" },
  "rs.rev.search.hint": { en: "Every kept search with this review on it: database, string, date, hits. Run a search in Find and keep it here, or import its hits as records.", bn: "এই পর্যালোচনায় রাখা প্রতিটা খোঁজ: ডেটাবেস, শব্দ, তারিখ, ফলাফল। Find-এ খুঁজে এখানে রাখুন, বা ফলাফলগুলো রেকর্ড হিসেবে আনুন।" },
  "rs.rev.import": { en: "Import hits as records", bn: "ফলাফল রেকর্ড হিসেবে আনুন" },
  "rs.rev.imported": { en: "records imported", bn: "রেকর্ড আনা হলো" },
  "rs.rev.dedupe": { en: "Mark duplicates", bn: "দ্বিত্ব চিহ্নিত করুন" },
  "rs.rev.screen": { en: "Screen", bn: "যাচাই" },
  "rs.rev.screen.hint": { en: "y include, x exclude with a reason by number, m maybe, j and k to move. Full text is the same page with the reader beside it.", bn: "y অন্তর্ভুক্ত, x কারণ-নম্বরসহ বাদ, m হয়তো, j আর k সরতে। পূর্ণ লেখা একই পাতা, পাশে পাঠক।" },
  "rs.rev.screen.title": { en: "Title and abstract", bn: "শিরোনাম ও সারাংশ" },
  "rs.rev.screen.fulltext": { en: "Full text", bn: "পূর্ণ লেখা" },
  "rs.rev.screen.done": { en: "Nothing left to screen at this stage.", bn: "এই ধাপে যাচাইয়ের কিছু বাকি নেই।" },
  "rs.rev.include": { en: "Include", bn: "অন্তর্ভুক্ত" },
  "rs.rev.exclude": { en: "Exclude", bn: "বাদ" },
  "rs.rev.maybe": { en: "Maybe", bn: "হয়তো" },
  "rs.rev.reason": { en: "Reason", bn: "কারণ" },
  "rs.rev.of": { en: "of", bn: "এর মধ্যে" },
  "rs.rev.prisma": { en: "PRISMA", bn: "PRISMA" },
  "rs.rev.prisma.hint": { en: "Counts of records by stage and reason, drawn from the rows and never typed. Change a decision and the diagram changes.", bn: "ধাপ আর কারণ অনুযায়ী রেকর্ডের গণনা, সারি থেকে আঁকা, কখনো টাইপ করা নয়। সিদ্ধান্ত বদলালে চিত্র বদলায়।" },
  "rs.rev.prisma.identified": { en: "Records identified", bn: "চিহ্নিত রেকর্ড" },
  "rs.rev.prisma.duplicates": { en: "Duplicates removed", bn: "দ্বিত্ব সরানো" },
  "rs.rev.prisma.screened": { en: "Records screened", bn: "যাচাই করা রেকর্ড" },
  "rs.rev.prisma.excluded": { en: "Records excluded", bn: "বাদ দেওয়া রেকর্ড" },
  "rs.rev.prisma.sought": { en: "Reports sought for retrieval", bn: "পূর্ণ লেখা চাওয়া" },
  "rs.rev.prisma.assessed": { en: "Reports assessed for eligibility", bn: "যোগ্যতা যাচাই" },
  "rs.rev.prisma.excluded.full": { en: "Reports excluded, by reason", bn: "বাদ, কারণসহ" },
  "rs.rev.prisma.included": { en: "Studies included", bn: "অন্তর্ভুক্ত গবেষণা" },
  "rs.rev.prisma.pending": { en: "awaiting a decision", bn: "সিদ্ধান্তের অপেক্ষায়" },
  "rs.rev.extract": { en: "Extraction", bn: "নিষ্কাশন" },
  "rs.rev.extract.hint": { en: "One row per included source, the columns yours, prefilled from the extraction cards made while reading. Exports as CSV.", bn: "প্রতিটা অন্তর্ভুক্ত উৎসে এক সারি, কলাম আপনার, পড়ার সময়ের নিষ্কাশন কার্ড থেকে আগে থেকে ভরা। CSV হিসেবে রপ্তানি।" },
  "rs.rev.extract.csv": { en: "CSV", bn: "CSV" },
  "rs.rev.appraise": { en: "Appraisal", bn: "মূল্যায়ন" },
  "rs.rev.appraise.hint": { en: "A checklist per included source; the score is derived and the answers kept.", bn: "প্রতিটা অন্তর্ভুক্ত উৎসে একটা চেকলিস্ট; নম্বর গণনা করা, উত্তর রাখা।" },
  "rs.rev.yes": { en: "Yes", bn: "হ্যাঁ" },
  "rs.rev.no": { en: "No", bn: "না" },
  "rs.rev.unclear": { en: "Unclear", bn: "অস্পষ্ট" },
  "rs.rev.score": { en: "Score", bn: "নম্বর" },
  "rs.rev.synthesis": { en: "Synthesis", bn: "সংশ্লেষ" },
  "rs.rev.synthesis.hint": { en: "Themes: the included sources' tags as a matrix, the empty cells the gaps.", bn: "থিম: অন্তর্ভুক্ত উৎসের ট্যাগ একটা ছকে, খালি ঘরগুলো ফাঁক।" },
  "rs.rev.records": { en: "records", bn: "রেকর্ড" },
  "rs.rev.query": { en: "Search string", bn: "খোঁজের শব্দ" },
  "rs.rev.run": { en: "Search, keep and import", bn: "খুঁজুন, রাখুন ও আনুন" },
  "rs.rev.hits": { en: "hits", bn: "ফলাফল" },
  "rs.rev.date": { en: "Date", bn: "তারিখ" },
  "rs.rev.duplicates.marked": { en: "duplicates marked", bn: "দ্বিত্ব চিহ্নিত" },
  "rs.rev.decided": { en: "decided", bn: "সিদ্ধান্ত হয়েছে" },
  "rs.rev.pickreason": { en: "Exclude: press the reason's number, Escape to keep it.", bn: "বাদ: কারণের নম্বর চাপুন, রাখতে Escape।" },
  "rs.rev.noreason": { en: "Add exclusion criteria to the protocol, one a line starting with minus, so an exclusion has a reason PRISMA can count.", bn: "প্রোটোকলে বাদ দেওয়ার মানদণ্ড যোগ করুন, প্রতি লাইনে একটা, মাইনাস দিয়ে শুরু, যাতে বাদের কারণ PRISMA গুনতে পারে।" },
  "rs.rev.noabstract": { en: "No abstract came with the record.", bn: "রেকর্ডের সঙ্গে সারাংশ আসেনি।" },
  "rs.rev.opendoi": { en: "Open at the publisher", bn: "প্রকাশকের কাছে খুলুন" },
  "rs.rev.openoa": { en: "Free copy", bn: "বিনামূল্যের কপি" },
  "rs.rev.inlibrary": { en: "Already in the library", bn: "লাইব্রেরিতে আছে" },
  "rs.rev.narrative": { en: "A narrative review has no screening: a protocol, a search log and a synthesis.", bn: "বর্ণনামূলক পর্যালোচনায় যাচাই নেই: প্রোটোকল, খোঁজের লগ আর সংশ্লেষ।" },
  "rs.rev.included.none": { en: "Nothing included yet. Screening fills this.", bn: "এখনো কিছু অন্তর্ভুক্ত হয়নি। যাচাই এটা ভরে।" },
  "rs.rev.changed": { en: "Protocol last changed", bn: "প্রোটোকল শেষ বদলেছে" },
  "rs.rev.screeners": { en: "Screeners", bn: "যাচাইকারী" },
  "rs.rev.save": { en: "Save the protocol", bn: "প্রোটোকল রাখুন" },
  "rs.rev.svg": { en: "SVG", bn: "SVG" },
  "rs.rev.png": { en: "PNG", bn: "PNG" },
  "rs.rev.template": { en: "Template", bn: "ছক" },
  "rs.rev.prisma.bydb": { en: "by database", bn: "ডেটাবেস অনুযায়ী" },
  "rs.rev.untagged": { en: "Tag the included sources in the library and the matrix draws itself.", bn: "লাইব্রেরিতে অন্তর্ভুক্ত উৎসগুলোয় ট্যাগ দিন, ছক নিজেই আঁকা হবে।" },
  "rs.copied": { en: "Copied", bn: "কপি হলো" },
  "rs.lab.datasets": { en: "Datasets", bn: "ডেটাসেট" },
  "rs.lab.sql": { en: "SQL", bn: "SQL" },
  "rs.lab.stats": { en: "Statistics", bn: "পরিসংখ্যান" },
  "rs.lab.charts": { en: "Charts", bn: "চার্ট" },
  "rs.lab.runs": { en: "Runs", bn: "রান" },
  "rs.lab.market": { en: "Market data", bn: "বাজারের তথ্য" },
  "rs.lab.group.describe": { en: "Describe", bn: "বর্ণনা" },
  "rs.lab.group.test": { en: "Tests", bn: "পরীক্ষা" },
  "rs.lab.group.regression": { en: "Regression", bn: "রিগ্রেশন" },
  "rs.lab.group.panel": { en: "Panels and treatments", bn: "প্যানেল ও হস্তক্ষেপ" },
  "rs.lab.group.finance": { en: "Finance", bn: "অর্থ" },
  "rs.lab.group.climate": { en: "Agriculture and climate", bn: "কৃষি ও জলবায়ু" },
  "rs.lab.upload": { en: "Add a dataset", bn: "ডেটাসেট যোগ করুন" },
  "rs.lab.upload.hint": { en: "A CSV, TSV, Parquet or JSON file. It is stored under your prefix, becomes a source of type dataset so the thesis can cite it, and its columns are read into the dictionary. The DSE's and Alpha Vantage's own column names are recognised.", bn: "CSV, TSV, Parquet বা JSON ফাইল। আপনার প্রিফিক্সে রাখা হয়, dataset ধরনের উৎস হয় যাতে থিসিস উদ্ধৃত করতে পারে, আর কলামগুলো অভিধানে পড়া হয়। DSE আর Alpha Vantage-এর নিজস্ব কলামের নাম চেনা হয়।" },
  "rs.lab.licence": { en: "Licence", bn: "লাইসেন্স" },
  "rs.lab.raw": { en: "Raw, never edited", bn: "কাঁচা, কখনো সম্পাদনা নয়" },
  "rs.lab.empty": { en: "No dataset yet. Add a file, or fetch a market series.", bn: "এখনো ডেটাসেট নেই। ফাইল যোগ করুন, বা বাজারের ধারা আনুন।" },
  "rs.lab.pick": { en: "Choose a dataset first.", bn: "আগে একটা ডেটাসেট বেছে নিন।" },
  "rs.lab.delete.confirm": { en: "Remove this dataset's row? The file stays in your storage and the library row stays.", bn: "এই ডেটাসেটের সারি সরাবেন? ফাইল আপনার স্টোরেজে থাকবে, লাইব্রেরির সারিও থাকবে।" },
  "rs.lab.engine.cost": { en: "The engine is DuckDB in this browser: about thirty megabytes the first time, cached after, and nothing of the data leaves the page.", bn: "ইঞ্জিন এই ব্রাউজারে DuckDB: প্রথমবার প্রায় তিরিশ মেগাবাইট, তারপর ক্যাশে, আর তথ্যের কিছুই পাতা ছেড়ে যায় না।" },
  "rs.lab.load": { en: "Load into the engine", bn: "ইঞ্জিনে লোড করুন" },
  "rs.lab.loaded": { en: "loaded", bn: "লোড হয়েছে" },
  "rs.lab.loading": { en: "Loading the engine and the file", bn: "ইঞ্জিন আর ফাইল লোড হচ্ছে" },
  "rs.lab.preview": { en: "First rows", bn: "প্রথম সারিগুলো" },
  "rs.lab.needs.load": { en: "Load the dataset into the engine first.", bn: "আগে ডেটাসেট ইঞ্জিনে লোড করুন।" },
  "rs.lab.engine.failed": { en: "The engine could not answer", bn: "ইঞ্জিন উত্তর দিতে পারেনি" },
  "rs.lab.failed": { en: "That did not work", bn: "এটা হয়নি" },
  "rs.lab.sanity": { en: "The four checks", bn: "চারটি যাচাই" },
  "rs.lab.sanity.hint": { en: "Rows and columns against the paper's stated N, missing values a column, anything a thousand times off its median, and the date and country coverage. The result is a run.", bn: "কাগজের বলা N-এর সাথে সারি আর কলাম, প্রতি কলামে অনুপস্থিত মান, মধ্যমার হাজার গুণ দূরের কিছু, আর তারিখ ও দেশের পরিধি। ফলটা একটা রান।" },
  "rs.lab.statedN": { en: "Stated N", bn: "বলা N" },
  "rs.lab.sanity.run": { en: "Run the checks", bn: "যাচাই চালান" },
  "rs.lab.rows": { en: "rows", bn: "সারি" },
  "rs.lab.columns": { en: "columns", bn: "কলাম" },
  "rs.lab.nmatch": { en: "N matches", bn: "N মিলেছে" },
  "rs.lab.nmismatch": { en: "N does not match the stated", bn: "N বলার সাথে মেলেনি" },
  "rs.lab.missing": { en: "Missing", bn: "অনুপস্থিত" },
  "rs.lab.outliers": { en: "Far from the median", bn: "মধ্যমা থেকে দূরে" },
  "rs.lab.coverage": { en: "Coverage", bn: "পরিধি" },
  "rs.lab.dictionary": { en: "Dictionary", bn: "অভিধান" },
  "rs.lab.dictionary.hint": { en: "One row a column: type, unit, definition, and the variable in the questions room it measures, so the thesis's variable table and this list are one list.", bn: "প্রতি কলামে এক সারি: ধরন, একক, সংজ্ঞা, আর প্রশ্ন ঘরের যে চলক এটা মাপে, যাতে থিসিসের চলকের তালিকা আর এই তালিকা এক।" },
  "rs.lab.column": { en: "Column", bn: "কলাম" },
  "rs.lab.type": { en: "Type", bn: "ধরন" },
  "rs.lab.unit": { en: "Unit", bn: "একক" },
  "rs.lab.definition": { en: "Definition", bn: "সংজ্ঞা" },
  "rs.lab.variable": { en: "Variable", bn: "চলক" },
  "rs.lab.novariable": { en: "no variable", bn: "কোনো চলক নয়" },
  "rs.lab.sql.hint": { en: "Any SQL DuckDB answers, over the loaded tables. This dataset is", bn: "লোড করা টেবিলের ওপর DuckDB যা উত্তর দেয়, যেকোনো SQL। এই ডেটাসেট হলো" },
  "rs.lab.run": { en: "Run", bn: "চালান" },
  "rs.lab.save.run": { en: "Save as a run", bn: "রান হিসেবে রাখুন" },
  "rs.lab.save.transform": { en: "Save as a transform", bn: "ট্রান্সফর্ম হিসেবে রাখুন" },
  "rs.lab.transform.name": { en: "Transform name", bn: "ট্রান্সফর্মের নাম" },
  "rs.lab.transforms": { en: "Transforms", bn: "ট্রান্সফর্ম" },
  "rs.lab.transforms.hint": { en: "SQL kept as rows, in order, so a dataset's lineage is readable and re-runnable. Run makes each a view under its name.", bn: "সারি হিসেবে রাখা SQL, ক্রমে, যাতে ডেটাসেটের বংশ পড়া যায় আর আবার চালানো যায়। Run প্রতিটাকে তার নামে ভিউ বানায়।" },
  "rs.lab.view.made": { en: "View made", bn: "ভিউ তৈরি" },
  "rs.lab.method": { en: "Method", bn: "পদ্ধতি" },
  "rs.lab.method.hint": { en: "Pick a method, give it its columns, run it. Every method here runs in this browser and is held to a closed form by a test; the result becomes a run a draft can point at.", bn: "পদ্ধতি বাছুন, কলাম দিন, চালান। এখানকার প্রতিটা পদ্ধতি এই ব্রাউজারে চলে আর একটা পরীক্ষা তাকে বদ্ধ রূপে ধরে রাখে; ফল একটা রান হয় যেটা খসড়া দেখাতে পারে।" },
  "rs.lab.stars": { en: "Stars on the table", bn: "টেবিলে তারা" },
  "rs.lab.apa": { en: "APA table (Markdown)", bn: "APA টেবিল (Markdown)" },
  "rs.lab.apa.copy": { en: "Copy the table", bn: "টেবিল কপি করুন" },
  "rs.lab.label": { en: "Label", bn: "লেবেল" },
  "rs.lab.saved.run": { en: "Saved as a run", bn: "রান হিসেবে রাখা হলো" },
  "rs.lab.charts.hint": { en: "A line, a scatter, bars or a histogram of the loaded columns, drawn as SVG so the figure is a file.", bn: "লোড করা কলামের রেখা, বিন্দু, বার বা হিস্টোগ্রাম, SVG হিসেবে আঁকা যাতে চিত্রটা একটা ফাইল।" },
  "rs.lab.chart.kind": { en: "Kind", bn: "ধরন" },
  "rs.lab.chart.x": { en: "x", bn: "x" },
  "rs.lab.chart.y": { en: "Series", bn: "ধারা" },
  "rs.lab.draw": { en: "Draw", bn: "আঁকুন" },
  "rs.lab.runs.hint": { en: "Every result, newest first. A run is a page: what was asked, the code, the answer and the figure, whole.", bn: "প্রতিটা ফল, নতুনটা আগে। রান একটা পাতা: কী চাওয়া হয়েছিল, কোড, উত্তর আর চিত্র, পুরোটা।" },
  "rs.lab.market.hint": { en: "A daily series by symbol through the Worker, cached a day. Saved, it is a dataset with its source. Dhaka's exchange is a CSV you download and drop on Datasets; its columns are recognised.", bn: "Worker-এর মাধ্যমে প্রতীক ধরে দৈনিক ধারা, একদিন ক্যাশে। রাখলে উৎসসহ একটা ডেটাসেট। ঢাকার এক্সচেঞ্জ একটা CSV যেটা নামিয়ে Datasets-এ ফেলবেন; কলামগুলো চেনা হয়।" },
  "rs.lab.symbol": { en: "Symbol", bn: "প্রতীক" },
  "rs.lab.market.full": { en: "Twenty years", bn: "বিশ বছর" },
  "rs.lab.fetch": { en: "Fetch", bn: "আনুন" },
  "rs.lab.market.off": { en: "No series came back: the market service is off, or the symbol is unknown.", bn: "কোনো ধারা আসেনি: বাজার সেবা বন্ধ, বা প্রতীক অজানা।" },
  "rs.lab.market.save": { en: "Save as a dataset", bn: "ডেটাসেট হিসেবে রাখুন" },
  "rs.lab.bars": { en: "days", bn: "দিন" },
  "rs.lab.back": { en: "Back to the lab", bn: "ল্যাবে ফিরুন" },
  "rs.lab.run.missing": { en: "No such run.", bn: "এমন কোনো রান নেই।" },
  "rs.lab.run.input": { en: "Asked", bn: "চাওয়া হয়েছিল" },
  "rs.lab.run.hash": { en: "Data hash", bn: "তথ্যের হ্যাশ" },
  "rs.lab.run.cite": { en: "A draft points at this run by its id:", bn: "খসড়া এই রানকে তার আইডি দিয়ে দেখায়:" },
  "rs.field.participants": { en: "Participants", bn: "অংশগ্রহণকারী" },
  "rs.field.interviews": { en: "Interviews", bn: "সাক্ষাৎকার" },
  "rs.field.codebook": { en: "Codebook", bn: "কোডবই" },
  "rs.field.retrieval": { en: "Retrieval", bn: "খুঁজে আনা" },
  "rs.field.matrices": { en: "Matrices", bn: "ছক" },
  "rs.field.surveys": { en: "Surveys", bn: "জরিপ" },
  "rs.field.guide": { en: "Interview guide", bn: "সাক্ষাৎকারের নির্দেশিকা" },
  "rs.field.participants.hint": { en: "A pseudonym, a role. Everything in this room refers to the pseudonym; a real name, if kept at all, is sealed below under a passphrase this site never sees.", bn: "ছদ্মনাম, ভূমিকা। এই ঘরের সবকিছু ছদ্মনাম ধরে; আসল নাম রাখলে নিচে একটা পাসফ্রেজে সিল করা থাকে যা এই সাইট কখনো দেখে না।" },
  "rs.field.pseudonym": { en: "Pseudonym", bn: "ছদ্মনাম" },
  "rs.field.role": { en: "Role", bn: "ভূমিকা" },
  "rs.field.participant": { en: "Participant", bn: "অংশগ্রহণকারী" },
  "rs.field.participant.add": { en: "Add a participant", bn: "অংশগ্রহণকারী যোগ করুন" },
  "rs.field.participant.remove": { en: "Remove this participant? Their interviews and codings stay, without a name on them.", bn: "এই অংশগ্রহণকারীকে সরাবেন? তাদের সাক্ষাৎকার আর কোডিং থাকবে, নাম ছাড়া।" },
  "rs.field.participants.empty": { en: "Nobody yet. A participant is a pseudonym first.", bn: "এখনো কেউ নেই। অংশগ্রহণকারী আগে একটা ছদ্মনাম।" },
  "rs.field.participants.pick": { en: "Choose a participant on the left, or add one.", bn: "বাঁয়ে একজনকে বেছে নিন, বা যোগ করুন।" },
  "rs.field.consent": { en: "Consent", bn: "সম্মতি" },
  "rs.field.consent.hint": { en: "Status, date, what was consented to, and whether quotes may be used. The signed form goes in the library as a file if you keep one.", bn: "অবস্থা, তারিখ, কীসে সম্মতি, আর উদ্ধৃতি ব্যবহার করা যাবে কি না। সই করা ফর্ম রাখলে লাইব্রেরিতে ফাইল হিসেবে থাকে।" },
  "rs.field.consent.status": { en: "Status", bn: "অবস্থা" },
  "rs.field.consent.date": { en: "Date", bn: "তারিখ" },
  "rs.field.consent.scope": { en: "Consented to", bn: "কীসে সম্মতি" },
  "rs.field.consent.quotes": { en: "Quotes may be used", bn: "উদ্ধৃতি ব্যবহার করা যাবে" },
  "rs.field.sealed": { en: "Sealed identity", bn: "সিল করা পরিচয়" },
  "rs.field.sealed.hint": { en: "Name and contact, encrypted in this browser under your passphrase before they are stored. The site holds only the ciphertext; a lost passphrase is a lost name.", bn: "নাম আর যোগাযোগ, রাখার আগে এই ব্রাউজারেই আপনার পাসফ্রেজে এনক্রিপ্ট করা। সাইটে থাকে শুধু সাইফারটেক্সট; পাসফ্রেজ হারালে নামও হারায়।" },
  "rs.field.passphrase": { en: "Passphrase", bn: "পাসফ্রেজ" },
  "rs.field.identity": { en: "Name and contact", bn: "নাম ও যোগাযোগ" },
  "rs.field.seal": { en: "Seal", bn: "সিল করুন" },
  "rs.field.unseal": { en: "Open", bn: "খুলুন" },
  "rs.field.sealed.held": { en: "held, sealed", bn: "রাখা আছে, সিল করা" },
  "rs.field.sealed.done": { en: "Sealed and stored", bn: "সিল করে রাখা হলো" },
  "rs.field.sealed.wrong": { en: "That passphrase does not open it.", bn: "এই পাসফ্রেজে খোলে না।" },
  "rs.field.interviews.hint": { en: "An interview is a library source of type interview: the participant as its author, the audio as its file, and its transcript a note.", bn: "সাক্ষাৎকার হলো interview ধরনের লাইব্রেরি উৎস: অংশগ্রহণকারী লেখক, অডিও তার ফাইল, আর ট্রান্সক্রিপ্ট একটা নোট।" },
  "rs.field.interview.title": { en: "Title", bn: "শিরোনাম" },
  "rs.field.interview.add": { en: "Add an interview", bn: "সাক্ষাৎকার যোগ করুন" },
  "rs.field.audio": { en: "Audio", bn: "অডিও" },
  "rs.field.noaudio": { en: "No audio on this interview.", bn: "এই সাক্ষাৎকারে অডিও নেই।" },
  "rs.field.interviews.pick": { en: "Choose an interview on the left, or add one.", bn: "বাঁয়ে একটা সাক্ষাৎকার বেছে নিন, বা যোগ করুন।" },
  "rs.field.player.hint": { en: "[ and ] nudge the player five seconds. A time in the margin seeks to it.", bn: "[ আর ] প্লেয়ার পাঁচ সেকেন্ড সরায়। পাশের সময়ে চাপলে সেখানে যায়।" },
  "rs.field.transcript": { en: "Transcript", bn: "ট্রান্সক্রিপ্ট" },
  "rs.field.transcript.hint": { en: "From the model through the Worker where transcription is connected, or pasted. Either way it arrives as a draft you check against the audio.", bn: "যেখানে ট্রান্সক্রিপশন যুক্ত, Worker-এর মাধ্যমে মডেল থেকে, নয়তো পেস্ট করে। যেভাবেই হোক, খসড়া হিসেবে আসে যা অডিওর সাথে মিলিয়ে যাচাই করেন।" },
  "rs.field.transcript.draft": { en: "draft", bn: "খসড়া" },
  "rs.field.transcript.checked": { en: "checked against the audio", bn: "অডিওর সাথে যাচাই করা" },
  "rs.field.language": { en: "Language code", bn: "ভাষার কোড" },
  "rs.field.transcribe": { en: "Transcribe", bn: "ট্রান্সক্রাইব করুন" },
  "rs.field.transcribe.off": { en: "Transcription is not connected. Paste the transcript instead.", bn: "ট্রান্সক্রিপশন যুক্ত নেই। ট্রান্সক্রিপ্ট পেস্ট করুন।" },
  "rs.field.paste": { en: "Paste a transcript", bn: "ট্রান্সক্রিপ্ট পেস্ট করুন" },
  "rs.field.paste.hint": { en: "A line that opens with a time and a speaker starts a segment: [12:34] P07: ... A blank line starts one too.", bn: "সময় আর বক্তা দিয়ে শুরু লাইন একটা অংশ শুরু করে: [12:34] P07: ... খালি লাইনও একটা শুরু করে।" },
  "rs.field.paste.keep": { en: "Keep as the transcript", bn: "ট্রান্সক্রিপ্ট হিসেবে রাখুন" },
  "rs.field.coding.hint": { en: "Select words in a segment and press a code on the right. A coding is offsets into that segment, shown as an underline in the code's colour.", bn: "অংশের শব্দ নির্বাচন করে ডানে একটা কোড চাপুন। কোডিং হলো সেই অংশে অবস্থান, কোডের রঙে আন্ডারলাইন হিসেবে দেখা যায়।" },
  "rs.field.selected": { en: "Selected", bn: "নির্বাচিত" },
  "rs.field.select": { en: "Select some words to code them.", bn: "কোড করতে কিছু শব্দ নির্বাচন করুন।" },
  "rs.field.codes.none": { en: "No codes yet. Make the codebook first, with a definition for each.", bn: "এখনো কোড নেই। আগে কোডবই বানান, প্রতিটার সংজ্ঞাসহ।" },
  "rs.field.present": { en: "Codes on this transcript", bn: "এই ট্রান্সক্রিপ্টের কোড" },
  "rs.field.codebook.hint": { en: "A tree of codes, each with its definition written when it is made, because a codebook without definitions is one nobody else can apply.", bn: "কোডের গাছ, প্রতিটার সংজ্ঞা বানানোর সময়েই লেখা, কারণ সংজ্ঞা ছাড়া কোডবই আর কেউ প্রয়োগ করতে পারে না।" },
  "rs.field.code.name": { en: "Code", bn: "কোড" },
  "rs.field.code.definition": { en: "Definition", bn: "সংজ্ঞা" },
  "rs.field.code.colour": { en: "Colour", bn: "রঙ" },
  "rs.field.code.parent": { en: "Under", bn: "যার নিচে" },
  "rs.field.code.add": { en: "Add the code", bn: "কোড যোগ করুন" },
  "rs.field.code.remove": { en: "Remove this code and every coding under it?", bn: "এই কোড আর তার নিচের সব কোডিং সরাবেন?" },
  "rs.field.retrieval.hint": { en: "Every coded segment of a code, across the project, with the participant and the time beside each. A translation and a memo can go on any of them.", bn: "একটা কোডের প্রতিটা কোড করা অংশ, পুরো প্রকল্প জুড়ে, পাশে অংশগ্রহণকারী আর সময়সহ। যেকোনোটায় অনুবাদ আর মেমো যোগ করা যায়।" },
  "rs.field.allcodes": { en: "All codes", bn: "সব কোড" },
  "rs.field.translation": { en: "Translation", bn: "অনুবাদ" },
  "rs.field.memo": { en: "Memo", bn: "মেমো" },
  "rs.field.matrices.hint": { en: "Code by participant, code co-occurrence and code frequency over the interviews in order. All derived from the codings, each a CSV.", bn: "অংশগ্রহণকারী অনুযায়ী কোড, কোডের সহ-উপস্থিতি, আর ক্রমে সাক্ষাৎকার জুড়ে কোডের ঘনত্ব। সবই কোডিং থেকে গড়া, প্রতিটা CSV।" },
  "rs.field.matrices.none": { en: "Nothing coded yet, so nothing to count.", bn: "এখনো কিছু কোড হয়নি, তাই গোনার কিছু নেই।" },
  "rs.field.matrix.participant": { en: "Code by participant", bn: "অংশগ্রহণকারী অনুযায়ী কোড" },
  "rs.field.matrix.cooccurrence": { en: "Code co-occurrence", bn: "কোডের সহ-উপস্থিতি" },
  "rs.field.matrix.interviews": { en: "Code over the interviews", bn: "সাক্ষাৎকার জুড়ে কোড" },
  "rs.field.surveys.hint": { en: "Questions as lines, a public link, answers collected here. A stranger's answers go into D1 through a throttled endpoint; the lab reads them as a dataset.", bn: "লাইনে প্রশ্ন, একটা পাবলিক লিংক, উত্তর এখানে জমা। অচেনা কারো উত্তর থ্রটল করা এন্ডপয়েন্ট দিয়ে D1-এ যায়; ল্যাব সেগুলো ডেটাসেট হিসেবে পড়ে।" },
  "rs.field.survey.new": { en: "New survey", bn: "নতুন জরিপ" },
  "rs.field.survey.open": { en: "open", bn: "খোলা" },
  "rs.field.survey.closed": { en: "closed", bn: "বন্ধ" },
  "rs.field.surveys.pick": { en: "Choose a survey on the left, or start one.", bn: "বাঁয়ে একটা জরিপ বেছে নিন, বা শুরু করুন।" },
  "rs.field.survey.intro": { en: "Introduction and consent note", bn: "ভূমিকা ও সম্মতির কথা" },
  "rs.field.survey.questions": { en: "Questions", bn: "প্রশ্ন" },
  "rs.field.survey.questions.hint": { en: "One a line: type | English | Bangla | option, option. A star after the English marks it required. Types: likert, choice, multi, text, number.", bn: "প্রতি লাইনে একটা: ধরন | ইংরেজি | বাংলা | বিকল্প, বিকল্প। ইংরেজির পরে তারা মানে বাধ্যতামূলক। ধরন: likert, choice, multi, text, number।" },
  "rs.field.survey.save": { en: "Save", bn: "রাখুন" },
  "rs.field.survey.publish": { en: "Publish", bn: "প্রকাশ করুন" },
  "rs.field.survey.close": { en: "Close the survey", bn: "জরিপ বন্ধ করুন" },
  "rs.field.survey.remove": { en: "Remove this survey? Answers already collected stay in D1 until the account is erased.", bn: "এই জরিপ সরাবেন? জমা উত্তর অ্যাকাউন্ট মোছা পর্যন্ত D1-এ থাকবে।" },
  "rs.field.survey.failed": { en: "Publishing did not work. Is the database connected?", bn: "প্রকাশ হয়নি। ডেটাবেস যুক্ত আছে?" },
  "rs.field.survey.link": { en: "Public link:", bn: "পাবলিক লিংক:" },
  "rs.field.survey.collect": { en: "Collect the answers", bn: "উত্তর সংগ্রহ করুন" },
  "rs.field.responses": { en: "responses", bn: "উত্তর" },
  "rs.field.survey.dataset": { en: "Save as a dataset", bn: "ডেটাসেট হিসেবে রাখুন" },
  "rs.field.survey.dataset.done": { en: "Saved as a dataset in the lab", bn: "ল্যাবে ডেটাসেট হিসেবে রাখা হলো" },
  "rs.field.guide.hint": { en: "The questions you put to people, one a line, and a tick per question per interview, so the methods chapter can say which were asked of whom.", bn: "যে প্রশ্নগুলো মানুষকে করেন, প্রতি লাইনে একটা, আর প্রতি সাক্ষাৎকারে প্রতি প্রশ্নে একটা টিক, যাতে পদ্ধতির অধ্যায় বলতে পারে কাকে কী জিজ্ঞেস করা হয়েছিল।" },
  "rs.field.guide.questions": { en: "Questions", bn: "প্রশ্ন" },
  "rs.field.guide.save": { en: "Save the guide", bn: "নির্দেশিকা রাখুন" },
};

/** One phrase, or a loud marker for a key nobody wrote. */
export const word = (k: string): Phrase =>
  RESEARCH_WORDS[k] ?? { en: `[${k}]`, bn: `[${k}]` };
