#!/usr/bin/env node
/* ============================================================
   build-fallback.ts: the stylesheet for the two pages that
   cannot have one.

       node scripts/build-fallback.ts           # write it
       node scripts/build-fallback.ts --check   # or compare

   `404.html` and `offline.html` are files, and they are files on
   purpose: they have to answer when the Worker, the route and the
   network are all unavailable, which is exactly when a route
   cannot. So they cannot link the stylesheet Next emits, because
   that name carries a content hash and changes on every build,
   and `sw.js` precaches by exact path.

   ---- it is the whole stylesheet, and that is deliberate ----

   The first version took a SUBSET: three layers whole, then every
   rule naming one of the classes those two pages carry. It came
   out at 27 KB against 330, and it was wrong four times over
   before it was looked at properly.

     The wordmark filled the screen, because `.slimbar-mark svg`
     is in the SECOND `@layer shell` block and the extractor read
     only the first.

     The breadcrumb came out as a numbered list, because both
     pages load `/app.js`, which is precached, so offline it runs
     and builds a crumb row, a palette and a sign-in button that
     appear in no markup a generator could read.

     `.crumbs` is in `@layer money`, which is not a misfiling: that
     layer holds the site's own `.hero`, `.band` and
     `.section-label` because they really are sitewide.

     And the footer came out on the wrong ground in dark mode.

   Each was one more name to add to a list. A subset of a design
   system is a second design system kept by hand, which is the
   drift most of the checks here exist for. So this is the whole
   file with its comments taken out: SMALLER than the 330 KB those
   two pages were loading before the stylesheet moved, and it
   cannot be missing a rule.

   The comments are worth their bytes in the source, where
   somebody reads them, and not in a file whose whole job is to
   arrive when nothing else has.
   ============================================================ */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "next", "styles", "site.css");
const OUT = join(ROOT, "aab", "fallback.css");

export function generate(): string {
  const body = readFileSync(SRC, "utf8")
    /* Block comments only. CSS has no line comment, and a comment
       close inside a string would need a string this file does
       not contain: every url() in it is a gradient or a data
       URI. */
    .replace(/\/\*[\s\S]*?\*\//g, "")
    /* What removing them leaves: trailing space where a comment
       sat at the end of a line, and runs of blank lines. */
    .replace(/[ \t]+$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  return `/* GENERATED by scripts/build-fallback.ts. Do not edit.

   next/styles/site.css with its comments removed, for /404.html
   and /offline.html. Those two are files rather than routes
   because they answer when nothing else can, so they cannot link
   a stylesheet whose name carries a hash. Edit the source and run
   the generator. */

${body}
`;
}

const RUN = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (RUN) {
  const wanted = generate();
  if (process.argv.includes("--check")) {
    const have = (() => {
      try { return readFileSync(OUT, "utf8"); } catch { return ""; }
    })();
    if (have !== wanted) {
      console.error("aab/fallback.css is not next/styles/site.css with its comments"
        + " out.\nRegenerate it:\n  node scripts/build-fallback.ts\n");
      process.exit(1);
    }
    console.log("aab/fallback.css matches the stylesheet it is drawn from.");
  } else {
    writeFileSync(OUT, wanted);
    const src = readFileSync(SRC, "utf8").length;
    console.log(`wrote aab/fallback.css, ${(wanted.length / 1024).toFixed(0)} KB`
      + ` from ${(src / 1024).toFixed(0)} KB of source.`);
  }
}
