#!/usr/bin/env node
/* build-fallback.ts: the stylesheet for the two pages that cannot
   have one.

       node scripts/build-fallback.ts           # write it
       node scripts/build-fallback.ts --check   # or compare

   `404.html` and `offline.html` are files on purpose: they answer
   when the Worker, the route and the network are all unavailable.
   So they cannot link the stylesheet Next emits, whose name
   carries a content hash, and `sw.js` precaches by exact path.

   IT IS THE WHOLE STYLESHEET WITH ITS COMMENTS TAKEN OUT. A subset
   is a second design system kept by hand: the first version took
   three layers plus every rule naming a class those pages carry,
   and was wrong four times over, partly because both pages load
   the precached `/app.js`, which offline builds a crumb row, a
   palette and a sign-in button that appear in no markup a
   generator could read.

   AND IT IS THE ONE PLACE A VENDOR PREFIX IS WRITTEN. `site.css`
   writes the standard property alone, because Next builds it
   through Lightning CSS, which adds the prefixes; a hand-written
   `-webkit-` twin there DELETES the standard property, and the
   whole site once shipped `-webkit-backdrop-filter` alone.
   `scripts/check-prefixes.ts` fails on that now. This file has no
   Lightning CSS, so it adds the twins itself. */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "next", "styles", "site.css");
const OUT = join(ROOT, "aab", "fallback.css");

/* The properties this stylesheet declares that WebKit shipped
   prefixed. Both are still needed: Safari wanted
   `-webkit-backdrop-filter` until 18 and `-webkit-mask-image`
   until 15.4. A third property added to `site.css` that needs a
   prefix has to be added here; nothing can work that out from the
   source. `scripts/check-prefixes.ts` stops one being
   hand-written into the source instead. */
const PREFIX = [
  "backdrop-filter",      // Safari until 18
  "mask-image",           // Safari until 15.4
  "text-size-adjust",     // iOS Safari reads only the prefixed name
  "appearance",           // Safari until 15.4
  "box-decoration-break", // Safari, still
];

export function generate(): string {
  const body = readFileSync(SRC, "utf8")
    /* Block comments only. CSS has no line comment, and a comment
       close inside a string would need a string this file does
       not contain: every url() in it is a gradient or a data
       URI. */
    .replace(/\/\*[\s\S]*?\*\//g, "")
    /* What removing them leaves: trailing space where a comment
       sat at the end of a line, and runs of blank lines. */
    .replace(/[ \t]+$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  const prefixed = body.replace(
    new RegExp(`^(\\s*)(${PREFIX.join("|")})(\\s*:[^;}]*;)`, "gm"),
    (_m, pad: string, prop: string, rest: string) =>
      `${pad}-webkit-${prop}${rest}\n${pad}${prop}${rest}`,
  );

  return `/* GENERATED by scripts/build-fallback.ts. Do not edit.

   next/styles/site.css with its comments removed, for /404.html
   and /offline.html. Those two are files rather than routes
   because they answer when nothing else can, so they cannot link
   a stylesheet whose name carries a hash. Edit the source and run
   the generator. */

${prefixed}
`;
}

const RUN = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (RUN) {
  const wanted = generate();
  if (process.argv.includes("--check")) {
    const have = (() => {
      try { return readFileSync(OUT, "utf8"); } catch { return ""; }
    })();
    if (have !== wanted) {
      console.error("aab/fallback.css is not next/styles/site.css with its comments"
        + " out.\nRegenerate it:\n  node scripts/build-fallback.ts\n");
      process.exit(1);
    }
    console.log("aab/fallback.css matches the stylesheet it is drawn from.");
  } else {
    writeFileSync(OUT, wanted);
    const src = readFileSync(SRC, "utf8").length;
    console.log(`wrote aab/fallback.css, ${(wanted.length / 1024).toFixed(0)} KB`
      + ` from ${(src / 1024).toFixed(0)} KB of source.`);
  }
}
