#!/usr/bin/env node
/* ============================================================
   build-stamp.ts: the React workspace's output really is its
   source's.

       node scripts/build-stamp.ts           # write it
       node scripts/build-stamp.ts --check   # or compare

   `aab/desk/**` and `aab/studio/**` are built from `app/src/**`
   and COMMITTED, because the site deploys by uploading `aab/`
   with no build step in CI. So the rule is edit the source, run
   the build, commit both, and nothing held anybody to the second
   half of it.

   WHAT WENT WRONG. `aab/desk/app.js` and `aab/studio/app.js` were
   last built at #105 and `app/src/**` changed in #143, #147 and
   #149. `app/src/Published.tsx` imports `accentStyle` from
   `next/lib/nav.ts`; the committed bundle contains no such
   string, so the desk and the Studio were serving a build from
   before that table grew, for four pull requests, and every check
   in this repository passed. A generated file that is stale looks
   exactly like one that is correct.

   ---- why a hash and not the git log ----

   `actions/checkout` clones at depth 1, so `git log` in CI sees
   one commit and can tell you nothing about when a file last
   changed. This reads the files themselves, which works the same
   everywhere.

   It hashes the SOURCES, not the output: an output hash would
   fail on any two builds that differ by a byte, and Vite's is not
   reproducible across versions. What this asserts is narrower and
   is the thing that actually goes wrong: the sources moved and
   nobody re-ran the build.
   ============================================================ */

import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "app", "build-stamp.json");

/* Everything the two bundles are built from. `vite.config.ts` and
   `tsconfig.json` are in here because a change to either changes
   the output without touching a line of `src/`. `next/lib/nav.ts`
   is in here because `app/src/Published.tsx` imports it, which is
   how this drift became visible in the first place.

   ANYTHING app/src IMPORTS OUT OF next/ BELONGS HERE. The two
   pages take their buttons and their labels from the site's own
   component library rather than keeping a second copy, and a
   change to one of those files changes what these bundles render
   with no file under `app/` touched. Add the file the day you add
   the import; a source this cannot see is the exact staleness the
   note above describes. */
const SOURCES = [
  "app/src",
  "app/vite.config.ts",
  "app/tsconfig.json",
  "app/package.json",
  "next/lib/nav.ts",
  "next/components/ui/button.tsx",
  "next/components/ui/field.tsx",
  "next/components/ui/label.tsx",
];

/** Every file under a path, or the file itself, repo-relative and
    sorted, so the hash does not depend on the order a directory
    happens to be read in. */
function filesUnder(path: string): string[] {
  const full = join(ROOT, path);
  if (!statSync(full).isDirectory()) return [path];
  const out: string[] = [];
  for (const name of readdirSync(full).sort()) {
    if (name === "node_modules" || name.startsWith(".")) continue;
    out.push(...filesUnder(join(path, name)));
  }
  return out;
}

function stamp(): { sources: number; hash: string } {
  const files = SOURCES.flatMap(filesUnder).sort();
  const sum = createHash("sha256");
  for (const file of files) {
    sum.update(file);
    sum.update("\0");
    sum.update(readFileSync(join(ROOT, file)));
    sum.update("\0");
  }
  return { sources: files.length, hash: sum.digest("hex") };
}

const RUN = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (RUN) {
  const now = stamp();
  const body = JSON.stringify({
    note: "GENERATED by scripts/build-stamp.ts. What aab/desk/** and"
      + " aab/studio/** were last built from. Run `cd app && npm run build`.",
    ...now,
  }, null, 2) + "\n";

  if (process.argv.includes("--check")) {
    const have = (() => {
      try { return JSON.parse(readFileSync(OUT, "utf8")) as { hash?: string }; }
      catch { return {}; }
    })();
    if (have.hash !== now.hash) {
      console.error(
        "aab/desk/** and aab/studio/** are not built from the app/ that is"
        + " committed beside them.\n"
        + "Those two are output, they are uploaded as they stand, and a stale"
        + " one serves\nold code while every check passes. Rebuild and commit"
        + " both:\n\n  cd app && npm run build\n");
      process.exit(1);
    }
    console.log(`app: ${now.sources} source file(s), and the committed desk and`
      + " Studio bundles were built from them.");
  } else {
    writeFileSync(OUT, body);
    console.log(`wrote app/build-stamp.json over ${now.sources} source file(s).`);
  }
}

export { stamp };
