#!/usr/bin/env node
/* ============================================================
   build-fallback.ts: the stylesheet for the two pages that
   cannot have one.

       node scripts/build-fallback.ts           # write it
       node scripts/build-fallback.ts --check   # or compare

   `404.html` and `offline.html` are files, and they are files on
   purpose: they have to answer when the Worker, the route and the
   network are all unavailable, which is exactly when a route
   cannot. So they cannot link the stylesheet Next emits, because
   that name carries a content hash and changes on every build,
   and `sw.js` precaches by exact path.

   ---- it is the whole stylesheet, and that is deliberate ----

   The first version took a SUBSET: three layers whole, then every
   rule naming one of the classes those two pages carry. It came
   out at 27 KB against 330, and it was wrong four times over
   before it was looked at properly.

     The wordmark filled the screen, because `.slimbar-mark svg`
     is in the SECOND `@layer shell` block and the extractor read
     only the first.

     The breadcrumb came out as a numbered list, because both
     pages load `/app.js`, which is precached, so offline it runs
     and builds a crumb row, a palette and a sign-in button that
     appear in no markup a generator could read.

     `.crumbs` is in `@layer money`, which is not a misfiling: that
     layer holds the site's own `.hero`, `.band` and
     `.section-label` because they really are sitewide.

     And the footer came out on the wrong ground in dark mode.

   Each was one more name to add to a list. A subset of a design
   system is a second design system kept by hand, which is the
   drift most of the checks here exist for. So this is the whole
   file with its comments taken out: SMALLER than the 330 KB those
   two pages were loading before the stylesheet moved, and it
   cannot be missing a rule.

   The comments are worth their bytes in the source, where
   somebody reads them, and not in a file whose whole job is to
   arrive when nothing else has.

   ---- and it is the one place a vendor prefix is written ----

   `site.css` writes the standard property alone, because Next
   builds it through Lightning CSS and Lightning CSS adds the
   prefixes from the build targets. Writing a `-webkit-` twin by
   hand there DELETES the standard property: Lightning CSS reads
   the pair as one property and keeps the last, so the whole site
   shipped `-webkit-backdrop-filter` alone, which Chrome has never
   supported, and no glass surface blurred anywhere but Safari.
   `scripts/check-prefixes.ts` fails on it now.

   This file has no Lightning CSS, so it adds the twins itself.
   Safari needed `-webkit-backdrop-filter` until 18 and
   `-webkit-mask-image` until 15.4, and `/404.html` reaching an
   iPhone on a bad connection is exactly the case this stylesheet
   exists for.
   ============================================================ */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "next", "styles", "site.css");
const OUT = join(ROOT, "aab", "fallback.css");

/* The properties this stylesheet declares that WebKit shipped
   prefixed. Both are still needed: Safari wanted
   `-webkit-backdrop-filter` until 18 and `-webkit-mask-image`
   until 15.4. A third property added to `site.css` that needs a
   prefix has to be added here; nothing can work that out from the
   source, and `caniuse` is not a dependency this file is worth.
   `scripts/check-prefixes.ts` is what stops one being hand-written
   into the source instead. */
const PREFIX = [
  "backdrop-filter",      // Safari until 18
  "mask-image",           // Safari until 15.4
  "text-size-adjust",     // iOS Safari reads only the prefixed name
  "appearance",           // Safari until 15.4
  "box-decoration-break", // Safari, still
];

export function generate(): string {
  const body = readFileSync(SRC, "utf8")
    /* Block comments only. CSS has no line comment, and a comment
       close inside a string would need a string this file does
       not contain: every url() in it is a gradient or a data
       URI. */
    .replace(/\/\*[\s\S]*?\*\//g, "")
    /* What removing them leaves: trailing space where a comment
       sat at the end of a line, and runs of blank lines. */
    .replace(/[ \t]+$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  const prefixed = body.replace(
    new RegExp(`^(\\s*)(${PREFIX.join("|")})(\\s*:[^;}]*;)`, "gm"),
    (_m, pad: string, prop: string, rest: string) =>
      `${pad}-webkit-${prop}${rest}\n${pad}${prop}${rest}`,
  );

  return `/* GENERATED by scripts/build-fallback.ts. Do not edit.

   next/styles/site.css with its comments removed, for /404.html
   and /offline.html. Those two are files rather than routes
   because they answer when nothing else can, so they cannot link
   a stylesheet whose name carries a hash. Edit the source and run
   the generator. */

${prefixed}
`;
}

const RUN = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (RUN) {
  const wanted = generate();
  if (process.argv.includes("--check")) {
    const have = (() => {
      try { return readFileSync(OUT, "utf8"); } catch { return ""; }
    })();
    if (have !== wanted) {
      console.error("aab/fallback.css is not next/styles/site.css with its comments"
        + " out.\nRegenerate it:\n  node scripts/build-fallback.ts\n");
      process.exit(1);
    }
    console.log("aab/fallback.css matches the stylesheet it is drawn from.");
  } else {
    writeFileSync(OUT, wanted);
    const src = readFileSync(SRC, "utf8").length;
    console.log(`wrote aab/fallback.css, ${(wanted.length / 1024).toFixed(0)} KB`
      + ` from ${(src / 1024).toFixed(0)} KB of source.`);
  }
}
