#!/usr/bin/env node
/* check-next.ts: the things `next/` has a second copy of.

       node scripts/check-next.ts

   The Next.js app is a package with its own root, and what it
   renders from outside that root is copied in. A copy nobody
   checks is the failure this repository has written up more times
   than any other.

   1. THE SCHOOLS' DRAWINGS, all 103, in
      `next/lib/school-icons.ts`, generated by
      `scripts/build-school-icons.ts` and regenerated and compared
      here.

   2. THE PRACTICE BOOKS' LENGTH. `next/lib/workbooks/*.ts` holds
      the days and the school's ladder DECLARES how many there
      are, in `workbook.days`, because the hub draws a progress bar
      from that number and must not pull five thousand lines of
      days down to count them. A declaration that drifts is a
      learner told they are on day 30 of 60 in a book that has 90.

   Plus the four ladders, the fallback stylesheet, the pre-paint
   boot script and the copy of `@reiad/shared` npm leaves in
   `next/node_modules`, each headed at the section that checks it. */

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SCHOOL_ICONS } from "../next/lib/school-icons.ts";
import { NAV, LADDER_SCHOOLS } from "../shared/nav.ts";
import { SCHOOL_LADDERS } from "../next/lib/school-ladders.ts";
import { STAGES, allLessons } from "../shared/curricula/money.ts";
import { STUFEN } from "../shared/curricula/deutsch.ts";
import { TERMS } from "../shared/curricula/english.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel: string): string => readFileSync(join(ROOT, rel), "utf8");

let failures = 0;
/** How many shared files the copy in next/node_modules matches, or
    0 where there is no copy to compare (every CI runner). */
let copiedShared = 0;
const fail = (line: string, ...detail: string[]): void => {
  failures += 1;
  console.error(`FAIL  ${line}`);
  detail.forEach((d) => console.error(`      ${d}`));
};

/* ---- 1. The schools' 103 drawings, generated ---- */

const { generate } = await import("./build-school-icons.ts");
const wanted = await generate();
const drawings = (wanted.match(/^\s{4}"/gm) ?? []).length;

if (read("next/lib/school-icons.ts") !== wanted) {
  fail("next/lib/school-icons.ts is not what aab/*/icons.js draws.",
    "Regenerate it and commit the result:",
    "  node scripts/build-school-icons.ts");
}

/* ---- 2b. The four ladders, the two depths of them

   Generated out of `content/schools.backup.json`, committed, and
   compared here. The stages are the header's tree, so a school
   that gains one and is not regenerated shows a header one stage
   short of the hub it links to. The lessons are `/account`, so the
   same drifts into a bar reading 60 of 59 finished. ---- */

const { generate: stages, generateLadders } = await import("./build-school-tree.ts");

for (const [name, wanted] of [
  ["next/lib/school-stages.ts", stages()],
  ["next/lib/school-ladders.ts", await generateLadders()],
]) {
  if (read(name) !== wanted) {
    fail(`${name} is not what content/schools.backup.json holds.`,
      "Regenerate it and commit the result:",
      "  node scripts/build-school-tree.ts");
  }
}

/* And that the two agree about which schools have one.

   `ladder: true` in NAV is what `/account` reads to know there is
   a bar to draw, and the generated file is where the denominator
   comes from. A school that gains a ladder and not the flag never
   appears on that page; a flag with no ladder behind it draws
   0 of 0. Neither looks broken. */

const flagged = LADDER_SCHOOLS.map((s) => s.key).sort();
const generated = Object.keys(SCHOOL_LADDERS).sort();

if (flagged.join() !== generated.join()) {
  fail("the schools flagged `ladder: true` in shared/nav.ts are not the"
    + " schools next/lib/school-ladders.ts holds a ladder for.",
    `nav.ts:            ${flagged.join(", ") || "(none)"}`,
    `school-ladders.ts: ${generated.join(", ") || "(none)"}`);
}

/* And that each one has lessons in it, because an empty array is
   what a snapshot refreshed against the wrong database looks
   like, and it draws a bar reading 0 of 0 rather than failing. */
for (const [school, lessons] of Object.entries(SCHOOL_LADDERS)) {
  if (!lessons.length) {
    fail(`next/lib/school-ladders.ts holds no lessons for ${school}.`,
      "Its bar on /account reads 0 of 0 and its resume card says"
      + " nothing is written.",
      "Refresh the snapshot and regenerate:",
      "  npx wrangler d1 export reiad --remote --output schools.db",
      "  node scripts/export-schools.ts --db schools.db",
      "  node scripts/build-school-tree.ts");
  }
}

/* ---- 2c. The stylesheet the two file pages link

   `404.html` and `offline.html` cannot link the stylesheet Next
   emits, because its name carries a content hash. They link
   `aab/fallback.css`, the same file with its comments removed,
   written by `scripts/build-fallback.ts`. ---- */

const { generate: fallback } = await import("./build-fallback.ts");

if (read("aab/fallback.css") !== fallback()) {
  fail("aab/fallback.css is not next/styles/site.css with its comments out.",
    "Regenerate it and commit the result:",
    "  node scripts/build-fallback.ts");
}

/* ---- 2. And that the cards can actually find those drawings

   The check above proves `next/` holds the same drawings `aab/`
   does. It does not prove anything looks them up correctly.

   `SCHOOL_ICONS` is keyed by school id, and a lookup on an id that
   has moved answers `undefined` through optional chaining rather
   than throwing, falls through to the shell set, misses there too
   and returns the empty string: `Icon` then renders a perfectly
   correct `<svg>` with nothing inside it. Sixteen empty icons on
   the money hub, with both checks above passing, because the
   drawings were all present and it was the key that had gone. ---- */

const iconsTsx = read("next/components/icons.tsx");

/** The school set `icons.tsx` draws its card icons from. */
const keyed = iconsTsx.match(/SCHOOL_ICONS\.(\w+)\s*\?\?/)
  ?? iconsTsx.match(/SCHOOL_ICONS\.(\w+)\?\.\[name\]/);

if (!keyed) {
  fail("cannot tell which set next/components/icons.tsx draws cards from.",
    "It should read SCHOOL_ICONS.<school> once, into CARD_ICONS.");
} else if (!wanted.includes(`  ${keyed[1]}: {`)) {
  fail(`next/components/icons.tsx reads SCHOOL_ICONS.${keyed[1]},`
    + " and no school is called that.",
    `The sets are: ${(wanted.match(/^  (\w+): \{/gm) ?? [])
      .map((m) => m.trim().replace(": {", "")).join(", ")}.`,
    "Every icon on every card is an empty <svg> until this matches.");
}

/* And the names themselves. The shell's own drawings are read out
   of the same file rather than listed here, so adding one does
   not mean editing this. */
const shellNames = new Set(
  [...iconsTsx.matchAll(/^  ([a-z]+):/gm)].map((m) => m[1]));

const cardIcons = keyed ? (SCHOOL_ICONS[keyed[1]] ?? {}) : {};

/* The icon names the money school's cards ask for. */
const asked = new Set<string>();
for (const stage of STAGES) if (stage.icon) asked.add(stage.icon);
for (const lesson of allLessons()) if (lesson.icon) asked.add(lesson.icon);
/* `group.items`. A `NavGroup` has never had a `links` and has
   never had an `icon` of its own: it has a label, an accent and
   `items`. `group.links ?? []` was an empty array on every group,
   so not one of the rail's seventeen icons was ever checked, and
   the check went on reporting a number, which is what made it
   invisible. TypeScript found it, this file did not. */
for (const group of NAV) {
  for (const item of group.items) if (item.icon) asked.add(item.icon);
}

const empty = [...asked].filter(
  (name) => !cardIcons[name] && !shellNames.has(name));

if (empty.length) {
  fail(`${empty.length} icon name(s) a card asks for draw nothing.`,
    empty.join(", "),
    "Each renders as an <svg> with no path inside it, which looks"
    + " like a missing icon and reports as nothing at all.");
}

/* ------------------------------------------------------------
   3. A practice book is as long as its curriculum says
   ------------------------------------------------------------ */

/** A rung of a ladder that may carry a book. Both schools spell
    the rung differently and the book identically, which is why
    this takes the two arrays and not the two schools. */
interface Rung {
  slug: string;
  workbook?: { slug: string; days: number };
}

/** The file under `next/lib/workbooks/` a rung's book lives in.
    `next/lib/workbook.ts` maps the same four by hand; this reads
    them off disk because the point is to compare the two. */
const BOOK_FILE: Record<string, string> = {
  "stufe-1": "deutsch-stufe-1",
  "stufe-2": "deutsch-stufe-2",
  "stufe-3": "deutsch-stufe-3",
  "term-1": "english-term-1",
};

let books = 0;
for (const rung of [...STUFEN, ...TERMS] as Rung[]) {
  if (!rung.workbook) continue;               // Stufe 4 has none, on purpose
  const file = BOOK_FILE[rung.slug];
  if (!file) {
    fail(`${rung.slug} declares a workbook and next/lib/workbooks/ has no file for it.`,
      `Add it to BOOK_FILE in this check, or the hub draws a bar over nothing.`);
    continue;
  }
  const loaded = await import(join(ROOT, "next", "lib", "workbooks", `${file}.ts`)) as
    { default?: { days?: unknown[] } | unknown[] };
  const book = loaded.default;
  const days = Array.isArray(book) ? book : book?.days;
  if (!Array.isArray(days)) {
    fail(`next/lib/workbooks/${file}.ts does not export a list of days.`,
      "The default export is what next/lib/workbook.ts reads.");
    continue;
  }
  books += 1;
  if (days.length !== rung.workbook.days) {
    fail(`${rung.slug}: the book is ${days.length} days and the ladder says `
      + `${rung.workbook.days}.`,
      `next/lib/workbooks/${file}.ts is the days themselves; workbook.days is what`,
      "the hub draws its progress bar from. A reader would be told they are on day",
      `${rung.workbook.days} of a book that has ${days.length}.`);
  }
}

/* THE PRE-PAINT BOOT, SAID THREE TIMES.

   `shell.tsx` writes it into every route. `404.html` and
   `offline.html` carry their own copy, and have to: they are
   files, and they answer when the Worker and the routes cannot.

   So the vocabulary is written out three times and it drifted. The
   two file pages tested a value that is not one of `AUDIENCES` in
   `shared/nav.ts`, so a reader who chose Learning got no
   `data-audience` and the rail's groups came out in the other
   order, on exactly the two pages that answer when everything else
   is down. Both pages render perfectly.

   This compares the ATTRIBUTE VALUES each copy tests for, not the
   text: `shell.tsx` minifies its copy into one line and the files
   space theirs out to be read. */
{
  const values = (src: string, attr: string): string[] => {
    /* Every `a === "x"` (or `t === "x"`) in the same statement as
       a `setAttribute` for this attribute. */
    const line = src.split("\n").find((l) => l.includes(`"${attr}"`) && l.includes("==="))
      ?? src.split(/;\s*/).find((l) => l.includes(`"${attr}"`) && l.includes("===")) ?? "";
    return [...line.matchAll(/===\s*"([a-z-]+)"/g)].map((m) => m[1]).sort();
  };

  const shell = read("next/components/shell.tsx");
  for (const attr of ["data-audience", "data-theme"]) {
    const want = values(shell, attr);
    if (!want.length) {
      fail(`check-next.ts cannot find the ${attr} test in shell.tsx any more.`,
        "This check compares the two file pages against it, so it is now",
        "comparing them against nothing. Point it at the boot script again.");
      continue;
    }
    for (const page of ["aab/404.html", "aab/offline.html"]) {
      const got = values(read(page), attr);
      if (got.join() === want.join()) continue;
      fail(`${page} tests ${attr} for ${got.join(", ") || "nothing"} and `
        + `shell.tsx tests ${want.join(", ")}.`,
        "The boot script is written three times because these two pages are",
        "files and cannot render one. A value only one of them knows is a",
        "reader whose choice is dropped on the two pages that answer when",
        "the Worker and the routes cannot.");
    }
  }
}

/* ---- 3. `@reiad/shared`, copied into next/node_modules by npm

   `next/.npmrc` sets `install-links=true`, so a `file:` dependency
   is COPIED rather than symlinked, and npm keys that copy by
   VERSION: editing a file in `shared/` leaves the copy in place
   however much the contents changed, and `next build` compiles the
   old code without a word. What it looks like is a function that
   is plainly exported reported as missing, or a fix that does not
   take. The fix:

       rm -rf next/node_modules/@reiad/shared && (cd next && npm install)

   It SKIPS where the copy is absent, which is every CI runner:
   there is no stale copy where there is no copy. ---- */
{
  const copied = join(ROOT, "next", "node_modules", "@reiad", "shared");
  if (existsSync(copied)) {
    const source = join(ROOT, "shared");
    const walk = (dir: string, base: string): string[] =>
      readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
        e.name === "node_modules" || e.name.startsWith(".")
          ? []
          : e.isDirectory()
            ? walk(join(dir, e.name), `${base}${e.name}/`)
            : e.name.endsWith(".ts")
              ? [`${base}${e.name}`]
              : []);
    const stale: string[] = [];
    for (const rel of walk(source, "")) {
      const there = join(copied, rel);
      if (!existsSync(there)) { stale.push(`${rel} (missing from the copy)`); continue; }
      if (readFileSync(join(source, rel), "utf8") !== readFileSync(there, "utf8")) stale.push(rel);
    }
    if (stale.length) {
      fail(`next/node_modules/@reiad/shared is ${stale.length} file(s) behind shared/.`,
        `The first is ${stale[0]}.`,
        "npm keys a file: dependency by its version, so it will not notice.",
        "Next compiles the copy, so a fix to shared/ has not taken and a",
        "function you can read in the source is reported as not exported.",
        "  rm -rf next/node_modules/@reiad/shared && (cd next && npm install)");
    } else {
      copiedShared = walk(source, "").length;
    }
  }
}

console.log(failures
  ? `\n${failures} copy(ies) in next/ have drifted from the original.\n`
  : `next/ holds 3 drawings copied out of aab/ by hand and ${drawings}\n`
    + `generated, every one still matches what icons.js draws, and all\n`
    + `${asked.size} names a card asks for come back with a drawing in them,\n`
    + `and ${books} practice book(s) are as long as their ladder says.\n`
    + (copiedShared
      ? `next/node_modules/@reiad/shared matches all ${copiedShared} of shared/.\n`
      : "next/ has no copy of @reiad/shared installed, so there is none to be stale.\n"));
process.exit(failures ? 1 : 0);
