/* ============================================================
   scripts/restore.mjs: turning a backup back into a database.

   A backup nobody has restored is a file, not a backup. This is
   the other half, and it is deliberately boring: it reads a
   backup JSON and writes SQL to stdout. It does not talk to D1,
   it does not hold a credential, and it cannot delete anything by
   itself. What you do with the SQL is a separate, visible step:

     node scripts/restore.mjs content/articles.backup.json > restore.sql
     less restore.sql                      # read it. Actually read it.
     npx wrangler d1 execute reiad --remote --file=restore.sql

   Add --local to that last command to practise on the local
   database first, which is what you should do the first time.

   ---- what it does to rows that are already there ----

   INSERT ... ON CONFLICT DO UPDATE, keyed on the table's own
   primary key. So restoring over a live database brings every row
   in the backup back to how it was and leaves anything newer
   alone rather than dropping it.

   It does NOT delete. A row deleted since the backup stays
   deleted, which is the safer default of the two: getting a
   deleted row back is a decision, and losing a new one to a
   restore is an accident. `--replace` exists for when you really
   do want the backup to be the whole truth, and it says what it
   is about to do before it does it.

   TRANSITION.md, Stage 2.
   ============================================================ */

import { readFileSync } from "node:fs";

export const BACKUP_FORMAT = 1;

/* Primary keys, which decide what ON CONFLICT is keyed on. A table
   missing from here cannot be restored, deliberately: guessing a
   primary key wrong turns an upsert into a duplicate-row machine. */
export const KEYS = {
  articles: ["slug"],
  article_versions: ["id"],
  questions: ["id"],
  subscribers: ["email"],
  enquiries: ["id"],
  reactions: ["slug", "kind"],
  views: ["path", "day"],
  settings: ["key"],
};

/** SQLite literal. Numbers stay numbers; everything else is a
    quoted string with its quotes doubled, which is the whole of
    SQLite's escaping rule. NULL is spelled out. */
export function literal(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "boolean") return value ? "1" : "0";
  return `'${String(value).replace(/'/g, "''")}'`;
}

/**
 * One INSERT for one row.
 *
 * Column names come from the row itself rather than from a schema
 * this script keeps a copy of, so a column added to the table in
 * db.js appears here the day it appears in a backup, with nothing
 * to remember to update.
 */
export function insertFor(table, row, { replace = false } = {}) {
  const key = KEYS[table];
  if (!key) throw new Error(`no primary key known for ${table}`);

  const columns = Object.keys(row);
  if (!columns.length) return null;

  const values = columns.map((c) => literal(row[c])).join(", ");
  const names = columns.map((c) => `"${c}"`).join(", ");

  if (replace) {
    return `INSERT OR REPLACE INTO ${table} (${names}) VALUES (${values});`;
  }

  /* Every column except the key ones, set from the row being
     inserted. A table whose only columns ARE the key has nothing
     to update, and `DO UPDATE SET` with an empty list is a syntax
     error, so it becomes DO NOTHING. */
  const updatable = columns.filter((c) => !key.includes(c));
  const conflict = key.map((c) => `"${c}"`).join(", ");

  if (!updatable.length) {
    return `INSERT INTO ${table} (${names}) VALUES (${values}) `
      + `ON CONFLICT(${conflict}) DO NOTHING;`;
  }

  const sets = updatable.map((c) => `"${c}" = excluded."${c}"`).join(", ");
  return `INSERT INTO ${table} (${names}) VALUES (${values}) `
    + `ON CONFLICT(${conflict}) DO UPDATE SET ${sets};`;
}

/** Both backup shapes, as one map of table name to rows. */
export function tablesIn(backup) {
  if (backup?.format !== BACKUP_FORMAT) {
    throw new Error(
      `backup format ${backup?.format ?? "missing"}, this script understands ${BACKUP_FORMAT}`
    );
  }
  if (backup.kind === "articles") return { articles: backup.articles ?? [] };
  if (backup.kind === "full") return backup.tables ?? {};
  throw new Error(`unknown backup kind: ${backup.kind}`);
}

/** The whole script, as a function, so the test can call it. */
export function toSQL(backup, { replace = false, only = null } = {}) {
  const tables = tablesIn(backup);
  const lines = [
    `-- Restored from a ${backup.kind} backup taken ${backup.taken_at}.`,
    `-- Generated by scripts/restore.mjs. Read before running.`,
  ];

  let rows = 0;
  for (const [table, list] of Object.entries(tables)) {
    if (only && only !== table) continue;
    if (!list?.length) continue;
    lines.push("", `-- ${table}: ${list.length} row(s)`);
    if (replace) lines.push(`DELETE FROM ${table};`);
    for (const row of list) {
      const sql = insertFor(table, row, { replace });
      if (sql) { lines.push(sql); rows += 1; }
    }
  }

  lines.push("", `-- ${rows} row(s) in total.`);
  return lines.join("\n");
}

/* ---------- the command line ---------- */

const isMain = import.meta.url === `file://${process.argv[1]}`;

if (isMain) {
  const args = process.argv.slice(2);
  const file = args.find((a) => !a.startsWith("--"));
  const replace = args.includes("--replace");
  const only = args.find((a) => a.startsWith("--only="))?.slice(7) ?? null;

  if (!file) {
    console.error(
      "usage: node scripts/restore.mjs <backup.json> [--replace] [--only=table]\n"
      + "\n"
      + "  writes SQL to stdout. Read it, then:\n"
      + "    npx wrangler d1 execute reiad --local  --file=restore.sql\n"
      + "    npx wrangler d1 execute reiad --remote --file=restore.sql\n"
      + "\n"
      + "  --replace  empty each table first, so the backup is the whole\n"
      + "             truth. Rows created since the backup are LOST.\n"
      + "  --only=x   one table.\n"
    );
    process.exit(2);
  }

  const backup = JSON.parse(readFileSync(file, "utf8"));

  if (replace) {
    console.error(
      "!! --replace will DELETE every row in each table before restoring.\n"
      + "!! Rows created since this backup was taken will be lost.\n"
    );
  }

  process.stdout.write(`${toSQL(backup, { replace, only })}\n`);
}
