/* ============================================================
   arbeitsbuch/stufe-2.js: the sixty days of Stufe Zwei.

   Straight out of "Das 60-Tage-Arbeitsbuch · Stufe Zwei", one
   object per day, in order. Same five parts as Stufe 1, because
   the shape of the page never changes: that is the whole point
   of the book. See ../arbeitsbuch.data.js for what a day holds.

   Sixty days rather than thirty, and that is the book being
   honest: cases and the Perfekt need room to settle. The daily
   tick at the foot of a page changes too. Stufe 1 asked whether
   yesterday's page had been read first; here it asks whether the
   six lines of "Mein Gestern" were actually spoken, because from
   this book on, the evening retelling is the exercise.
   ============================================================ */


export default {
  /* The second line of every day's footer tick. */
  fuss: "রাতের ছয় লাইন বলেছি",

  lede: {
    de: "Drei Brücken: WER & WEN · GEBEN & GESTERN · DENKEN & ERZÄHLEN.",
    bn:
      "তিন সেতু: কে-কাকে, দেওয়া ও গতকাল, ভাবা ও গল্প বলা। প্রতিদিন একটা পাতা, " +
      "প্রতি রাতে একটা Mein Gestern।",
  },

  /* No sound key from here on: the sounds are behind you. What
     this book collects instead is pairs, because from Stufe 2 a
     verb is never learned alone again. */
  sammlung: {
    de: "Die Partizip-Sammlung",
    bn: "জোড়া-সংগ্রহ",
    key: "partizip",
    blurb:
      "প্রতিটা নতুন ক্রিয়া এখানে জোড়ায় জমাও: ক্রিয়া, তারপর তার Partizip। haben-দল বাঁয়ে, sein-দল (গতি ও বদল) ডানে। সপ্তাহে একবার পুরো পাতা গানের মতো জোরে পড়ো।",
    columns: [
      { key: "haben", head: "haben + ge…", placeholder: "machen – gemacht\nessen – gegessen\n…" },
      { key: "sein", head: "sein + ge… (গতি)", placeholder: "gehen – gegangen\nkommen – gekommen\n…" },
    ],
  },

  schluss: {
    de: "Die Brücken sind gebaut. Jetzt wohnst du auf der anderen Seite.",
    bn:
      "সেতু তৈরি শেষ, এখন থেকে তুমি ওপারে থাকো, আর অভ্যাসগুলোই তোমার নতুন ঠিকানা: " +
      "রোজ রাতে ছয় লাইনে গতকাল, সপ্তাহে দশ জোড়া Partizip পড়ে নয় গেয়ে, রোজ একটা weil-বাক্য, " +
      "রোজ দশ মিনিট আসল জার্মান, আর সপ্তাহে একজন সত্যিকারের মানুষ।",
  },

  motto: {
    de: "Hör auf zu übersetzen. Fang an zu denken.",
    bn: "দুটোই কাতাপল্ট-ক্রিয়া, আর তুমি এইমাত্র পুরনো বন্ধুর মতো পড়ে ফেললে।",
  },

  days: [
    {
      n: 1,
      de: "Akkusativ I: der → den",
      bn: "নীল দল কোট পরে",
      muster: {
        pattern: "WER? → der Mann WEN/WAS? → den Mann",
        why: "কর্তা হলে der, গ্রহীতা হলে den। শুধু নীল দল বদলায়, die, das, বহুবচন অটল।",
        examples: "Ich sehe den Mann. · Ich trinke den Tee. · Ich lese das Buch. (অটল!)",
        tip: "সবুজ আর লাল দলকে ছুঁয়ো না, এটাই আজকের একমাত্র কাজ।",
      },
      schau: [
        { de: "Ich sehe den Mann.", bn: "আমি লোকটাকে দেখি।" },
        { de: "Ich trinke den Tee.", bn: "আমি চা-টা খাই।" },
        { de: "Ich frage den Lehrer.", bn: "আমি শিক্ষককে জিজ্ঞেস করি।" },
        { de: "Ich öffne die Tür. (অটল)", bn: "আমি দরজাটা খুলি।" },
        { de: "Ich lese das Buch. (অটল)", bn: "আমি বইটা পড়ি।" },
      ],
      sagEs: [
        { q: "আমি লোকটাকে দেখি।", a: "Ich sehe den Mann." },
        { q: "আমি চা-টা খাচ্ছি।", a: "Ich trinke den Tee." },
        { q: "আমি শিক্ষককে জিজ্ঞেস করি।", a: "Ich frage den Lehrer." },
        { q: "আমি বাসটা দেখি।", a: "Ich sehe den Bus." },
        { q: "আমি দরজাটা খুলি।", a: "Ich öffne die Tür." },
        { q: "আমি বইটা পড়ি।", a: "Ich lese das Buch." },
      ],
      vonHerzen: { en: "Look around: three der-things you see. → Ich sehe den ___.", bn: "চারপাশ দেখো: তিনটা der-জিনিস। → Ich sehe den ___।" },
    },
    {
      n: 2,
      de: "Akkusativ II: einen · keinen",
      bn: "একটা → einen, নেই → keinen",
      muster: {
        pattern: "ein → einen kein → keinen (শুধু নীল দলে)",
        why: "গ্রহীতা হলে ein-এর মাথায় -en। eine, ein (সবুজ), অটল।",
        examples: "Ich esse einen Apfel. · Ich habe keinen Bruder.",
        tip: "'একটা আপেল খাই', Apfel নীল, তাই einen।",
      },
      schau: [
        { de: "Ich esse einen Apfel.", bn: "আমি একটা আপেল খাই।" },
        { de: "Ich brauche einen Stift.", bn: "আমার একটা কলম দরকার।" },
        { de: "Ich habe keinen Bruder.", bn: "আমার কোনো ভাই নেই।" },
        { de: "Sie kauft eine Jacke. (অটল)", bn: "সে একটা জ্যাকেট কেনে।" },
        { de: "Ich habe kein Geld. (অটল)", bn: "আমার টাকা নেই।" },
      ],
      sagEs: [
        { q: "আমি একটা আপেল খাই।", a: "Ich esse einen Apfel." },
        { q: "আমার একটা কলম দরকার।", a: "Ich brauche einen Stift." },
        { q: "আমার কোনো ভাই নেই।", a: "Ich habe keinen Bruder." },
        { q: "সে একটা জ্যাকেট কেনে।", a: "Sie kauft eine Jacke." },
        { q: "আমাদের একটা প্ল্যান দরকার।", a: "Wir brauchen einen Plan." },
        { q: "আমার সময় নেই।", a: "Ich habe keine Zeit." },
      ],
      vonHerzen: { en: "Three true sentences: Ich brauche einen/eine/ein ___.", bn: "তিনটা সত্যি বাক্য: আমার কী কী দরকার।" },
    },
    {
      n: 3,
      de: "Akkusativ III: mich · dich",
      bn: "আমাকে · তোমাকে",
      muster: {
        pattern: "ich → mich du → dich",
        why: "বাংলার '-কে' জার্মানে শব্দটাই বদলে দেয়: আমাকে = mich, তোমাকে = dich।",
        examples: "Ich liebe dich., পৃথিবীর সবচেয়ে বিখ্যাত জার্মান বাক্য।",
        tip: "আজ থেকে এটা তোমারও।",
      },
      schau: [
        { de: "Ich liebe dich.", bn: "আমি তোমাকে ভালোবাসি।" },
        { de: "Siehst du mich?", bn: "তুমি কি আমাকে দেখছো?" },
        { de: "Ich verstehe dich.", bn: "আমি তোমাকে বুঝি।" },
        { de: "Hörst du mich?", bn: "তুমি কি আমাকে শুনছো?" },
        { de: "Ich brauche dich.", bn: "তোমাকে আমার দরকার।" },
      ],
      sagEs: [
        { q: "আমি তোমাকে ভালোবাসি।", a: "Ich liebe dich." },
        { q: "তুমি কি আমাকে দেখছো?", a: "Siehst du mich?" },
        { q: "আমি তোমাকে বুঝি।", a: "Ich verstehe dich." },
        { q: "তুমি কি আমাকে শুনছো?", a: "Hörst du mich?" },
        { q: "তোমাকে আমার দরকার।", a: "Ich brauche dich." },
        { q: "আমি তোমাকে চিনি।", a: "Ich kenne dich." },
      ],
      vonHerzen: { en: "Say to the mirror: Ich sehe dich. Ich kenne dich. Ich mag dich!", bn: "আয়নাকে বলো: Ich sehe dich। Ich kenne dich। Ich mag dich!" },
    },
    {
      n: 4,
      de: "Akkusativ IV: ihn, আর যারা বদলায় না",
      bn: "তাকে (ছেলে) = ihn",
      muster: {
        pattern: "er → ihn sie/es/uns/euch/Sie → অটল",
        why: "সত্যিকারের নতুন শুধু ihn। বাকিরা কর্তা-রূপেই থাকে।",
        examples: "Ich kenne ihn. · Ich sehe sie. · Sie kennt uns.",
        tip: "er-ই একমাত্র ছেলে যে কোট বদলায়!",
      },
      schau: [
        { de: "Ich kenne ihn.", bn: "আমি তাকে চিনি।" },
        { de: "Ich sehe sie.", bn: "আমি তাকে (মেয়ে) দেখি।" },
        { de: "Sie kennt uns.", bn: "সে আমাদের চেনে।" },
        { de: "Ich höre euch!", bn: "আমি তোমাদের শুনছি!" },
        { de: "Ich verstehe Sie.", bn: "আমি আপনাকে বুঝছি।" },
      ],
      sagEs: [
        { q: "আমি তাকে (ছেলে) চিনি।", a: "Ich kenne ihn." },
        { q: "আমি তাকে (মেয়ে) দেখি।", a: "Ich sehe sie." },
        { q: "সে আমাদের চেনে।", a: "Sie kennt uns." },
        { q: "আমি তোমাদের শুনছি।", a: "Ich höre euch." },
        { q: "আমি আপনাকে বুঝছি।", a: "Ich verstehe Sie." },
        { q: "তুমি কি তাকে (ছেলে) দেখছো?", a: "Siehst du ihn?" },
      ],
      vonHerzen: { en: "Three sentences about people you know: Ich kenne ihn/sie…", bn: "চেনা মানুষদের নিয়ে তিনটা বাক্য: ihn না sie?" },
    },
    {
      n: 5,
      de: "Akkusativ-Verben",
      bn: "যে ক্রিয়ারা সবসময় গ্রহীতা নেয়",
      muster: {
        pattern: "sehen · kaufen · brauchen · suchen · finden + WEN/WAS",
        why: "এই ক্রিয়াদের পরে সবসময় Akkusativ, নিয়মটা ক্রিয়ার সাথেই শেখো।",
        examples: "Ich suche meinen Stift., Poss + Akk একসাথে (১১ দিনে পুরোটা)।",
        tip: "আজ চেনা রাখো, ঘাবড়িয়ো না।",
      },
      schau: [
        { de: "Ich sehe den Bus.", bn: "আমি বাসটা দেখছি।" },
        { de: "Sie kauft einen Apfel.", bn: "সে একটা আপেল কেনে।" },
        { de: "Wir brauchen einen Plan.", bn: "আমাদের একটা প্ল্যান দরকার।" },
        { de: "Ich suche den Schlüssel.", bn: "আমি চাবিটা খুঁজছি।" },
        { de: "Ich finde den Weg.", bn: "আমি পথটা পাই।" },
      ],
      sagEs: [
        { q: "আমি বাসটা দেখছি।", a: "Ich sehe den Bus." },
        { q: "সে একটা আপেল কেনে।", a: "Sie kauft einen Apfel." },
        { q: "আমাদের একটা প্ল্যান দরকার।", a: "Wir brauchen einen Plan." },
        { q: "আমি চাবিটা খুঁজছি।", a: "Ich suche den Schlüssel." },
        { q: "তুমি কি পথটা পাচ্ছো?", a: "Findest du den Weg?" },
        { q: "আমি একটা টেবিল কিনছি।", a: "Ich kaufe einen Tisch." },
      ],
      vonHerzen: { en: "Ich suche… / Ich brauche…, two true ones each.", bn: "সত্যি করে: দুটো 'খুঁজছি', দুটো 'দরকার'।" },
    },
    {
      n: 6,
      de: "es gibt, আছে",
      bn: "অস্তিত্বের মেশিন + Akkusativ",
      muster: {
        pattern: "Es gibt + einen/keinen ___",
        why: "যা 'আছে' বলবে, তা Akkusativ-এ ঢোকে। মেশিনটা একবার শিখলে সারাজীবন চলে।",
        examples: "Es gibt einen Markt. · Es gibt keinen Tee mehr.",
        tip: "'আর নেই' = keinen … mehr।",
      },
      schau: [
        { de: "Es gibt einen Markt hier.", bn: "এখানে একটা বাজার আছে।" },
        { de: "Es gibt einen Park.", bn: "একটা পার্ক আছে।" },
        { de: "Es gibt keinen Tee mehr.", bn: "চা আর নেই।" },
        { de: "Gibt es Fragen?", bn: "কোনো প্রশ্ন আছে?" },
        { de: "Es gibt viel zu lernen!", bn: "শেখার অনেক কিছু আছে!" },
      ],
      sagEs: [
        { q: "এখানে একটা বাজার আছে।", a: "Es gibt einen Markt hier." },
        { q: "একটা পার্ক আছে।", a: "Es gibt einen Park." },
        { q: "চা আর নেই।", a: "Es gibt keinen Tee mehr." },
        { q: "কোনো প্রশ্ন আছে?", a: "Gibt es Fragen?" },
        { q: "একটা সমস্যা আছে।", a: "Es gibt ein Problem." },
        { q: "খাবারে কী আছে?", a: "Was gibt es zum Essen?" },
      ],
      vonHerzen: { en: "Your area: Es gibt einen/eine/ein ___, three true things.", bn: "তোমার এলাকায় কী কী আছে, তিনটা।" },
    },
    {
      n: 7,
      de: "Akkusativ, মিশ্র মহড়া",
      bn: "সপ্তাহের কোট-পরীক্ষা",
      muster: {
        pattern: "den · einen · keinen · mich · dich · ihn, সব একসাথে",
        why: "আজ নতুন কিছু নেই, শুধু গতি। প্রতিটা উত্তর তিন সেকেন্ডে মুখে আসা চাই।",
        examples: "আটকালে প্রশ্ন করো: WEN/WAS?, গ্রহীতা কে?",
        tip: "die/das ফাঁদগুলোতে পা দিও না।",
      },
      schau: [
        { de: "Ich sehe den Mann und die Frau.", bn: "লোকটা ও মহিলাটিকে দেখি।" },
        { de: "Er isst einen Fisch.", bn: "সে একটা মাছ খায়।" },
        { de: "Wir haben keinen Reis mehr.", bn: "আমাদের চাল আর নেই।" },
        { de: "Kennst du ihn?", bn: "তুমি কি তাকে চেনো?" },
        { de: "Es gibt einen Weg.", bn: "একটা পথ আছে।" },
      ],
      sagEs: [
        { q: "আমি লোকটাকে ও মহিলাটিকে দেখি।", a: "Ich sehe den Mann und die Frau." },
        { q: "সে একটা মাছ খায়।", a: "Er isst einen Fisch." },
        { q: "আমাদের চাল আর নেই।", a: "Wir haben keinen Reis mehr." },
        { q: "তুমি কি তাকে (ছেলে) চেনো?", a: "Kennst du ihn?" },
        { q: "আমি তোমাকে বুঝি।", a: "Ich verstehe dich." },
        { q: "আমি বইটা পড়ছি। (সাবধান!)", a: "Ich lese das Buch." },
      ],
      vonHerzen: { en: "Write your fastest six, time yourself, out loud.", bn: "ছয়টা বাক্য, ঘড়ি ধরে, জোরে। গতিই আজকের লক্ষ্য।" },
    },
    {
      n: 8,
      de: "Possessiv I: mein · dein",
      bn: "আমার · তোমার",
      muster: {
        pattern: "mein Vater · meine Mutter · mein Buch dein/deine",
        why: "মালিকানার শব্দ ein-এর পোশাক পরে: নীল/সবুজে mein, লালে meine।",
        examples: "der Vater → mein Vater · die Mutter → meine Mutter",
        tip: "টুপি চেনা থাকলে এটা ফ্রি।",
      },
      schau: [
        { de: "Das ist mein Vater.", bn: "এই আমার বাবা।" },
        { de: "Das ist meine Mutter.", bn: "এই আমার মা।" },
        { de: "Mein Haus ist klein.", bn: "আমার বাড়ি ছোট।" },
        { de: "Deine Schwester ist nett.", bn: "তোমার বোন ভালো।" },
        { de: "Wo ist dein Buch?", bn: "তোমার বই কোথায়?" },
      ],
      sagEs: [
        { q: "এই আমার বাবা।", a: "Das ist mein Vater." },
        { q: "এই আমার মা।", a: "Das ist meine Mutter." },
        { q: "আমার বাড়ি ছোট।", a: "Mein Haus ist klein." },
        { q: "তোমার বোন ভালো।", a: "Deine Schwester ist nett." },
        { q: "তোমার বই কোথায়?", a: "Wo ist dein Buch?" },
        { q: "আমার ভাই ঢাকায় থাকে।", a: "Mein Bruder wohnt in Dhaka." },
      ],
      vonHerzen: { en: "Your family, one line each: Das ist mein/meine ___.", bn: "পরিবারের প্রত্যেককে এক লাইনে: mein না meine?" },
    },
    {
      n: 9,
      de: "Possessiv II: sein · ihr",
      bn: "তার (ছেলের) · তার (মেয়ের)",
      muster: {
        pattern: "sein = তার (মালিক ছেলে) ihr = তার (মালিক মেয়ে)",
        why: "মালিক ঠিক করে শব্দ, জিনিসের টুপি ঠিক করে পোশাক। দুই ধাপ, গুলিয়ো না।",
        examples: "seine Schwester = তার (ছেলের) বোন · ihr Bruder = তার (মেয়ের) ভাই",
        tip: "জিনিস না, মালিক দেখো!",
      },
      schau: [
        { de: "Sein Bruder wohnt hier.", bn: "তার (ছেলের) ভাই এখানে থাকে।" },
        { de: "Seine Mutter kocht gut.", bn: "তার (ছেলের) মা ভালো রান্না করেন।" },
        { de: "Ihr Vater ist Lehrer.", bn: "তার (মেয়ের) বাবা শিক্ষক।" },
        { de: "Ihre Schule ist groß.", bn: "তার (মেয়ের) স্কুল বড়।" },
        { de: "Ihr Haus ist schön.", bn: "তাদের বাড়ি সুন্দর।" },
      ],
      sagEs: [
        { q: "তার (ছেলের) ভাই এখানে থাকে।", a: "Sein Bruder wohnt hier." },
        { q: "তার (ছেলের) মা ভালো রান্না করেন।", a: "Seine Mutter kocht gut." },
        { q: "তার (মেয়ের) বাবা শিক্ষক।", a: "Ihr Vater ist Lehrer." },
        { q: "তার (মেয়ের) স্কুল বড়।", a: "Ihre Schule ist groß." },
        { q: "তার (ছেলের) বই এখানে।", a: "Sein Buch ist hier." },
        { q: "তার (মেয়ের) নাম রিমা।", a: "Ihr Name ist Rima." },
      ],
      vonHerzen: { en: "One friend (boy) + one friend (girl): describe their things.", bn: "এক ছেলে-বন্ধু, এক মেয়ে-বন্ধু, তাদের জিনিস নিয়ে বাক্য।" },
    },
    {
      n: 10,
      de: "Possessiv III: unser · euer · Ihr",
      bn: "আমাদের · তোমাদের · আপনার",
      muster: {
        pattern: "unser Haus · eure Schule (e পড়ে যায়!) · Ihr Name",
        why: "euer + e = eure, মাঝের e পালায়। Ihr (বড় I) = আপনার।",
        examples: "Wie ist Ihr Name?, অফিস-আদালতের প্রথম প্রশ্ন।",
        tip: "ভদ্রতার Ihr সবসময় বড় হাতের।",
      },
      schau: [
        { de: "Unser Haus ist klein, aber schön.", bn: "আমাদের বাড়ি ছোট, কিন্তু সুন্দর।" },
        { de: "Unsere Familie ist groß.", bn: "আমাদের পরিবার বড়।" },
        { de: "Eure Schule ist weit.", bn: "তোমাদের স্কুল দূরে।" },
        { de: "Wie ist Ihr Name?", bn: "আপনার নাম কী?" },
        { de: "Ihre Frage ist gut.", bn: "আপনার প্রশ্নটা ভালো।" },
      ],
      sagEs: [
        { q: "আমাদের বাড়ি ছোট।", a: "Unser Haus ist klein." },
        { q: "আমাদের পরিবার বড়।", a: "Unsere Familie ist groß." },
        { q: "তোমাদের স্কুল দূরে।", a: "Eure Schule ist weit." },
        { q: "আপনার নাম কী?", a: "Wie ist Ihr Name?" },
        { q: "আপনার প্রশ্নটা ভালো।", a: "Ihre Frage ist gut." },
        { q: "আমাদের দেশ সুন্দর।", a: "Unser Land ist schön." },
      ],
      vonHerzen: { en: "Unser/Unsere ___, three sentences about your home & family. '", bn: "আমাদের' দিয়ে তিনটা বাক্য, বাড়ি, পরিবার, দেশ।" },
    },
    {
      n: 11,
      de: "Possessiv + Akkusativ: meinen",
      bn: "আমার ভাইকে = meinen Bruder",
      muster: {
        pattern: "নীল-জিনিস গ্রহীতা হলে: mein → meinen · dein → deinen",
        why: "দুই নিয়ম মিললো: মালিকানা + কোট। শুধু নীল দলে -en।",
        examples: "Ich liebe meinen Bruder. কিন্তু: Ich liebe meine Mutter (অটল)।",
        tip: "এটাই এই সেতুর চূড়া, এরপর সব নামা।",
      },
      schau: [
        { de: "Ich liebe meinen Bruder.", bn: "আমি আমার ভাইকে ভালোবাসি।" },
        { de: "Ich liebe meine Familie.", bn: "আমি আমার পরিবারকে ভালোবাসি।" },
        { de: "Ich suche meinen Stift.", bn: "আমি আমার কলম খুঁজছি।" },
        { de: "Kennst du seinen Vater?", bn: "তুমি কি তার বাবাকে চেনো?" },
        { de: "Sie besucht ihren Bruder.", bn: "সে তার ভাইকে দেখতে যাচ্ছে।" },
      ],
      sagEs: [
        { q: "আমি আমার ভাইকে ভালোবাসি।", a: "Ich liebe meinen Bruder." },
        { q: "আমি আমার পরিবারকে ভালোবাসি।", a: "Ich liebe meine Familie." },
        { q: "আমি আমার কলম খুঁজছি।", a: "Ich suche meinen Stift." },
        { q: "তুমি কি তার (ছেলের) বাবাকে চেনো?", a: "Kennst du seinen Vater?" },
        { q: "সে তার (মেয়ের) ভাইকে দেখতে যাচ্ছে।", a: "Sie besucht ihren Bruder." },
        { q: "আমি আমার বইটা খুঁজছি। (সাবধান!)", a: "Ich suche mein Buch." },
      ],
      vonHerzen: { en: "Who do you love? Ich liebe meinen/meine ___, truthfully.", bn: "কাকে ভালোবাসো? সত্যি করে লেখো, -en লাগবে কি না ভেবে।" },
    },
    {
      n: 12,
      de: "Trennbar I: aufstehen · anrufen",
      bn: "কাতাপল্ট চালু",
      muster: {
        pattern: "Ich stehe … auf. Ich rufe … an.",
        why: "মূল ক্রিয়া আসন-দুইয়ে, উপসর্গ উড়ে গিয়ে একদম শেষে। মাঝে যা খুশি।",
        examples: "Ich stehe um sechs Uhr auf., স্তর-একের chunk, আজ যন্ত্র খোলা।",
        tip: "শেষের ছোট্ট শব্দটা ভুলো না, ওটাই অর্থ বহন করে!",
      },
      schau: [
        { de: "Ich stehe um sechs Uhr auf.", bn: "আমি ছয়টায় উঠি।" },
        { de: "Er steht spät auf.", bn: "সে দেরিতে ওঠে।" },
        { de: "Ich rufe dich an.", bn: "আমি তোমাকে ফোন করি।" },
        { de: "Sie ruft ihre Mutter an.", bn: "সে তার মাকে ফোন করে।" },
        { de: "Wann stehst du auf?", bn: "তুমি কখন ওঠো?" },
      ],
      sagEs: [
        { q: "আমি ছয়টায় উঠি।", a: "Ich stehe um sechs Uhr auf." },
        { q: "সে দেরিতে ওঠে।", a: "Er steht spät auf." },
        { q: "আমি তোমাকে ফোন করি।", a: "Ich rufe dich an." },
        { q: "সে তার মাকে ফোন করে।", a: "Sie ruft ihre Mutter an." },
        { q: "তুমি কখন ওঠো?", a: "Wann stehst du auf?" },
        { q: "আমি আজ রাতে ফোন করবো।", a: "Ich rufe heute Abend an." },
      ],
      vonHerzen: { en: "Your mornings: Ich stehe um ___ auf. Dann… (2 more lines)", bn: "তোমার সকাল: কখন ওঠো, তারপর কী করো, তিন লাইন।" },
    },
    {
      n: 13,
      de: "Trennbar II: einkaufen · fernsehen · mitkommen",
      bn: "বাজার · টিভি · সাথে আসা",
      muster: {
        pattern: "kaufe … ein · sehe … fern · kommst du mit?",
        why: "তিনটা রোজকার কাতাপল্ট, প্রশ্নেও উপসর্গ শেষে থাকে।",
        examples: "Kommst du mit?, বন্ধুত্বের সবচেয়ে ছোট দাওয়াত।",
        tip: "উত্তর: Ja, ich komme mit!",
      },
      schau: [
        { de: "Wir kaufen am Freitag ein.", bn: "আমরা শুক্রবারে বাজার করি।" },
        { de: "Ich sehe abends fern.", bn: "আমি সন্ধ্যায় টিভি দেখি।" },
        { de: "Er sieht zu viel fern!", bn: "সে বেশি টিভি দেখে!" },
        { de: "Kommst du mit?", bn: "তুমি কি সাথে আসছো?" },
        { de: "Ja, ich komme mit!", bn: "হ্যাঁ, আসছি!" },
      ],
      sagEs: [
        { q: "আমরা শুক্রবারে বাজার করি।", a: "Wir kaufen am Freitag ein." },
        { q: "আমি সন্ধ্যায় টিভি দেখি।", a: "Ich sehe abends fern." },
        { q: "সে বেশি টিভি দেখে।", a: "Er sieht zu viel fern." },
        { q: "তুমি কি সাথে আসছো?", a: "Kommst du mit?" },
        { q: "হ্যাঁ, আমি সাথে আসছি!", a: "Ja, ich komme mit!" },
        { q: "মা আজ বাজার করছেন।", a: "Mama kauft heute ein." },
      ],
      vonHerzen: { en: "Your week: when do you shop, watch, go along? 3 lines.", bn: "তোমার সপ্তাহ: কবে বাজার, কখন টিভি, তিন লাইনে।" },
    },
    {
      n: 14,
      de: "Trennbar III: anfangen · aufhören · aussehen · zumachen",
      bn: "শুরু · শেষ · দেখতে লাগা · বন্ধ করা",
      muster: {
        pattern: "fängt … an (ä!) · hört … auf · siehst … aus · mache … zu",
        why: "anfangen রূপবদলকারীও: du fängst, er fängt। দুই নিয়ম এক ক্রিয়ায়!",
        examples: "Du siehst müde aus!, 'তোমাকে ক্লান্ত দেখাচ্ছে'।",
        tip: "aussehen = ভেতর নয়, বাইরে থেকে যেমন লাগে।",
      },
      schau: [
        { de: "Die Schule fängt um acht an.", bn: "স্কুল আটটায় শুরু হয়।" },
        { de: "Der Film fängt jetzt an!", bn: "সিনেমাটা এখন শুরু হচ্ছে!" },
        { de: "Hör auf!", bn: "থামো!" },
        { de: "Du siehst müde aus.", bn: "তোমাকে ক্লান্ত দেখাচ্ছে।" },
        { de: "Ich mache die Tür zu.", bn: "আমি দরজাটা বন্ধ করছি।" },
      ],
      sagEs: [
        { q: "স্কুল আটটায় শুরু হয়।", a: "Die Schule fängt um acht an." },
        { q: "সিনেমাটা এখন শুরু হচ্ছে।", a: "Der Film fängt jetzt an." },
        { q: "থামো!", a: "Hör auf!" },
        { q: "তোমাকে ক্লান্ত দেখাচ্ছে।", a: "Du siehst müde aus." },
        { q: "আমি দরজাটা বন্ধ করছি।", a: "Ich mache die Tür zu." },
        { q: "তোমাকে খুশি দেখাচ্ছে!", a: "Du siehst glücklich aus!" },
      ],
      vonHerzen: { en: "When does your day start & stop? fängt an / hört auf.", bn: "তোমার দিন কখন শুরু, কখন শেষ, কাতাপল্টে বলো।" },
    },
    {
      n: 15,
      de: "Trennbar + Modal: জোড়া লাগে",
      bn: "modal এলে কাতাপল্ট বন্ধ",
      muster: {
        pattern: "Ich muss früh aufstehen. Ich möchte einkaufen.",
        why: "modal আসন-দুইয়ে, পুরো ক্রিয়া (জোড়া অবস্থায়) একদম শেষে, চেনা বন্ধনী।",
        examples: "একা → ভাঙে। modal-সহ → জোড়া।",
        tip: "দুটো ছবি মাথায় রাখো, গুলিয়ো না।",
      },
      schau: [
        { de: "Ich muss früh aufstehen.", bn: "আমাকে সকালে উঠতেই হবে।" },
        { de: "Ich möchte dich anrufen.", bn: "আমি তোমাকে ফোন করতে চাই।" },
        { de: "Kann ich mitkommen?", bn: "আমি কি সাথে আসতে পারি?" },
        { de: "Wir müssen heute einkaufen.", bn: "আজ আমাদের বাজার করতেই হবে।" },
        { de: "Du kannst jetzt anfangen.", bn: "তুমি এখন শুরু করতে পারো।" },
      ],
      sagEs: [
        { q: "আমাকে সকালে উঠতেই হবে।", a: "Ich muss früh aufstehen." },
        { q: "আমি তোমাকে ফোন করতে চাই।", a: "Ich möchte dich anrufen." },
        { q: "আমি কি সাথে আসতে পারি?", a: "Kann ich mitkommen?" },
        { q: "আজ আমাদের বাজার করতেই হবে।", a: "Wir müssen heute einkaufen." },
        { q: "তুমি এখন শুরু করতে পারো।", a: "Du kannst jetzt anfangen." },
        { q: "আমি টিভি দেখতে চাই না।", a: "Ich möchte nicht fernsehen." },
      ],
      vonHerzen: { en: "Tomorrow: one muss, one möchte, one kann, all with catapult verbs.", bn: "আগামীকাল: একটা muss, একটা möchte, একটা kann, সব কাতাপল্ট-ক্রিয়ায়।" },
    },
    {
      n: 16,
      de: "Trennbar-Fragen",
      bn: "কাতাপল্ট দিয়ে প্রশ্ন",
      muster: {
        pattern: "Wann stehst du auf? Kaufst du heute ein?",
        why: "W-প্রশ্নে ও হ্যাঁ/না প্রশ্নে, উপসর্গ শেষেই থাকে।",
        examples: "Wann fängt der Film an?, রোজকার সবচেয়ে দরকারি প্রশ্নগুলোর একটা।",
        tip: "প্রশ্ন করো, উত্তরও নিজে দাও, দুই দিকই অনুশীলন।",
      },
      schau: [
        { de: "Wann stehst du auf?", bn: "তুমি কখন ওঠো?" },
        { de: "Wann fängt der Film an?", bn: "সিনেমা কখন শুরু?" },
        { de: "Kaufst du heute ein?", bn: "আজ কি বাজার করছো?" },
        { de: "Siehst du abends fern?", bn: "সন্ধ্যায় টিভি দেখো?" },
        { de: "Rufst du mich an?", bn: "আমাকে ফোন করবে?" },
      ],
      sagEs: [
        { q: "তুমি কখন ওঠো?", a: "Wann stehst du auf?" },
        { q: "সিনেমা কখন শুরু হয়?", a: "Wann fängt der Film an?" },
        { q: "আজ কি বাজার করছো?", a: "Kaufst du heute ein?" },
        { q: "সন্ধ্যায় কি টিভি দেখো?", a: "Siehst du abends fern?" },
        { q: "আমাকে কি ফোন করবে?", a: "Rufst du mich an?" },
        { q: "তুমি কি সাথে আসছো?", a: "Kommst du mit?" },
      ],
      vonHerzen: { en: "Ask a family member two of these, for real, today.", bn: "এর দুটো প্রশ্ন আজই বাড়ির কাউকে সত্যি সত্যি করো।" },
    },
    {
      n: 17,
      de: "Mischung I: Akk + Possessiv",
      bn: "মিশ্রণ, কোট ও মালিকানা",
      muster: {
        pattern: "Ich rufe meinen Vater an. Ich suche deine Tasche.",
        why: "এক বাক্যে দুই নিয়ম, এখন থেকে সব বাক্যই এমন হবে।",
        examples: "ধীরে বলো, ঠিক বলো, গতি পরে আসবে।",
        tip: "ভুল হলে শুধু আবার বলো, থেমো না।",
      },
      schau: [
        { de: "Ich rufe meinen Vater an.", bn: "আমি বাবাকে ফোন করছি।" },
        { de: "Ich suche meine Tasche.", bn: "আমি আমার ব্যাগ খুঁজছি।" },
        { de: "Er liebt seinen Sohn.", bn: "সে তার ছেলেকে ভালোবাসে।" },
        { de: "Sie sucht ihren Schlüssel.", bn: "সে তার চাবি খুঁজছে।" },
        { de: "Kennst du unseren Lehrer?", bn: "আমাদের শিক্ষককে চেনো?" },
      ],
      sagEs: [
        { q: "আমি আমার বাবাকে ফোন করছি।", a: "Ich rufe meinen Vater an." },
        { q: "আমি আমার ব্যাগ খুঁজছি।", a: "Ich suche meine Tasche." },
        { q: "সে তার (ছেলের) ছেলেকে ভালোবাসে।", a: "Er liebt seinen Sohn." },
        { q: "সে তার (মেয়ের) চাবি খুঁজছে।", a: "Sie sucht ihren Schlüssel." },
        { q: "তুমি কি আমাদের শিক্ষককে চেনো?", a: "Kennst du unseren Lehrer?" },
        { q: "আমি আমার মাকে ফোন করছি।", a: "Ich rufe meine Mutter an." },
      ],
      vonHerzen: { en: "Three sentences with BOTH a possessive and a catapult/Akk.", bn: "তিনটা বাক্য, প্রতিটায় মালিকানা + কোট/কাতাপল্ট।" },
    },
    {
      n: 18,
      de: "Mischung II: গতি-দিন",
      bn: "তিন সেকেন্ডের খেলা",
      muster: {
        pattern: "সব হাতিয়ার, ঘড়ি ধরে",
        why: "আজ শুদ্ধতা নয়, সাহস। ভুল কোটেও সবাই বোঝে, গতিটা তৈরি করো।",
        examples: "প্রতিটা উত্তর তিনবার: ধীরে → স্বাভাবিক → দ্রুত।",
        tip: "তৃতীয়বারে হাসি এলে বুঝবে, বসে গেছে।",
      },
      schau: [
        { de: "Ich sehe ihn jeden Tag.", bn: "আমি তাকে রোজ দেখি।" },
        { de: "Er kauft einen Apfel für mich!", bn: "সে আমার জন্য একটা আপেল কেনে!" },
        { de: "Wir rufen unsere Oma an.", bn: "আমরা দাদিকে ফোন করি।" },
        { de: "Machst du das Fenster zu?", bn: "জানালাটা বন্ধ করবে?" },
        { de: "Es gibt keinen Zucker mehr.", bn: "চিনি আর নেই।" },
      ],
      sagEs: [
        { q: "আমি তাকে রোজ দেখি।", a: "Ich sehe ihn jeden Tag." },
        { q: "আমরা আমাদের দাদিকে ফোন করি।", a: "Wir rufen unsere Oma an." },
        { q: "জানালাটা কি বন্ধ করবে?", a: "Machst du das Fenster zu?" },
        { q: "চিনি আর নেই।", a: "Es gibt keinen Zucker mehr." },
        { q: "আমার আমার ফোনটা দরকার।", a: "Ich brauche mein Handy." },
        { q: "সে তার (মেয়ের) ভাইকে ভালোবাসে।", a: "Sie liebt ihren Bruder." },
      ],
      vonHerzen: { en: "Six of your own, timed, aloud, smiling by round three.", bn: "নিজের ছয়টা, ঘড়ি ধরে, জোরে, তৃতীয়বারে হাসিমুখে।" },
    },
    {
      n: 19,
      de: "Mini-Geschichte: Mein Morgen",
      bn: "ছোট্ট গল্প, বর্তমান কালে",
      muster: {
        pattern: "Ich stehe auf → trinke → rufe an → kaufe ein …",
        why: "আজ প্রথম টানা গল্প, সব হাতিয়ার এক সুতোয়। এখনো বর্তমান কালে; গতকালের কাল আসছে সামনের সেতুতে।",
        examples: "পাঁচ লাইন = একটা সকাল। জোরে, না থেমে।",
        tip: "এটাই ২১ দিন পরের 'Mein Gestern'-এর মহড়া।",
      },
      schau: [
        { de: "Ich stehe um sechs Uhr auf.", bn: "ছয়টায় উঠি।" },
        { de: "Ich trinke Tee und esse Brot.", bn: "চা খাই, রুটি খাই।" },
        { de: "Ich rufe meine Freundin an.", bn: "বান্ধবীকে ফোন করি।" },
        { de: "Dann kaufen wir ein.", bn: "তারপর আমরা বাজার করি।" },
        { de: "Es gibt einen neuen Markt!", bn: "একটা নতুন বাজার আছে!" },
      ],
      sagEs: [
        { q: "আমি ছয়টায় উঠি।", a: "Ich stehe um sechs Uhr auf." },
        { q: "আমি চা খাই আর রুটি খাই।", a: "Ich trinke Tee und esse Brot." },
        { q: "আমি আমার বান্ধবীকে ফোন করি।", a: "Ich rufe meine Freundin an." },
        { q: "তারপর আমরা বাজার করি।", a: "Dann kaufen wir ein." },
        { q: "একটা নতুন বাজার আছে।", a: "Es gibt einen neuen Markt." },
        { q: "আমি আমার ব্যাগ নিই। (nehmen)", a: "Ich nehme meine Tasche." },
      ],
      vonHerzen: { en: "YOUR morning, five connected lines, read aloud twice.", bn: "তোমার সকাল, পাঁচ লাইনের টানা গল্প, দু'বার জোরে।" },
    },
    {
      n: 20,
      de: "BRÜCKEN-CHECK 1: WER & WEN",
      bn: "প্রথম সেতু পার, নিজেকে যাচাই",
      muster: {
        pattern: "Akkusativ + Possessiv + Trennbar, একসাথে, বই বন্ধ করে",
        why: "আগে না দেখে করো। তারপর মিলাও। ৫/৬ পেলে সেতু পার, এগোও। কম হলে ২ দিন ফিরে দেখো, লজ্জা নেই।",
        examples: "আজ রেকর্ড করো: 'Mein Morgen' গল্পটা ফোনে। তারিখ লিখে রাখো।",
        tip: "৪০ দিন পরে এটা শুনে নিজেই অবাক হবে।",
      },
      schau: [
        { de: "Ich rufe meinen Bruder an.", bn: "কাতাপল্ট + Poss-Akk" },
        { de: "Er sieht mich, ich sehe ihn.", bn: "mich · ihn" },
        { de: "Wir müssen heute einkaufen.", bn: "modal + জোড়া" },
        { de: "Es gibt keinen Reis mehr.", bn: "es gibt + keinen" },
        { de: "Du siehst glücklich aus!", bn: "aussehen" },
      ],
      sagEs: [
        { q: "আমি আমার ভাইকে ফোন করছি।", a: "Ich rufe meinen Bruder an." },
        { q: "সে আমাকে দেখে, আমি তাকে দেখি।", a: "Er sieht mich, ich sehe ihn." },
        { q: "আজ আমাদের বাজার করতেই হবে।", a: "Wir müssen heute einkaufen." },
        { q: "চাল আর নেই।", a: "Es gibt keinen Reis mehr." },
        { q: "তোমাকে খুশি দেখাচ্ছে!", a: "Du siehst glücklich aus!" },
        { q: "আমি আমার পরিবারকে ভালোবাসি।", a: "Ich liebe meine Familie." },
      ],
      vonHerzen: { en: "Record 'Mein Morgen' on your phone. Write the date here: ____ 'Mein Morgen'", bn: "রেকর্ড করো। তারিখটা এখানে লেখো, এটা তোমার প্রথম মাইলফলক।" },
    },
    {
      n: 21,
      de: "Dativ I: mir · dir + helfen · danken",
      bn: "আমাকে সাহায্য · তোমাকে ধন্যবাদ",
      muster: {
        pattern: "Hilf mir! Ich danke dir!",
        why: "দ্বিতীয় সেতু শুরু। helfen আর danken সবসময় Dativ নেয়: mir, dir।",
        examples: "❌ hilf mich → ✅ hilf mir, এটাই আজকের একমাত্র যুদ্ধ।",
        tip: "দুই শব্দের হৃদস্পন্দন: hilf mir · danke dir।",
      },
      schau: [
        { de: "Kannst du mir helfen?", bn: "আমাকে সাহায্য করতে পারবে?" },
        { de: "Ich helfe dir!", bn: "আমি তোমাকে সাহায্য করবো!" },
        { de: "Hilf mir, bitte!", bn: "আমাকে সাহায্য করো, প্লিজ!" },
        { de: "Ich danke dir.", bn: "তোমাকে ধন্যবাদ।" },
        { de: "Wir danken Ihnen!", bn: "আপনাকে ধন্যবাদ!" },
      ],
      sagEs: [
        { q: "তুমি কি আমাকে সাহায্য করতে পারবে?", a: "Kannst du mir helfen?" },
        { q: "আমি তোমাকে সাহায্য করবো।", a: "Ich helfe dir." },
        { q: "আমাকে সাহায্য করো, প্লিজ!", a: "Hilf mir, bitte!" },
        { q: "আমি তোমাকে ধন্যবাদ দিচ্ছি।", a: "Ich danke dir." },
        { q: "আপনাকে ধন্যবাদ।", a: "Ich danke Ihnen." },
        { q: "আপনি কি আমাকে সাহায্য করতে পারবেন?", a: "Können Sie mir helfen?" },
      ],
      vonHerzen: { en: "Who helped you this week? Ich danke ___, write it, say it.", bn: "এই সপ্তাহে কে সাহায্য করেছে? তাকে জার্মানে ধন্যবাদ লেখো ও বলো।" },
    },
    {
      n: 22,
      de: "Dativ II: ihm · ihr · Ihnen + gehören",
      bn: "এটা কার?, gehört",
      muster: {
        pattern: "Das gehört mir / dir / ihm / ihr / uns / Ihnen.",
        why: "মালিকানা Dativ-এ: 'এটা আমার' = Das gehört mir।",
        examples: "ihm = তাকে (ছেলে/জিনিস), ihr = তাকে (মেয়ে)।",
        tip: "Poss-এর ihr (তার) আর Dativ-এর ihr (তাকে), বাক্যই বলে দেবে কোনটা।",
      },
      schau: [
        { de: "Das gehört mir.", bn: "এটা আমার।" },
        { de: "Das Buch gehört ihm.", bn: "বইটা তার (ছেলের)।" },
        { de: "Die Tasche gehört ihr.", bn: "ব্যাগটা তার (মেয়ের)।" },
        { de: "Das gehört uns allen.", bn: "এটা আমাদের সবার।" },
        { de: "Gehört das Ihnen?", bn: "এটা কি আপনার?" },
      ],
      sagEs: [
        { q: "এটা আমার।", a: "Das gehört mir." },
        { q: "বইটা তার (ছেলের)।", a: "Das Buch gehört ihm." },
        { q: "ব্যাগটা তার (মেয়ের)।", a: "Die Tasche gehört ihr." },
        { q: "এটা আমাদের সবার।", a: "Das gehört uns allen." },
        { q: "এটা কি আপনার?", a: "Gehört das Ihnen?" },
        { q: "এটা কি তোমার?", a: "Gehört das dir?" },
      ],
      vonHerzen: { en: "Point at five things: Das gehört mir / meiner Mutter…", bn: "পাঁচটা জিনিস দেখিয়ে বলো, কোনটা কার।" },
    },
    {
      n: 23,
      de: "Dativ III: gefallen · schmecken, বাংলা-উপহার",
      bn: "আমার ভালো লাগে = mir gefällt",
      muster: {
        pattern: "Das gefällt mir. Der Tee schmeckt mir.",
        why: "বাংলা আর জার্মান একমত: যে অনুভব করে, সে গ্রহীতা। 'আমার ভালো লাগে', হুবহু এই গঠন!",
        examples: "Wie geht es dir?, স্তর-এক থেকেই তুমি Dativ বলছো!",
        tip: "আজ শুধু জানলে, কেন।",
      },
      schau: [
        { de: "Das gefällt mir!", bn: "আমার এটা ভালো লাগে!" },
        { de: "Gefällt dir das Lied?", bn: "গানটা কি তোমার ভালো লাগে?" },
        { de: "Der Reis schmeckt mir.", bn: "ভাতটা আমার ভালো লাগছে।" },
        { de: "Schmeckt es dir?", bn: "খেতে ভালো লাগছে?" },
        { de: "Mir ist kalt.", bn: "আমার ঠান্ডা লাগছে।" },
      ],
      sagEs: [
        { q: "আমার এটা ভালো লাগে।", a: "Das gefällt mir." },
        { q: "গানটা কি তোমার ভালো লাগে?", a: "Gefällt dir das Lied?" },
        { q: "ভাতটা আমার ভালো লাগছে।", a: "Der Reis schmeckt mir." },
        { q: "খেতে কি ভালো লাগছে?", a: "Schmeckt es dir?" },
        { q: "আমার ঠান্ডা লাগছে।", a: "Mir ist kalt." },
        { q: "তোমার কেমন চলছে?", a: "Wie geht es dir?" },
      ],
      vonHerzen: { en: "Three honest 'gefällt mir' lines, what do you truly like?", bn: "সত্যি করে: কী কী তোমার ভালো লাগে, তিন লাইন।" },
    },
    {
      n: 24,
      de: "Dativ IV: dem · der + mit",
      bn: "টুপির Dativ-গান: dem-der-dem",
      muster: {
        pattern: "mit dem Mann · mit der Frau · mit dem Kind",
        why: "নীল→dem, লাল→der (!), সবুজ→dem। mit সবসময় Dativ ডাকে।",
        examples: "mit meiner Mutter, mein-ও একই পোশাক পরে: meinem/meiner।",
        tip: "গাও: dem-der-dem। দশবার।",
      },
      schau: [
        { de: "Ich fahre mit dem Bus.", bn: "আমি বাসে যাই।" },
        { de: "Ich koche mit meiner Mutter.", bn: "মায়ের সাথে রান্না করি।" },
        { de: "Er spricht mit dem Lehrer.", bn: "সে শিক্ষকের সাথে কথা বলছে।" },
        { de: "Sie spielt mit dem Kind.", bn: "সে বাচ্চাটার সাথে খেলছে।" },
        { de: "Ich lerne mit meinem Bruder.", bn: "ভাইয়ের সাথে পড়ি।" },
      ],
      sagEs: [
        { q: "আমি বাসে যাই।", a: "Ich fahre mit dem Bus." },
        { q: "আমি আমার মায়ের সাথে রান্না করি।", a: "Ich koche mit meiner Mutter." },
        { q: "সে শিক্ষকের সাথে কথা বলছে।", a: "Er spricht mit dem Lehrer." },
        { q: "সে বাচ্চাটার সাথে খেলছে।", a: "Sie spielt mit dem Kind." },
        { q: "আমি আমার ভাইয়ের সাথে পড়ি।", a: "Ich lerne mit meinem Bruder." },
        { q: "তুমি কার সাথে যাচ্ছো?", a: "Mit wem fährst du?" },
      ],
      vonHerzen: { en: "Who do you do things WITH? Three mit-sentences.", bn: "কার সাথে কী করো, তিনটা mit-বাক্য।" },
    },
    {
      n: 25,
      de: "Dativ-Präp I: nach · aus · zu",
      bn: "বাড়ি · দেশ · স্কুল",
      muster: {
        pattern: "nach Hause · aus Bangladesch · zur Schule · zum Markt",
        why: "zu + der = zur, zu + dem = zum। এই ছোট জোড়া দুটো মুখস্থই চলবে।",
        examples: "nach Hause (বাড়ির দিকে) · zu Hause (বাড়িতে), দুই আলাদা!",
        tip: "যাচ্ছি → nach Hause। আছি → zu Hause।",
      },
      schau: [
        { de: "Ich gehe nach Hause.", bn: "আমি বাড়ি যাচ্ছি।" },
        { de: "Ich bin zu Hause.", bn: "আমি বাড়িতে আছি।" },
        { de: "Ich komme aus Bangladesch.", bn: "আমি বাংলাদেশ থেকে।" },
        { de: "Wir fahren zur Schule.", bn: "আমরা স্কুলে যাচ্ছি।" },
        { de: "Er geht zum Markt.", bn: "সে বাজারে যাচ্ছে।" },
      ],
      sagEs: [
        { q: "আমি বাড়ি যাচ্ছি।", a: "Ich gehe nach Hause." },
        { q: "আমি বাড়িতে আছি।", a: "Ich bin zu Hause." },
        { q: "আমি বাংলাদেশ থেকে এসেছি।", a: "Ich komme aus Bangladesch." },
        { q: "আমরা স্কুলে যাচ্ছি।", a: "Wir fahren zur Schule." },
        { q: "সে বাজারে যাচ্ছে।", a: "Er geht zum Markt." },
        { q: "তুমি কি বাড়ি যাচ্ছো?", a: "Gehst du nach Hause?" },
      ],
      vonHerzen: { en: "Your daily route: aus → zur/zum → nach Hause. Tell it.", bn: "তোমার রোজকার পথ: কোথা থেকে, কোথায়, শেষে বাড়ি, বলো।" },
    },
    {
      n: 26,
      de: "Dativ-Präp II: von · bei · seit",
      bn: "কাছ থেকে · ওখানে · কবে থেকে",
      muster: {
        pattern: "von meinem Vater · bei uns · seit zwei Jahren + বর্তমান!",
        why: "seit-ফাঁদ: এখনো চলছে → বর্তমান কাল। ইংরেজির 'has been' এখানে নিষিদ্ধ।",
        examples: "Ich lerne seit zwei Jahren Englisch., শিখছি, এখনো।",
        tip: "❌ habe gelernt seit…, কক্ষনো না।",
      },
      schau: [
        { de: "Das ist von meinem Vater.", bn: "এটা বাবার কাছ থেকে।" },
        { de: "Wir essen heute bei uns.", bn: "আজ আমাদের ওখানে খাচ্ছি।" },
        { de: "Sie wohnt bei ihrer Tante.", bn: "সে খালার ওখানে থাকে।" },
        { de: "Ich lerne seit zwei Jahren Englisch.", bn: "দুই বছর ধরে ইংরেজি শিখছি।" },
        { de: "Seit wann lernst du Deutsch?", bn: "কবে থেকে জার্মান শিখছো?" },
      ],
      sagEs: [
        { q: "এটা আমার বাবার কাছ থেকে।", a: "Das ist von meinem Vater." },
        { q: "সে তার খালার ওখানে থাকে।", a: "Sie wohnt bei ihrer Tante." },
        { q: "আমি দুই বছর ধরে ইংরেজি শিখছি।", a: "Ich lerne seit zwei Jahren Englisch." },
        { q: "আমি ২০২০ থেকে ঢাকায় থাকি।", a: "Ich wohne seit 2020 in Dhaka." },
        { q: "কবে থেকে জার্মান শিখছো?", a: "Seit wann lernst du Deutsch?" },
        { q: "আজ আমরা আমাদের ওখানে খাচ্ছি।", a: "Wir essen heute bei uns." },
      ],
      vonHerzen: { en: "seit wann…? Three true 'since' facts about your life, present tense!", bn: "তোমার জীবনের তিনটা 'কবে থেকে', বর্তমান কালে!" },
    },
    {
      n: 27,
      de: "Akk-Präp: für · ohne · um",
      bn: "জন্য · ছাড়া · -টায়",
      muster: {
        pattern: "für dich · für meinen Bruder · ohne Zucker · um drei Uhr",
        why: "এই দল Akkusativ ডাকে, für-এর পরে নীল দলে -en।",
        examples: "Das ist für dich!, উপহার দেওয়ার বাক্য।",
        tip: "um drei Uhr, স্তর-এক থেকেই চেনা, আজ জানলে কেন।",
      },
      schau: [
        { de: "Das ist für dich!", bn: "এটা তোমার জন্য!" },
        { de: "Ich koche für meine Familie.", bn: "পরিবারের জন্য রান্না করি।" },
        { de: "Das ist für meinen Bruder.", bn: "এটা আমার ভাইয়ের জন্য।" },
        { de: "Tee ohne Zucker, bitte.", bn: "চিনি ছাড়া চা, প্লিজ।" },
        { de: "Wir essen um acht Uhr.", bn: "আমরা আটটায় খাই।" },
      ],
      sagEs: [
        { q: "এটা তোমার জন্য!", a: "Das ist für dich!" },
        { q: "আমি আমার পরিবারের জন্য রান্না করি।", a: "Ich koche für meine Familie." },
        { q: "এটা আমার ভাইয়ের জন্য।", a: "Das ist für meinen Bruder." },
        { q: "চিনি ছাড়া চা, প্লিজ।", a: "Tee ohne Zucker, bitte." },
        { q: "আমরা আটটায় খাই।", a: "Wir essen um acht Uhr." },
        { q: "আমি তোমাকে ছাড়া যাবো না।", a: "Ich gehe nicht ohne dich." },
      ],
      vonHerzen: { en: "Für wen…? Three 'for someone' lines about your real life.", bn: "কার জন্য কী করো, তিনটা সত্যি für-বাক্য।" },
    },
    {
      n: 28,
      de: "Wo? / Wohin?, in · auf",
      bn: "স্থির না গতি?",
      muster: {
        pattern: "Wo? → in der Schule (Dativ) Wohin? → in die Schule (Akk)",
        why: "দাঁড়িয়ে আছো → Dativ। ঢুকছো/যাচ্ছো → Akkusativ। ছবিটাকে জিজ্ঞেস করো: কিছু কি নড়ছে?",
        examples: "im = in dem · ins = in das · am = an dem",
        tip: "এই ছোট জোড়াগুলো মুখস্থ চলবে।",
      },
      schau: [
        { de: "Ich bin in der Schule.", bn: "আমি স্কুলে আছি।" },
        { de: "Ich gehe in die Schule.", bn: "আমি স্কুলে যাচ্ছি।" },
        { de: "Das Buch ist auf dem Tisch.", bn: "বইটা টেবিলের উপর।" },
        { de: "Ich lege das Buch auf den Tisch.", bn: "বইটা টেবিলে রাখছি।" },
        { de: "Wir essen im Zimmer.", bn: "আমরা ঘরে খাচ্ছি।" },
      ],
      sagEs: [
        { q: "আমি স্কুলে আছি।", a: "Ich bin in der Schule." },
        { q: "আমি স্কুলে যাচ্ছি।", a: "Ich gehe in die Schule." },
        { q: "বইটা টেবিলের উপর।", a: "Das Buch ist auf dem Tisch." },
        { q: "আমি বইটা টেবিলে রাখছি।", a: "Ich lege das Buch auf den Tisch." },
        { q: "আমরা ঘরে খাচ্ছি।", a: "Wir essen im Zimmer." },
        { q: "আমি বিছানায় যাচ্ছি।", a: "Ich gehe ins Bett." },
      ],
      vonHerzen: { en: "Five things in your room: Wo ist…?, auf dem / in der…", bn: "তোমার ঘরের পাঁচটা জিনিস কোথায়, Dativ-এ বলো।" },
    },
    {
      n: 29,
      de: "Perfekt I: ge____t",
      bn: "গতকালের কাল শুরু, নিয়মিত দল",
      muster: {
        pattern: "habe + ge___t (শেষে!): gemacht · gelernt · gekocht",
        why: "গতকাল বলার বন্ধনী: haben আসন-দুইয়ে, ge-শব্দ একদম শেষে।",
        examples: "Ich habe Reis gekocht., তোমার প্রথম জার্মান অতীত-বাক্য!",
        tip: "আজ থেকে জোড়ায় শেখো: machen–gemacht।",
      },
      schau: [
        { de: "Ich habe Reis gekocht.", bn: "আমি ভাত রান্না করেছি।" },
        { de: "Ich habe Deutsch gelernt.", bn: "আমি জার্মান পড়েছি।" },
        { de: "Was hast du gemacht?", bn: "তুমি কী করেছো?" },
        { de: "Wir haben Cricket gespielt.", bn: "আমরা ক্রিকেট খেলেছি।" },
        { de: "Sie hat viel gearbeitet.", bn: "সে অনেক কাজ করেছে।" },
      ],
      sagEs: [
        { q: "আমি ভাত রান্না করেছি।", a: "Ich habe Reis gekocht." },
        { q: "আমি জার্মান পড়েছি।", a: "Ich habe Deutsch gelernt." },
        { q: "তুমি কী করেছো?", a: "Was hast du gemacht?" },
        { q: "আমরা ক্রিকেট খেলেছি।", a: "Wir haben Cricket gespielt." },
        { q: "সে অনেক কাজ করেছে।", a: "Sie hat viel gearbeitet." },
        { q: "আমি একটা জ্যাকেট কিনেছি।", a: "Ich habe eine Jacke gekauft." },
      ],
      vonHerzen: { en: "Yesterday, three ge___t lines: Ich habe ___ gemacht/gelernt/gekocht.", bn: "গতকাল: তিনটা ge___t বাক্য, সত্যিগুলো।" },
    },
    {
      n: 30,
      de: "Perfekt II: আরও নিয়মিত + প্রশ্ন",
      bn: "gehört · gefragt · gesucht",
      muster: {
        pattern: "Hast du …? Habt ihr …?, Perfekt-প্রশ্নও চেনা লাফে",
        why: "haben সামনে লাফায়, ge-শব্দ শেষেই থাকে। নতুন কিছু নেই, শুধু জোড়া।",
        examples: "Ich habe Musik gehört. · Ich habe dich gesucht!",
        tip: "রোজ রাতে: গতকালের তিনটা কাজ Perfekt-এ।",
      },
      schau: [
        { de: "Ich habe Musik gehört.", bn: "আমি গান শুনেছি।" },
        { de: "Ich habe dich gesucht!", bn: "আমি তোমাকে খুঁজেছি!" },
        { de: "Er hat den Lehrer gefragt.", bn: "সে শিক্ষককে জিজ্ঞেস করেছে।" },
        { de: "Hast du gut geschlafen? *", bn: "ভালো ঘুমিয়েছো?" },
        { de: "Wir haben lange gewartet.", bn: "আমরা অনেকক্ষণ অপেক্ষা করেছি।" },
      ],
      sagEs: [
        { q: "আমি গান শুনেছি।", a: "Ich habe Musik gehört." },
        { q: "আমি তোমাকে খুঁজেছি।", a: "Ich habe dich gesucht." },
        { q: "সে শিক্ষককে জিজ্ঞেস করেছে।", a: "Er hat den Lehrer gefragt." },
        { q: "আমরা অনেকক্ষণ অপেক্ষা করেছি।", a: "Wir haben lange gewartet." },
        { q: "তুমি কি কাজ করেছো?", a: "Hast du gearbeitet?" },
        { q: "তোমরা কী খেলেছো?", a: "Was habt ihr gespielt?" },
      ],
      vonHerzen: { en: "Ask someone: Was hast du gestern gemacht? Note their answer.", bn: "কাউকে জিজ্ঞেস করো: কাল কী করেছো?, উত্তরটা জার্মানে টুকে নাও। (* geschlafen, আগাম ঝলক, কাল আসছে!)" },
    },
    {
      n: 31,
      de: "Perfekt III: অনিয়মিত, gegessen · getrunken · gesehen",
      bn: "বদলে গিয়ে -en",
      muster: {
        pattern: "ge + বদল + en: essen→gegessen · trinken→getrunken · sehen→gesehen",
        why: "অনিয়মিত দল শেষে -en নেয়, মাঝেরটাও বদলায়। জোড়া গাও, নিয়ম খুঁজো না।",
        examples: "schlafen→geschlafen, কালকের ঝলকটা আজ পুরো তোমার।",
        tip: "জোড়া-কার্ড বানাও: সামনে essen, পিছনে gegessen।",
      },
      schau: [
        { de: "Wir haben Fisch gegessen.", bn: "আমরা মাছ খেয়েছি।" },
        { de: "Ich habe Wasser getrunken.", bn: "আমি পানি খেয়েছি।" },
        { de: "Ich habe dich gesehen!", bn: "আমি তোমাকে দেখেছি!" },
        { de: "Ich habe gut geschlafen.", bn: "আমি ভালো ঘুমিয়েছি।" },
        { de: "Was hast du gegessen?", bn: "তুমি কী খেয়েছো?" },
      ],
      sagEs: [
        { q: "আমরা মাছ খেয়েছি।", a: "Wir haben Fisch gegessen." },
        { q: "আমি পানি খেয়েছি।", a: "Ich habe Wasser getrunken." },
        { q: "আমি তোমাকে দেখেছি।", a: "Ich habe dich gesehen." },
        { q: "আমি ভালো ঘুমিয়েছি।", a: "Ich habe gut geschlafen." },
        { q: "তুমি কী খেয়েছো?", a: "Was hast du gegessen?" },
        { q: "সে চা খেয়েছে।", a: "Er hat Tee getrunken." },
      ],
      vonHerzen: { en: "Last night's dinner, in Perfekt: gegessen, getrunken.", bn: "কাল রাতের খাবার, Perfekt-এ: কী খেলে, কী পান করলে।" },
    },
    {
      n: 32,
      de: "Perfekt IV: gelesen · geschrieben · gesprochen",
      bn: "পড়া · লেখা · বলা, অতীতে",
      muster: {
        pattern: "lesen→gelesen · schreiben→geschrieben · sprechen→gesprochen · nehmen→genommen",
        why: "শেখার ক্রিয়াগুলোর অতীত, এগুলো দিয়েই রোজ নিজের পড়াশোনার গল্প বলবে।",
        examples: "Ich habe zehn Sätze geschrieben!, রোজকার জয়ের বাক্য।",
        tip: "আজ থেকে দিনের শেষে এটা সত্যি করে বলো।",
      },
      schau: [
        { de: "Ich habe ein Buch gelesen.", bn: "আমি একটা বই পড়েছি।" },
        { de: "Ich habe zehn Sätze geschrieben.", bn: "দশটা বাক্য লিখেছি।" },
        { de: "Wir haben Deutsch gesprochen!", bn: "আমরা জার্মান বলেছি!" },
        { de: "Er hat den Bus genommen.", bn: "সে বাসটা নিয়েছে।" },
        { de: "Sie hat mir das Buch gegeben.", bn: "সে আমাকে বইটা দিয়েছে।" },
      ],
      sagEs: [
        { q: "আমি একটা বই পড়েছি।", a: "Ich habe ein Buch gelesen." },
        { q: "আমি দশটা বাক্য লিখেছি।", a: "Ich habe zehn Sätze geschrieben." },
        { q: "আমরা জার্মান বলেছি।", a: "Wir haben Deutsch gesprochen." },
        { q: "সে বাসটা নিয়েছে।", a: "Er hat den Bus genommen." },
        { q: "সে আমাকে বইটা দিয়েছে।", a: "Sie hat mir das Buch gegeben." },
        { q: "তুমি কী পড়েছো?", a: "Was hast du gelesen?" },
      ],
      vonHerzen: { en: "Today's honest report: gelesen? geschrieben? gesprochen?", bn: "আজকের সৎ রিপোর্ট: কী পড়লে, লিখলে, বললে, তিন লাইন।" },
    },
    {
      n: 33,
      de: "Perfekt V: sein-দল, gegangen · gekommen · gefahren",
      bn: "শরীর নড়লে sein",
      muster: {
        pattern: "bin/ist/sind + gegangen · gekommen · gefahren",
        why: "শরীর এক জায়গা থেকে আরেক জায়গায় গেছে? তাহলে haben নয়, sein!",
        examples: "Ich bin nach Hause gegangen., bin আসন-দুইয়ে, gegangen শেষে।",
        tip: "সহজ পরীক্ষা: গেছে/এসেছে? → sein।",
      },
      schau: [
        { de: "Ich bin nach Hause gegangen.", bn: "আমি বাড়ি গিয়েছি।" },
        { de: "Sie ist spät gekommen.", bn: "সে দেরিতে এসেছে।" },
        { de: "Wir sind nach Dhaka gefahren.", bn: "আমরা ঢাকায় গিয়েছি।" },
        { de: "Bist du zur Schule gegangen?", bn: "তুমি কি স্কুলে গিয়েছিলে?" },
        { de: "Er ist mit dem Bus gefahren.", bn: "সে বাসে গিয়েছে।" },
      ],
      sagEs: [
        { q: "আমি বাড়ি গিয়েছি।", a: "Ich bin nach Hause gegangen." },
        { q: "সে দেরিতে এসেছে।", a: "Sie ist spät gekommen." },
        { q: "আমরা ঢাকায় গিয়েছি।", a: "Wir sind nach Dhaka gefahren." },
        { q: "তুমি কি স্কুলে গিয়েছিলে?", a: "Bist du zur Schule gegangen?" },
        { q: "সে বাসে গিয়েছে।", a: "Er ist mit dem Bus gefahren." },
        { q: "আমি বাজারে গিয়েছি।", a: "Ich bin zum Markt gegangen." },
      ],
      vonHerzen: { en: "Where did you GO yesterday? Three bin/sind-lines.", bn: "কাল কোথায় কোথায় গেলে, তিনটা sein-বাক্য।" },
    },
    {
      n: 34,
      de: "Perfekt VI: aufgestanden · geblieben · passiert",
      bn: "sein-দলের বাকি তারকারা",
      muster: {
        pattern: "bin aufgestanden · ist geblieben (!) · ist passiert (!)",
        why: "bleiben (থাকা) আর passieren (ঘটা) নড়ে না, তবু sein নেয়, দুই বিখ্যাত ব্যতিক্রম।",
        examples: "Was ist passiert?, 'কী হয়েছে?', রোজকার জরুরি প্রশ্ন।",
        tip: "aufgestanden, কাতাপল্ট-Partizip-এর প্রথম দেখা, কাল পুরো দল।",
      },
      schau: [
        { de: "Ich bin um sechs aufgestanden.", bn: "আমি ছয়টায় উঠেছি।" },
        { de: "Er ist zu Hause geblieben.", bn: "সে বাসায় থেকেছে।" },
        { de: "Was ist passiert?", bn: "কী হয়েছে?" },
        { de: "Nichts ist passiert!", bn: "কিছু হয়নি!" },
        { de: "Wir sind lange geblieben.", bn: "আমরা অনেকক্ষণ ছিলাম।" },
      ],
      sagEs: [
        { q: "আমি ছয়টায় উঠেছি।", a: "Ich bin um sechs aufgestanden." },
        { q: "সে বাসায় থেকেছে।", a: "Er ist zu Hause geblieben." },
        { q: "কী হয়েছে?", a: "Was ist passiert?" },
        { q: "কিছু হয়নি।", a: "Nichts ist passiert." },
        { q: "আমরা অনেকক্ষণ ছিলাম।", a: "Wir sind lange geblieben." },
        { q: "তুমি কখন উঠেছো?", a: "Wann bist du aufgestanden?" },
      ],
      vonHerzen: { en: "Your yesterday's start: Ich bin um ___ aufgestanden. Dann…", bn: "কাল কখন উঠলে, তারপর কী, দুই লাইন Perfekt-এ।" },
    },
    {
      n: 35,
      de: "Perfekt VII: কাতাপল্ট-Partizip",
      bn: "eingekauft · angerufen · ferngesehen",
      muster: {
        pattern: "উপসর্গ + ge + মূল: ein·ge·kauft · an·ge·rufen · fern·ge·sehen",
        why: "কাতাপল্ট-ক্রিয়ার ge মাঝখানে ঢোকে, উপসর্গ আর মূলের ফাঁকে।",
        examples: "Ich habe dich angerufen!, 'ফোন করেছিলাম তো!'",
        tip: "জোড়া গাও: anrufen–angerufen, einkaufen–eingekauft।",
      },
      schau: [
        { de: "Ich habe eingekauft.", bn: "আমি বাজার করেছি।" },
        { de: "Ich habe dich angerufen!", bn: "আমি তোমাকে ফোন করেছিলাম!" },
        { de: "Wir haben ferngesehen.", bn: "আমরা টিভি দেখেছি।" },
        { de: "Der Film hat angefangen.", bn: "সিনেমাটা শুরু হয়ে গেছে।" },
        { de: "Ich habe die Tür zugemacht.", bn: "আমি দরজাটা বন্ধ করেছি।" },
      ],
      sagEs: [
        { q: "আমি বাজার করেছি।", a: "Ich habe eingekauft." },
        { q: "আমি তোমাকে ফোন করেছিলাম।", a: "Ich habe dich angerufen." },
        { q: "আমরা টিভি দেখেছি।", a: "Wir haben ferngesehen." },
        { q: "সিনেমাটা শুরু হয়ে গেছে।", a: "Der Film hat angefangen." },
        { q: "আমি দরজাটা বন্ধ করেছি।", a: "Ich habe die Tür zugemacht." },
        { q: "মা বাজার করেছেন।", a: "Mama hat eingekauft." },
      ],
      vonHerzen: { en: "Yesterday's catapults: eingekauft? angerufen? ferngesehen?", bn: "কালকের কাতাপল্ট-কাজগুলো, Perfekt-এ তিনটা।" },
    },
    {
      n: 36,
      de: "Perfekt VIII: ge-হীন দল",
      bn: "studiert · besucht · verstanden",
      muster: {
        pattern: "-ieren / be- / ver- শুরু হলে: ge নেই!",
        why: "এই তিন পরিবারে ge ঢোকে না, এমনিতেই ভারী শব্দ, আর বোঝা নেয় না।",
        examples: "Ich habe alles verstanden!, ক্লাসের সেরা বাক্য।",
        tip: "telefoniert, besucht, bekommen, verstanden, চারটাই ge-হীন।",
      },
      schau: [
        { de: "Ich habe alles verstanden!", bn: "আমি সব বুঝেছি!" },
        { de: "Sie hat Medizin studiert.", bn: "সে মেডিসিন পড়েছে।" },
        { de: "Wir haben Oma besucht.", bn: "আমরা দাদিকে দেখতে গিয়েছি।" },
        { de: "Ich habe lange telefoniert.", bn: "আমি অনেকক্ষণ ফোনে কথা বলেছি।" },
        { de: "Er hat ein Geschenk bekommen.", bn: "সে একটা উপহার পেয়েছে।" },
      ],
      sagEs: [
        { q: "আমি সব বুঝেছি!", a: "Ich habe alles verstanden!" },
        { q: "সে মেডিসিন পড়েছে।", a: "Sie hat Medizin studiert." },
        { q: "আমরা দাদিকে দেখতে গিয়েছি।", a: "Wir haben Oma besucht." },
        { q: "আমি অনেকক্ষণ ফোনে কথা বলেছি।", a: "Ich habe lange telefoniert." },
        { q: "সে একটা উপহার পেয়েছে।", a: "Er hat ein Geschenk bekommen." },
        { q: "তুমি কি বুঝেছো?", a: "Hast du verstanden?" },
      ],
      vonHerzen: { en: "besucht / telefoniert / verstanden, one true line each.", bn: "তিন ge-হীন ক্রিয়া দিয়ে নিজের তিনটা সত্যি বাক্য।" },
    },
    {
      n: 37,
      de: "war · hatte, দুই শর্টকাট",
      bn: "ছিলাম · ছিল",
      muster: {
        pattern: "Ich war müde. Ich hatte keine Zeit.",
        why: "sein/haben-এর অতীতে Perfekt কেউ বলে না, সবাই war/hatte। ich = er/sie/es!",
        examples: "Der Tag war gut., আজ থেকে প্রতিটা গল্পের শেষ লাইন।",
        tip: "war-hatte দিয়েই অতীতের অর্ধেক আড্ডা চলে।",
      },
      schau: [
        { de: "Ich war müde.", bn: "আমি ক্লান্ত ছিলাম।" },
        { de: "Wo warst du?", bn: "তুমি কোথায় ছিলে?" },
        { de: "Ich hatte keine Zeit.", bn: "আমার সময় ছিল না।" },
        { de: "Wir waren zu Hause.", bn: "আমরা বাসায় ছিলাম।" },
        { de: "Der Tag war schön!", bn: "দিনটা সুন্দর ছিল!" },
      ],
      sagEs: [
        { q: "আমি ক্লান্ত ছিলাম।", a: "Ich war müde." },
        { q: "তুমি কোথায় ছিলে?", a: "Wo warst du?" },
        { q: "আমার সময় ছিল না।", a: "Ich hatte keine Zeit." },
        { q: "আমরা বাসায় ছিলাম।", a: "Wir waren zu Hause." },
        { q: "দিনটা সুন্দর ছিল।", a: "Der Tag war schön." },
        { q: "তার খিদে পেয়েছিল।", a: "Er hatte Hunger." },
      ],
      vonHerzen: { en: "Yesterday's feelings: Ich war… Ich hatte…, three lines.", bn: "কালকের অনুভূতি: war আর hatte দিয়ে তিন লাইন।" },
    },
    {
      n: 38,
      de: "Erzählen I: zuerst · dann",
      bn: "গল্পের প্রথম দুই পুঁতি",
      muster: {
        pattern: "Zuerst habe ich … Dann bin ich …",
        why: "পুঁতি আসন-এক নেয় → ক্রিয়া দুইয়ে (সিসো)। Perfekt-বাক্যগুলো এবার সুতোয় গাঁথা শুরু।",
        examples: "Zuerst … Dann …, দুই শব্দেই গল্প জন্মায়।",
        tip: "আজ দুই পুঁতি, পরশু পুরো মালা।",
      },
      schau: [
        { de: "Zuerst habe ich Tee getrunken.", bn: "প্রথমে চা খেয়েছি।" },
        { de: "Dann habe ich gelernt.", bn: "তারপর পড়েছি।" },
        { de: "Zuerst bin ich aufgestanden.", bn: "প্রথমে উঠেছি।" },
        { de: "Dann bin ich zur Schule gegangen.", bn: "তারপর স্কুলে গিয়েছি।" },
        { de: "Dann haben wir gegessen.", bn: "তারপর আমরা খেয়েছি।" },
      ],
      sagEs: [
        { q: "প্রথমে আমি চা খেয়েছি।", a: "Zuerst habe ich Tee getrunken." },
        { q: "তারপর আমি পড়েছি।", a: "Dann habe ich gelernt." },
        { q: "প্রথমে আমি উঠেছি।", a: "Zuerst bin ich aufgestanden." },
        { q: "তারপর আমি স্কুলে গিয়েছি।", a: "Dann bin ich zur Schule gegangen." },
        { q: "তারপর আমরা খেয়েছি।", a: "Dann haben wir gegessen." },
        { q: "তারপর সে বাড়ি গিয়েছে।", a: "Dann ist er nach Hause gegangen." },
      ],
      vonHerzen: { en: "Your yesterday in four beads: Zuerst… Dann… Dann… Dann…", bn: "কালকের দিন চার পুঁতিতে, Zuerst, তারপর তিনটা Dann।" },
    },
    {
      n: 39,
      de: "Dativ + Perfekt: geholfen",
      bn: "কাকে সাহায্য করেছো, অতীতে",
      muster: {
        pattern: "Ich habe meiner Mutter geholfen. Er hat mir geholfen.",
        why: "দুই সেতুর মিলন: Dativ (কাকে) + Perfekt (গতকাল)। helfen→geholfen।",
        examples: "danken→gedankt · gefallen→gefallen: Das hat mir gefallen!",
        tip: "'ভালো লেগেছিল' = hat mir gefallen, উপহার-গঠন অতীতেও।",
      },
      schau: [
        { de: "Ich habe meiner Mutter geholfen.", bn: "আমি মাকে সাহায্য করেছি।" },
        { de: "Er hat mir geholfen.", bn: "সে আমাকে সাহায্য করেছে।" },
        { de: "Das hat mir gefallen!", bn: "এটা আমার ভালো লেগেছিল!" },
        { de: "Der Film hat uns gefallen.", bn: "সিনেমাটা আমাদের ভালো লেগেছে।" },
        { de: "Das Essen hat mir geschmeckt.", bn: "খাবারটা ভালো লেগেছিল।" },
      ],
      sagEs: [
        { q: "আমি আমার মাকে সাহায্য করেছি।", a: "Ich habe meiner Mutter geholfen." },
        { q: "সে আমাকে সাহায্য করেছে।", a: "Er hat mir geholfen." },
        { q: "এটা আমার ভালো লেগেছিল।", a: "Das hat mir gefallen." },
        { q: "সিনেমাটা আমাদের ভালো লেগেছে।", a: "Der Film hat uns gefallen." },
        { q: "খাবারটা আমার ভালো লেগেছিল।", a: "Das Essen hat mir geschmeckt." },
        { q: "তুমি কি তাকে (মেয়ে) সাহায্য করেছো?", a: "Hast du ihr geholfen?" },
      ],
      vonHerzen: { en: "Who did you help this week? Wem hast du geholfen?", bn: "এই সপ্তাহে কাকে সাহায্য করলে, Perfekt-এ দুই লাইন।" },
    },
    {
      n: 40,
      de: "BRÜCKEN-CHECK 2: GEBEN & GESTERN",
      bn: "দ্বিতীয় সেতু পার",
      muster: {
        pattern: "Dativ + Präpositionen + Perfekt, বই বন্ধ, মুখ খোলা",
        why: "৫/৬ = পার। আজ আবার রেকর্ড করো, এবার 'Mein Gestern' Perfekt-এ। ২০ দিনের রেকর্ডিংটাও শোনো: পার্থক্যটা তোমার কানে বাজবে।",
        examples: "সেতু দুই পার মানে: তুমি এখন অতীত বলতে পারো, জার্মানের অর্ধেক আড্ডা।",
        tip: "তারিখ লেখো, এগোও।",
      },
      schau: [
        { de: "Ich bin um sechs aufgestanden.", bn: "sein + কাতাপল্ট" },
        { de: "Ich habe meiner Mutter geholfen.", bn: "Dativ + Perfekt" },
        { de: "Wir sind zum Markt gegangen.", bn: "zum + sein" },
        { de: "Das hat mir gefallen!", bn: "উপহার-গঠন, অতীতে" },
        { de: "Ich lerne seit 40 Tagen Deutsch!", bn: "seit + বর্তমান, ৪০ দিন!" },
      ],
      sagEs: [
        { q: "আমি ছয়টায় উঠেছি।", a: "Ich bin um sechs aufgestanden." },
        { q: "আমি আমার মাকে সাহায্য করেছি।", a: "Ich habe meiner Mutter geholfen." },
        { q: "আমরা বাজারে গিয়েছি।", a: "Wir sind zum Markt gegangen." },
        { q: "এটা আমার ভালো লেগেছিল।", a: "Das hat mir gefallen." },
        { q: "আমি ৪০ দিন ধরে জার্মান শিখছি!", a: "Ich lerne seit 40 Tagen Deutsch!" },
        { q: "খাবারটা ভালো লেগেছিল, ধন্যবাদ!", a: "Das Essen hat mir geschmeckt, danke!" },
      ],
      vonHerzen: { en: "Record 'Mein Gestern' (Perfekt). Then play Day 20's recording. Smile. 'Mein Gestern'", bn: "রেকর্ড করো। তারপর ২০ দিনেরটা শোনো, হাসিটা প্রাপ্য।" },
    },
    {
      n: 41,
      de: "weil I: ক্রিয়া বাড়ি ফেরে",
      bn: "সোনার দরজা খুললো",
      muster: {
        pattern: "…, weil ich müde bin. …, weil es wichtig ist.",
        why: "weil-এর পরে ক্রিয়া অংশের একদম শেষে, ঠিক বাংলার মতো: 'কারণ আমি ক্লান্ত'। তোমার জন্মগত চাবি।",
        examples: "বাংলায় ভাবো → জার্মানে বলো। এখানে অনুবাদই বন্ধু!",
        tip: "রোজ একটা weil-বাক্য, আজ থেকে আজীবন।",
      },
      schau: [
        { de: "Ich bleibe zu Hause, weil ich müde bin.", bn: "বাসায় থাকছি, কারণ ক্লান্ত।" },
        { de: "Ich lerne Deutsch, weil es wichtig ist.", bn: "জার্মান শিখি, কারণ জরুরি।" },
        { de: "Ich esse jetzt, weil ich Hunger habe.", bn: "এখন খাচ্ছি, কারণ খিদে।" },
        { de: "Sie ist glücklich, weil du hier bist.", bn: "সে খুশি, কারণ তুমি এখানে।" },
        { de: "Warum?, Weil ich es liebe!", bn: "কেন?, কারণ ভালোবাসি!" },
      ],
      sagEs: [
        { q: "আমি বাসায় থাকছি, কারণ আমি ক্লান্ত।", a: "Ich bleibe zu Hause, weil ich müde bin." },
        { q: "আমি জার্মান শিখি, কারণ এটা জরুরি।", a: "Ich lerne Deutsch, weil es wichtig ist." },
        { q: "আমি এখন খাচ্ছি, কারণ আমার খিদে পেয়েছে।", a: "Ich esse jetzt, weil ich Hunger habe." },
        { q: "সে খুশি, কারণ তুমি এখানে আছো।", a: "Sie ist glücklich, weil du hier bist." },
        { q: "আমি চা খাই, কারণ এটা ভালো লাগে।", a: "Ich trinke Tee, weil er mir schmeckt." },
        { q: "আমি পড়ছি, কারণ আমার সময় আছে।", a: "Ich lese, weil ich Zeit habe." },
      ],
      vonHerzen: { en: "Warum lernst du Deutsch? Answer with weil, your real reason.", bn: "কেন জার্মান শিখছো? weil দিয়ে আসল কারণটা লেখো ও বলো।" },
    },
    {
      n: 42,
      de: "weil II: Perfekt ও modal শেষে",
      bn: "লম্বা লেজেও ক্রিয়া শেষেই",
      muster: {
        pattern: "…, weil ich gestern gearbeitet habe. …, weil ich lernen muss.",
        why: "Perfekt-এ habe/bin একদম শেষে; modal-এ modal-টা শেষে। লেজ যত লম্বাই হোক, ক্রিয়া বাড়িতেই ঘুমায়।",
        examples: "…, weil ich früh aufstehe., কাতাপল্ট weil-ঘরে জোড়া লাগে!",
        tip: "তিন কঠিনতম গঠন, বাংলা-মন দিয়ে সহজ।",
      },
      schau: [
        { de: "…, weil ich gestern gearbeitet habe.", bn: "কারণ কাল কাজ করেছি।" },
        { de: "…, weil ich viel gelernt habe.", bn: "কারণ অনেক পড়েছি।" },
        { de: "…, weil ich lernen muss.", bn: "কারণ পড়তে হবে।" },
        { de: "…, weil ich früh aufstehe.", bn: "কারণ সকালে উঠি (জোড়া!)" },
        { de: "…, weil wir nach Dhaka gefahren sind.", bn: "কারণ ঢাকায় গিয়েছি।" },
      ],
      sagEs: [
        { q: "আমি ক্লান্ত, কারণ আমি কাল কাজ করেছি।", a: "Ich bin müde, weil ich gestern gearbeitet habe." },
        { q: "আমি খুশি, কারণ আমি অনেক শিখেছি।", a: "Ich bin glücklich, weil ich viel gelernt habe." },
        { q: "আমি পারবো না, কারণ আমাকে পড়তে হবে।", a: "Ich kann nicht, weil ich lernen muss." },
        { q: "আমি ক্লান্ত, কারণ আমি সকালে উঠি।", a: "Ich bin müde, weil ich früh aufstehe." },
        { q: "সে খুশি, কারণ সে ভালো ঘুমিয়েছে।", a: "Sie ist glücklich, weil sie gut geschlafen hat." },
        { q: "আমরা দেরি করেছি, কারণ বাস আসেনি।", a: "Wir waren spät, weil der Bus nicht gekommen ist." },
      ],
      vonHerzen: { en: "One weil + Perfekt, one weil + muss, about your real week.", bn: "তোমার সপ্তাহ: একটা weil+Perfekt, একটা weil+muss।" },
    },
    {
      n: 43,
      de: "dass, আমি মনে করি যে…",
      bn: "মতামতের দরজা",
      muster: {
        pattern: "Ich denke, dass … Ich glaube, dass … Ich finde, dass …",
        why: "dass-এর পরেও ক্রিয়া শেষে। এই এক গঠনে তুমি মতামতের জগতে ঢুকে গেলে।",
        examples: "Ich weiß, dass du das kannst!, নিজেকেও রোজ বলো।",
        tip: "denke/glaube/finde/weiß/hoffe, পাঁচ দরজা, এক তালা।",
      },
      schau: [
        { de: "Ich denke, dass Deutsch schön ist.", bn: "মনে হয় জার্মান সুন্দর।" },
        { de: "Ich glaube, dass du recht hast.", bn: "মনে হয় তুমি ঠিক।" },
        { de: "Ich finde, dass das gut ist.", bn: "আমার মতে এটা ভালো।" },
        { de: "Ich weiß, dass du das kannst!", bn: "জানি তুমি পারবে!" },
        { de: "Ich hoffe, dass es dir gefällt.", bn: "আশা করি ভালো লাগবে।" },
      ],
      sagEs: [
        { q: "আমার মনে হয় জার্মান সুন্দর।", a: "Ich denke, dass Deutsch schön ist." },
        { q: "আমার মনে হয় তুমি ঠিক।", a: "Ich glaube, dass du recht hast." },
        { q: "আমার মতে এটা ভালো।", a: "Ich finde, dass das gut ist." },
        { q: "আমি জানি যে তুমি এটা পারবে।", a: "Ich weiß, dass du das kannst." },
        { q: "আমি আশা করি এটা তোমার ভালো লাগবে।", a: "Ich hoffe, dass es dir gefällt." },
        { q: "আমি মনে করি যে এটা জরুরি।", a: "Ich denke, dass es wichtig ist." },
      ],
      vonHerzen: { en: "Three real opinions: Ich finde, dass…, about your world.", bn: "নিজের জগৎ নিয়ে তিনটা সত্যি মত, dass দিয়ে।" },
    },
    {
      n: 44,
      de: "wenn, যখন / যদি + সেতু",
      bn: "ক্রিয়া–কমা–ক্রিয়া",
      muster: {
        pattern: "Wenn ich Zeit habe, lese ich.",
        why: "wenn-অংশ আগে এলে কমার দুই পাশে দুই ক্রিয়া বসে, habe, lese। এটাই বিখ্যাত সেতু-ছবি।",
        examples: "উল্টালেও ঠিক: Ich lese, wenn ich Zeit habe.",
        tip: "দুই দিকেই বলে অভ্যাস করো।",
      },
      schau: [
        { de: "Wenn ich Zeit habe, lese ich.", bn: "সময় থাকলে পড়ি।" },
        { de: "Wenn es regnet, bleibe ich zu Hause.", bn: "বৃষ্টি হলে বাসায় থাকি।" },
        { de: "Wenn du willst, helfe ich dir.", bn: "চাইলে সাহায্য করবো।" },
        { de: "Wenn ich müde bin, schlafe ich früh.", bn: "ক্লান্ত হলে তাড়াতাড়ি ঘুমাই।" },
        { de: "Ich bin glücklich, wenn du lachst.", bn: "তুমি হাসলে আমি খুশি।" },
      ],
      sagEs: [
        { q: "সময় থাকলে আমি পড়ি।", a: "Wenn ich Zeit habe, lese ich." },
        { q: "বৃষ্টি হলে আমি বাসায় থাকি।", a: "Wenn es regnet, bleibe ich zu Hause." },
        { q: "তুমি চাইলে আমি সাহায্য করবো।", a: "Wenn du willst, helfe ich dir." },
        { q: "ক্লান্ত হলে আমি তাড়াতাড়ি ঘুমাই।", a: "Wenn ich müde bin, schlafe ich früh." },
        { q: "তুমি হাসলে আমি খুশি হই।", a: "Ich bin glücklich, wenn du lachst." },
        { q: "খিদে পেলে আমি ভাত খাই।", a: "Wenn ich Hunger habe, esse ich Reis." },
      ],
      vonHerzen: { en: "Three Wenn-truths about yourself, bridge shape, aloud.", bn: "নিজের তিনটা 'যদি/যখন'-সত্য, সেতু-গঠনে, জোরে।" },
    },
    {
      n: 45,
      de: "denn · deshalb, তিন পরিবার সম্পূর্ণ",
      bn: "শূন্য-আসন ও সিসো",
      muster: {
        pattern: "…, denn es regnet. (স্বাভাবিক) Es regnet, deshalb bleibe ich. (সিসো)",
        why: "denn = weil-এর সহজ ভাই, কিছু বদলায় না। deshalb আসন-এক নেয় → ক্রিয়া দুইয়ে।",
        examples: "এক ঘটনা, তিন স্বাদ: weil / denn / deshalb।",
        tip: "তিনটা দিয়েই একই কথা বলে দেখো, এটাই আজকের খেলা।",
      },
      schau: [
        { de: "Ich bleibe, weil es regnet.", bn: "ক্রিয়া শেষে।" },
        { de: "Ich bleibe, denn es regnet.", bn: "স্বাভাবিক, শূন্য আসন।" },
        { de: "Es regnet, deshalb bleibe ich.", bn: "সিসো, ক্রিয়া দুইয়ে।" },
        { de: "Ich bin müde, deshalb gehe ich früh schlafen.", bn: "তাই তাড়াতাড়ি ঘুমাতে যাচ্ছি।" },
        { de: "Sie lernt viel, deshalb spricht sie gut.", bn: "তাই সে ভালো বলে।" },
      ],
      sagEs: [
        { q: "আমি থাকছি, কারণ বৃষ্টি হচ্ছে। (weil)", a: "Ich bleibe, weil es regnet." },
        { q: "আমি থাকছি, কারণ বৃষ্টি হচ্ছে। (denn)", a: "Ich bleibe, denn es regnet." },
        { q: "বৃষ্টি হচ্ছে, তাই আমি থাকছি। (deshalb)", a: "Es regnet, deshalb bleibe ich." },
        { q: "আমি ক্লান্ত, তাই তাড়াতাড়ি ঘুমাতে যাচ্ছি।", a: "Ich bin müde, deshalb gehe ich früh schlafen." },
        { q: "সে অনেক পড়ে, তাই ভালো বলে।", a: "Sie lernt viel, deshalb spricht sie gut." },
        { q: "আমার খিদে পেয়েছে, তাই আমি রান্না করছি।", a: "Ich habe Hunger, deshalb koche ich." },
      ],
      vonHerzen: { en: "One fact from your day, say it all three ways.", bn: "আজকের একটা ঘটনা, weil, denn, deshalb: তিনভাবেই বলো।" },
    },
    {
      n: 46,
      de: "Komparativ I: -er als",
      bn: "তুলনার মেশিন",
      muster: {
        pattern: "größer als · kleiner als · jünger als (উমলাউট!)",
        why: "বিশেষণ + er + als। ছোট শব্দে a→ä, o→ö, u→ü। ইংরেজির 'more' এখানে নেই, সব -er।",
        examples: "❌ mehr groß → ✅ größer। ❌ als-এর জায়গায় wie নয়!",
        tip: "als = চেয়ে। এটুকুই।",
      },
      schau: [
        { de: "Dhaka ist größer als Gazipur.", bn: "ঢাকা গাজীপুরের চেয়ে বড়।" },
        { de: "Ich bin jünger als mein Bruder.", bn: "আমি ভাইয়ের চেয়ে ছোট।" },
        { de: "Deutsch ist schwerer als Englisch.", bn: "জার্মান ইংরেজির চেয়ে কঠিন।" },
        { de: "Heute ist es kälter als gestern.", bn: "আজ কালকের চেয়ে ঠান্ডা।" },
        { de: "Mein Zimmer ist kleiner als deins.", bn: "আমার ঘর তোমারটার চেয়ে ছোট।" },
      ],
      sagEs: [
        { q: "ঢাকা গাজীপুরের চেয়ে বড়।", a: "Dhaka ist größer als Gazipur." },
        { q: "আমি আমার ভাইয়ের চেয়ে ছোট।", a: "Ich bin jünger als mein Bruder." },
        { q: "জার্মান ইংরেজির চেয়ে কঠিন।", a: "Deutsch ist schwerer als Englisch." },
        { q: "আজ কালকের চেয়ে ঠান্ডা।", a: "Heute ist es kälter als gestern." },
        { q: "আমার ঘর ছোট।", a: "Mein Zimmer ist klein." },
        { q: "সে আমার চেয়ে লম্বা।", a: "Er ist größer als ich." },
      ],
      vonHerzen: { en: "Compare three real pairs from your life, with als.", bn: "নিজের জীবনের তিন জোড়া তুলনা, als দিয়ে।" },
    },
    {
      n: 47,
      de: "Komparativ II: besser · lieber · am liebsten",
      bn: "রুচির মেশিন",
      muster: {
        pattern: "gut→besser→am besten gern→lieber→am liebsten",
        why: "পছন্দের তিন ধাপ: ভালো লাগে → বেশি ভালো → সবচেয়ে। এতেই সব রুচি বলা যায়।",
        examples: "Am liebsten esse ich Mangos!, am liebsten সামনে এলে সিসো!",
        tip: "viel→mehr→am meisten, বোনাস জোড়া।",
      },
      schau: [
        { de: "Ich esse gern Reis.", bn: "ভাত খেতে ভালো লাগে।" },
        { de: "Ich esse lieber Fisch.", bn: "মাছ আরও ভালো লাগে।" },
        { de: "Am liebsten esse ich Mangos!", bn: "সবচেয়ে ভালো লাগে আম!" },
        { de: "Ich trinke lieber Tee als Kaffee.", bn: "কফির চেয়ে চা বেশি পছন্দ।" },
        { de: "Übung ist besser als Angst.", bn: "ভয়ের চেয়ে অনুশীলন ভালো।" },
      ],
      sagEs: [
        { q: "আমি ভাত খেতে পছন্দ করি।", a: "Ich esse gern Reis." },
        { q: "আমি মাছ বেশি পছন্দ করি।", a: "Ich esse lieber Fisch." },
        { q: "সবচেয়ে ভালো লাগে আম খেতে।", a: "Am liebsten esse ich Mangos." },
        { q: "আমি কফির চেয়ে চা বেশি পছন্দ করি।", a: "Ich trinke lieber Tee als Kaffee." },
        { q: "তুমি কোনটা বেশি পছন্দ করো?", a: "Was magst du lieber?" },
        { q: "আজ আমি ভালো বোধ করছি। (besser)", a: "Heute geht es mir besser." },
      ],
      vonHerzen: { en: "Your taste ladder: gern → lieber → am liebsten, food, music, days.", bn: "তোমার রুচির সিঁড়ি: খাবার, গান, দিন, তিন ধাপে।" },
    },
    {
      n: 48,
      de: "Imperativ I: du-রূপ",
      bn: "বলো! খাও! সাহায্য করো!",
      muster: {
        pattern: "du ফেলে দাও, -st ফেলে দাও: Komm! Iss! Sprich! Hilf mir!",
        why: "e→i/ie বদল থাকে (Iss! Sprich! Lies!), কিন্তু ä হয় না (Schlaf! Fahr!)। সবসময় bitte যোগ করো।",
        examples: "Hilf mir, bitte!, Dativ-হৃদস্পন্দন আদেশেও।",
        tip: "কাতাপল্টও চলে: Mach die Tür zu!",
      },
      schau: [
        { de: "Komm her!", bn: "এদিকে এসো!" },
        { de: "Sprich langsam, bitte!", bn: "আস্তে বলো, প্লিজ!" },
        { de: "Iss dein Brot!", bn: "তোমার রুটিটা খাও!" },
        { de: "Hilf mir, bitte!", bn: "আমাকে সাহায্য করো!" },
        { de: "Mach die Tür zu!", bn: "দরজাটা বন্ধ করো!" },
      ],
      sagEs: [
        { q: "এদিকে এসো!", a: "Komm her!" },
        { q: "আস্তে বলো, প্লিজ!", a: "Sprich langsam, bitte!" },
        { q: "খাও!", a: "Iss!" },
        { q: "আমাকে সাহায্য করো, প্লিজ!", a: "Hilf mir, bitte!" },
        { q: "দরজাটা বন্ধ করো!", a: "Mach die Tür zu!" },
        { q: "ভালো করে ঘুমাও!", a: "Schlaf gut!" },
      ],
      vonHerzen: { en: "Five kind commands you'd really say at home, with bitte.", bn: "বাড়িতে সত্যিই বলার মতো পাঁচটা ভদ্র আদেশ, bitte-সহ।" },
    },
    {
      n: 49,
      de: "Imperativ II: ihr · Sie + Lass uns",
      bn: "তোমরা · আপনি · চলো আমরা",
      muster: {
        pattern: "Kommt! (ihr) Kommen Sie bitte! (Sie) Lass uns gehen!",
        why: "ihr-রূপ থেকে ihr ফেলে দাও। Sie-তে ক্রিয়া+Sie। Lass uns = 'চলো আমরা', বন্ধুত্বের ব্যাকরণ।",
        examples: "Wollen wir essen?, প্রস্তাবের প্রশ্ন-রূপ।",
        tip: "রোজ একবার: Lass uns Deutsch sprechen!",
      },
      schau: [
        { de: "Kommt, wir essen!", bn: "এসো তোমরা, খাবো!" },
        { de: "Hört zu!", bn: "শোনো (তোমরা)!" },
        { de: "Kommen Sie bitte!", bn: "আসুন, প্লিজ!" },
        { de: "Sprechen Sie bitte langsam!", bn: "আস্তে বলুন, প্লিজ!" },
        { de: "Lass uns Deutsch sprechen!", bn: "চলো জার্মান বলি!" },
      ],
      sagEs: [
        { q: "এসো তোমরা, আমরা খাবো!", a: "Kommt, wir essen!" },
        { q: "শোনো তোমরা!", a: "Hört zu!" },
        { q: "আসুন, প্লিজ!", a: "Kommen Sie bitte!" },
        { q: "আস্তে বলুন, প্লিজ!", a: "Sprechen Sie bitte langsam!" },
        { q: "চলো আমরা জার্মান বলি!", a: "Lass uns Deutsch sprechen!" },
        { q: "আমরা কি খাবো?", a: "Wollen wir essen?" },
      ],
      vonHerzen: { en: "Invite someone today: Lass uns ___!, for real.", bn: "আজ কাউকে সত্যি প্রস্তাব দাও: Lass uns ___!" },
    },
    {
      n: 50,
      de: "Zeit vor Ort + man",
      bn: "সময় আগে, জায়গা পরে, আর 'লোকে'",
      muster: {
        pattern: "Ich fahre morgen nach Dhaka. Man spricht hier Bangla.",
        why: "ইংরেজির উল্টো, বাংলার মতো: আগে কখন, পরে কোথায়। man = লোকে/সবাই, er-রূপ নেয়।",
        examples: "Wie sagt man das auf Deutsch?, শেখার প্রধান হাতিয়ার।",
        tip: "এই প্রশ্নটাই তোমাকে চিরকাল এগিয়ে নেবে।",
      },
      schau: [
        { de: "Ich fahre morgen nach Dhaka.", bn: "আমি কাল ঢাকায় যাবো।" },
        { de: "Wir essen heute Abend zu Hause.", bn: "আজ রাতে বাসায় খাবো।" },
        { de: "Man spricht hier Bangla.", bn: "এখানে বাংলা বলা হয়।" },
        { de: "In Bangladesch isst man Reis mit Fisch.", bn: "বাংলাদেশে ভাত-মাছ খাওয়া হয়।" },
        { de: "Wie sagt man das auf Deutsch?", bn: "এটা জার্মানে কীভাবে বলে?" },
      ],
      sagEs: [
        { q: "আমি কাল ঢাকায় যাবো।", a: "Ich fahre morgen nach Dhaka." },
        { q: "আমরা আজ রাতে বাসায় খাবো।", a: "Wir essen heute Abend zu Hause." },
        { q: "এখানে বাংলা বলা হয়।", a: "Man spricht hier Bangla." },
        { q: "বাংলাদেশে ভাত-মাছ খাওয়া হয়।", a: "In Bangladesch isst man Reis mit Fisch." },
        { q: "এটা জার্মানে কীভাবে বলে?", a: "Wie sagt man das auf Deutsch?" },
        { q: "আজ আমি তাড়াতাড়ি ঘুমাতে যাচ্ছি।", a: "Heute gehe ich früh schlafen." },
      ],
      vonHerzen: { en: "Your country, three man-lines: what do people do here?", bn: "তোমার দেশ নিয়ে তিনটা man-বাক্য, এখানে লোকে কী করে?" },
    },
    {
      n: 51,
      de: "Wiederholung: es gibt + সব কারক",
      bn: "ঝালাই-দিন",
      muster: {
        pattern: "Es gibt / mit dem / für meinen / weil … ist, মিশ্রণ",
        why: "আজ ঝালাই, চার সপ্তাহের হাতিয়ার এক পাতায়। ধীরে, নিখুঁত, জোরে।",
        examples: "আটকালে সেই প্রশ্ন: Wo? Wohin? Wem? Wen?",
        tip: "প্রশ্নই কারক চেনায়।",
      },
      schau: [
        { de: "Es gibt einen neuen Markt in Gazipur.", bn: "গাজীপুরে নতুন বাজার আছে।" },
        { de: "Ich fahre mit meiner Familie dorthin.", bn: "পরিবারের সাথে ওখানে যাই।" },
        { de: "Ich kaufe etwas für meinen Vater.", bn: "বাবার জন্য কিছু কিনি।" },
        { de: "Es gefällt mir, weil es billig ist.", bn: "ভালো লাগে, কারণ সস্তা।" },
        { de: "Danach gehen wir nach Hause.", bn: "তারপর বাড়ি ফিরি।" },
      ],
      sagEs: [
        { q: "গাজীপুরে একটা নতুন বাজার আছে।", a: "Es gibt einen neuen Markt in Gazipur." },
        { q: "আমি আমার পরিবারের সাথে যাই।", a: "Ich fahre mit meiner Familie." },
        { q: "আমি আমার বাবার জন্য কিছু কিনি।", a: "Ich kaufe etwas für meinen Vater." },
        { q: "আমার ভালো লাগে, কারণ এটা সস্তা।", a: "Es gefällt mir, weil es billig ist." },
        { q: "তারপর আমরা বাড়ি যাই।", a: "Danach gehen wir nach Hause." },
        { q: "কোনো প্রশ্ন আছে?, না, সব পরিষ্কার!", a: "Gibt es Fragen?, Nein, alles klar!" },
      ],
      vonHerzen: { en: "Five-line market story: es gibt → mit → für → weil → danach.", bn: "বাজারের গল্প পাঁচ লাইনে, পাঁচ হাতিয়ার পরপর।" },
    },
    {
      n: 52,
      de: "Erzählen II: পুরো মালা",
      bn: "zuerst · dann · danach · später · am Ende",
      muster: {
        pattern: "পাঁচ পুঁতি + Perfekt = গল্প",
        why: "প্রতিটা পুঁতি আসন-এক → ক্রিয়া দুইয়ে। সিসো পাঁচবার দোলে, গল্প এগোয়।",
        examples: "Am Ende war ich müde, aber glücklich., গল্পের সঠিক শেষ।",
        tip: "war দিয়ে অনুভূতিতে নামো, প্রতিবার।",
      },
      schau: [
        { de: "Zuerst habe ich Tee getrunken.", bn: "প্রথমে চা।" },
        { de: "Dann bin ich zur Schule gegangen.", bn: "তারপর স্কুল।" },
        { de: "Danach habe ich meiner Mutter geholfen.", bn: "তারপর মাকে সাহায্য।" },
        { de: "Später habe ich ferngesehen.", bn: "পরে টিভি।" },
        { de: "Am Ende war ich müde, aber glücklich.", bn: "শেষে ক্লান্ত, কিন্তু খুশি।" },
      ],
      sagEs: [
        { q: "প্রথমে আমি চা খেয়েছি।", a: "Zuerst habe ich Tee getrunken." },
        { q: "তারপর আমি স্কুলে গিয়েছি।", a: "Dann bin ich zur Schule gegangen." },
        { q: "তারপর আমি আমার মাকে সাহায্য করেছি।", a: "Danach habe ich meiner Mutter geholfen." },
        { q: "পরে আমি টিভি দেখেছি।", a: "Später habe ich ferngesehen." },
        { q: "শেষে আমি ক্লান্ত ছিলাম, কিন্তু খুশি।", a: "Am Ende war ich müde, aber glücklich." },
        { q: "তারপর আমরা একসাথে খেয়েছি।", a: "Danach haben wir zusammen gegessen." },
      ],
      vonHerzen: { en: "Your yesterday on the full thread, five beads, aloud, no stopping.", bn: "তোমার গতকাল পুরো মালায়, পাঁচ পুঁতি, জোরে, না থেমে।" },
    },
    {
      n: 53,
      de: "Mein Gestern, সম্পূর্ণ",
      bn: "আজ থেকে এটাই রাতের প্রার্থনা",
      muster: {
        pattern: "ছয় লাইন: aufgestanden → getrunken → gegangen → geholfen, weil → ferngesehen → war",
        why: "ডেকের সেই ছয়-লাইনের গল্প, আজ সম্পূর্ণ তোমার। খাতার সামনের 'Mein Gestern' পাতাটা এখন থেকে রোজ রাতের সঙ্গী।",
        examples: "এক মাস রোজ বললে Perfekt মুখের ভাষা হয়ে যায়। কথা দিচ্ছি।",
        tip: "রেকর্ড করলে আরও ভালো।",
      },
      schau: [
        { de: "Gestern bin ich um sechs aufgestanden.", bn: "কাল ছয়টায় উঠেছি।" },
        { de: "Zuerst habe ich Tee getrunken.", bn: "প্রথমে চা খেয়েছি।" },
        { de: "Dann bin ich zur Schule gegangen.", bn: "তারপর স্কুলে গিয়েছি।" },
        { de: "Danach habe ich geholfen, weil Mama müde war.", bn: "মাকে সাহায্য, কারণসহ!" },
        { de: "Der Tag war lang, aber gut.", bn: "দিনটা লম্বা, কিন্তু ভালো।" },
      ],
      sagEs: [
        { q: "কাল আমি সাতটায় উঠেছি।", a: "Gestern bin ich um sieben aufgestanden." },
        { q: "প্রথমে আমি নাস্তা খেয়েছি। (gefrühstückt নয়, gegessen চলবে)", a: "Zuerst habe ich gegessen." },
        { q: "তারপর আমি পড়েছি।", a: "Dann habe ich gelernt." },
        { q: "আমি মাকে সাহায্য করেছি, কারণ তিনি ক্লান্ত ছিলেন।", a: "Ich habe meiner Mutter geholfen, weil sie müde war." },
        { q: "পরে আমরা টিভি দেখেছি।", a: "Später haben wir ferngesehen." },
        { q: "দিনটা ভালো ছিল।", a: "Der Tag war gut." },
      ],
      vonHerzen: { en: "Tonight and every night: your Gestern, six lines, out loud.", bn: "আজ রাত থেকে প্রতি রাতে: তোমার গতকাল, ছয় লাইন, জোরে।" },
    },
    {
      n: 54,
      de: "Satzbank: Pläne machen",
      bn: "দাওয়াত ও পরিকল্পনা, মহড়া",
      muster: {
        pattern: "Hast du Zeit? · Wollen wir …? · Ich kann leider nicht, weil …",
        why: "আজ মহড়ার দিন: দুই ভূমিকাতেই বলো, প্রস্তাব দাও, হ্যাঁ/না বলো।",
        examples: "না বলার সেরা গঠন: Ich kann leider nicht, weil …, ভদ্র + কারণ।",
        tip: "weil এখানেই রোজ ফল দেয়।",
      },
      schau: [
        { de: "Hast du am Samstag Zeit?", bn: "শনিবারে সময় আছে?" },
        { de: "Wollen wir ins Kino gehen?", bn: "সিনেমায় যাবো নাকি?" },
        { de: "Ja, gern! Das passt mir gut.", bn: "হ্যাঁ, খুশি হয়ে!" },
        { de: "Ich kann leider nicht, weil ich lernen muss.", bn: "পারছি না, কারণ পড়তে হবে।" },
        { de: "Vielleicht am Sonntag?", bn: "রবিবারে হলে?" },
      ],
      sagEs: [
        { q: "শনিবারে কি তোমার সময় আছে?", a: "Hast du am Samstag Zeit?" },
        { q: "আমরা কি সিনেমায় যাবো?", a: "Wollen wir ins Kino gehen?" },
        { q: "হ্যাঁ, খুশি হয়ে! আমার সুবিধা হবে।", a: "Ja, gern! Das passt mir gut." },
        { q: "পারছি না, কারণ আমাকে পড়তে হবে।", a: "Ich kann leider nicht, weil ich lernen muss." },
        { q: "রবিবারে হলে কেমন হয়?", a: "Vielleicht am Sonntag?" },
        { q: "তাহলে শনিবারে দেখা!", a: "Bis Samstag dann!" },
      ],
      vonHerzen: { en: "Role-play both sides aloud: invite → refuse kindly → new plan.", bn: "দুই চরিত্রে জোরে: দাওয়াত → ভদ্র না → নতুন প্ল্যান।" },
    },
    {
      n: 55,
      de: "Satzbank: Beim Arzt",
      bn: "শরীর খারাপ, Dativ-এর দিন",
      muster: {
        pattern: "Mir ist schlecht. · Ich habe seit zwei Tagen Fieber.",
        why: "অসুস্থতার জার্মান Dativ-ময়: mir ist…, mir geht es…। আর seit+বর্তমান ফাঁদটা এখানেই।",
        examples: "Gute Besserung!, কাউকে বলার মতো সবচেয়ে উষ্ণ বাক্য।",
        tip: "আজই কাউকে বলো।",
      },
      schau: [
        { de: "Ich bin krank.", bn: "আমি অসুস্থ।" },
        { de: "Mir ist schlecht.", bn: "আমার খারাপ লাগছে।" },
        { de: "Ich habe Kopfschmerzen.", bn: "মাথাব্যথা করছে।" },
        { de: "Ich habe seit zwei Tagen Fieber.", bn: "দুই দিন ধরে জ্বর।" },
        { de: "Gute Besserung!", bn: "দ্রুত সুস্থ হও!" },
      ],
      sagEs: [
        { q: "আমি অসুস্থ।", a: "Ich bin krank." },
        { q: "আমার খারাপ লাগছে।", a: "Mir ist schlecht." },
        { q: "আমার মাথাব্যথা করছে।", a: "Ich habe Kopfschmerzen." },
        { q: "আমার দুই দিন ধরে জ্বর।", a: "Ich habe seit zwei Tagen Fieber." },
        { q: "আমার একটা অ্যাপয়েন্টমেন্ট দরকার।", a: "Ich brauche einen Termin." },
        { q: "দ্রুত সুস্থ হও!", a: "Gute Besserung!" },
      ],
      vonHerzen: { en: "Role-play the clinic: symptoms → seit → Termin → thanks.", bn: "ক্লিনিকের দৃশ্য: লক্ষণ → কবে থেকে → অ্যাপয়েন্টমেন্ট → ধন্যবাদ।" },
    },
    {
      n: 56,
      de: "Satzbank: Einkaufen",
      bn: "কেনাকাটা, mir-এর জাদু",
      muster: {
        pattern: "Das ist mir zu teuer. · Kann ich das anprobieren?",
        why: "'আমার জন্য বেশি' = mir zu…। কাতাপল্ট anprobieren-ও আজ দোকানে।",
        examples: "Ich nehme es!, সিদ্ধান্তের বাক্য।",
        tip: "দরদাম বাংলায় পারো, আজ জার্মানে।",
      },
      schau: [
        { de: "Ich suche eine Jacke.", bn: "একটা জ্যাকেট খুঁজছি।" },
        { de: "Kann ich das anprobieren?", bn: "এটা পরে দেখতে পারি?" },
        { de: "Das ist mir zu teuer!", bn: "এটা আমার জন্য বেশি দামি!" },
        { de: "Gibt es etwas Billigeres?", bn: "সস্তা কিছু আছে?" },
        { de: "Ich nehme es!", bn: "আমি এটা নিচ্ছি!" },
      ],
      sagEs: [
        { q: "আমি একটা জ্যাকেট খুঁজছি।", a: "Ich suche eine Jacke." },
        { q: "এটা কি পরে দেখতে পারি?", a: "Kann ich das anprobieren?" },
        { q: "এটা আমার জন্য বেশি দামি।", a: "Das ist mir zu teuer." },
        { q: "আরেকটু সস্তা কিছু আছে?", a: "Gibt es etwas Billigeres?" },
        { q: "আমি এটা নিচ্ছি!", a: "Ich nehme es!" },
        { q: "এটায় তোমাকে মানিয়েছে!", a: "Das steht dir gut!" },
      ],
      vonHerzen: { en: "Shop scene, both roles: search → try → too dear → cheaper → take it.", bn: "দোকানের দৃশ্য দুই চরিত্রে, খোঁজা থেকে কেনা পর্যন্ত।" },
    },
    {
      n: 57,
      de: "Satzbank: Meinung sagen",
      bn: "মতামত, dass ও weil-এর ফসল",
      muster: {
        pattern: "Ich finde, dass … · Mir gefällt …, weil … · Ich sehe das anders.",
        why: "মত দেওয়া, একমত হওয়া, ভদ্র দ্বিমত, আজ তিনটাই।",
        examples: "Vielleicht hast du recht, aber…, সোনার দ্বিমত-গঠন।",
        tip: "তর্ক নয়, আলাপ।",
      },
      schau: [
        { de: "Ich finde, dass das gut ist.", bn: "আমার মতে এটা ভালো।" },
        { de: "Mir gefällt das, weil es einfach ist.", bn: "ভালো লাগে, কারণ সহজ।" },
        { de: "Das stimmt!", bn: "ঠিক!" },
        { de: "Ich sehe das anders.", bn: "আমি অন্যভাবে দেখি।" },
        { de: "Vielleicht hast du recht, aber…", bn: "হয়তো ঠিক, কিন্তু…" },
      ],
      sagEs: [
        { q: "আমার মতে এটা ভালো।", a: "Ich finde, dass das gut ist." },
        { q: "আমার এটা ভালো লাগে, কারণ এটা সহজ।", a: "Mir gefällt das, weil es einfach ist." },
        { q: "ঠিক বলেছো!", a: "Das stimmt!" },
        { q: "আমি এটা অন্যভাবে দেখি।", a: "Ich sehe das anders." },
        { q: "হয়তো তুমি ঠিক, কিন্তু…", a: "Vielleicht hast du recht, aber…" },
        { q: "তোমার কেমন লাগে?", a: "Wie findest du das?" },
      ],
      vonHerzen: { en: "Pick a topic (tea vs coffee?). Agree AND disagree, both aloud.", bn: "একটা বিষয় নাও, একমত ও দ্বিমত, দুটোই জোরে বলো।" },
    },
    {
      n: 58,
      de: "চার-ধাপ উত্তর",
      bn: "এক মিনিট টানা জার্মান",
      muster: {
        pattern: "Also, ich denke, dass … , weil … . Zum Beispiel … . Aber … . Deshalb … .",
        why: "যেকোনো প্রশ্নের এক-মিনিট উত্তর: অবস্থান → কারণ → উদাহরণ → অন্য দিক → উপসংহার।",
        examples: "প্রতিটা ধাপে তোমার শেখা হাতিয়ার, এটাই ফসল তোলার দিন।",
        tip: "রেকর্ড করো, শোনো, আবার।",
      },
      schau: [
        { de: "Also, ich denke, dass Tee gut ist.", bn: "অবস্থান, dass দিয়ে।" },
        { de: "…, weil er mir schmeckt.", bn: "কারণ, Dativ-উপহার!" },
        { de: "Zum Beispiel trinke ich morgens Tee.", bn: "উদাহরণ, সিসো।" },
        { de: "Aber Kaffee ist auch okay.", bn: "অন্য দিক।" },
        { de: "Deshalb sage ich: Tee ist besser!", bn: "উপসংহার, সিসো + Komparativ।" },
      ],
      sagEs: [
        { q: "আচ্ছা, আমার মনে হয় চা ভালো।", a: "Also, ich denke, dass Tee gut ist." },
        { q: "…কারণ এটা আমার ভালো লাগে।", a: "…, weil er mir schmeckt." },
        { q: "যেমন, আমি সকালে চা খাই।", a: "Zum Beispiel trinke ich morgens Tee." },
        { q: "কিন্তু কফিও মন্দ না।", a: "Aber Kaffee ist auch okay." },
        { q: "তাই আমি বলি: চা-ই ভালো!", a: "Deshalb sage ich: Tee ist besser!" },
        { q: "তুমি কী ভাবো?", a: "Was denkst du?" },
      ],
      vonHerzen: { en: "One question, four moves, one minute, recorded. Topic: Handy in der Schule?", bn: "একটা প্রশ্ন, চার ধাপ, এক মিনিট, রেকর্ডসহ। বিষয়: স্কুলে মোবাইল?" },
    },
    {
      n: 59,
      de: "Reparatur + মুক্ত কথা",
      bn: "আটকে গেলে সারাও, থেমো না",
      muster: {
        pattern: "Wie sagt man …? · Ich habe das Wort vergessen, es ist ein Ding für …",
        why: "ফ্লুয়েন্সি মানে না-আটকানো নয়, আটকে গিয়েও চালিয়ে যাওয়া। আজ সারানোর দিন।",
        examples: "Moment… ich meine…, এই ছোট শব্দগুলোই নদী সচল রাখে।",
        tip: "চুপ থাকাই একমাত্র আসল ভুল, শেষবারের মতো মনে করিয়ে দিলাম।",
      },
      schau: [
        { de: "Wie sagt man das auf Deutsch?", bn: "এটা জার্মানে কী বলে?" },
        { de: "Ich habe das Wort vergessen.", bn: "শব্দটা ভুলে গেছি।" },
        { de: "Es ist ein Ding für Wasser…", bn: "এটা পানির জন্য একটা জিনিস…" },
        { de: "Moment, ich meine…", bn: "এক সেকেন্ড, মানে…" },
        { de: "Verstehst du, was ich meine?", bn: "বুঝতে পারছো কী বলছি?" },
      ],
      sagEs: [
        { q: "এটা জার্মানে কীভাবে বলে?", a: "Wie sagt man das auf Deutsch?" },
        { q: "আমি শব্দটা ভুলে গেছি।", a: "Ich habe das Wort vergessen." },
        { q: "এটা পানির জন্য একটা জিনিস…", a: "Es ist ein Ding für Wasser." },
        { q: "এক সেকেন্ড, আমি বলতে চাইছি…", a: "Moment, ich meine…" },
        { q: "তুমি কি বুঝতে পারছো কী বলছি?", a: "Verstehst du, was ich meine?" },
        { q: "আরেকবার বলবেন, প্লিজ?", a: "Noch einmal, bitte?" },
      ],
      vonHerzen: { en: "Speak 2 minutes about anything. When stuck, repair, don't stop.", bn: "যেকোনো বিষয়ে দুই মিনিট, আটকালে সারাও, থেমো না। এটাই পরীক্ষা।" },
    },
    {
      n: 60,
      de: "FINALE: Brücken-Check 3 + তোমার গল্প",
      bn: "তৃতীয় সেতু পার, নদী এখন তোমার",
      muster: {
        pattern: "সব হাতিয়ার, এক পরিচয়: Ich heiße … Ich lerne seit … Gestern habe ich … Ich möchte …, weil …",
        why: "ষাট দিন। তিন সেতু। আজ নিজের গল্পটা সম্পূর্ণ জার্মানে বলবে, অতীত, কারণ, স্বপ্নসহ। রেকর্ড করো, আর দিন-১-এর রেকর্ডিং শোনো।",
        examples: "Hör auf zu übersetzen. Fang an zu denken., এখন তুমি এই বাক্য নিজেই পড়তে পারো।",
        tip: "দুটোই কাতাপল্ট-ক্রিয়া। ষাট দিন আগে দেয়াল ছিল, আজ তোমার কণ্ঠ।",
      },
      schau: [
        { de: "Ich heiße Rima und komme aus Bangladesch.", bn: "পরিচয়।" },
        { de: "Ich lerne seit sechzig Tagen Deutsch.", bn: "seit + বর্তমান!" },
        { de: "Gestern habe ich viel gelernt und meiner Mutter geholfen.", bn: "Perfekt + Dativ।" },
        { de: "Ich möchte gut sprechen, weil Deutsch meine Brücke ist.", bn: "স্বপ্ন + কারণ।" },
        { de: "Ich gebe nicht auf!", bn: "কাতাপল্ট, চিরকালের বাক্য।" },
      ],
      sagEs: [
        { q: "আমার নাম ___, আমি বাংলাদেশ থেকে।", a: "Ich heiße ___ und komme aus Bangladesch." },
        { q: "আমি ষাট দিন ধরে জার্মান শিখছি।", a: "Ich lerne seit sechzig Tagen Deutsch." },
        { q: "কাল আমি অনেক শিখেছি আর মাকে সাহায্য করেছি।", a: "Gestern habe ich viel gelernt und meiner Mutter geholfen." },
        { q: "আমি ভালো বলতে চাই, কারণ জার্মান আমার সেতু।", a: "Ich möchte gut sprechen, weil Deutsch meine Brücke ist." },
        { q: "এটা কঠিন ছিল, কিন্তু আমি এসেছি!", a: "Es war schwer, aber ich bin gekommen!" },
        { q: "আমি হাল ছাড়ি না!", a: "Ich gebe nicht auf!" },
      ],
      vonHerzen: { en: "Record your full self-story (6+ lines). Play Day 1. That distance? You built it.", bn: "পুরো আত্মপরিচয় রেকর্ড করো (৬+ লাইন)। দিন-১ চালাও। মাঝের দূরত্বটা? ওটা তুমি নিজে বানিয়েছো।" },
    },
  ],
};
