/* ============================================================
   arbeitsbuch/stufe-1.js: the thirty days of Stufe Eins.

   Straight out of "Das 30-Tage-Arbeitsbuch · Stufe Eins", one
   object per day, in order. See ../arbeitsbuch.data.js for what
   a day holds and why the workbook is one page and not thirty.

   Days 1-3 are pronunciation, so their sagEs prompts are German
   words to read out and their answers are the Bangla phonetics
   rather than translations. Same shape, different job.
   ============================================================ */


export default {
  /* The second line of every day's footer tick. */
  fuss: "গতকালের পাতা আগে পড়েছি",

  /* The two lines under the title. */
  lede: {
    de: "Eine Seite pro Tag. Ein Muster pro Tag. Ein ehrlicher Satz pro Tag.",
    bn: "দিনে একটা পাতা। একটা ছাঁচ। নিজের জীবনের একটা সত্যি অনুচ্ছেদ।",
  },

  /* The sound key from the front of the book. Only this book has
     one: by Stufe 2 the sounds are behind you. It is here as well
     as in Teil 2 on purpose, because this is the page a learner
     has open while stuck on a word, and sending them to another
     tab to look up "does w sound like v again?" is how a practice
     session ends. */
  schluessel: [
    ["w → ভ", "Wasser (ভাসা)"], ["v → ফ", "Vater (ফাটা)"],
    ["z → ৎস", "zehn (ৎসেন)"], ["s + স্বর → জ়", "sie (জ়ী)"],
    ["ß / ss → স", "heißen (হাইসেন)"], ["sch → শ", "Schule (শূলে)"],
    ["st- / sp- → শ্ট / শ্প", "Stadt (শ্টাট)"], ["j → ইয়", "ja (ইয়া)"],
    ["ch (i/e-র পরে) → ইশ্", "ich · nicht"], ["ch (a/o/u-র পরে) → খ", "Buch (বুখ)"],
    ["ei → আই", "nein (নাইন)"], ["ie → ঈ", "vier (ফীয়া)"],
    ["au → আউ", "Haus (হাউস)"], ["eu / äu → অয়", "Deutsch (ডয়চ)"],
    ["ä → এ্যা", "Mädchen (মেটশেন)"], ["ö → এ + ও-ঠোঁট", "schön (শ্যোন)"],
    ["ü → ই + উ-ঠোঁট", "fünf (ফ্যুন্ফ)"], ["-er (শেষে) → আ", "Mutter (মুটা)"],
  ],

  /* What this book asks the learner to collect as they go. Every
     book has one, and it is always the thing that Stufe is about:
     hats here, Partizip pairs in Stufe 2, three verb forms in
     Stufe 3. `key` prefixes the storage keys of the boxes, so it
     must never change once a book has shipped. */
  sammlung: {
    de: "Die Hut-Sammlung",
    bn: "টুপি-সংগ্রহ",
    key: "huete",
    blurb:
      "নতুন বিশেষ্য পেলেই এখানে জমান, সঠিক কলামে, টুপিসহ। সপ্তাহে একবার পুরোটা জোরে পড়ুন: টুপি আর শব্দ এক নিঃশ্বাসে।",
    columns: [
      { key: "der", head: "der", placeholder: "der Vater\nder Tisch\n…" },
      { key: "die", head: "die", placeholder: "die Mutter\ndie Tür\n…" },
      { key: "das", head: "das", placeholder: "das Kind\ndas Buch\n…" },
    ],
  },

  /* The band after the last day. Every book ends by handing the
     habits back to the learner and closing itself. */
  schluss: {
    de: "Tag 31 ist der Tag, an dem die Gewohnheiten ohne das Buch laufen.",
    bn:
      "৩১তম দিন হলো সেই দিন, যেদিন অভ্যাসগুলো খাতা ছাড়াই হাঁটে: সারাদিন নিজের সাথে জার্মানে বলা, " +
      "রোজ রাতে দিনটা জার্মানে বলা, সপ্তাহে দশটা নতুন বিশেষ্য টুপিসহ, আর না বুঝলে চুপ না থেকে " +
      "\"Wie bitte? Langsam, bitte!\"",
  },

  /* The last line on the page. */
  motto: {
    de: "Sprich schlecht. Sprich heute.",
    bn: "আজকের ভাঙা জার্মান কালকের নিখুঁত জার্মানের চেয়ে অনেক দামি।",
  },

  days: [
    {
      n: 1,
      de: "Die Laute I: w · v · z · s",
      bn: "বড় চমকগুলো, w মানে ভ!",
      muster: {
        pattern: "w = ভ v = ফ z = ৎস s + স্বর = জ়",
        why: "জার্মান কথা রাখে: যা লেখা, তাই বলা। আজ শুধু চারটা বড় চমক মুখে বসাও।",
        examples: "Wasser (ভাসা) · Vater (ফাটা) · zehn (ৎসেন) · sie (জ়ী)",
        tip: "w কখনোই ইংরেজি w নয়, সবসময় ভ। এটাই প্রথম দিনের সবচেয়ে বড় উপহার।",
      },
      schau: [
        { de: "Wasser = ভাসা", bn: "পানি" },
        { de: "wohnen = ভোনেন", bn: "থাকা" },
        { de: "Vater = ফাটা", bn: "বাবা" },
        { de: "Zeit = ৎসাইট", bn: "সময়" },
        { de: "sie = জ়ী", bn: "সে (মেয়ে) / তারা" },
      ],
      sagEs: [
        { q: "জোরে পড়ো: wir", a: "ভিয়া" },
        { q: "জোরে পড়ো: viel", a: "ফীল" },
        { q: "জোরে পড়ো: zwei", a: "ৎসভাই" },
        { q: "জোরে পড়ো: sagen", a: "জ়াগেন" },
        { q: "জোরে পড়ো: was", a: "ভাস" },
        { q: "জোরে পড়ো: Vogel", a: "ফোগেল (পাখি)" },
      ],
      vonHerzen: { en: "Write 5 German words from today. Read each aloud 5 times.", bn: "আজকের পাঁচটা শব্দ লেখো। প্রতিটা পাঁচবার জোরে পড়ো।" },
    },
    {
      n: 2,
      de: "Die Laute II: ä · ö · ü · ß · ch",
      bn: "ঠোঁটের ব্যায়াম ও দুই রকম ch",
      muster: {
        pattern: "ö = এ + ও-ঠোঁট ü = ই + উ-ঠোঁট ß = স ch = ইশ্ / খ",
        why: "ö আর ü নতুন ধ্বনি নয়, ঠোঁটের ব্যায়াম। আয়নার সামনে করো। ch: i/e-র পরে ইশ্, a/o/u-র পরে খ।",
        examples: "schön (শ্যোন) · fünf (ফ্যুন্ফ) · ich (ইশ্) · Buch (বুখ)",
        tip: "'ই' বলতে বলতে ঠোঁট গোল করো, ü নিজেই বেরিয়ে আসবে।",
      },
      schau: [
        { de: "schön = শ্যোন", bn: "সুন্দর" },
        { de: "fünf = ফ্যুন্ফ", bn: "পাঁচ" },
        { de: "müde = ম্যুদে", bn: "ক্লান্ত" },
        { de: "ich = ইশ্", bn: "আমি" },
        { de: "Buch = বুখ", bn: "বই" },
      ],
      sagEs: [
        { q: "জোরে পড়ো: nicht", a: "নিশ্ট" },
        { q: "জোরে পড়ো: acht", a: "আখট" },
        { q: "জোরে পড়ো: heißen", a: "হাইসেন" },
        { q: "জোরে পড়ো: Tür", a: "ট্যুয়া" },
        { q: "জোরে পড়ো: hören", a: "হ্যোরেন" },
        { q: "জোরে পড়ো: Mädchen", a: "মেটশেন" },
      ],
      vonHerzen: { en: "Mirror: say ö and ü ten times each. Then write 3 words with umlauts.", bn: "আয়নায় ö আর ü দশবার করে বলো। তারপর উমলাউটওয়ালা তিনটা শব্দ লেখো।" },
    },
    {
      n: 3,
      de: "Die Laute III: ei · ie · au · eu",
      bn: "জোড়া-স্বর, এবং তোমার প্রথম বাক্য",
      muster: {
        pattern: "ei = আই ie = ঈ au = আউ eu = অয়",
        why: "ছড়াটা মনে রাখো: ei = আই, ie = ঈ। আজ প্রথমবার সম্পূর্ণ জার্মান বাক্য পড়বে, নিজের নাম দিয়ে।",
        examples: "nein (নাইন) · vier (ফীয়া) · Haus (হাউস) · Deutsch (ডয়চ)",
        tip: "ভাষার নামটাই eu দিয়ে: Deutsch = ডয়চ!",
      },
      schau: [
        { de: "nein = নাইন", bn: "না" },
        { de: "vier = ফীয়া", bn: "চার" },
        { de: "Haus = হাউস", bn: "বাড়ি" },
        { de: "Deutsch = ডয়চ", bn: "জার্মান" },
        { de: "Freund = ফ্রয়ন্ট", bn: "বন্ধু" },
      ],
      sagEs: [
        { q: "জোরে পড়ো: mein", a: "মাইন (আমার)" },
        { q: "জোরে পড়ো: Liebe", a: "লীবে (ভালোবাসা)" },
        { q: "জোরে পড়ো: Frau", a: "ফ্রাউ (মহিলা)" },
        { q: "জোরে পড়ো: neun", a: "নয়ন (নয়)" },
        { q: "পড়ো: Ich heiße Rima.", a: "ইশ্ হাইসে রিমা।" },
        { q: "পড়ো: Ich wohne in Dhaka.", a: "ইশ্ ভোনে ইন ঢাকা।" },
      ],
      vonHerzen: { en: "Read Days 1–3 aloud once more. Then write: Ich heiße ______.", bn: "১–৩ দিনের পাতা আরেকবার জোরে পড়ো। তারপর লেখো: Ich heiße ___, তোমার নাম!" },
    },
    {
      n: 4,
      de: "sein I: ich bin · du bist",
      bn: "আমি হই · তুমি হও",
      muster: {
        pattern: "Ich bin ______ Du bist ______",
        why: "সেই লুকানো ক্রিয়া, ইংরেজির am/is। বাংলায় নেই, জার্মানে বলতেই হবে।",
        examples: "❌ Ich müde. ✅ Ich bin müde.",
        tip: "bin ছাড়া বাক্য অসম্পূর্ণ, ইংরেজির সেই একই পাঠ।",
      },
      schau: [
        { de: "Ich bin müde.", bn: "আমি ক্লান্ত।" },
        { de: "Ich bin glücklich.", bn: "আমি খুশি।" },
        { de: "Ich bin Schülerin.", bn: "আমি ছাত্রী।" },
        { de: "Du bist nett.", bn: "তুমি ভালো।" },
        { de: "Ich bin aus Bangladesch.", bn: "আমি বাংলাদেশের।" },
      ],
      sagEs: [
        { q: "আমি ক্লান্ত।", a: "Ich bin müde." },
        { q: "আমি খুশি।", a: "Ich bin glücklich." },
        { q: "আমি ছাত্রী।", a: "Ich bin Schülerin." },
        { q: "তুমি খুব ভালো।", a: "Du bist sehr nett." },
        { q: "আমি প্রস্তুত।", a: "Ich bin bereit." },
        { q: "আমি বাসায়।", a: "Ich bin zu Hause." },
      ],
      vonHerzen: { en: "Three true sentences with Ich bin. 'Ich bin'", bn: "দিয়ে নিজের তিনটা সত্যি বাক্য।" },
    },
    {
      n: 5,
      de: "sein II: ist · sind · seid",
      bn: "সে হয় · আমরা হই · তোমরা হও",
      muster: {
        pattern: "er/sie/es ist · wir sind · ihr seid · sie/Sie sind",
        why: "ছড়াটা গাও: বিন–বিস্ট–ইস্ট, জ়িন্ট–জ়াইট–জ়িন্ট। দশবার, গানের মতো ঢুকে যাবে।",
        examples: "ihr seid, শুধু ihr-এর জন্য। du bist, কিন্তু ihr seid।",
        tip: "seid আর sind গুলিয়ো না: তোমরা seid, তারা sind।",
      },
      schau: [
        { de: "Sie ist meine Schwester.", bn: "সে আমার বোন।" },
        { de: "Er ist müde.", bn: "সে ক্লান্ত।" },
        { de: "Wir sind bereit.", bn: "আমরা প্রস্তুত।" },
        { de: "Ihr seid laut!", bn: "তোমরা জোরে কথা বলছো!" },
        { de: "Sie sind zu Hause.", bn: "তারা বাসায়।" },
      ],
      sagEs: [
        { q: "সে আমার ভাই।", a: "Er ist mein Bruder." },
        { q: "আজ ঠান্ডা। (এটা ঠান্ডা)", a: "Es ist kalt." },
        { q: "আমরা বন্ধু।", a: "Wir sind Freunde." },
        { q: "তারা প্রস্তুত।", a: "Sie sind bereit." },
        { q: "তোমরা ক্লান্ত।", a: "Ihr seid müde." },
        { q: "আপনি শিক্ষক।", a: "Sie sind Lehrer." },
      ],
      vonHerzen: { en: "Three sentences about people in your family.", bn: "পরিবারের মানুষদের নিয়ে তিনটা বাক্য।" },
    },
    {
      n: 6,
      de: "sein III: nicht + Fragen",
      bn: "না বলা ও প্রশ্ন, কোনো 'do' নেই!",
      muster: {
        pattern: "Ich bin nicht ______ Bist du ______ ?",
        why: "না = nicht বসাও। প্রশ্ন = ক্রিয়া সামনে আনো। ইংরেজির Do/Does-এর ভারা এখানে লাগে না!",
        examples: "Du bist müde. → Bist du müde?, দুটো শব্দ জায়গা বদল, ব্যস।",
        tip: "বাংলার 'কি'-প্রশ্নের মতোই সরল।",
      },
      schau: [
        { de: "Ich bin nicht müde.", bn: "আমি ক্লান্ত নই।" },
        { de: "Er ist nicht hier.", bn: "সে এখানে নেই।" },
        { de: "Bist du glücklich?", bn: "তুমি কি খুশি?" },
        { de: "Ist das schwer?", bn: "এটা কি কঠিন?" },
        { de: "– Ja. / Nein.", bn: "উত্তর ছোট: হ্যাঁ / না।" },
      ],
      sagEs: [
        { q: "আমি একা নই।", a: "Ich bin nicht allein." },
        { q: "সে বাসায় নেই।", a: "Sie ist nicht zu Hause." },
        { q: "তুমি কি ক্লান্ত?", a: "Bist du müde?" },
        { q: "এটা কি কঠিন?", a: "Ist das schwer?" },
        { q: "তোমরা কি প্রস্তুত?", a: "Seid ihr bereit?" },
        { q: "আপনি কি শিক্ষক?", a: "Sind Sie Lehrer?" },
      ],
      vonHerzen: { en: "Three questions for a new friend, auf Deutsch.", bn: "নতুন বন্ধুকে করার মতো তিনটা প্রশ্ন, জার্মানে।" },
    },
    {
      n: 7,
      de: "haben I: habe · hast · hat",
      bn: "আমার আছে · তোমার আছে · তার আছে",
      muster: {
        pattern: "Ich habe ______ · Du hast ______ · Er/Sie hat ______",
        why: "বাংলায় জিনিস আগে (আমার বোন আছে), জার্মানে মানুষ আগে: Ich habe eine Schwester।",
        examples: "ছড়া: habe–hast–hat, haben–habt–haben।",
        tip: "sein-এর মতোই গান বানাও।",
      },
      schau: [
        { de: "Ich habe eine Schwester.", bn: "আমার একটা বোন আছে।" },
        { de: "Ich habe Zeit.", bn: "আমার সময় আছে।" },
        { de: "Du hast ein Buch.", bn: "তোমার একটা বই আছে।" },
        { de: "Er hat ein Fahrrad.", bn: "তার একটা সাইকেল আছে।" },
        { de: "Sie hat zwei Kinder.", bn: "তার দুটো সন্তান আছে।" },
      ],
      sagEs: [
        { q: "আমার দুই ভাই আছে।", a: "Ich habe zwei Brüder." },
        { q: "তোমার সময় আছে।", a: "Du hast Zeit." },
        { q: "তার একটা বই আছে।", a: "Sie hat ein Buch." },
        { q: "আমার একটা প্রশ্ন আছে।", a: "Ich habe eine Frage." },
        { q: "তার একটা বোন আছে।", a: "Er hat eine Schwester." },
        { q: "আমার একটা বুদ্ধি আছে।", a: "Ich habe eine Idee." },
      ],
      vonHerzen: { en: "Three things you have.", bn: "তোমার যা যা আছে, তিনটা বাক্য।" },
    },
    {
      n: 8,
      de: "haben II: Hunger · Durst · Angst",
      bn: "খিদে-তেষ্টা-ভয়, জার্মানে এগুলো 'থাকে'",
      muster: {
        pattern: "Ich habe Hunger. · Wir haben … · Ihr habt … · Sie haben …",
        why: "ইংরেজির 'I am hungry' ভুলে যাও, জার্মানে খিদে তোমার 'আছে': Ich habe Hunger!",
        examples: "Hunger (খিদে) · Durst (তেষ্টা) · Angst (ভয়), সব haben দিয়ে।",
        tip: "এটা জার্মান ভাবনার ধরন, মেনে নাও, অনুবাদ কোরো না।",
      },
      schau: [
        { de: "Ich habe Hunger!", bn: "আমার খিদে পেয়েছে!" },
        { de: "Ich habe Durst.", bn: "আমার তেষ্টা পেয়েছে।" },
        { de: "Wir haben Zeit.", bn: "আমাদের সময় আছে।" },
        { de: "Ihr habt ein schönes Haus.", bn: "তোমাদের বাড়িটা সুন্দর।" },
        { de: "Er hat Angst.", bn: "সে ভয় পাচ্ছে।" },
      ],
      sagEs: [
        { q: "আমার খিদে পেয়েছে।", a: "Ich habe Hunger." },
        { q: "আমার তেষ্টা পেয়েছে।", a: "Ich habe Durst." },
        { q: "আমাদের সময় আছে।", a: "Wir haben Zeit." },
        { q: "তোমাদের একটা সুন্দর বাড়ি আছে।", a: "Ihr habt ein schönes Haus." },
        { q: "তাদের দুটো সন্তান আছে।", a: "Sie haben zwei Kinder." },
        { q: "সে ভয় পাচ্ছে।", a: "Sie hat Angst." },
      ],
      vonHerzen: { en: "What do your family members have? Three sentences.", bn: "পরিবারের কার কী আছে, তিনটা বাক্য।" },
    },
    {
      n: 9,
      de: "kein · keine",
      bn: "নেই, ein-এর সামনে k",
      muster: {
        pattern: "ein → kein eine → keine বহুবচন → keine",
        why: "'নেই' বলার জার্মান অস্ত্র: ein-এর মাথায় k বসাও। kein Geld, keine Zeit।",
        examples: "❌ Ich habe nicht Geld. ✅ Ich habe kein Geld.",
        tip: "বিশেষ্যকে মারে kein, nicht নয়। (nicht-এর পালা ১৮ দিনে।)",
      },
      schau: [
        { de: "Ich habe kein Geld.", bn: "আমার টাকা নেই।" },
        { de: "Ich habe keine Zeit.", bn: "আমার সময় নেই।" },
        { de: "Er hat kein Fahrrad.", bn: "তার সাইকেল নেই।" },
        { de: "Wir haben kein Wasser.", bn: "আমাদের পানি নেই।" },
        { de: "Ich habe keine Angst!", bn: "আমার ভয় নেই!" },
      ],
      sagEs: [
        { q: "আমার টাকা নেই।", a: "Ich habe kein Geld." },
        { q: "আমার সময় নেই।", a: "Ich habe keine Zeit." },
        { q: "তার ভাইবোন নেই।", a: "Sie hat keine Geschwister." },
        { q: "আমাদের পানি নেই।", a: "Wir haben kein Wasser." },
        { q: "আমার কোনো প্রশ্ন নেই।", a: "Ich habe keine Frage." },
        { q: "আমার ভয় নেই।", a: "Ich habe keine Angst." },
      ],
      vonHerzen: { en: "Three things you don't have, and want one day.", bn: "যা নেই কিন্তু একদিন চাও, তিনটা।" },
    },
    {
      n: 10,
      de: "Verben I: ich -e · du -st",
      bn: "মেশিন চালু: আমি-তে e, তুমি-তে st",
      muster: {
        pattern: "ich lerne · du lernst ich wohne · du wohnst",
        why: "বাংলাও এই খেলা খেলে: খাই-খাও-খায়। জার্মান মেশিন: ich-এ -e, du-তে -st।",
        examples: "lernen → ich lerne, du lernst · trinken → ich trinke, du trinkst",
        tip: "অভিধানের রূপ থেকে -n/-en ফেলে পোশাক পরাও।",
      },
      schau: [
        { de: "Ich lerne Deutsch.", bn: "আমি জার্মান শিখি।" },
        { de: "Ich wohne in Dhaka.", bn: "আমি ঢাকায় থাকি।" },
        { de: "Ich trinke Tee.", bn: "আমি চা খাই।" },
        { de: "Du lernst schnell!", bn: "তুমি দ্রুত শেখো!" },
        { de: "Du spielst Cricket.", bn: "তুমি ক্রিকেট খেলো।" },
      ],
      sagEs: [
        { q: "আমি জার্মান শিখি।", a: "Ich lerne Deutsch." },
        { q: "আমি চা খাই।", a: "Ich trinke Tee." },
        { q: "আমি ঢাকায় থাকি।", a: "Ich wohne in Dhaka." },
        { q: "তুমি দ্রুত শেখো।", a: "Du lernst schnell." },
        { q: "তুমি ক্রিকেট খেলো।", a: "Du spielst Cricket." },
        { q: "আমি ভাত রান্না করি।", a: "Ich koche Reis." },
      ],
      vonHerzen: { en: "Three things you do every day, ich-form.", bn: "রোজ যা করো, ich দিয়ে তিনটা।" },
    },
    {
      n: 11,
      de: "Verben II: er / sie / es -t",
      bn: "সে-তে t",
      muster: {
        pattern: "er lernt · sie kocht · es spielt",
        why: "একজন অন্য কেউ করলে -t। ইংরেজির সেই ছোট্ট -s মনে আছে? এটা তার জার্মান ভাই।",
        examples: "kochen → sie kocht · spielen → das Kind spielt",
        tip: "-t ভুললে মানুষ তবু বুঝবে, কিন্তু অভ্যাস করো।",
      },
      schau: [
        { de: "Er trinkt Tee.", bn: "সে চা খায়।" },
        { de: "Sie lernt Deutsch.", bn: "সে জার্মান শেখে।" },
        { de: "Mama kocht Reis.", bn: "মা ভাত রান্না করেন।" },
        { de: "Das Kind spielt.", bn: "বাচ্চাটা খেলে।" },
        { de: "Sie hört Musik.", bn: "সে গান শোনে।" },
      ],
      sagEs: [
        { q: "সে চা খায়।", a: "Er trinkt Tee." },
        { q: "মা রান্না করেন।", a: "Mama kocht." },
        { q: "সে জার্মান শেখে।", a: "Sie lernt Deutsch." },
        { q: "বাচ্চাটা খেলে।", a: "Das Kind spielt." },
        { q: "সে ঢাকায় থাকে।", a: "Er wohnt in Dhaka." },
        { q: "সে গান শোনে।", a: "Sie hört Musik." },
      ],
      vonHerzen: { en: "Three sentences about your mother's or a friend's day.", bn: "মা বা বন্ধুর দিন নিয়ে তিনটা বাক্য।" },
    },
    {
      n: 12,
      de: "Verben III: wir · ihr · sie",
      bn: "পুরো মেশিন: -en · -t · -en",
      muster: {
        pattern: "wir lernen · ihr lernt · sie/Sie lernen",
        why: "wir আর sie/Sie সবসময় অভিধানের পুরো রূপ। ihr-এ -t। মেশিন সম্পূর্ণ!",
        examples: "-e, -st, -t, -en, -t, -en, এই ছয় পোশাকে জার্মানের ৯০% ক্রিয়া চলে।",
        tip: "তিনটা ক্রিয়া নিয়ে ছয় ঘরের ছক নিজে বানাও।",
      },
      schau: [
        { de: "Wir lernen zusammen.", bn: "আমরা একসাথে শিখি।" },
        { de: "Wir essen Reis.", bn: "আমরা ভাত খাই।" },
        { de: "Ihr spielt Cricket.", bn: "তোমরা ক্রিকেট খেলো।" },
        { de: "Sie wohnen in Gazipur.", bn: "তারা গাজীপুরে থাকে।" },
        { de: "Sie lernen Deutsch.", bn: "তারা জার্মান শেখে।" },
      ],
      sagEs: [
        { q: "আমরা একসাথে শিখি।", a: "Wir lernen zusammen." },
        { q: "আমরা ভাত খাই।", a: "Wir essen Reis." },
        { q: "তোমরা ক্রিকেট খেলো।", a: "Ihr spielt Cricket." },
        { q: "তারা ঢাকায় থাকে।", a: "Sie wohnen in Dhaka." },
        { q: "আমরা গান শুনি।", a: "Wir hören Musik." },
        { q: "তোমরা দ্রুত শেখো।", a: "Ihr lernt schnell." },
      ],
      vonHerzen: { en: "Three wir-sentences about your family.", bn: "পরিবার নিয়ে 'wir' দিয়ে তিনটা বাক্য।" },
    },
    {
      n: 13,
      de: "রূপবদল I: e → i / ie",
      bn: "sprechen → spricht · sehen → sieht",
      muster: {
        pattern: "ich spreche → du sprichst, er spricht ich sehe → du siehst, er sieht",
        why: "শুধু du আর er/sie/es-এর ঘরে চেহারা বদলায়। ich, wir, ihr, sie, সব স্বাভাবিক।",
        examples: "essen → isst · lesen → liest · geben → gibt · helfen → hilft",
        tip: "নিয়ম নয়, জোড়াটা গাও: ich spreche, du sprichst, দশবার।",
      },
      schau: [
        { de: "Ich spreche Bangla.", bn: "আমি বাংলা বলি।" },
        { de: "Er spricht Deutsch.", bn: "সে জার্মান বলে।" },
        { de: "Du isst Fisch.", bn: "তুমি মাছ খাও।" },
        { de: "Sie liest viel.", bn: "সে অনেক পড়ে।" },
        { de: "Er sieht gut.", bn: "সে ভালো দেখে।" },
      ],
      sagEs: [
        { q: "সে বাংলা বলে।", a: "Er spricht Bangla." },
        { q: "তুমি মাছ খাও।", a: "Du isst Fisch." },
        { q: "সে অনেক পড়ে।", a: "Sie liest viel." },
        { q: "সে ভালো দেখে।", a: "Er sieht gut." },
        { q: "তুমি জার্মান বলো।", a: "Du sprichst Deutsch." },
        { q: "বাচ্চাটা খায়।", a: "Das Kind isst." },
      ],
      vonHerzen: { en: "Sing the pairs aloud, then 3 sentences with sprechen / essen / lesen.", bn: "জোড়াগুলো গেয়ে নাও, তারপর sprechen/essen/lesen দিয়ে তিনটা বাক্য।" },
    },
    {
      n: 14,
      de: "রূপবদল II: a → ä + wissen",
      bn: "schlafen → schläft · আর 'জানা'র বিশেষ ক্রিয়া",
      muster: {
        pattern: "ich schlafe → du schläfst, er schläft wissen: ich weiß, du weißt, er weiß",
        why: "a → ä শুধু du/er-এ। আর wissen একমাত্র ব্যতিক্রম, ich-ও বদলায়: ich weiß।",
        examples: "fahren → du fährst, sie fährt (গাড়ি/বাসে যাওয়া)",
        tip: "'Ich weiß nicht' (জানি না), রোজকার সবচেয়ে দরকারি বাক্যগুলোর একটা।",
      },
      schau: [
        { de: "Er schläft viel.", bn: "সে অনেক ঘুমায়।" },
        { de: "Du schläfst zu viel!", bn: "তুমি বেশি ঘুমাও!" },
        { de: "Sie fährt nach Dhaka.", bn: "সে ঢাকায় যাচ্ছে (গাড়িতে)।" },
        { de: "Ich weiß.", bn: "আমি জানি।" },
        { de: "Ich weiß nicht.", bn: "আমি জানি না।" },
      ],
      sagEs: [
        { q: "সে অনেক ঘুমায়।", a: "Sie schläft viel." },
        { q: "তুমি বেশি ঘুমাও।", a: "Du schläfst zu viel." },
        { q: "সে ঢাকায় যাচ্ছে (গাড়িতে)।", a: "Er fährt nach Dhaka." },
        { q: "আমি জানি।", a: "Ich weiß." },
        { q: "তুমি জানো।", a: "Du weißt." },
        { q: "সে জানে না।", a: "Sie weiß nicht." },
      ],
      vonHerzen: { en: "One true sentence each with schlafen, fahren, wissen. schlafen, fahren, wissen,", bn: "প্রতিটা দিয়ে নিজের একটা সত্যি বাক্য।" },
    },
    {
      n: 15,
      de: "der · die · das I: মানুষ ও ঘর",
      bn: "টুপি পরানো শুরু, তিন রঙে",
      muster: {
        pattern: "der (নীল) · die (লাল) · das (সবুজ)",
        why: "প্রতিটা শব্দ টুপিসহ, এক নিঃশ্বাসে: derVater, dieMutter, dasKind। রঙিন কলম থাকলে তিন রঙে লেখো।",
        examples: "das Mädchen, 'মেয়ে' পর্যন্ত das! যুক্তি খুঁজো না, রঙ মনে রাখো।",
        tip: "টুপি ভুল হলেও সবাই বুঝবে, থেমো না, শুধু আবার বলো।",
      },
      schau: [
        { de: "der Vater · der Bruder", bn: "বাবা · ভাই (নীল)" },
        { de: "die Mutter · die Schwester", bn: "মা · বোন (লাল)" },
        { de: "das Kind · das Mädchen", bn: "শিশু · মেয়ে (সবুজ!)" },
        { de: "das Haus · die Tür", bn: "বাড়ি · দরজা" },
        { de: "der Mann · die Frau", bn: "লোক · মহিলা" },
      ],
      sagEs: [
        { q: "বাবা", a: "der Vater" },
        { q: "মা", a: "die Mutter" },
        { q: "ভাই", a: "der Bruder" },
        { q: "বোন", a: "die Schwester" },
        { q: "শিশু", a: "das Kind" },
        { q: "বাড়ি", a: "das Haus" },
      ],
      vonHerzen: { en: "Six nouns from YOUR home, with hats. Colours if you can.", bn: "নিজের বাড়ির ছয়টা জিনিস, টুপিসহ। পারলে তিন রঙে।" },
    },
    {
      n: 16,
      de: "der · die · das II: জিনিসপত্র",
      bn: "আলমারি বড় হচ্ছে, আর বহুবচনের সুখবর",
      muster: {
        pattern: "সব বহুবচন = die: das Buch → die Bücher",
        why: "যত শব্দ, তত টুপি, কিন্তু বহুবচনে সবাই die পরে। একটাই নিয়ম, শূন্য ব্যতিক্রম।",
        examples: "der Tisch · die Schule · das Wasser · die Zeit · der Tee",
        tip: "প্রতিদিন ১০টা শব্দ টুপিসহ, খাতার শেষের 'Hut-Sammlung' পাতায় জমাও।",
      },
      schau: [
        { de: "der Tisch · der Tee", bn: "টেবিল · চা" },
        { de: "die Tür · die Schule", bn: "দরজা · স্কুল" },
        { de: "das Buch · das Wasser", bn: "বই · পানি" },
        { de: "die Bücher (বহুবচন!)", bn: "বইগুলো, die!" },
        { de: "die Zeit · das Brot", bn: "সময় · রুটি" },
      ],
      sagEs: [
        { q: "টেবিল", a: "der Tisch" },
        { q: "দরজা", a: "die Tür" },
        { q: "বই", a: "das Buch" },
        { q: "পানি", a: "das Wasser" },
        { q: "স্কুল", a: "die Schule" },
        { q: "মেয়ে", a: "das Mädchen (!)" },
      ],
      vonHerzen: { en: "Six more nouns with hats. Say each as ONE word: derTisch.", bn: "আরও ছয়টা শব্দ টুপিসহ। প্রতিটা এক নিঃশ্বাসে বলো: derTisch।" },
    },
    {
      n: 17,
      de: "ein · eine + kein মিল",
      bn: "একটা, আর তার 'নেই' জোড়া",
      muster: {
        pattern: "der/das → ein → kein die → eine → keine",
        why: "নীল ও সবুজ দল: ein/kein। লাল দল: eine/keine। জোড়ায় জোড়ায় মেলে।",
        examples: "Das ist ein Buch. → Ich habe kein Buch.",
        tip: "ein চিনলে kein ফ্রি, একই পোশাক, সামনে শুধু k।",
      },
      schau: [
        { de: "Das ist ein Buch.", bn: "এটা একটা বই।" },
        { de: "Das ist eine Tür.", bn: "এটা একটা দরজা।" },
        { de: "Das ist ein Tisch.", bn: "এটা একটা টেবিল।" },
        { de: "Ich habe kein Buch.", bn: "আমার বই নেই।" },
        { de: "Ich habe keine Zeit.", bn: "আমার সময় নেই।" },
      ],
      sagEs: [
        { q: "এটা একটা বই।", a: "Das ist ein Buch." },
        { q: "এটা একটা দরজা।", a: "Das ist eine Tür." },
        { q: "এটা একটা টেবিল।", a: "Das ist ein Tisch." },
        { q: "ওটা একটা স্কুল।", a: "Das ist eine Schule." },
        { q: "আমার বই নেই।", a: "Ich habe kein Buch." },
        { q: "আমার সময় নেই।", a: "Ich habe keine Zeit." },
      ],
      vonHerzen: { en: "Point at 5 things around you: Das ist ein/eine ___.", bn: "চারপাশের পাঁচটা জিনিস দেখিয়ে বলো: Das ist ein/eine ___।" },
    },
    {
      n: 18,
      de: "nicht, কোথায় বসে",
      bn: "nicht-এর আসন",
      muster: {
        pattern: "ক্রিয়ার পরে: Ich verstehe nicht. বিশেষণের আগে: Ich bin nicht müde.",
        why: "nicht ক্রিয়াকে বা বিশেষণকে মারে। ক্রিয়া কিন্তু ২ নম্বর আসনে অটল, nicht তার পরে।",
        examples: "❌ Ich nicht verstehe. ✅ Ich verstehe nicht.",
        tip: "nicht কখনো ক্রিয়ার আগে বসে না।",
      },
      schau: [
        { de: "Ich verstehe nicht.", bn: "আমি বুঝি না।" },
        { de: "Ich bin nicht müde.", bn: "আমি ক্লান্ত নই।" },
        { de: "Er wohnt nicht hier.", bn: "সে এখানে থাকে না।" },
        { de: "Das ist nicht schwer.", bn: "এটা কঠিন নয়।" },
        { de: "Sie kommt nicht.", bn: "সে আসছে না।" },
      ],
      sagEs: [
        { q: "আমি বুঝি না।", a: "Ich verstehe nicht." },
        { q: "আমি ক্লান্ত নই।", a: "Ich bin nicht müde." },
        { q: "সে এখানে থাকে না।", a: "Er wohnt nicht hier." },
        { q: "এটা কঠিন নয়।", a: "Das ist nicht schwer." },
        { q: "আমি খেলি না।", a: "Ich spiele nicht." },
        { q: "সে আসছে না।", a: "Sie kommt nicht." },
      ],
      vonHerzen: { en: "Three things you do NOT do.", bn: "যা করো না, তিনটা।" },
    },
    {
      n: 19,
      de: "nicht বনাম kein",
      bn: "কোন অস্ত্র কখন",
      muster: {
        pattern: "বিশেষ্য (ein-ওয়ালা/খালি) → kein বাকি সব → nicht",
        why: "দ্রুত পরীক্ষা: ক্রিয়ার পরে কি একটা 'জিনিস' আছে? জিনিস হলে kein, নাহলে nicht।",
        examples: "kein Geld (জিনিস) · verstehe nicht (কাজ) · nicht müde (অবস্থা)",
        tip: "এই বাছাইটাই ১৯ দিনের পুরো কাজ, বাকি সব চেনা।",
      },
      schau: [
        { de: "Ich habe kein Geld.", bn: "টাকা নেই, জিনিস → kein।" },
        { de: "Ich verstehe nicht.", bn: "বুঝি না, কাজ → nicht।" },
        { de: "Das ist kein Problem.", bn: "সমস্যা না, জিনিস → kein।" },
        { de: "Ich bin nicht müde.", bn: "ক্লান্ত নই, অবস্থা → nicht।" },
        { de: "Wir haben keine Zeit.", bn: "সময় নেই, জিনিস → keine।" },
      ],
      sagEs: [
        { q: "আমার টাকা নেই।", a: "Ich habe kein Geld." },
        { q: "আমি বুঝি না।", a: "Ich verstehe nicht." },
        { q: "এটা কোনো সমস্যা না।", a: "Das ist kein Problem." },
        { q: "আমি ক্লান্ত নই।", a: "Ich bin nicht müde." },
        { q: "আমাদের সময় নেই।", a: "Wir haben keine Zeit." },
        { q: "সে এখানে নেই।", a: "Er ist nicht hier." },
      ],
      vonHerzen: { en: "Two kein-sentences + two nicht-sentences. True ones.", bn: "দুটো kein, দুটো nicht, সব নিজের সত্যি।" },
    },
    {
      n: 20,
      de: "ভদ্রভাবে 'না'",
      bn: "না বলাও একটা শিল্প",
      muster: {
        pattern: "Nein, danke. · Leider … · Ich kann heute nicht.",
        why: "'না' রুক্ষ শোনায়, danke আর leider (দুঃখিত/দুর্ভাগ্যবশত) সেটাকে নরম করে।",
        examples: "Leider habe ich keine Zeit., leider সামনে এলে ক্রিয়া ২ নম্বরে!",
        tip: "আসন-দুই আইন সব জায়গায়, এমনকি 'না'-তেও।",
      },
      schau: [
        { de: "Nein, danke.", bn: "না, ধন্যবাদ।" },
        { de: "Ich weiß nicht.", bn: "আমি জানি না।" },
        { de: "Leider habe ich keine Zeit.", bn: "দুঃখিত, আমার সময় নেই।" },
        { de: "Kein Problem!", bn: "কোনো সমস্যা নেই!" },
        { de: "Ich kann heute nicht.", bn: "আমি আজ পারবো না।" },
      ],
      sagEs: [
        { q: "না, ধন্যবাদ।", a: "Nein, danke." },
        { q: "আমি জানি না।", a: "Ich weiß nicht." },
        { q: "দুঃখিত, আমার সময় নেই।", a: "Leider habe ich keine Zeit." },
        { q: "এটা সমস্যা না।", a: "Kein Problem." },
        { q: "আমি চাই না।", a: "Ich möchte nicht." },
        { q: "আমি আজ পারবো না।", a: "Ich kann heute nicht." },
      ],
      vonHerzen: { en: "Politely refuse three imaginary invitations.", bn: "তিনটা কাল্পনিক দাওয়াত ভদ্রভাবে ফিরিয়ে দাও, জার্মানে।" },
    },
    {
      n: 21,
      de: "হ্যাঁ/না প্রশ্ন, ক্রিয়া সামনে",
      bn: "লাফ দাও, 'do' ছাড়াই",
      muster: {
        pattern: "Du kommst. → Kommst du? Sie hat Zeit. → Hat sie Zeit?",
        why: "বলা থেকে প্রশ্ন: প্রথম দুটো শব্দ জায়গা বদল করে। ইংরেজির Do/Does-এর কষ্ট এখানে নেই।",
        examples: "উত্তর: Ja. / Nein. / Ja, gern! / Nein, leider.",
        tip: "ছোট উত্তরই স্বাভাবিক।",
      },
      schau: [
        { de: "Kommst du morgen?", bn: "তুমি কি কাল আসছো?" },
        { de: "Hast du Zeit?", bn: "তোমার কি সময় আছে?" },
        { de: "Bist du müde?", bn: "তুমি কি ক্লান্ত?" },
        { de: "Sprichst du Deutsch?", bn: "তুমি কি জার্মান বলো?" },
        { de: "Haben Sie eine Frage?", bn: "আপনার কি প্রশ্ন আছে?" },
      ],
      sagEs: [
        { q: "তুমি কি আসছো?", a: "Kommst du?" },
        { q: "তোমার কি সময় আছে?", a: "Hast du Zeit?" },
        { q: "তুমি কি ক্লান্ত?", a: "Bist du müde?" },
        { q: "তুমি কি জার্মান বলো?", a: "Sprichst du Deutsch?" },
        { q: "আপনার কি প্রশ্ন আছে?", a: "Haben Sie eine Frage?" },
        { q: "সে কি বাসায়?", a: "Ist sie zu Hause?" },
      ],
      vonHerzen: { en: "Ask the mirror 3 questions. Answer: Ja / Nein.", bn: "আয়নাকে তিনটা প্রশ্ন করো। উত্তর দাও: Ja / Nein।" },
    },
    {
      n: 22,
      de: "W-Fragen I: wer · was · wo · woher",
      bn: "কে · কী · কোথায় · কোথা থেকে",
      muster: {
        pattern: "W-শব্দ + ক্রিয়া + কে ?",
        why: "গঠন সবসময় এক: Wo | wohnst | du? প্রশ্নের মেশিনে ক্রিয়া দুই নম্বরে, চেনা আইন।",
        examples: "Wer? কে · Was? কী · Wo? কোথায় · Woher? কোথা থেকে",
        tip: "সব W দিয়ে শুরু, তাই নাম W-Fragen।",
      },
      schau: [
        { de: "Wer ist das?", bn: "ওটা কে?" },
        { de: "Was ist das?", bn: "এটা কী?" },
        { de: "Was machst du?", bn: "তুমি কী করছো?" },
        { de: "Wo wohnst du?", bn: "তুমি কোথায় থাকো?" },
        { de: "Woher kommst du?", bn: "তুমি কোথা থেকে এসেছো?" },
      ],
      sagEs: [
        { q: "ওটা কে?", a: "Wer ist das?" },
        { q: "এটা কী?", a: "Was ist das?" },
        { q: "তুমি কী করছো?", a: "Was machst du?" },
        { q: "তুমি কোথায় থাকো?", a: "Wo wohnst du?" },
        { q: "তুমি কোথা থেকে এসেছো?", a: "Woher kommst du?" },
        { q: "সে কোথায়?", a: "Wo ist er?" },
      ],
      vonHerzen: { en: "Interview a family member with 3 W-questions.", bn: "পরিবারের কাউকে তিনটা W-প্রশ্ন করো, জার্মানে জিজ্ঞেস করে বাংলায় উত্তর নাও।" },
    },
    {
      n: 23,
      de: "W-Fragen II: wann · warum · wie · wie viel",
      bn: "কখন · কেন · কেমন · কত",
      muster: {
        pattern: "Wie heißt du? · Wie geht's? · Wie viel kostet das?",
        why: "wie একাই তিনটা কাজ করে: নাম, কুশল, দাম। এই তিন বাক্য মুখস্থ চলবে, এগুলোই দরজা খোলে।",
        examples: "Wann? কখন · Warum? কেন · Wie? কেমন/কীভাবে · Wie viel? কত",
        tip: "Warum-এর উত্তর পরে শিখবে, আগে প্রশ্নটা করতে শেখো।",
      },
      schau: [
        { de: "Wann kommst du?", bn: "তুমি কখন আসবে?" },
        { de: "Warum lernst du Deutsch?", bn: "তুমি কেন জার্মান শিখছো?" },
        { de: "Wie heißt du?", bn: "তোমার নাম কী?" },
        { de: "Wie geht's?, Gut, danke!", bn: "কেমন আছো?, ভালো!" },
        { de: "Wie viel kostet das?", bn: "এটার দাম কত?" },
      ],
      sagEs: [
        { q: "তুমি কখন আসবে?", a: "Wann kommst du?" },
        { q: "তোমার নাম কী?", a: "Wie heißt du?" },
        { q: "কেমন আছো?", a: "Wie geht's?" },
        { q: "এটার দাম কত?", a: "Wie viel kostet das?" },
        { q: "তুমি কেন জার্মান শিখছো?", a: "Warum lernst du Deutsch?" },
        { q: "সে কখন খায়?", a: "Wann isst sie?" },
      ],
      vonHerzen: { en: "Write YOUR answers to all five model questions.", bn: "পাঁচটা মডেল প্রশ্নের নিজের উত্তর লেখো।" },
    },
    {
      n: 24,
      de: "möchte + বন্ধনী",
      bn: "চাই, আর কাজ শেষে",
      muster: {
        pattern: "Ich möchte … মাঝে যা খুশি … VERB (শেষে!)",
        why: "জার্মানের স্বাক্ষর: সাহায্যকারী ২ নম্বরে, আসল কাজ একদম শেষে। খিলানটা অনুভব করো।",
        examples: "❌ Ich möchte lernen Deutsch. ✅ Ich möchte Deutsch lernen.",
        tip: "শেষ শব্দটা দরজা বন্ধ করে, তবেই জার্মান কানে 'সম্পূর্ণ' লাগে।",
      },
      schau: [
        { de: "Ich möchte Deutsch lernen.", bn: "আমি জার্মান শিখতে চাই।" },
        { de: "Ich möchte schlafen.", bn: "আমি ঘুমাতে চাই।" },
        { de: "Ich möchte Tee trinken.", bn: "আমি চা খেতে চাই।" },
        { de: "Möchtest du essen?", bn: "তুমি কি খেতে চাও?" },
        { de: "Wir möchten nach Hause gehen.", bn: "আমরা বাড়ি যেতে চাই।" },
      ],
      sagEs: [
        { q: "আমি জার্মান শিখতে চাই।", a: "Ich möchte Deutsch lernen." },
        { q: "আমি ঘুমাতে চাই।", a: "Ich möchte schlafen." },
        { q: "আমি চা খেতে চাই।", a: "Ich möchte Tee trinken." },
        { q: "তুমি কি খেতে চাও?", a: "Möchtest du essen?" },
        { q: "আমরা বাড়ি যেতে চাই।", a: "Wir möchten nach Hause gehen." },
        { q: "সে পড়তে চায়।", a: "Sie möchte lesen." },
      ],
      vonHerzen: { en: "Three real wishes, verb at the END.", bn: "নিজের তিনটা সত্যি ইচ্ছা, ক্রিয়া শেষে!" },
    },
    {
      n: 25,
      de: "kann, পারা",
      bn: "পারি / পারি না",
      muster: {
        pattern: "Ich kann … VERB. Kannst du … VERB?",
        why: "একই খিলান, নতুন সাহায্যকারী। মজা: ich আর er/sie/es-এ kann একই, কোনো -t নেই!",
        examples: "kann · kannst · kann · können · könnt · können",
        tip: "পরের ক্রিয়া কখনো বদলায় না, অভিধান-রূপ, শেষে।",
      },
      schau: [
        { de: "Ich kann kochen.", bn: "আমি রান্না করতে পারি।" },
        { de: "Ich kann nicht schwimmen.", bn: "আমি সাঁতার পারি না।" },
        { de: "Kannst du helfen?", bn: "তুমি কি সাহায্য করতে পারবে?" },
        { de: "Sie kann gut singen.", bn: "সে ভালো গাইতে পারে।" },
        { de: "Wir können morgen kommen.", bn: "আমরা কাল আসতে পারবো।" },
      ],
      sagEs: [
        { q: "আমি রান্না করতে পারি।", a: "Ich kann kochen." },
        { q: "আমি সাঁতার পারি না।", a: "Ich kann nicht schwimmen." },
        { q: "তুমি কি সাহায্য করতে পারবে?", a: "Kannst du helfen?" },
        { q: "সে ভালো গাইতে পারে।", a: "Sie kann gut singen." },
        { q: "আমরা কাল আসতে পারবো।", a: "Wir können morgen kommen." },
        { q: "আপনি কি সাহায্য করতে পারবেন?", a: "Können Sie helfen?" },
      ],
      vonHerzen: { en: "Three things you CAN do, one you can't yet.", bn: "যা পারো তিনটা, যা এখনো পারো না একটা।" },
    },
    {
      n: 26,
      de: "muss, করতেই হবে + তিনে মিল",
      bn: "বাধ্যতা, আর তিন সাহায্যকারী একসাথে",
      muster: {
        pattern: "muss · musst · muss · müssen · müsst · müssen",
        why: "আজ তিনজন একসাথে: möchte (চাই), kann (পারি), muss (হবেই)। একই খিলান, তিন রঙ।",
        examples: "Ich möchte spielen, aber ich muss lernen.",
        tip: "'চাই কিন্তু হবেই'– এই বাক্যটা জীবনের অর্ধেক!",
      },
      schau: [
        { de: "Ich muss jetzt gehen.", bn: "আমাকে এখন যেতেই হবে।" },
        { de: "Ich muss lernen.", bn: "আমাকে পড়তেই হবে।" },
        { de: "Du musst essen!", bn: "তোমাকে খেতেই হবে!" },
        { de: "Wir müssen warten.", bn: "আমাদের অপেক্ষা করতে হবে।" },
        { de: "Ich möchte spielen, aber ich muss lernen.", bn: "খেলতে চাই, কিন্তু পড়তে হবে।" },
      ],
      sagEs: [
        { q: "আমাকে এখন যেতেই হবে।", a: "Ich muss jetzt gehen." },
        { q: "আমাকে পড়তেই হবে।", a: "Ich muss lernen." },
        { q: "তোমাকে খেতেই হবে।", a: "Du musst essen." },
        { q: "আমাদের অপেক্ষা করতে হবে।", a: "Wir müssen warten." },
        { q: "খেলতে চাই, কিন্তু পড়তে হবে।", a: "Ich möchte spielen, aber ich muss lernen." },
        { q: "সে আজ কাজ করতে পারবে না।", a: "Er kann heute nicht arbeiten." },
      ],
      vonHerzen: { en: "About tomorrow: one möchte, one kann, one muss.", bn: "আগামীকাল নিয়ে: একটা möchte, একটা kann, একটা muss।" },
    },
    {
      n: 27,
      de: "Zahlen 0–100",
      bn: "সংখ্যা, আর উল্টো প্যাঁচ",
      muster: {
        pattern: "21 = einundzwanzig (এক-আর-বিশ!) 35 = fünfunddreißig",
        why: "ছোট সংখ্যা আগে, দশক পরে, ইংরেজির উল্টো। তিন দিনে অভ্যাস হয়ে যায়।",
        examples: "eins zwei drei vier fünf sechs sieben acht neun zehn, elf zwölf!",
        tip: "১৬ = sechzehn (s-এর x নেই), ১৭ = siebzehn (sieben ছোট)।",
      },
      schau: [
        { de: "eins · zwei · drei · vier · fünf", bn: "১ ২ ৩ ৪ ৫" },
        { de: "sechs · sieben · acht · neun · zehn", bn: "৬ ৭ ৮ ৯ ১০" },
        { de: "elf · zwölf · zwanzig · dreißig", bn: "১১ ১২ ২০ ৩০" },
        { de: "einundzwanzig = ২১!", bn: "এক-আর-বিশ" },
        { de: "Ich bin sechzehn Jahre alt.", bn: "আমার বয়স ষোলো।" },
      ],
      sagEs: [
        { q: "৭", a: "sieben" },
        { q: "১২", a: "zwölf" },
        { q: "১৬", a: "sechzehn" },
        { q: "২১", a: "einundzwanzig" },
        { q: "৩৫", a: "fünfunddreißig" },
        { q: "তোমার বয়স বলো।", a: "Ich bin ___ Jahre alt." },
      ],
      vonHerzen: { en: "Say your phone number in German, five times.", bn: "নিজের ফোন নম্বর জার্মানে পাঁচবার বলো।" },
    },
    {
      n: 28,
      de: "Tage + Uhrzeit",
      bn: "দিন ও ঘড়ি, halb-ফাঁদসহ",
      muster: {
        pattern: "Wie spät ist es?, Es ist drei Uhr. um drei Uhr = তিনটায়",
        why: "দিনের আগে am (am Montag), ঘণ্টার আগে um (um drei Uhr)। আর সাবধান: halb vier = সাড়ে তিন!",
        examples: "Montag Dienstag Mittwoch Donnerstag Freitag Samstag Sonntag",
        tip: "halb মানে 'পরের ঘণ্টার অর্ধেক পথে'– halb sechs = ৫:৩০।",
      },
      schau: [
        { de: "Heute ist Montag.", bn: "আজ সোমবার।" },
        { de: "Wie spät ist es?", bn: "কয়টা বাজে?" },
        { de: "Es ist drei Uhr.", bn: "তিনটা বাজে।" },
        { de: "Wir essen um sieben Uhr.", bn: "আমরা সাতটায় খাই।" },
        { de: "halb vier = ৩:৩০ (!)", bn: "ফাঁদটা মনে রাখো!" },
      ],
      sagEs: [
        { q: "আজ সোমবার।", a: "Heute ist Montag." },
        { q: "কয়টা বাজে?", a: "Wie spät ist es?" },
        { q: "দশটা বাজে।", a: "Es ist zehn Uhr." },
        { q: "আমরা তিনটায় খাই।", a: "Wir essen um drei Uhr." },
        { q: "সোমবারে আমার স্কুল আছে।", a: "Am Montag habe ich Schule." },
        { q: "halb sechs মানে কয়টা?", a: "৫:৩০ (সাড়ে পাঁচ!)" },
      ],
      vonHerzen: { en: "Your daily times: Ich esse um ___. Ich schlafe um ___.", bn: "নিজের সময়সূচি বলো: কখন খাও, কখন ঘুমাও।" },
    },
    {
      n: 29,
      de: "Satzbank-Tag: Café & Straße",
      bn: "বাস্তবের মহড়া, ক্যাফে ও রাস্তা",
      muster: {
        pattern: "Ich möchte einen Tee, bitte. · Wie viel kostet das? · Zahlen, bitte!",
        why: "'einen Tee'– তৈরি টুকরো হিসেবে নাও (নীল দলের object-রূপ, Stufe Zwei-র গল্প)। আজ মহড়ার দিন: দুই ভূমিকাতেই বলো।",
        examples: "Entschuldigung! · Vielen Dank! · Bitte schön! · Langsam, bitte!",
        tip: "ভদ্রতার শব্দগুলো সোনার চাবি, প্রতিটা কথোপকথনে।",
      },
      schau: [
        { de: "Ich möchte einen Tee, bitte.", bn: "একটা চা দিন, প্লিজ।" },
        { de: "Wie viel kostet das?", bn: "এটার দাম কত?" },
        { de: "Zahlen, bitte!", bn: "বিল দিন, প্লিজ!" },
        { de: "Entschuldigung, wo ist der Bahnhof?", bn: "মাফ করবেন, স্টেশন কোথায়?" },
        { de: "Vielen Dank!, Bitte schön!", bn: "অনেক ধন্যবাদ!, কিছু না!" },
      ],
      sagEs: [
        { q: "কেমন আছো?, ভালো, ধন্যবাদ!", a: "Wie geht's?, Gut, danke!" },
        { q: "এটার দাম কত?", a: "Wie viel kostet das?" },
        { q: "বিল দিন, প্লিজ!", a: "Zahlen, bitte!" },
        { q: "মাফ করবেন, স্টেশন কোথায়?", a: "Entschuldigung, wo ist der Bahnhof?" },
        { q: "আমি বুঝিনি। আস্তে বলুন, প্লিজ!", a: "Ich verstehe nicht. Langsam, bitte!" },
        { q: "অনেক ধন্যবাদ!", a: "Vielen Dank!" },
      ],
      vonHerzen: { en: "Role-play the café aloud, both roles: order, price, pay, thank.", bn: "ক্যাফের দৃশ্যটা জোরে অভিনয় করো, দুই চরিত্রেই: অর্ডার, দাম, বিল, ধন্যবাদ।" },
    },
    {
      n: 30,
      de: "Alles zusammen, মুক্ত কথা",
      bn: "সব একসাথে, এবার নিজের গল্প",
      muster: {
        pattern: "Ich heiße … Ich komme aus … Ich lerne … Ich möchte … Ich gebe nicht auf!",
        why: "আজ সব হাতিয়ার একসাথে: sein, haben, ক্রিয়া-মেশিন, টুপি, না-বলা, প্রশ্ন, বন্ধনী। তোমার প্রথম জার্মান আত্মপরিচয়।",
        examples: "Es ist schwer, aber ich kann das!",
        tip: "'কঠিন, কিন্তু আমি পারি'– এটাই এই খাতার শেষ কথা, আর তোমার শুরুর কথা।",
      },
      schau: [
        { de: "Ich heiße Rima.", bn: "আমার নাম রিমা।" },
        { de: "Ich komme aus Bangladesch.", bn: "আমি বাংলাদেশ থেকে।" },
        { de: "Ich lerne jeden Tag Deutsch.", bn: "আমি রোজ জার্মান শিখি।" },
        { de: "Ich möchte gut sprechen.", bn: "আমি ভালো বলতে চাই।" },
        { de: "Ich gebe nicht auf!", bn: "আমি হাল ছাড়ি না!" },
      ],
      sagEs: [
        { q: "আমার নাম ___।", a: "Ich heiße ___." },
        { q: "আমি বাংলাদেশ থেকে।", a: "Ich komme aus Bangladesch." },
        { q: "আমি রোজ জার্মান শিখি।", a: "Ich lerne jeden Tag Deutsch." },
        { q: "আমি ভালো বলতে চাই।", a: "Ich möchte gut sprechen." },
        { q: "এটা কঠিন, কিন্তু আমি পারি।", a: "Es ist schwer, aber ich kann das." },
        { q: "আমি হাল ছাড়ি না!", a: "Ich gebe nicht auf!" },
      ],
      vonHerzen: { en: "Dein Tag auf Deutsch: 6+ sentences, morning to night. Read it aloud twice.", bn: "তোমার দিনটা জার্মানে: সকাল থেকে রাত, অন্তত ছয় বাক্য। দু'বার জোরে পড়ো।" },
    },
  ],
};
