/* ============================================================
   workbooks/english-term-3.ts: the thirty days of Term Three,
   the grammar term.

   One object per day, in order. The days walk the twenty-five
   parts of the term from the basic rung to the advanced one; the
   map at the end of part 25 says which day stands on which part.

   THE SHAPE IS TERM ONE'S PLUS ONE THING. A day still has a
   pattern, five lines to hear and say, six prompts to translate
   with an answer key, and one true paragraph. What this book
   adds is `gaps`: six sentences with a hole in each and a few
   words to try there, which is how a grammar rule is drilled
   rather than read. `components/lesson/language.tsx` draws them
   with the same component a lesson's `gap` block uses, and the
   shape is `GapItem` in `shared/lesson.ts`.

   House rules for the text here:

     · the learner is তুমি, as in the rest of this school
     · every English string is the thing being taught; every
       Bangla string is what it means or why it works
     · the answers are answers, not the only answer: if the
       shape is right, the learner is right
     · no field inside a day is called `a` except `say[].a`:
       `/api/book/<stage>` strips that one and asserts no field
       of that name leaves in the bytes
   ============================================================ */

export default {
  /* The second line of every day's footer tick. */
  foot: "নিয়মটা একবার জোরে বলেছি",

  /* The two lines under the title. */
  lede: {
    en: "One rule a day. Six holes to fill. One honest paragraph.",
    bn: "দিনে একটা নিয়ম। ছয়টা ফাঁকা ঘর। নিজের জীবনের একটা সত্যি অনুচ্ছেদ।",
  },

  /* What this book asks the learner to collect as they go: the
     rules they keep tripping on, the rebel verbs in three forms
     because every perfect and every passive needs V3, and their
     own best lines. `key` prefixes the storage keys of the boxes
     and must never change once the book has shipped. */
  collect: {
    en: "The collection",
    bn: "সংগ্রহ",
    key: "collect",
    blurb:
      "যে নিয়মে বারবার আটকাও সেটা এখানে এক লাইনে লেখো, রেবেল ক্রিয়াগুলো তিন রূপে জমাও, আর নিজের যে বাক্যটা আজ সবচেয়ে ভালো লেগেছে সেটাও। সপ্তাহে একবার পুরোটা জোরে পড়ো।",
    columns: [
      {
        key: "rules",
        head: "Rules I forget · যে নিয়ম ভুলি",
        placeholder: "if-এর ঘরে will নয়\nenjoy + -ing\n…",
      },
      {
        key: "rebels",
        head: "Rebels · go went gone",
        placeholder: "go → went → gone\nsee → saw → seen\nwrite → wrote → written\n…",
      },
      {
        key: "mine",
        head: "My own lines · নিজের বাক্য",
        placeholder: "Never have I seen such a catch.\nI had my bat repaired.\n…",
      },
    ],
  },

  /* The band after the last day. */
  end: {
    en: "Day 31 is the day you catch your own mistakes.",
    bn:
      "৩১তম দিন হলো সেই দিন, যেদিন আর কেউ লাল কালি ধরে না: নিজের বাক্য নিজে পড়ে নিজেই ভুল ধরো, " +
      "রোজ একটা সত্যিকারের ইংরেজি লেখা পড়ে প্রতিটা বাক্যে একটা নিয়ম চেনো, আর পরীক্ষার হলে আন্দাজে নয়, নিয়ম জেনে লেখো।",
  },

  /* The last line on the page. */
  motto: {
    en: "Know the rule. Then break the silence.",
    bn: "নিয়মটা জানো। তারপর চুপ থেকো না।",
  },

  days: [
    {
      n: 1,
      en: "WHO + DOES + WHAT",
      bn: "কে, কী করে, কী",
      pattern: {
        shape: "WHO + DOES + WHAT",
        why: "প্রতিটা ইংরেজি বাক্যের তিনটা ঘর: কে (noun বা pronoun), কী করে (verb), কী (noun)। আজ শুধু এই তিনটা ঘর চেনো আর ভরো।",
        examples: "Rafi plays cricket. · Nanu tells stories. · The cat drinks milk.",
        tip: "ঘর তিনটা একই রেখে শব্দ বদলাও: বিশটা বাক্য তোমার।",
      },
      watch: [
        { en: "Rafi plays cricket.", bn: "রাফি ক্রিকেট খেলে।" },
        { en: "Nanu tells stories.", bn: "নানু গল্প বলেন।" },
        { en: "The cat drinks milk.", bn: "বেড়ালটা দুধ খায়।" },
        { en: "Mitu reads books.", bn: "মিতু বই পড়ে।" },
        { en: "We love mangoes.", bn: "আমরা আম ভালোবাসি।" },
      ],
      say: [
        { q: "আমি ভাত খাই।", a: "I eat rice." },
        { q: "সে চা বানায়।", a: "She makes tea." },
        { q: "তারা ফুটবল খেলে।", a: "They play football." },
        { q: "বাবা খবর পড়েন।", a: "Baba reads the news." },
        { q: "আমরা গান শুনি।", a: "We listen to songs." },
        { q: "পাখিটা গান গায়।", a: "The bird sings." },
      ],
      gaps: [
        { text: "Rafi ___ cricket.", bn: "রাফি ক্রিকেট খেলে।", options: ["plays", "player", "play"], right: 0, why: { bn: "কী করে-র ঘরে ক্রিয়া: plays। player একটা noun।", en: "The does slot takes a verb: plays. Player is a noun." } },
        { text: "The ___ drinks milk.", bn: "বেড়ালটা দুধ খায়।", options: ["cat", "drinks", "quickly"], right: 0, why: { bn: "কে-র ঘরে noun: cat।", en: "The who slot takes a noun: cat." } },
        { text: "Nanu tells ___.", bn: "নানু গল্প বলেন।", options: ["stories", "tells", "slowly"], right: 0, why: { bn: "কী-র ঘরে noun: stories।", en: "The what slot takes a noun: stories." } },
        { text: "Mitu ___ a book.", bn: "মিতু একটা বই পড়ে।", options: ["book", "reads", "reader"], right: 1, why: { bn: "মাঝের ঘর ক্রিয়ার: reads।", en: "The middle slot is the verb's: reads." } },
        { text: "The bowler bowls ___.", bn: "বোলার দ্রুত বল করে।", options: ["fast", "ball", "bowl"], right: 0, why: { bn: "কীভাবে: adverb, fast।", en: "How: an adverb, fast." } },
        { text: "___ love mangoes.", bn: "আমরা আম ভালোবাসি।", options: ["We", "Us", "Our"], right: 0, why: { bn: "কে-র ঘরে কর্তা-রূপ: We।", en: "The who slot takes the subject form: We." } },
      ],
      heart: {
        en: "Write 3 true sentences about your family: who does what.",
        bn: "নিজের পরিবার নিয়ে তিনটা সত্যি বাক্য লেখো: কে কী করে।",
      },
    },
    {
      n: 2,
      en: "a cat, two cats, some water",
      bn: "একটা, অনেক, মাপা",
      pattern: {
        shape: "a + cat · two + cats · some + water",
        why: "গোনা যায় এমন জিনিসে সংখ্যা আর -s। গোনা যায় না এমন জিনিসে some, আর মাপতে একটা পাত্র: a cup of tea।",
        examples: "I have two cats. · We need some rice. · She gave me a piece of advice.",
        tip: "a বসিয়ে দেখো: a ball হয়, a rice হয় না।",
      },
      watch: [
        { en: "I have two cats and a dog.", bn: "আমার দুটো বেড়াল আর একটা কুকুর আছে।" },
        { en: "We need some rice and some oil.", bn: "আমাদের একটু চাল আর একটু তেল লাগবে।" },
        { en: "The children are playing outside.", bn: "বাচ্চারা বাইরে খেলছে।" },
        { en: "Nanu knows a hundred stories.", bn: "নানু একশোটা গল্প জানেন।" },
        { en: "Please give me a glass of water.", bn: "আমাকে এক গ্লাস পানি দাও তো।" },
      ],
      say: [
        { q: "আমার তিনটে বই আছে।", a: "I have three books." },
        { q: "আমাদের একটু চিনি লাগবে।", a: "We need some sugar." },
        { q: "বাচ্চারা খেলছে।", a: "The children are playing." },
        { q: "সে একটা ভালো উপদেশ দিল।", a: "She gave a piece of good advice." },
        { q: "দুটো বাস দেরি করেছে।", a: "Two buses are late." },
        { q: "এক কাপ চা, প্লিজ।", a: "A cup of tea, please." },
      ],
      gaps: [
        { text: "I have two ___.", bn: "আমার দুটো ভাই।", options: ["brother", "brothers", "brotheres"], right: 1, why: { bn: "two, তাই -s: brothers।", en: "Two, so -s: brothers." } },
        { text: "Please give me some ___.", bn: "আমাকে একটু পানি দাও।", options: ["water", "waters", "a water"], right: 0, why: { bn: "গোনা যায় না: some water।", en: "Uncountable: some water." } },
        { text: "Bangladesh won three ___.", bn: "বাংলাদেশ তিনটে ম্যাচ জিতল।", options: ["matchs", "matches", "match"], right: 1, why: { bn: "-ch, তাই -es।", en: "-ch takes -es." } },
        { text: "The ___ are at school.", bn: "বাচ্চারা স্কুলে।", options: ["childs", "children", "childrens"], right: 1, why: { bn: "রেবেল: children।", en: "A rebel: children." } },
        { text: "She has a lot of ___.", bn: "তার অনেক হোমওয়ার্ক।", options: ["homework", "homeworks", "a homework"], right: 0, why: { bn: "homework গোনা যায় না।", en: "Homework is uncountable." } },
        { text: "This is ___ bat.", bn: "এটা রাফির ব্যাট।", options: ["Rafi", "Rafi's", "Rafis"], right: 1, why: { bn: "মালিকানা: 's।", en: "Possession: 's." } },
      ],
      heart: {
        en: "Write 3 sentences about what is in your kitchen: countable and uncountable.",
        bn: "রান্নাঘরে কী কী আছে, তিন বাক্যে: গোনা যায় আর যায় না।",
      },
    },
    {
      n: 3,
      en: "She called him.",
      bn: "সে তাকে ডাকল",
      pattern: {
        shape: "WHO (he / she / they) + VERB + WHOM (him / her / them)",
        why: "ক্রিয়ার বাঁয়ে কর্তা-রূপ, ডানে কর্ম-রূপ। with, to, for-এর পরেও ডানের রূপ।",
        examples: "She called him. · They invited us. · I told her the story.",
        tip: "অন্যজনকে সরিয়ে পরীক্ষা করো: Sir called me, তাই Mitu and me।",
      },
      watch: [
        { en: "She helped him with the homework.", bn: "সে তাকে হোমওয়ার্কে সাহায্য করল।" },
        { en: "They invited us to the match.", bn: "তারা আমাদের ম্যাচে ডাকল।" },
        { en: "I told her the whole story.", bn: "আমি তাকে পুরো গল্পটা বললাম।" },
        { en: "Rafi and I are cousins.", bn: "রাফি আর আমি কাজিন।" },
        { en: "This bat is mine, not yours.", bn: "এই ব্যাটটা আমার, তোমার নয়।" },
      ],
      say: [
        { q: "আমি তাকে দেখলাম।", a: "I saw him." },
        { q: "সে আমাকে ফোন করল।", a: "She called me." },
        { q: "তারা আমাদের সাথে খেলল।", a: "They played with us." },
        { q: "এটা আমার বই।", a: "This is my book." },
        { q: "বইটা আমার।", a: "The book is mine." },
        { q: "রাফি নিজেকে কেটে ফেলল।", a: "Rafi cut himself." },
      ],
      gaps: [
        { text: "Mitu and ___ went to the fair.", bn: "মিতু আর আমি মেলায় গেলাম।", options: ["me", "I", "my"], right: 1, why: { bn: "কর্তা: I।", en: "Subject: I." } },
        { text: "Coach praised Rafi and ___.", bn: "কোচ রাফি আর আমাকে প্রশংসা করলেন।", options: ["I", "me", "mine"], right: 1, why: { bn: "কর্ম: me।", en: "Object: me." } },
        { text: "This phone is ___.", bn: "এই ফোনটা আমার।", options: ["my", "mine", "me"], right: 1, why: { bn: "পরে noun নেই: mine।", en: "No noun follows: mine." } },
        { text: "The cat licked ___ paw.", bn: "বেড়ালটা তার থাবা চাটল।", options: ["it's", "its", "it"], right: 1, why: { bn: "মালিকানা: its।", en: "Possession: its." } },
        { text: "We enjoyed ___ at the fair.", bn: "মেলায় আমরা মজা করলাম।", options: ["us", "ourselves", "our"], right: 1, why: { bn: "নিজেরাই: ourselves।", en: "Ourselves." } },
        { text: "Give the ball to ___.", bn: "বলটা তাদের দাও।", options: ["they", "them", "their"], right: 1, why: { bn: "to-এর পরে কর্ম-রূপ: them।", en: "After to, the object form: them." } },
      ],
      heart: {
        en: "Write 3 sentences about a friend using he/she, him/her and his/her.",
        bn: "একজন বন্ধু নিয়ে তিন বাক্য, he/she, him/her আর his/her দিয়ে।",
      },
    },
    {
      n: 4,
      en: "I saw a dog. The dog was hungry.",
      bn: "প্রথমবার a, তারপর the",
      pattern: {
        shape: "a ____ (প্রথমবার) → the ____ (তারপর)",
        why: "প্রথমবার বললে শ্রোতা জানে না কোনটা, তাই a। তারপর থেকে দুজনেই জানো, তাই the। স্বরের আওয়াজে an।",
        examples: "I saw a dog. The dog was hungry. · an hour · the sun",
        tip: "মনে মনে 'ওই যে' বসাও; মানে হলে the।",
      },
      watch: [
        { en: "I saw a dog. The dog was hungry.", bn: "একটা কুকুর দেখলাম। কুকুরটা ক্ষুধার্ত ছিল।" },
        { en: "We waited for an hour.", bn: "আমরা এক ঘণ্টা অপেক্ষা করলাম।" },
        { en: "The sun rises in the east.", bn: "সূর্য পূর্বে ওঠে।" },
        { en: "I go to school by bus.", bn: "আমি বাসে স্কুলে যাই।" },
        { en: "Mustafiz is the best bowler in the team.", bn: "মুস্তাফিজ দলের সেরা বোলার।" },
      ],
      say: [
        { q: "আমি একটা বই কিনলাম। বইটা পুরনো।", a: "I bought a book. The book is old." },
        { q: "চাঁদটা উজ্জ্বল।", a: "The moon is bright." },
        { q: "সে একটা আপেল খেল।", a: "She ate an apple." },
        { q: "আমি আম ভালোবাসি।", a: "I love mangoes." },
        { q: "দরজাটা বন্ধ করো।", a: "Close the door." },
        { q: "রাফি বাসায় আছে।", a: "Rafi is at home." },
      ],
      gaps: [
        { text: "Rafi has ___ new bat.", bn: "রাফির একটা নতুন ব্যাট আছে।", options: ["a", "an", "the"], right: 0, why: { bn: "প্রথমবার, n-এর আওয়াজ: a।", en: "First mention, n sound: a." } },
        { text: "It took ___ hour.", bn: "এক ঘণ্টা লাগল।", options: ["a", "an", "the"], right: 1, why: { bn: "h চুপ, স্বরের আওয়াজ: an।", en: "Silent h, vowel sound: an." } },
        { text: "___ sky is grey today.", bn: "আজ আকাশ ধূসর।", options: ["A", "The", "An"], right: 1, why: { bn: "একটাই আকাশ: the।", en: "One sky: the." } },
        { text: "I go to ___ school every day.", bn: "আমি রোজ স্কুলে যাই।", options: ["a", "the", "(nothing)"], right: 2, why: { bn: "প্রতিষ্ঠান হিসেবে: কিছু নয়।", en: "As an institution: nothing." } },
        { text: "She is ___ honest girl.", bn: "সে একজন সৎ মেয়ে।", options: ["a", "an", "the"], right: 1, why: { bn: "honest-এর h চুপ: an।", en: "Silent h in honest: an." } },
        { text: "I love ___ tea.", bn: "আমি চা ভালোবাসি।", options: ["a", "the", "(nothing)"], right: 2, why: { bn: "সাধারণভাবে, গোনা যায় না: কিছু নয়।", en: "In general, uncountable: nothing." } },
      ],
      heart: {
        en: "Tell a tiny story: I saw a… The… was…",
        bn: "ছোট্ট একটা গল্প: I saw a… The… was…",
      },
    },
    {
      n: 5,
      en: "taller than, the tallest",
      bn: "তুলনার সিঁড়ি",
      pattern: {
        shape: "as ___ as · ___er than · the ___est",
        why: "সমান হলে as … as, দুজনে -er than বা more … than, সবার সেরা the -est বা the most। good, better, best রেবেল।",
        examples: "Rafi is taller than Mitu. · Shakib is the best. · as fast as",
        tip: "than শুনলে -er, the শুনলে -est।",
      },
      watch: [
        { en: "Rafi is taller than Mitu.", bn: "রাফি মিতুর চেয়ে লম্বা।" },
        { en: "Mashrafe is the tallest of them all.", bn: "মাশরাফি সবার মধ্যে সবচেয়ে লম্বা।" },
        { en: "This film is more exciting than the last one.", bn: "এই সিনেমাটা আগেরটার চেয়ে বেশি উত্তেজনাপূর্ণ।" },
        { en: "Nanu makes the best pitha in the world.", bn: "নানু দুনিয়ার সেরা পিঠা বানান।" },
        { en: "Today is as hot as yesterday.", bn: "আজ কালকের মতোই গরম।" },
      ],
      say: [
        { q: "ঢাকা সিলেটের চেয়ে বড়।", a: "Dhaka is bigger than Sylhet." },
        { q: "এটা বছরের সবচেয়ে গরম দিন।", a: "This is the hottest day of the year." },
        { q: "মিতুর নম্বর আমার চেয়ে ভালো।", a: "Mitu's marks are better than mine." },
        { q: "সে আমার মতোই লম্বা।", a: "She is as tall as me." },
        { q: "এটা সবচেয়ে মজার গল্প।", a: "This is the funniest story." },
        { q: "ম্যাচটা খুব উত্তেজনাপূর্ণ ছিল।", a: "The match was very exciting." },
      ],
      gaps: [
        { text: "Rafi runs ___ than his friend.", bn: "রাফি তার বন্ধুর চেয়ে দ্রুত দৌড়ায়।", options: ["fast", "faster", "fastest"], right: 1, why: { bn: "than: faster।", en: "Than: faster." } },
        { text: "This is the ___ day of the year.", bn: "এটা বছরের সবচেয়ে ঠান্ডা দিন।", options: ["cold", "colder", "coldest"], right: 2, why: { bn: "the … of the year: coldest।", en: "The … of the year: coldest." } },
        { text: "Dhaka is ___ than Sylhet.", bn: "ঢাকা সিলেটের চেয়ে বেশি জনবহুল।", options: ["crowdeder", "more crowded", "most crowded"], right: 1, why: { bn: "লম্বা শব্দ: more crowded।", en: "Long word: more crowded." } },
        { text: "Her marks are ___ than mine.", bn: "তার নম্বর আমার চেয়ে ভালো।", options: ["gooder", "better", "best"], right: 1, why: { bn: "good, better, best।", en: "Good, better, best." } },
        { text: "He is as ___ as his brother.", bn: "সে তার ভাইয়ের মতোই লম্বা।", options: ["tall", "taller", "tallest"], right: 0, why: { bn: "as … as: সাধারণ রূপ।", en: "As … as: the plain form." } },
        { text: "The match was ___.", bn: "ম্যাচটা ছিল উত্তেজনাপূর্ণ।", options: ["exciting", "excited", "excitement"], right: 0, why: { bn: "জিনিসটা -ing।", en: "The thing is -ing." } },
      ],
      heart: {
        en: "Compare two people you know in 3 sentences.",
        bn: "পরিচিত দুজন মানুষের তুলনা তিন বাক্যে।",
      },
    },
    {
      n: 6,
      en: "She plays. They play.",
      bn: "একটাই টুপি",
      pattern: {
        shape: "He / She / It + VERB-s · I / You / We / They + VERB",
        why: "বর্তমান কালে একজন তৃতীয় ব্যক্তি হলে ক্রিয়ায় -s। অনেক হলে টুপি কর্তার মাথায়, ক্রিয়া খালি। does, can, must-এর পরে খালি।",
        examples: "Rafi plays. His friends play. · She doesn't play. · Everyone loves Nanu.",
        tip: "কর্তায় s? ক্রিয়ায় নয়। কর্তায় নয়? ক্রিয়ায় হ্যাঁ। I আর you বাদে।",
      },
      watch: [
        { en: "Rafi plays cricket every evening.", bn: "রাফি রোজ সন্ধ্যায় ক্রিকেট খেলে।" },
        { en: "His friends play with him.", bn: "তার বন্ধুরা তার সাথে খেলে।" },
        { en: "Mitu studies at night.", bn: "মিতু রাতে পড়ে।" },
        { en: "The cat has a red collar.", bn: "বেড়ালটার একটা লাল কলার আছে।" },
        { en: "Everyone loves a good story.", bn: "সবাই ভালো গল্প ভালোবাসে।" },
      ],
      say: [
        { q: "সে রোজ পড়ে।", a: "She studies every day." },
        { q: "তারা রোজ পড়ে।", a: "They study every day." },
        { q: "নানুর একটা গল্প আছে।", a: "Nanu has a story." },
        { q: "রাফি পালংশাক পছন্দ করে না।", a: "Rafi doesn't like spinach." },
        { q: "সবাই শাকিবকে ভালোবাসে।", a: "Everyone loves Shakib." },
        { q: "বাসটা সাতটায় ছাড়ে।", a: "The bus leaves at seven." },
      ],
      gaps: [
        { text: "Mitu ___ English every morning.", bn: "মিতু রোজ সকালে ইংরেজি পড়ে।", options: ["study", "studies", "studys"], right: 1, why: { bn: "একজন, y হয় ies: studies।", en: "One person, y becomes ies: studies." } },
        { text: "The players ___ before a match.", bn: "খেলোয়াড়রা ম্যাচের আগে অনুশীলন করে।", options: ["practises", "practise", "practising"], right: 1, why: { bn: "অনেক, খালি ক্রিয়া।", en: "Many, bare verb." } },
        { text: "The captain of the players ___ tired.", bn: "খেলোয়াড়দের অধিনায়ক ক্লান্ত।", options: ["is", "are", "be"], right: 0, why: { bn: "কর্তা captain, একজন: is।", en: "The subject is captain, one: is." } },
        { text: "Everybody ___ Nanu's pitha.", bn: "সবাই নানুর পিঠা পছন্দ করে।", options: ["like", "likes", "liking"], right: 1, why: { bn: "everybody একজন: likes।", en: "Everybody counts as one: likes." } },
        { text: "Rafi doesn't ___ spinach.", bn: "রাফি পালংশাক পছন্দ করে না।", options: ["likes", "like", "liked"], right: 1, why: { bn: "does টুপি পরেছে: like।", en: "Does wears the hat: like." } },
        { text: "There ___ three mangoes here.", bn: "এখানে তিনটে আম আছে।", options: ["is", "are", "be"], right: 1, why: { bn: "কর্তা three mangoes: are।", en: "The subject is three mangoes: are." } },
      ],
      heart: {
        en: "Write what each person in your home does every day, with the -s.",
        bn: "বাসার প্রত্যেকে রোজ কী করে, -s সহ লেখো।",
      },
    },
    {
      n: 7,
      en: "plays / is playing",
      bn: "স্থির ছবি, নড়া ছবি",
      pattern: {
        shape: "every day → plays · now → is playing",
        why: "অভ্যাস আর সত্যি হলে present simple; এই মুহূর্তে চলছে হলে am/is/are + -ing। বাংলাও এই ভাগটা করে: খেলে, খেলছে।",
        examples: "Rafi plays on Fridays. · Rafi is playing now. · It rains a lot in July. · Look, it is raining!",
        tip: "সময়ের শব্দটা আগে খোঁজো: every day, now।",
      },
      watch: [
        { en: "Nanu tells stories every night.", bn: "নানু রোজ রাতে গল্প বলেন।" },
        { en: "Nanu is telling a story right now.", bn: "নানু এখনই একটা গল্প বলছেন।" },
        { en: "Mitu studies in the morning.", bn: "মিতু সকালে পড়ে।" },
        { en: "Be quiet, Mitu is studying.", bn: "চুপ করো, মিতু পড়ছে।" },
        { en: "Look, it is raining!", bn: "দেখো, বৃষ্টি হচ্ছে!" },
      ],
      say: [
        { q: "আমি রোজ সকালে হাঁটি।", a: "I walk every morning." },
        { q: "আমি এখন হাঁটছি।", a: "I am walking now." },
        { q: "সে প্রতি শুক্রবার খেলে।", a: "He plays every Friday." },
        { q: "সে এখন খেলছে।", a: "He is playing now." },
        { q: "জুলাইয়ে অনেক বৃষ্টি হয়।", a: "It rains a lot in July." },
        { q: "বাচ্চারা ঘুমাচ্ছে।", a: "The children are sleeping." },
      ],
      gaps: [
        { text: "Rafi ___ cricket every Friday.", bn: "রাফি প্রতি শুক্রবার ক্রিকেট খেলে।", options: ["plays", "is playing", "played"], right: 0, why: { bn: "every Friday: অভ্যাস।", en: "Every Friday: a habit." } },
        { text: "Be quiet! The baby ___.", bn: "চুপ! বাচ্চাটা ঘুমাচ্ছে।", options: ["sleeps", "is sleeping", "slept"], right: 1, why: { bn: "এই মুহূর্তে: is sleeping।", en: "Right now: is sleeping." } },
        { text: "Water ___ at 100 degrees.", bn: "পানি ১০০ ডিগ্রিতে ফোটে।", options: ["boils", "is boiling", "boiled"], right: 0, why: { bn: "চিরসত্য: boils।", en: "Always true: boils." } },
        { text: "Look! The bus ___.", bn: "দেখো! বাস আসছে।", options: ["comes", "is coming", "came"], right: 1, why: { bn: "Look: এখন চলছে।", en: "Look: happening now." } },
        { text: "Mitu ___ two brothers.", bn: "মিতুর দুই ভাই।", options: ["has", "is having", "have"], right: 0, why: { bn: "have অবস্থা, -ing নয়।", en: "Have is a state, no -ing." } },
        { text: "I ___ him very well.", bn: "আমি তাকে খুব ভালো চিনি।", options: ["know", "am knowing", "knows"], right: 0, why: { bn: "know অবস্থার ক্রিয়া: know।", en: "Know is a state verb: know." } },
      ],
      heart: {
        en: "Look out of the window. Write what is happening now, and what happens there every day.",
        bn: "জানালার বাইরে তাকাও। এখন যা হচ্ছে আর রোজ যা হয়, লেখো।",
      },
    },
    {
      n: 8,
      en: "played / was playing",
      bn: "কাল যা হয়েছে, তখন যা চলছিল",
      pattern: {
        shape: "yesterday → played · while → was playing when …",
        why: "শেষ হয়ে যাওয়া অতীতে -ed বা রেবেল রূপ, সব কর্তায় এক। অতীতের একটা মুহূর্তে চলছিল হলে was/were + -ing, আর হঠাৎ কাজটা past simple।",
        examples: "Rafi played yesterday. · I was sleeping when the phone rang. · Bangladesh beat India in 2007.",
        tip: "লম্বা কাজ was -ing, হঠাৎ কাজ -ed।",
      },
      watch: [
        { en: "Rafi played cricket yesterday.", bn: "রাফি কাল ক্রিকেট খেলেছে।" },
        { en: "I was sleeping when the phone rang.", bn: "আমি ঘুমাচ্ছিলাম, তখন ফোন বাজল।" },
        { en: "Bangladesh beat India in 2007.", bn: "বাংলাদেশ ২০০৭ সালে ভারতকে হারিয়েছিল।" },
        { en: "The king was sleeping when the thief entered.", bn: "রাজা ঘুমাচ্ছিলেন, তখন চোর ঢুকল।" },
        { en: "We went to Cox's Bazar two years ago.", bn: "আমরা দুই বছর আগে কক্সবাজার গিয়েছিলাম।" },
      ],
      say: [
        { q: "আমি কাল একটা সিনেমা দেখলাম।", a: "I watched a film yesterday." },
        { q: "সে গত সপ্তাহে ঢাকায় গিয়েছিল।", a: "She went to Dhaka last week." },
        { q: "আমি টিভি দেখছিলাম, তখন কারেন্ট চলে গেল।", a: "I was watching TV when the lights went out." },
        { q: "তারা মাঠে খেলছিল।", a: "They were playing in the field." },
        { q: "নানু একটা গল্প বললেন।", a: "Nanu told a story." },
        { q: "আমরা ম্যাচটা জিতলাম।", a: "We won the match." },
      ],
      gaps: [
        { text: "Bangladesh ___ the match last night.", bn: "বাংলাদেশ কাল রাতে ম্যাচটা জিতেছে।", options: ["wins", "won", "was winning"], right: 1, why: { bn: "last night: won।", en: "Last night: won." } },
        { text: "I ___ TV when the lights went out.", bn: "আমি টিভি দেখছিলাম, তখন কারেন্ট গেল।", options: ["watched", "was watching", "watch"], right: 1, why: { bn: "লম্বা কাজ চলছিল: was watching।", en: "The long action was running: was watching." } },
        { text: "Nanu ___ me a story yesterday.", bn: "নানু কাল আমাকে একটা গল্প বললেন।", options: ["tells", "told", "was telling"], right: 1, why: { bn: "tell-এর রেবেল রূপ: told।", en: "Tell's rebel form: told." } },
        { text: "We ___ to school when it started to rain.", bn: "আমরা স্কুলে যাচ্ছিলাম, তখন বৃষ্টি শুরু হলো।", options: ["walked", "were walking", "walk"], right: 1, why: { bn: "were walking when …।", en: "Were walking when …" } },
        { text: "He ___ his keys two days ago.", bn: "সে দুই দিন আগে চাবি হারিয়েছিল।", options: ["loses", "lost", "has lost"], right: 1, why: { bn: "ago: lost।", en: "Ago: lost." } },
        { text: "She ___ at home yesterday.", bn: "সে কাল বাসায় ছিল।", options: ["is", "was", "were"], right: 1, why: { bn: "একজন, অতীত: was।", en: "One person, past: was." } },
      ],
      heart: {
        en: "Write about your yesterday: 3 things that happened, and one thing you were doing when something happened.",
        bn: "কালকের দিন: তিনটা যা হলো, আর একটা যা করছিলে তখন কিছু ঘটল।",
      },
    },
    {
      n: 9,
      en: "will / going to",
      bn: "যা হবে",
      pattern: {
        shape: "will + VERB (এইমাত্র ঠিক করলাম) · going to + VERB (আগেই ঠিক করা)",
        why: "will মানে এইমাত্র ঠিক করলাম, কথা দিচ্ছি, বা অনুমান। going to মানে আগেই পরিকল্পনা ছিল, প্রমাণ আছে। will be -ing ভবিষ্যতের একটা মুহূর্তে যা চলবে।",
        examples: "I will call you. · We are going to watch the final. · It will rain tomorrow.",
        tip: "will-এর পরে ক্রিয়া খালি: will play, will plays নয়।",
      },
      watch: [
        { en: "Don't worry, I will call you tomorrow.", bn: "চিন্তা কোরো না, কাল ফোন করব।" },
        { en: "We are going to watch the final together.", bn: "আমরা একসাথে ফাইনাল দেখব।" },
        { en: "It will rain tonight.", bn: "আজ রাতে বৃষ্টি হবে।" },
        { en: "This time tomorrow I will be sitting in the exam hall.", bn: "কাল এই সময় আমি পরীক্ষার হলে বসে থাকব।" },
        { en: "Rafi is going to be a fast bowler.", bn: "রাফি ফাস্ট বোলার হবে।" },
      ],
      say: [
        { q: "আমি কাল আসব।", a: "I will come tomorrow." },
        { q: "আমরা রবিবারে সিনেমা দেখব।", a: "We are going to watch a film on Sunday." },
        { q: "সে ডাক্তার হবে।", a: "She will be a doctor." },
        { q: "আমি তোমাকে সাহায্য করব।", a: "I will help you." },
        { q: "কাল বৃষ্টি হবে।", a: "It will rain tomorrow." },
        { q: "তারা আগামী সপ্তাহে ঢাকায় যাবে।", a: "They are going to Dhaka next week." },
      ],
      gaps: [
        { text: "Don't worry, I ___ you tomorrow.", bn: "চিন্তা কোরো না, কাল তোমাকে ফোন করব।", options: ["call", "will call", "called"], right: 1, why: { bn: "কথা দেওয়া: will call।", en: "A promise: will call." } },
        { text: "Look at those clouds! It ___ rain.", bn: "মেঘ দেখো! বৃষ্টি হবে।", options: ["is going to", "will to", "goes to"], right: 0, why: { bn: "প্রমাণ দেখে: is going to।", en: "Evidence in view: is going to." } },
        { text: "She ___ be fifteen next June.", bn: "আগামী জুনে তার পনেরো হবে।", options: ["will", "is", "was"], right: 0, why: { bn: "ভবিষ্যৎ: will be।", en: "Future: will be." } },
        { text: "We ___ the match at five o'clock.", bn: "আমরা পাঁচটায় ম্যাচ দেখতে থাকব।", options: ["will be watching", "watched", "watch"], right: 0, why: { bn: "ভবিষ্যতের একটা মুহূর্তে চলবে: will be watching।", en: "In progress at a future moment: will be watching." } },
        { text: "I ___ to bed early tonight.", bn: "আজ রাতে আমি তাড়াতাড়ি ঘুমাতে যাব।", options: ["will go", "will goes", "will going"], right: 0, why: { bn: "will + খালি ক্রিয়া।", en: "Will + bare verb." } },
        { text: "The exam ___ next Sunday.", bn: "পরীক্ষা আগামী রবিবার।", options: ["will be", "is being", "was"], right: 0, why: { bn: "next Sunday: will be।", en: "Next Sunday: will be." } },
      ],
      heart: {
        en: "Write 3 plans for next week: two with going to, one promise with will.",
        bn: "আগামী সপ্তাহের তিনটা পরিকল্পনা: দুটো going to, একটা কথা will দিয়ে।",
      },
    },
    {
      n: 10,
      en: "quickly, always, well",
      bn: "কাজের রং",
      pattern: {
        shape: "a careful driver → drives carefully · always + VERB · is + always",
        why: "adjective নামের রং, adverb কাজের রং: -ly লেগে যায়। fast, hard, late, early একই থাকে; good-এর adverb well। always, never সাধারণ ক্রিয়ার আগে, be-র পরে।",
        examples: "She sings well. · He always plays on Fridays. · Speak slowly, please.",
        tip: "কীভাবে, কোথায়, কখন: এই ক্রমে শেষে।",
      },
      watch: [
        { en: "Speak slowly, please.", bn: "একটু ধীরে বলো তো।" },
        { en: "She sings really well.", bn: "সে সত্যিই খুব ভালো গায়।" },
        { en: "I usually walk to school.", bn: "আমি সাধারণত হেঁটে স্কুলে যাই।" },
        { en: "Rafi is never late.", bn: "রাফি কখনো দেরি করে না।" },
        { en: "He played well at the club yesterday.", bn: "সে কাল ক্লাবে ভালো খেলল।" },
      ],
      say: [
        { q: "সে দ্রুত দৌড়ায়।", a: "He runs fast." },
        { q: "সাবধানে চালাও।", a: "Drive carefully." },
        { q: "আমি সবসময় সকালে চা খাই।", a: "I always drink tea in the morning." },
        { q: "সে কখনো দেরি করে না।", a: "She is never late." },
        { q: "শাকিব ভালো খেলে।", a: "Shakib plays well." },
        { q: "চা-টা খুব গরম।", a: "The tea is too hot." },
      ],
      gaps: [
        { text: "Shakib bats ___.", bn: "শাকিব ভালো ব্যাট করে।", options: ["good", "well", "goodly"], right: 1, why: { bn: "good-এর adverb well।", en: "The adverb of good is well." } },
        { text: "Please drive ___.", bn: "সাবধানে চালাও।", options: ["careful", "carefully", "carefuly"], right: 1, why: { bn: "কীভাবে: carefully।", en: "How: carefully." } },
        { text: "The bus came ___.", bn: "বাসটা দেরিতে এল।", options: ["lately", "late", "latly"], right: 1, why: { bn: "late -ly নেয় না।", en: "Late takes no -ly." } },
        { text: "Rafi ___ forgets his kit.", bn: "রাফি কখনো কিট ভোলে না।", options: ["never", "is never", "forgets never"], right: 0, why: { bn: "সাধারণ ক্রিয়ার আগে: never forgets।", en: "Before an ordinary verb: never forgets." } },
        { text: "She is ___ late.", bn: "সে সবসময় দেরি করে।", options: ["always", "always is", "is always"], right: 0, why: { bn: "be-র পরে: is always late।", en: "After be: is always late." } },
        { text: "This pitha tastes ___.", bn: "এই পিঠাটা খেতে দারুণ।", options: ["wonderfully", "wonderful", "wonder"], right: 1, why: { bn: "taste-এর পরে adjective।", en: "After taste, an adjective." } },
      ],
      heart: {
        en: "Describe how 3 people you know do things: quickly, slowly, carefully, well.",
        bn: "পরিচিত তিনজন কীভাবে কাজ করে: দ্রুত, ধীরে, সাবধানে, ভালো।",
      },
    },
    {
      n: 11,
      en: "in, on, at",
      bn: "তিনটা ছবি",
      pattern: {
        shape: "in = ভিতরে · on = উপরে · at = একটা বিন্দুতে",
        why: "জায়গায় তিনটা ছবি, সময়ে তিনটা আকার: in বড় (মাস, বছর), on মাঝারি (দিন), at ছোট (ঘড়ির সময়)। আর জোড়া: good at, afraid of, listen to।",
        examples: "in the box, on the table, at the door · in June, on Friday, at 5 o'clock",
        tip: "at night, কিন্তু in the morning।",
      },
      watch: [
        { en: "My keys are in my bag.", bn: "আমার চাবি আমার ব্যাগে।" },
        { en: "There is a lizard on the wall.", bn: "দেয়ালে একটা টিকটিকি আছে।" },
        { en: "Meet me at the gate at five.", bn: "পাঁচটায় গেটে দেখা করো।" },
        { en: "School starts in January, on a Sunday.", bn: "স্কুল শুরু জানুয়ারিতে, এক রবিবারে।" },
        { en: "She is good at English and afraid of dogs.", bn: "সে ইংরেজিতে ভালো আর কুকুরকে ভয় পায়।" },
      ],
      say: [
        { q: "বইটা টেবিলের উপরে।", a: "The book is on the table." },
        { q: "বেড়ালটা বাক্সের ভিতরে।", a: "The cat is in the box." },
        { q: "আমরা গেটে দেখা করব।", a: "We will meet at the gate." },
        { q: "আমার জন্মদিন মার্চে।", a: "My birthday is in March." },
        { q: "ম্যাচ শুক্রবারে।", a: "The match is on Friday." },
        { q: "সে অঙ্কে ভালো।", a: "He is good at maths." },
      ],
      gaps: [
        { text: "The match starts ___ 3 o'clock.", bn: "ম্যাচ তিনটায় শুরু।", options: ["in", "on", "at"], right: 2, why: { bn: "ঘড়ির সময়: at।", en: "Clock time: at." } },
        { text: "Rafi was born ___ 2012.", bn: "রাফি ২০১২ সালে জন্মেছে।", options: ["in", "on", "at"], right: 0, why: { bn: "বছর: in।", en: "A year: in." } },
        { text: "We have a holiday ___ Friday.", bn: "শুক্রবারে ছুটি।", options: ["in", "on", "at"], right: 1, why: { bn: "দিন: on।", en: "A day: on." } },
        { text: "Nanu is afraid ___ lizards.", bn: "নানু টিকটিকিকে ভয় পান।", options: ["from", "of", "with"], right: 1, why: { bn: "afraid of।", en: "Afraid of." } },
        { text: "I go to bed ___ night.", bn: "আমি রাতে ঘুমাতে যাই।", options: ["in", "on", "at"], right: 2, why: { bn: "at night।", en: "At night." } },
        { text: "We are ___ the bus.", bn: "আমরা বাসে।", options: ["in", "on", "at"], right: 1, why: { bn: "বাসে হাঁটা যায়: on the bus।", en: "You can walk on a bus: on the bus." } },
      ],
      heart: {
        en: "Write where 5 things in your room are, and when 3 things in your week happen.",
        bn: "ঘরের পাঁচটা জিনিস কোথায়, আর সপ্তাহের তিনটা কাজ কখন।",
      },
    },
    {
      n: 12,
      en: "Are you ready? Sit down. What a shot!",
      bn: "চার জাতের বাক্য",
      pattern: {
        shape: "Rafi plays. · Does Rafi play? · Play! · What a shot!",
        why: "বলা: কর্তা আগে। জিজ্ঞেস: সাহায্যকারী আগে, নইলে do বসাও। আদেশ: কর্তা নেই, ক্রিয়া দিয়ে শুরু। চমক: What a + noun, How + adjective।",
        examples: "Is Nanu telling a story? · Tell us a story, Nanu. · What a story that was!",
        tip: "বাংলায় সুরে প্রশ্ন, ইংরেজিতে শব্দ নড়াতে হয়।",
      },
      watch: [
        { en: "You are ready. Are you ready?", bn: "তুমি প্রস্তুত। তুমি কি প্রস্তুত?" },
        { en: "Rafi likes mangoes. Does Rafi like mangoes?", bn: "রাফি আম পছন্দ করে। রাফি কি আম পছন্দ করে?" },
        { en: "Please open the window.", bn: "জানালাটা খোলো তো।" },
        { en: "Don't shout in the library.", bn: "লাইব্রেরিতে চেঁচিও না।" },
        { en: "What a beautiful morning!", bn: "কী সুন্দর সকাল!" },
      ],
      say: [
        { q: "তুমি কি ক্ষুধার্ত?", a: "Are you hungry?" },
        { q: "সে কি সাঁতার পারে?", a: "Can she swim?" },
        { q: "তারা কি ম্যাচ জিতেছে?", a: "Did they win the match?" },
        { q: "দরজাটা বন্ধ করো।", a: "Close the door." },
        { q: "দেরি কোরো না।", a: "Don't be late." },
        { q: "কী দারুণ ক্যাচ!", a: "What a catch!" },
      ],
      gaps: [
        { text: "___ you like ice cream?", bn: "তুমি কি আইসক্রিম পছন্দ করো?", options: ["Are", "Do", "Is"], right: 1, why: { bn: "সাধারণ ক্রিয়া, do দিয়ে প্রশ্ন।", en: "An ordinary verb, so do." } },
        { text: "___ a lovely day it is!", bn: "কী সুন্দর দিন!", options: ["How", "What", "Which"], right: 1, why: { bn: "a + noun: What।", en: "A + noun: What." } },
        { text: "___ kind of you!", bn: "কী দয়ালু তুমি!", options: ["What", "How", "So"], right: 1, why: { bn: "শুধু adjective: How।", en: "Adjective alone: How." } },
        { text: "___ late for the exam.", bn: "পরীক্ষায় দেরি কোরো না।", options: ["Not be", "Don't be", "No be"], right: 1, why: { bn: "Don't + খালি ক্রিয়া।", en: "Don't + bare verb." } },
        { text: "___ she come yesterday?", bn: "সে কি কাল এসেছিল?", options: ["Does", "Did", "Was"], right: 1, why: { bn: "অতীত, সাধারণ ক্রিয়া: Did।", en: "Past, ordinary verb: Did." } },
        { text: "___ go to the field!", bn: "চলো মাঠে যাই!", options: ["Let's", "Lets", "Let us to"], right: 0, why: { bn: "Let's + খালি ক্রিয়া।", en: "Let's + bare verb." } },
      ],
      heart: {
        en: "Write one sentence of each kind about your day: a statement, a question, a command, an exclamation.",
        bn: "নিজের দিন নিয়ে চার জাতের একটা করে বাক্য।",
      },
    },
    {
      n: 13,
      en: "have + V3",
      bn: "সেতু-কাল",
      pattern: {
        shape: "have / has + V3 · already, yet, just, ever, never",
        why: "অতীতে শুরু, এখনের সাথে যোগ: ফল এখনো আছে, জীবনের অভিজ্ঞতা, বা এখনো চলছে। বন্ধ সময়ের শব্দ (yesterday, ago) দেখলে সেতু নয়, past simple।",
        examples: "I have finished. · Have you ever seen a live match? · I have lost my keys.",
        tip: "yesterday-র সাথে have seen নয়, saw।",
      },
      watch: [
        { en: "I have finished my homework.", bn: "আমি হোমওয়ার্ক শেষ করেছি।" },
        { en: "Have you ever seen a live match?", bn: "তুমি কি কখনো মাঠে ম্যাচ দেখেছ?" },
        { en: "I have lost my keys.", bn: "আমি চাবি হারিয়ে ফেলেছি।" },
        { en: "She has just left.", bn: "সে এইমাত্র চলে গেল।" },
        { en: "I have never been to Sylhet.", bn: "আমি কখনো সিলেটে যাইনি।" },
      ],
      say: [
        { q: "আমি খেয়েছি।", a: "I have eaten." },
        { q: "সে এইমাত্র এসেছে।", a: "He has just arrived." },
        { q: "তুমি কি কখনো বিমানে চড়েছ?", a: "Have you ever flown in a plane?" },
        { q: "আমি কখনো সাপ দেখিনি।", a: "I have never seen a snake." },
        { q: "তারা এরই মধ্যে ম্যাচ জিতেছে।", a: "They have already won the match." },
        { q: "আমি কাল তাকে দেখেছি।", a: "I saw him yesterday." },
      ],
      gaps: [
        { text: "Mitu ___ her homework already.", bn: "মিতু এরই মধ্যে হোমওয়ার্ক শেষ করেছে।", options: ["finished", "has finished", "finishes"], right: 1, why: { bn: "already: has finished।", en: "Already: has finished." } },
        { text: "I ___ that film last night.", bn: "আমি কাল রাতে সিনেমাটা দেখেছি।", options: ["have seen", "saw", "see"], right: 1, why: { bn: "last night বন্ধ সময়: saw।", en: "Last night is closed: saw." } },
        { text: "Have you ___ eaten hilsa?", bn: "তুমি কি কখনো ইলিশ খেয়েছ?", options: ["ever", "yet", "ago"], right: 0, why: { bn: "জীবনের অভিজ্ঞতা: ever।", en: "Life experience: ever." } },
        { text: "She has ___ left.", bn: "সে এইমাত্র চলে গেছে।", options: ["just", "yesterday", "ago"], right: 0, why: { bn: "এইমাত্র: just।", en: "Just now: just." } },
        { text: "I have never ___ snow.", bn: "আমি কখনো বরফ দেখিনি।", options: ["see", "saw", "seen"], right: 2, why: { bn: "have-এর পরে V3: seen।", en: "After have, V3: seen." } },
        { text: "Rafi ___ a century twice.", bn: "রাফি দুবার সেঞ্চুরি করেছে।", options: ["has scored", "have scored", "scores"], right: 0, why: { bn: "একজন: has scored।", en: "One person: has scored." } },
      ],
      heart: {
        en: "Write 3 things you have done in your life and 2 you have never done.",
        bn: "জীবনে যা করেছ তিনটা, আর কখনো করোনি দুটো।",
      },
    },
    {
      n: 14,
      en: "had + V3, since / for",
      bn: "অতীতের আগের অতীত",
      pattern: {
        shape: "had + V3 (আগেরটা) · since + শুরু · for + কতক্ষণ",
        why: "দুটো অতীত ঘটনার আগেরটা had + V3। since-এর পরে শুরুর বিন্দু, for-এর পরে সময়ের দৈর্ঘ্য। কতক্ষণ ধরে চলছে হলে have been + -ing।",
        examples: "The match had started when I arrived. · since 1985 · for forty years · It has been raining since morning.",
        tip: "since two days নয়, for two days।",
      },
      watch: [
        { en: "When I reached the stadium, the match had started.", bn: "স্টেডিয়ামে পৌঁছে দেখি ম্যাচ শুরু হয়ে গেছে।" },
        { en: "Nanu has lived here since 1985.", bn: "নানু ১৯৮৫ থেকে এখানে থাকেন।" },
        { en: "We have known each other for ten years.", bn: "আমরা দশ বছর ধরে একে অপরকে চিনি।" },
        { en: "It has been raining since morning.", bn: "সকাল থেকে বৃষ্টি হচ্ছে।" },
        { en: "He was sad because he had missed the bus.", bn: "সে দুঃখিত ছিল, কারণ বাস মিস করেছিল।" },
      ],
      say: [
        { q: "আমরা পৌঁছানোর আগেই সিনেমা শুরু হয়ে গিয়েছিল।", a: "The film had started before we arrived." },
        { q: "সে দুই বছর ধরে ঢাকায় থাকে।", a: "She has lived in Dhaka for two years." },
        { q: "আমি ২০২০ থেকে ইংরেজি শিখছি।", a: "I have been learning English since 2020." },
        { q: "সে খেয়ে নিয়েছিল, তাই ক্ষুধার্ত ছিল না।", a: "He had eaten, so he was not hungry." },
        { q: "মিতু তিন ঘণ্টা ধরে পড়ছে।", a: "Mitu has been studying for three hours." },
        { q: "তারা আগেই চলে গিয়েছিল।", a: "They had already left." },
      ],
      gaps: [
        { text: "When we arrived, the film ___.", bn: "আমরা পৌঁছাতে সিনেমা শুরু হয়ে গিয়েছিল।", options: ["started", "has started", "had started"], right: 2, why: { bn: "আগের অতীত: had started।", en: "The earlier past: had started." } },
        { text: "Nanu has lived here ___ 1985.", bn: "নানু ১৯৮৫ থেকে এখানে থাকেন।", options: ["since", "for", "from"], right: 0, why: { bn: "শুরুর বিন্দু: since।", en: "Starting point: since." } },
        { text: "I have waited ___ two hours.", bn: "আমি দুই ঘণ্টা ধরে অপেক্ষা করছি।", options: ["since", "for", "during"], right: 1, why: { bn: "দৈর্ঘ্য: for।", en: "A length of time: for." } },
        { text: "It ___ raining since morning.", bn: "সকাল থেকে বৃষ্টি হচ্ছে।", options: ["is", "has been", "was"], right: 1, why: { bn: "কতক্ষণ ধরে, চলছে: has been raining।", en: "How long, still going: has been raining." } },
        { text: "By next June, Rafi ___ fifteen.", bn: "আগামী জুনের মধ্যে রাফির পনেরো হয়ে যাবে।", options: ["will turn", "will have turned", "has turned"], right: 1, why: { bn: "by + ভবিষ্যৎ: will have turned।", en: "By + future: will have turned." } },
        { text: "The patient ___ before the doctor came.", bn: "ডাক্তার আসার আগেই রোগী মারা গিয়েছিল।", options: ["died", "had died", "has died"], right: 1, why: { bn: "before, আগেরটা: had died।", en: "Before, the earlier one: had died." } },
      ],
      heart: {
        en: "Write about something you have done for a long time: since when, for how long, and what had happened before you started.",
        bn: "অনেক দিন ধরে যা করছ: কবে থেকে, কতদিন ধরে, আর শুরুর আগে কী হয়েছিল।",
      },
    },
    {
      n: 15,
      en: "can, must, should",
      bn: "শক্তির শব্দ",
      pattern: {
        shape: "WHO + can / must / should / may + VERB (খালি)",
        why: "modal-এর পরে ক্রিয়া সবসময় খালি: to নয়, -s নয়। can পারা, must লাগবেই, should উচিত, may হতে পারে। must not নিষেধ, don't have to দরকার নেই।",
        examples: "Rafi can bowl. · You must wear a helmet. · You should sleep early. · Could you help me?",
        tip: "She can sings নয়, She can sing।",
      },
      watch: [
        { en: "Rafi can bowl fast.", bn: "রাফি জোরে বল করতে পারে।" },
        { en: "You must wear a helmet while batting.", bn: "ব্যাট করার সময় হেলমেট পরতেই হবে।" },
        { en: "You should sleep early before an exam.", bn: "পরীক্ষার আগে তাড়াতাড়ি ঘুমানো উচিত।" },
        { en: "Could you pass the salt, please?", bn: "লবণটা একটু দেবে?" },
        { en: "It may rain later.", bn: "পরে বৃষ্টি হতে পারে।" },
      ],
      say: [
        { q: "আমি সাঁতার পারি।", a: "I can swim." },
        { q: "তোমাকে এখনই যেতে হবে।", a: "You must go now." },
        { q: "তোমার বিশ্রাম নেওয়া উচিত।", a: "You should rest." },
        { q: "আমি কি ভিতরে আসতে পারি?", a: "May I come in?" },
        { q: "নানু ছোটবেলায় গাছে চড়তে পারতেন।", a: "Nanu could climb trees as a girl." },
        { q: "তোমার আমাকে বলা উচিত ছিল।", a: "You should have told me." },
      ],
      gaps: [
        { text: "You ___ wear a helmet. It is the rule.", bn: "হেলমেট পরতেই হবে। নিয়ম।", options: ["can", "must", "might"], right: 1, why: { bn: "নিয়ম: must।", en: "A rule: must." } },
        { text: "It is a holiday. You ___ go to school.", bn: "ছুটি। স্কুলে যাওয়ার দরকার নেই।", options: ["must not", "don't have to", "should not"], right: 1, why: { bn: "দরকার নেই: don't have to।", en: "No need: don't have to." } },
        { text: "She can ___ very well.", bn: "সে খুব ভালো গাইতে পারে।", options: ["sings", "sing", "to sing"], right: 1, why: { bn: "modal + খালি।", en: "Modal + bare verb." } },
        { text: "The ground is wet. It ___ have rained.", bn: "মাঠ ভেজা। নিশ্চয়ই বৃষ্টি হয়েছে।", options: ["must", "can", "should"], right: 0, why: { bn: "নিশ্চিত অনুমান: must have।", en: "A sure guess: must have." } },
        { text: "___ I have some water, please?", bn: "আমি কি একটু পানি পেতে পারি?", options: ["Must", "May", "Should"], right: 1, why: { bn: "ভদ্র অনুরোধ: May I।", en: "A polite request: May I." } },
        { text: "You ___ have called me. I waited!", bn: "তোমার ফোন করা উচিত ছিল। আমি অপেক্ষা করেছি!", options: ["should", "can", "may"], right: 0, why: { bn: "আফসোস: should have।", en: "Regret: should have." } },
      ],
      heart: {
        en: "Write 5 rules of your home or school with must, must not and should.",
        bn: "বাসা বা স্কুলের পাঁচটা নিয়ম must, must not আর should দিয়ে।",
      },
    },
    {
      n: 16,
      en: "Where does she play? It's hot, isn't it?",
      bn: "প্রশ্ন-মেশিন আর লেজ",
      pattern: {
        shape: "(Wh-) + HELPER + WHO + VERB …? · …, isn't it?",
        why: "সাহায্যকারী কর্তার আগে, নইলে do। wh-শব্দ সবার আগে। লেজ: বাক্য হ্যাঁ হলে লেজ না, একই সাহায্যকারী, কর্তা pronoun।",
        examples: "Does Rafi play? · Where does Rafi play? · Rafi can bowl, can't he? · Nanu doesn't drive, does she?",
        tip: "Does he plays? দুই টুপি, ভুল।",
      },
      watch: [
        { en: "Where does Rafi play?", bn: "রাফি কোথায় খেলে?" },
        { en: "How long have you lived here?", bn: "তুমি কতদিন ধরে এখানে থাকো?" },
        { en: "Who taught you this?", bn: "কে তোমাকে এটা শেখাল?" },
        { en: "It is hot today, isn't it?", bn: "আজ গরম, তাই না?" },
        { en: "Nanu doesn't like loud music, does she?", bn: "নানু জোরে গান পছন্দ করেন না, তাই না?" },
      ],
      say: [
        { q: "তুমি কোথায় থাকো?", a: "Where do you live?" },
        { q: "সে কখন আসবে?", a: "When will she come?" },
        { q: "কে জানালা ভাঙল?", a: "Who broke the window?" },
        { q: "তুমি ক্লান্ত, তাই না?", a: "You are tired, aren't you?" },
        { q: "সে আসেনি, তাই না?", a: "He didn't come, did he?" },
        { q: "চলো শুরু করি, কেমন?", a: "Let's start, shall we?" },
      ],
      gaps: [
        { text: "___ Mitu study at night?", bn: "মিতু কি রাতে পড়ে?", options: ["Do", "Does", "Is"], right: 1, why: { bn: "একজন, সাধারণ ক্রিয়া: Does।", en: "One person, ordinary verb: Does." } },
        { text: "Where ___ you yesterday?", bn: "তুমি কাল কোথায় ছিলে?", options: ["was", "were", "did"], right: 1, why: { bn: "be উল্টে: were you।", en: "Invert be: were you." } },
        { text: "___ broke the window?", bn: "কে জানালা ভাঙল?", options: ["Who did", "Who", "Did who"], right: 1, why: { bn: "who নিজেই কর্তা।", en: "Who is the subject." } },
        { text: "Rafi can swim, ___?", bn: "রাফি সাঁতার পারে, তাই না?", options: ["can he", "can't he", "doesn't he"], right: 1, why: { bn: "হ্যাঁ-বাক্য, না-লেজ: can't he।", en: "Positive sentence, negative tag: can't he." } },
        { text: "I am late, ___?", bn: "আমি দেরি করেছি, তাই না?", options: ["amn't I", "aren't I", "am I"], right: 1, why: { bn: "রেবেল লেজ: aren't I।", en: "The rebel tag: aren't I." } },
        { text: "Could you tell me where ___?", bn: "স্টেশনটা কোথায় বলতে পারবেন?", options: ["is the station", "the station is", "does the station"], right: 1, why: { bn: "পরোক্ষ প্রশ্নে সোজা ক্রম।", en: "Indirect questions keep plain order." } },
      ],
      heart: {
        en: "Write 6 questions you would ask a famous cricketer, one for each wh-word.",
        bn: "একজন বিখ্যাত ক্রিকেটারকে ছয়টা প্রশ্ন, প্রতিটা wh-শব্দ দিয়ে একটা।",
      },
    },
    {
      n: 17,
      en: "because, so, although",
      bn: "বাক্য জোড়া",
      pattern: {
        shape: "SENTENCE, and / but / so SENTENCE · Because / Although SENTENCE, SENTENCE",
        why: "and, but, so দুটো সমান বাক্যের মাঝে, আগে কমা। because, although, when একটাকে অধীন করে; শুরুতে বসলে শেষে কমা। একটা জোড়ায় একটাই জোড়ার শব্দ।",
        examples: "It rained, so we stayed home. · Although he was tired, he kept bowling. · Call me when you get home.",
        tip: "Although … but কখনো নয়।",
      },
      watch: [
        { en: "Rafi bowled well, but the team lost.", bn: "রাফি ভালো বল করল, কিন্তু দল হারল।" },
        { en: "It was raining, so we stayed home.", bn: "বৃষ্টি হচ্ছিল, তাই আমরা বাসায় থাকলাম।" },
        { en: "Although he was tired, Rafi kept practising.", bn: "যদিও ক্লান্ত, রাফি অনুশীলন চালিয়ে গেল।" },
        { en: "Call me when you get home.", bn: "বাসায় পৌঁছে ফোন কোরো।" },
        { en: "Wait here until I come back.", bn: "আমি ফিরে না আসা পর্যন্ত এখানে অপেক্ষা করো।" },
      ],
      say: [
        { q: "আমি ক্লান্ত, তাই আমি ঘুমাব।", a: "I am tired, so I will sleep." },
        { q: "সে দেরি করল, কারণ বাস নষ্ট হয়েছিল।", a: "He was late because the bus broke down." },
        { q: "যদিও গরম ছিল, আমরা খেললাম।", a: "Although it was hot, we played." },
        { q: "আমি পৌঁছে তোমাকে ফোন করব।", a: "I will call you when I arrive." },
        { q: "চা বা কফি, যেকোনো একটা।", a: "Either tea or coffee." },
        { q: "তাড়াতাড়ি না করলে বাস মিস করবে।", a: "Unless you hurry, you will miss the bus." },
      ],
      gaps: [
        { text: "Rafi was late ___ the bus broke down.", bn: "বাস নষ্ট হওয়ায় রাফির দেরি হলো।", options: ["so", "because", "although"], right: 1, why: { bn: "কারণ: because।", en: "Reason: because." } },
        { text: "The bus broke down, ___ Rafi was late.", bn: "বাস নষ্ট হলো, তাই রাফির দেরি।", options: ["so", "because", "but"], right: 0, why: { bn: "ফল: so।", en: "Result: so." } },
        { text: "___ it was hot, we played the whole match.", bn: "যদিও গরম, আমরা পুরো ম্যাচ খেললাম।", options: ["Because", "Although", "So"], right: 1, why: { bn: "বিপরীত: Although।", en: "Contrast: Although." } },
        { text: "Wait here ___ I come back.", bn: "আমি ফিরে না আসা পর্যন্ত অপেক্ষা করো।", options: ["until", "unless", "while"], right: 0, why: { bn: "যতক্ষণ না: until।", en: "Up to when: until." } },
        { text: "You will miss the bus ___ you hurry.", bn: "তাড়াতাড়ি না করলে বাস মিস করবে।", options: ["if", "unless", "although"], right: 1, why: { bn: "না করলে: unless।", en: "If not: unless." } },
        { text: "___ Tamim nor Shakib played that day.", bn: "তামিম বা শাকিব কেউই সেদিন খেলেনি।", options: ["Either", "Neither", "Both"], right: 1, why: { bn: "nor-এর জোড়া neither।", en: "Nor pairs with neither." } },
      ],
      heart: {
        en: "Tell the story of your day in one long sentence with because, so and but.",
        bn: "নিজের দিনের গল্প এক লম্বা বাক্যে, because, so আর but দিয়ে।",
      },
    },
    {
      n: 18,
      en: "was broken by",
      bn: "উল্টানো বাক্য",
      pattern: {
        shape: "OBJECT + be + V3 (+ by SUBJECT)",
        why: "কর্ম সামনে, be ক্রিয়ার কালে, V3, দরকার হলে by কর্তা। -ing দেখলে being, have দেখলে been, will/must দেখলে be। কর্তা people, someone হলে বাদ।",
        examples: "The window was broken by Rafi. · My bike was stolen. · A bridge is being built. · Phones must be switched off.",
        tip: "was broke নয়, was broken: V3।",
      },
      watch: [
        { en: "The window was broken by Rafi.", bn: "জানালাটা রাফির দ্বারা ভাঙা হলো।" },
        { en: "My bike was stolen last night.", bn: "কাল রাতে আমার সাইকেল চুরি হয়েছে।" },
        { en: "Rice is grown in Bangladesh.", bn: "বাংলাদেশে ধান চাষ হয়।" },
        { en: "The road is being repaired.", bn: "রাস্তা সারানো হচ্ছে।" },
        { en: "The results will be announced on Sunday.", bn: "ফল রবিবার ঘোষণা হবে।" },
      ],
      say: [
        { q: "চিঠিটা কাল লেখা হয়েছিল।", a: "The letter was written yesterday." },
        { q: "এখানে ইংরেজি বলা হয়।", a: "English is spoken here." },
        { q: "আমার ফোন সারানো হয়েছে।", a: "My phone has been repaired." },
        { q: "ম্যাচটা বাতিল করা হয়েছে।", a: "The match has been cancelled." },
        { q: "একটা নতুন স্কুল বানানো হচ্ছে।", a: "A new school is being built." },
        { q: "হোমওয়ার্ক সময়মতো জমা দিতে হবে।", a: "Homework must be submitted on time." },
      ],
      gaps: [
        { text: "The letter ___ written yesterday.", bn: "চিঠিটা কাল লেখা হয়েছিল।", options: ["is", "was", "has been"], right: 1, why: { bn: "yesterday: was।", en: "Yesterday: was." } },
        { text: "A new school ___ built near us now.", bn: "আমাদের কাছে এখন একটা স্কুল বানানো হচ্ছে।", options: ["is being", "is", "has been"], right: 0, why: { bn: "চলছে: is being built।", en: "In progress: is being built." } },
        { text: "The match ___ cancelled because of rain.", bn: "বৃষ্টির কারণে ম্যাচ বাতিল হয়েছে।", options: ["has been", "is being", "will be"], right: 0, why: { bn: "হয়ে গেছে: has been।", en: "Done: has been." } },
        { text: "Homework must ___ on time.", bn: "হোমওয়ার্ক সময়মতো জমা দিতে হবে।", options: ["submit", "be submitted", "submitted"], right: 1, why: { bn: "modal + be + V3।", en: "Modal + be + V3." } },
        { text: "The window was ___ by Rafi.", bn: "জানালাটা রাফি ভেঙেছে।", options: ["broke", "broken", "breaking"], right: 1, why: { bn: "V3: broken।", en: "V3: broken." } },
        { text: "The children ___ given new books every year.", bn: "বাচ্চাদের প্রতি বছর নতুন বই দেওয়া হয়।", options: ["is", "are", "was"], right: 1, why: { bn: "children অনেক, every year: are।", en: "Children are many, every year: are." } },
      ],
      heart: {
        en: "Write 4 pieces of news from your area in the passive: was opened, was built, has been repaired…",
        bn: "নিজের এলাকার চারটা খবর passive-এ: was opened, was built, has been repaired…",
      },
    },
    {
      n: 19,
      en: "She said that she was busy.",
      bn: "কথা বহন",
      pattern: {
        shape: "X said, \"I VERB …\" → X said that he / she VERB-ed …",
        why: "উদ্ধৃতি যায়, that আসে, কাল এক ধাপ পিছোয়, I হয় he/she, today হয় that day। প্রশ্নে asked আর সোজা ক্রম, আদেশে told + to।",
        examples: "Mitu said that she was busy. · She asked me where I lived. · Coach told us not to be late.",
        tip: "tell-এর পরে কাকে; say-এর পরে that।",
      },
      watch: [
        { en: "Mitu said that she was busy that day.", bn: "মিতু বলল যে সে সেদিন ব্যস্ত।" },
        { en: "Rafi said that he would win.", bn: "রাফি বলল যে সে জিতবে।" },
        { en: "She asked me where I lived.", bn: "সে জিজ্ঞেস করল আমি কোথায় থাকি।" },
        { en: "Coach told us not to be late.", bn: "কোচ আমাদের দেরি না করতে বললেন।" },
        { en: "The teacher said that the sun rises in the east.", bn: "শিক্ষক বললেন সূর্য পূর্বে ওঠে।" },
      ],
      say: [
        { q: "সে বলল যে সে ক্লান্ত।", a: "He said that he was tired." },
        { q: "মা বললেন যে তিনি কাল আসবেন।", a: "Ma said that she would come the next day." },
        { q: "সে জিজ্ঞেস করল আমি সাঁতার পারি কি না।", a: "She asked if I could swim." },
        { q: "কোচ আমাদের রোজ অনুশীলন করতে বললেন।", a: "Coach told us to practise every day." },
        { q: "রাফি বলল যে সে চাবি হারিয়ে ফেলেছিল।", a: "Rafi said that he had lost his keys." },
        { q: "সে জিজ্ঞেস করল আমি কোথায় যাচ্ছি।", a: "He asked me where I was going." },
      ],
      gaps: [
        { text: "Rafi said, \"I am hungry.\" Rafi said that he ___ hungry.", bn: "রাফি বলল যে সে ক্ষুধার্ত।", options: ["is", "was", "had been"], right: 1, why: { bn: "am → was।", en: "Am becomes was." } },
        { text: "Mitu said she ___ call me the next day.", bn: "মিতু বলল সে পরদিন ফোন করবে।", options: ["will", "would", "can"], right: 1, why: { bn: "will → would।", en: "Will becomes would." } },
        { text: "He said that he ___ his keys.", bn: "সে বলল যে সে চাবি হারিয়ে ফেলেছিল।", options: ["lost", "had lost", "has lost"], right: 1, why: { bn: "lost → had lost।", en: "Lost becomes had lost." } },
        { text: "She asked ___ I was ready.", bn: "সে জিজ্ঞেস করল আমি প্রস্তুত কি না।", options: ["that", "if", "what"], right: 1, why: { bn: "হ্যাঁ/না প্রশ্ন: if।", en: "A yes/no question: if." } },
        { text: "Coach told us ___ every day.", bn: "কোচ আমাদের রোজ অনুশীলন করতে বললেন।", options: ["practise", "to practise", "practising"], right: 1, why: { bn: "আদেশ: told + to।", en: "A command: told + to." } },
        { text: "She ___ me that she was busy.", bn: "সে আমাকে বলল যে সে ব্যস্ত।", options: ["said", "told", "asked"], right: 1, why: { bn: "কাকে থাকলে told।", en: "With a person: told." } },
      ],
      heart: {
        en: "Report 4 things people said to you today: X said that… Y told me to…",
        bn: "আজ মানুষ তোমাকে যা বলেছে, চারটা বহন করো: X said that… Y told me to…",
      },
    },
    {
      n: 20,
      en: "If it rains, we will stay.",
      bn: "if-এর সিঁড়ি",
      pattern: {
        shape: "If + present, will · If + past (were), would · If + had V3, would have V3",
        why: "if-এর ঘরে কাল যত পিছনে, কথাটা তত কম সত্যি। present হতে পারে, past কল্পনা, past perfect হয়নি। if-এর ঘরে will বা would কখনো নয়।",
        examples: "If it rains, we will stay. · If I were you, I would apologise. · If we had won, we would have been champions.",
        tip: "if-এর ঘরে will: প্রবেশ নিষেধ।",
      },
      watch: [
        { en: "If it rains tomorrow, we will play indoors.", bn: "কাল বৃষ্টি হলে ঘরে খেলব।" },
        { en: "If I were Shakib, I would bowl the last over.", bn: "আমি শাকিব হলে শেষ ওভার করতাম।" },
        { en: "If we had won, we would have been champions.", bn: "জিতলে আমরা চ্যাম্পিয়ন হতাম।" },
        { en: "If you heat ice, it melts.", bn: "বরফ গরম করলে গলে।" },
        { en: "Unless you hurry, you will miss the train.", bn: "তাড়াতাড়ি না করলে ট্রেন মিস করবে।" },
      ],
      say: [
        { q: "বৃষ্টি হলে আমরা বাসায় থাকব।", a: "If it rains, we will stay home." },
        { q: "আমি তুমি হলে ক্ষমা চাইতাম।", a: "If I were you, I would apologise." },
        { q: "আমার টাকা থাকলে একটা ব্যাট কিনতাম।", a: "If I had money, I would buy a bat." },
        { q: "আমি পড়লে পাশ করতাম।", a: "If I had studied, I would have passed." },
        { q: "পানি গরম করলে ফোটে।", a: "If you heat water, it boils." },
        { q: "আমি যদি লম্বা হতাম।", a: "I wish I were taller." },
      ],
      gaps: [
        { text: "If you ___ hard, you will pass.", bn: "কঠোর পরিশ্রম করলে পাশ করবে।", options: ["work", "will work", "worked"], right: 0, why: { bn: "will অন্য দিকে, if-এ present।", en: "Will is on the other side, so present after if." } },
        { text: "If I ___ a bird, I would fly.", bn: "আমি পাখি হলে উড়তাম।", options: ["am", "was", "were"], right: 2, why: { bn: "কল্পনা: were।", en: "Imagined: were." } },
        { text: "If Rafi had practised, he ___ the match.", bn: "রাফি অনুশীলন করলে জিতত।", options: ["would win", "would have won", "will win"], right: 1, why: { bn: "তৃতীয় সিঁড়ি: would have won।", en: "Third step: would have won." } },
        { text: "If you mix red and blue, you ___ purple.", bn: "লাল আর নীল মেশালে বেগুনি হয়।", options: ["get", "will get", "would get"], right: 0, why: { bn: "চিরসত্য: get।", en: "Always true: get." } },
        { text: "___ you hurry, you will be late.", bn: "তাড়াতাড়ি না করলে দেরি হবে।", options: ["If", "Unless", "When"], right: 1, why: { bn: "না করলে: Unless।", en: "If not: Unless." } },
        { text: "If it ___ rain, we will play.", bn: "বৃষ্টি না হলে আমরা খেলব।", options: ["doesn't", "won't", "didn't"], right: 0, why: { bn: "if + present, না-বাচক: doesn't।", en: "If + present, negative: doesn't." } },
      ],
      heart: {
        en: "Write 3 ifs about your life: one possible, one imagined, one regret.",
        bn: "নিজের জীবনের তিনটা if: একটা সম্ভব, একটা কল্পনা, একটা আফসোস।",
      },
    },
    {
      n: 21,
      en: "enjoy playing, want to play",
      bn: "-ing নাকি to",
      pattern: {
        shape: "enjoy / finish / keep + -ing · want / hope / decide + to · make / let + VERB",
        why: "প্রথম ক্রিয়াই দ্বিতীয়টার রূপ ঠিক করে। to সামনে তাকায়, -ing কাজটাকে ছবি হিসেবে ধরে, make আর let-এর পরে খালি। preposition-এর পরে সবসময় -ing।",
        examples: "I enjoy playing. · I want to win. · Ma let me watch. · good at bowling",
        tip: "stop smoking = ছাড়া। stop to smoke = থামা।",
      },
      watch: [
        { en: "I enjoy playing, but I want to win.", bn: "খেলতে ভালোবাসি, কিন্তু জিততে চাই।" },
        { en: "Rafi finished eating and decided to go out.", bn: "রাফি খাওয়া শেষ করে বাইরে যাওয়ার সিদ্ধান্ত নিল।" },
        { en: "Ma let me watch the final.", bn: "মা আমাকে ফাইনাল দেখতে দিলেন।" },
        { en: "She is good at bowling and afraid of failing.", bn: "সে বোলিংয়ে ভালো আর ব্যর্থ হতে ভয় পায়।" },
        { en: "Remember to call Nanu tonight.", bn: "আজ রাতে নানুকে ফোন করতে মনে রেখো।" },
      ],
      say: [
        { q: "আমি গান শুনতে ভালোবাসি।", a: "I enjoy listening to music." },
        { q: "আমি ডাক্তার হতে চাই।", a: "I want to be a doctor." },
        { q: "সে ধূমপান ছেড়ে দিয়েছে।", a: "He has stopped smoking." },
        { q: "কোচ আমাদের দৌড় করালেন।", a: "Coach made us run." },
        { q: "দরজায় তালা দিতে ভুলো না।", a: "Don't forget to lock the door." },
        { q: "সাহায্যের জন্য ধন্যবাদ।", a: "Thank you for helping." },
      ],
      gaps: [
        { text: "Rafi enjoys ___ cricket.", bn: "রাফি ক্রিকেট খেলতে ভালোবাসে।", options: ["to play", "playing", "play"], right: 1, why: { bn: "enjoy + -ing।", en: "Enjoy + -ing." } },
        { text: "Mitu hopes ___ a doctor.", bn: "মিতু ডাক্তার হওয়ার আশা করে।", options: ["becoming", "to become", "become"], right: 1, why: { bn: "hope + to।", en: "Hope + to." } },
        { text: "Coach made us ___ ten laps.", bn: "কোচ আমাদের দশ চক্কর দৌড় করালেন।", options: ["to run", "running", "run"], right: 2, why: { bn: "make + খালি।", en: "Make + bare verb." } },
        { text: "He stopped ___ last year.", bn: "সে গত বছর ধূমপান ছেড়েছে।", options: ["to smoke", "smoking", "smoke"], right: 1, why: { bn: "ছাড়া: stop + -ing।", en: "Quitting: stop + -ing." } },
        { text: "She is interested ___ Japanese.", bn: "সে জাপানি শিখতে আগ্রহী।", options: ["to learn", "in learning", "learn"], right: 1, why: { bn: "preposition-এর পরে -ing।", en: "After a preposition, -ing." } },
        { text: "I look forward to ___ you.", bn: "তোমার সাথে দেখার অপেক্ষায় আছি।", options: ["meet", "meeting", "met"], right: 1, why: { bn: "এই to একটা preposition: meeting।", en: "This to is a preposition: meeting." } },
      ],
      heart: {
        en: "Write 3 things you enjoy doing and 3 things you want to do this year.",
        bn: "যা করতে ভালোবাসো তিনটা, আর এ বছর যা করতে চাও তিনটা।",
      },
    },
    {
      n: 22,
      en: "the boy who scored",
      bn: "বাক্যের ভিতরে বাক্য",
      pattern: {
        shape: "NOUN + who / which / that + CLAUSE · NAME, who …,",
        why: "যার কথা বলছ তার ঠিক পরে who বা which দিয়ে আরেকটা খবর। কমা ছাড়া চেনাচ্ছে কোনটা, কমা সহ বাড়তি খবর। whose কার, where জায়গা।",
        examples: "The boy who scored is sixteen. · Shakib, who captained the side, took three wickets. · the stadium where we met",
        tip: "নামের পরে সবসময় কমা।",
      },
      watch: [
        { en: "The boy who scored the century is sixteen.", bn: "যে ছেলেটা সেঞ্চুরি করল তার বয়স ষোলো।" },
        { en: "This is the bat which Rafi bought yesterday.", bn: "এটাই সেই ব্যাট যেটা রাফি কাল কিনেছে।" },
        { en: "Shakib, who captained the side, took three wickets.", bn: "শাকিব, যিনি অধিনায়ক ছিলেন, তিন উইকেট নিলেন।" },
        { en: "That is the girl whose brother plays for Khulna.", bn: "ওই সেই মেয়ে যার ভাই খুলনার হয়ে খেলে।" },
        { en: "This is the stadium where we watched the final.", bn: "এটাই সেই স্টেডিয়াম যেখানে আমরা ফাইনাল দেখেছিলাম।" },
      ],
      say: [
        { q: "আমার এক বন্ধু আছে যে লন্ডনে থাকে।", a: "I have a friend who lives in London." },
        { q: "এটা সেই গল্প যেটা নানু বলেছিলেন।", a: "This is the story that Nanu told." },
        { q: "যে বাড়িতে আমি জন্মেছি সেটা আর নেই।", a: "The house where I was born is gone." },
        { q: "ঢাকা, যেটা বুড়িগঙ্গার ধারে, খুব ভিড়।", a: "Dhaka, which is on the Buriganga, is crowded." },
        { q: "যে শিক্ষক আমাদের ইংরেজি পড়ান, তিনি খুব ভালো।", a: "The teacher who teaches us English is very good." },
        { q: "কাল যে সিনেমাটা দেখলাম, দারুণ ছিল।", a: "The film I saw yesterday was great." },
      ],
      gaps: [
        { text: "The man ___ lives next door is a pilot.", bn: "পাশের বাসার লোকটা পাইলট।", options: ["which", "who", "whose"], right: 1, why: { bn: "মানুষ: who।", en: "A person: who." } },
        { text: "The ball ___ broke the window was Rafi's.", bn: "যে বল জানালা ভাঙল সেটা রাফির।", options: ["who", "which", "whose"], right: 1, why: { bn: "জিনিস: which।", en: "A thing: which." } },
        { text: "Mitu, ___ is in class ten, has an exam.", bn: "মিতু, যে ক্লাস টেনে পড়ে, তার পরীক্ষা।", options: ["that", "who", "which"], right: 1, why: { bn: "কমা সহ: who, that নয়।", en: "With commas: who, not that." } },
        { text: "I met a girl ___ father is a singer.", bn: "এক মেয়ের সাথে পরিচয় হলো যার বাবা গায়ক।", options: ["who", "whose", "which"], right: 1, why: { bn: "কার: whose।", en: "Whose." } },
        { text: "This is the café ___ we first met.", bn: "এটাই সেই ক্যাফে যেখানে প্রথম দেখা।", options: ["which", "where", "when"], right: 1, why: { bn: "জায়গা: where।", en: "A place: where." } },
        { text: "The bat ___ I bought is red.", bn: "যে ব্যাটটা কিনেছি সেটা লাল।", options: ["which I bought it", "which", "who"], right: 1, why: { bn: "which একাই কর্ম, it বাড়তি।", en: "Which is already the object; it is extra." } },
      ],
      heart: {
        en: "Describe 3 people and 2 things in your life with who, which and whose.",
        bn: "জীবনের তিনজন মানুষ আর দুটো জিনিস, who, which আর whose দিয়ে।",
      },
    },
    {
      n: 23,
      en: "some, any, much, many, a few",
      bn: "কয়টা, কতটুকু",
      pattern: {
        shape: "many / few / a few + PLURAL · much / little / a little + UNCOUNTABLE · some (হ্যাঁ) / any (না, ?)",
        why: "গোনা যায় এমন জিনিসে many আর few, গোনা যায় না এমন জিনিসে much আর little। a few মানে আছে, few মানে প্রায় নেই। every-র পরে একবচন।",
        examples: "How many runs? How much time? · a few friends, few friends · some milk, isn't any milk",
        tip: "a থাকলে আধা গ্লাস ভরা, না থাকলে আধা খালি।",
      },
      watch: [
        { en: "There is some milk in the fridge.", bn: "ফ্রিজে কিছু দুধ আছে।" },
        { en: "There isn't any milk in the fridge.", bn: "ফ্রিজে কোনো দুধ নেই।" },
        { en: "I have a few friends and a little money.", bn: "আমার কয়েকজন বন্ধু আর একটু টাকা আছে।" },
        { en: "We don't have much time, so hurry.", bn: "সময় বেশি নেই, তাড়াতাড়ি করো।" },
        { en: "Every player has a number.", bn: "প্রতিটা খেলোয়াড়ের একটা নম্বর আছে।" },
      ],
      say: [
        { q: "তুমি কত রান করলে?", a: "How many runs did you score?" },
        { q: "কতটুকু সময় বাকি?", a: "How much time is left?" },
        { q: "আমার কয়েকজন বন্ধু আছে।", a: "I have a few friends." },
        { q: "আমার টাকা প্রায় নেই।", a: "I have little money." },
        { q: "ফ্রিজে কি দুধ আছে?", a: "Is there any milk in the fridge?" },
        { q: "প্রত্যেক ছাত্রকে কলম আনতে হবে।", a: "Every student must bring a pen." },
      ],
      gaps: [
        { text: "How ___ sugar do you take?", bn: "তুমি কতটুকু চিনি খাও?", options: ["many", "much", "few"], right: 1, why: { bn: "sugar গোনা যায় না: much।", en: "Sugar is uncountable: much." } },
        { text: "There are ___ people at the ground.", bn: "মাঠে অনেক মানুষ।", options: ["much", "many", "little"], right: 1, why: { bn: "people গোনা যায়: many।", en: "People are countable: many." } },
        { text: "Hurry! We have ___ time.", bn: "তাড়াতাড়ি! সময় প্রায় নেই।", options: ["a little", "little", "few"], right: 1, why: { bn: "প্রায় নেই: little।", en: "Hardly any: little." } },
        { text: "I have ___ friends who can help.", bn: "আমার কয়েকজন বন্ধু আছে যারা সাহায্য করতে পারে।", options: ["few", "a few", "little"], right: 1, why: { bn: "আছে, ভালো: a few।", en: "There are some, good: a few." } },
        { text: "I don't have ___ money with me.", bn: "আমার সাথে টাকা নেই।", options: ["some", "any", "many"], right: 1, why: { bn: "না-বাক্য: any।", en: "Negative: any." } },
        { text: "___ student must bring a pen.", bn: "প্রত্যেক ছাত্রকে কলম আনতে হবে।", options: ["Every", "All", "Many"], right: 0, why: { bn: "একবচন noun: Every।", en: "Singular noun: Every." } },
      ],
      heart: {
        en: "Open the fridge and write 5 sentences: some, any, a few, a little, much.",
        bn: "ফ্রিজ খুলে পাঁচ বাক্য: some, any, a few, a little, much।",
      },
    },
    {
      n: 24,
      en: "had my phone repaired",
      bn: "করা, নাকি করানো",
      pattern: {
        shape: "make / let / have + PERSON + VERB · get + PERSON + to VERB · have / get + THING + V3",
        why: "মাঝের শব্দটা মানুষ হলে তার পরে ক্রিয়া (get-এ to)। জিনিস হলে V3, কারণ জিনিসের উপর কাজ হয়। I had my hair cut মানে সেলুনে গেছি।",
        examples: "Coach made us run. · I got Rafi to help. · I had my phone repaired.",
        tip: "মানুষ হলে ক্রিয়া, জিনিস হলে V3।",
      },
      watch: [
        { en: "Coach made us run ten laps.", bn: "কোচ আমাদের দশ চক্কর দৌড় করালেন।" },
        { en: "Ma let me watch the final.", bn: "মা আমাকে ফাইনাল দেখতে দিলেন।" },
        { en: "I had the mechanic check the bike.", bn: "আমি মেকানিককে দিয়ে সাইকেল দেখালাম।" },
        { en: "I got Rafi to help me with the bags.", bn: "রাফিকে রাজি করিয়ে ব্যাগে সাহায্য নিলাম।" },
        { en: "I had my phone repaired yesterday.", bn: "কাল ফোনটা সারিয়ে নিয়েছি।" },
      ],
      say: [
        { q: "শিক্ষক আমাদের রচনা আবার লেখালেন।", a: "The teacher made us rewrite the essay." },
        { q: "বাবা আমাকে দেরি করে জাগতে দিলেন।", a: "Baba let me stay up late." },
        { q: "আমি চুল কাটিয়েছি।", a: "I had my hair cut." },
        { q: "আমরা বাড়িটা রং করিয়েছি।", a: "We got the house painted." },
        { q: "আমি আমার ভাইকে দিয়ে ফ্যানটা সারালাম।", a: "I had my brother fix the fan." },
        { q: "তোমার চোখ পরীক্ষা করানো উচিত।", a: "You should get your eyes tested." },
      ],
      gaps: [
        { text: "The teacher made us ___ the essay again.", bn: "শিক্ষক আমাদের রচনা আবার লেখালেন।", options: ["write", "to write", "written"], right: 0, why: { bn: "make + মানুষ + খালি।", en: "Make + person + bare verb." } },
        { text: "I got my cousin ___ me with maths.", bn: "কাজিনকে দিয়ে অঙ্কে সাহায্য করালাম।", options: ["help", "to help", "helped"], right: 1, why: { bn: "get + মানুষ + to।", en: "Get + person + to." } },
        { text: "We had the house ___ last month.", bn: "গত মাসে বাড়ি রং করিয়েছি।", options: ["paint", "to paint", "painted"], right: 2, why: { bn: "have + জিনিস + V3।", en: "Have + thing + V3." } },
        { text: "Ma didn't let me ___ out after dark.", bn: "মা সন্ধ্যার পর বাইরে যেতে দেননি।", options: ["go", "to go", "going"], right: 0, why: { bn: "let + খালি।", en: "Let + bare verb." } },
        { text: "Rafi is having his bat ___.", bn: "রাফি ব্যাট মেরামত করাচ্ছে।", options: ["repair", "repairing", "repaired"], right: 2, why: { bn: "জিনিস: V3।", en: "A thing: V3." } },
        { text: "The doctor advised Nanu ___ more.", bn: "ডাক্তার নানুকে আরও বিশ্রাম নিতে বললেন।", options: ["rest", "to rest", "resting"], right: 1, why: { bn: "advise + মানুষ + to।", en: "Advise + person + to." } },
      ],
      heart: {
        en: "Write 4 things you had done or got someone to do this month.",
        bn: "এ মাসে যা করিয়েছ বা কাউকে দিয়ে করিয়েছ, চারটা।",
      },
    },
    {
      n: 25,
      en: "Never have I seen…",
      bn: "উল্টে দিয়ে জোর",
      pattern: {
        shape: "Never / Not only + HELPER + WHO … · It was X who … · What I need is …",
        why: "না-বাচক শব্দ শুরুতে নিলে প্রশ্নের ক্রম। It was দিয়ে একটা অংশে আলো। What … is দিয়ে যা চাই সেটার উপরে।",
        examples: "Never have I seen such a catch! · It was Shakib who took the catch. · What I need is sleep.",
        tip: "Never I have seen: অর্ধেক উল্টানো, সবচেয়ে খারাপ।",
      },
      watch: [
        { en: "Never have I seen such a catch!", bn: "এমন ক্যাচ আমি কখনো দেখিনি!" },
        { en: "Not only did Shakib bat well, but he also bowled well.", bn: "শাকিব শুধু ব্যাটই নয়, বলও ভালো করল।" },
        { en: "It was Mustafiz who took the last wicket.", bn: "শেষ উইকেটটা মুস্তাফিজই নিয়েছিল।" },
        { en: "What I need now is a cup of tea.", bn: "এখন আমার যা দরকার তা এক কাপ চা।" },
        { en: "No sooner had the match started than it rained.", bn: "ম্যাচ শুরু হতে না হতেই বৃষ্টি।" },
      ],
      say: [
        { q: "এমন গল্প আমি কখনো শুনিনি!", a: "Never have I heard such a story!" },
        { q: "নানু-ই এই গল্পটা বলেছিলেন।", a: "It was Nanu who told this story." },
        { q: "আমি শুধু ঘুমাতে চাই।", a: "All I want is to sleep." },
        { q: "সে খুব কমই আমাদের দেখতে আসে।", a: "Seldom does she visit us." },
        { q: "আমার সত্যিই এটা পছন্দ।", a: "I do like it." },
        { q: "সে শুধু গানই গায় না, নাচেও।", a: "Not only does she sing, but she also dances." },
      ],
      gaps: [
        { text: "Never ___ such a beautiful sunset.", bn: "এমন সূর্যাস্ত কখনো দেখিনি।", options: ["I have seen", "have I seen", "I saw"], right: 1, why: { bn: "Never শুরুতে: have I seen।", en: "Never first: have I seen." } },
        { text: "Not only ___ the exam, but she topped the class.", bn: "সে শুধু পাশই নয়, প্রথমও হলো।", options: ["she passed", "did she pass", "she did pass"], right: 1, why: { bn: "did she pass।", en: "Did she pass." } },
        { text: "It was in 2007 ___ Bangladesh beat India.", bn: "২০০৭-এই বাংলাদেশ ভারতকে হারাল।", options: ["who", "that", "which"], right: 1, why: { bn: "সময়ের পরে that।", en: "After a time, that." } },
        { text: "Seldom ___ she visit us.", bn: "সে খুব কমই আমাদের দেখতে আসে।", options: ["does", "do", "is"], right: 0, why: { bn: "একজন, বর্তমান: does।", en: "One person, present: does." } },
        { text: "No sooner ___ the bell rung than they ran.", bn: "ঘণ্টা বাজতে না বাজতেই তারা দৌড়াল।", options: ["had", "has", "did"], right: 0, why: { bn: "No sooner had।", en: "No sooner had." } },
        { text: "___ I want is a cup of tea.", bn: "আমি শুধু এক কাপ চা চাই।", options: ["What", "All", "That"], right: 1, why: { bn: "শুধু: All I want।", en: "Only: All I want." } },
      ],
      heart: {
        en: "Write 3 Never have I… sentences and 2 It was … who … sentences about your life.",
        bn: "নিজের জীবনে তিনটা Never have I… আর দুটো It was … who …।",
      },
    },
    {
      n: 26,
      en: "Let's eat, Nanu.",
      bn: "কমা আর অ্যাপস্ট্রফি",
      pattern: {
        shape: "Let's eat, Nanu. · it's = it is · its = এর · two mangoes (কোনো ' নয়)",
        why: "কমা সম্বোধন আলাদা করে, তালিকা ভাগ করে, শুরুর অধীন অংশের পরে বসে। অ্যাপস্ট্রফি মালিকানা বা দুটো শব্দ জোড়া, কখনো বহুবচন নয়।",
        examples: "Although it rained, we played. · It's raining, and the cat is licking its paw. · Rafi's bat",
        tip: "it's দেখলে খুলে দেখো: it is হয় কি না।",
      },
      watch: [
        { en: "Let's eat, Nanu.", bn: "চলো খাই, নানু।" },
        { en: "It's raining, and the cat is licking its paw.", bn: "বৃষ্টি হচ্ছে, আর বেড়ালটা তার থাবা চাটছে।" },
        { en: "Although it rained, we played the whole match.", bn: "যদিও বৃষ্টি হলো, আমরা পুরো ম্যাচ খেললাম।" },
        { en: "Shakib, our captain, took three wickets.", bn: "শাকিব, আমাদের অধিনায়ক, তিন উইকেট নিলেন।" },
        { en: "We bought rice, dal, oil and salt.", bn: "আমরা চাল, ডাল, তেল আর লবণ কিনলাম।" },
      ],
      say: [
        { q: "হ্যাঁ, নানু, আসছি।", a: "Yes, Nanu, I am coming." },
        { q: "এটা রাফির ব্যাট।", a: "This is Rafi's bat." },
        { q: "বৃষ্টি হচ্ছে।", a: "It's raining." },
        { q: "কুকুরটা তার লেজ নাড়ল।", a: "The dog wagged its tail." },
        { q: "আমি দুটো আম কিনলাম।", a: "I bought two mangoes." },
        { q: "রাফি বল করে; মিতু ব্যাট করে।", a: "Rafi bowls; Mitu bats." },
      ],
      gaps: [
        { text: "The dog wagged ___ tail.", bn: "কুকুরটা তার লেজ নাড়ল।", options: ["it's", "its", "its'"], right: 1, why: { bn: "মালিকানা: its।", en: "Possession: its." } },
        { text: "___ going to rain tonight.", bn: "আজ রাতে বৃষ্টি হবে।", options: ["Its", "It's", "Its'"], right: 1, why: { bn: "It is: It's।", en: "It is: It's." } },
        { text: "I bought two ___.", bn: "দুটো আম কিনলাম।", options: ["mango's", "mangoes", "mangoes'"], right: 1, why: { bn: "বহুবচন, অ্যাপস্ট্রফি নয়।", en: "A plural, no apostrophe." } },
        { text: "This is the ___ changing room.", bn: "এটা খেলোয়াড়দের ড্রেসিং রুম।", options: ["players", "player's", "players'"], right: 2, why: { bn: "অনেকের: players'।", en: "Belonging to many: players'." } },
        { text: "Nanu has one rule ___ no phones at dinner.", bn: "নানুর একটা নিয়ম: খাওয়ার সময় ফোন নয়।", options: [",", ";", ":"], right: 2, why: { bn: "ব্যাখ্যা আসছে: কোলন।", en: "An explanation follows: a colon." } },
        { text: "It rained ___ we played anyway.", bn: "বৃষ্টি হলো, তবু খেললাম।", options: [",", ", but", " but,"], right: 1, why: { bn: "দুটো বাক্য: কমা + but।", en: "Two sentences: comma + but." } },
      ],
      heart: {
        en: "Write a paragraph about your family with at least 5 commas and 3 apostrophes, all in the right places.",
        bn: "পরিবার নিয়ে একটা অনুচ্ছেদ, অন্তত পাঁচটা কমা আর তিনটা অ্যাপস্ট্রফি, সব ঠিক জায়গায়।",
      },
    },
    {
      n: 27,
      en: "so … that, too … to",
      bn: "এত… যে",
      pattern: {
        shape: "so + adjective + that · such + a + noun + that · too + adjective + to · adjective + enough + to",
        why: "so বসে adjective-এর আগে, such বসে noun-এর আগে। so … that … not = too … to। enough বসে adjective-এর পরে।",
        examples: "He was so tired that he slept. · It was such a good film that we watched it twice. · too hot to drink · hot enough to drink",
        tip: "too মানে সমস্যা, very মানে শুধু অনেক।",
      },
      watch: [
        { en: "He was so tired that he fell asleep on the bus.", bn: "সে এত ক্লান্ত ছিল যে বাসেই ঘুমিয়ে পড়ল।" },
        { en: "It was such a good film that we watched it twice.", bn: "এত ভালো সিনেমা যে দুবার দেখলাম।" },
        { en: "The tea is too hot to drink.", bn: "চা-টা খাওয়ার পক্ষে খুব গরম।" },
        { en: "The tea is hot enough to drink now.", bn: "চা এখন খাওয়ার মতো গরম।" },
        { en: "Rafi is so fast that nobody can catch him.", bn: "রাফি এত দ্রুত যে কেউ ধরতে পারে না।" },
      ],
      say: [
        { q: "সে এত দুর্বল যে হাঁটতে পারে না।", a: "He is so weak that he cannot walk." },
        { q: "সে হাঁটার পক্ষে খুব দুর্বল।", a: "He is too weak to walk." },
        { q: "এত সুন্দর দিন যে আমরা বাইরে গেলাম।", a: "It was such a nice day that we went out." },
        { q: "বাক্সটা তোলার পক্ষে খুব ভারী।", a: "The box is too heavy to lift." },
        { q: "সে খুব ভালো খেলে।", a: "She plays very well." },
        { q: "আমি যথেষ্ট লম্বা।", a: "I am tall enough." },
      ],
      gaps: [
        { text: "Rafi is ___ fast that nobody can catch him.", bn: "রাফি এত দ্রুত যে কেউ ধরতে পারে না।", options: ["so", "such", "such a"], right: 0, why: { bn: "adjective: so।", en: "An adjective: so." } },
        { text: "It was ___ good film that we watched it twice.", bn: "এত ভালো সিনেমা যে দুবার দেখলাম।", options: ["so", "such", "such a"], right: 2, why: { bn: "a + noun: such a।", en: "A + noun: such a." } },
        { text: "The tea is too hot ___.", bn: "চা খাওয়ার পক্ষে খুব গরম।", options: ["to drink", "that drink", "for drink"], right: 0, why: { bn: "too … to + খালি।", en: "Too … to + bare verb." } },
        { text: "The tea is hot ___ to drink.", bn: "চা খাওয়ার মতো গরম।", options: ["enough", "too", "so"], right: 0, why: { bn: "যথেষ্ট, adjective-এর পরে: enough।", en: "Sufficiently, after the adjective: enough." } },
        { text: "He is so weak that he ___ walk.", bn: "সে এত দুর্বল যে হাঁটতে পারে না।", options: ["can", "cannot", "could"], right: 1, why: { bn: "too weak to walk-এর মানে: cannot।", en: "Same as too weak to walk: cannot." } },
        { text: "It was ___ weather that we stayed in.", bn: "এমন আবহাওয়া যে আমরা ঘরে থাকলাম।", options: ["so", "such", "such a"], right: 1, why: { bn: "weather গোনা যায় না: such, a নয়।", en: "Weather is uncountable: such, no a." } },
      ],
      heart: {
        en: "Write 3 so…that sentences about your day, then say each one again with too…to.",
        bn: "নিজের দিন নিয়ে তিনটা so…that, তারপর প্রতিটা too…to দিয়ে আবার।",
      },
    },
    {
      n: 28,
      en: "Unless you hurry…",
      bn: "পরীক্ষার হল: বদল",
      pattern: {
        shape: "unless ↔ if … not · the best ↔ better than any other ↔ no other … as … as · What a …! ↔ It was a …",
        why: "প্রতিটা transformation একটা ছাঁচ থেকে আরেকটায় যাওয়া, মানে একই রেখে। বদলের পর একটা প্রশ্ন: একই ঘটনা বলছে তো?",
        examples: "Unless you study, you will fail. = If you do not study, you will fail. · Shakib is the best. = No other player is as good as Shakib.",
        tip: "not হারিয়ে গেছে কি না, শেষে দেখো।",
      },
      watch: [
        { en: "Unless you study, you will fail. If you do not study, you will fail.", bn: "না পড়লে ফেল করবে।" },
        { en: "Shakib is the best all-rounder. No other all-rounder is as good as Shakib.", bn: "শাকিব সেরা অলরাউন্ডার।" },
        { en: "Shakib is better than any other all-rounder.", bn: "শাকিব অন্য যেকোনো অলরাউন্ডারের চেয়ে ভালো।" },
        { en: "It was a great match. What a great match it was!", bn: "দারুণ ম্যাচ ছিল। কী দারুণ ম্যাচই না ছিল!" },
        { en: "Everyone loves Nanu. There is no one who does not love Nanu.", bn: "সবাই নানুকে ভালোবাসে।" },
      ],
      say: [
        { q: "তাড়াতাড়ি না করলে দেরি হবে। (unless)", a: "Unless you hurry, you will be late." },
        { q: "তাড়াতাড়ি না করলে দেরি হবে। (if not)", a: "If you do not hurry, you will be late." },
        { q: "ঢাকা সবচেয়ে বড় শহর। (no other)", a: "No other city is as big as Dhaka." },
        { q: "কী সুন্দর দিন! (assertive)", a: "It is a beautiful day." },
        { q: "কে না তার দেশকে ভালোবাসে? (assertive)", a: "Everybody loves his country." },
        { q: "বাঘ দেখে সে দৌড়াল। (complex)", a: "When he saw the tiger, he ran." },
      ],
      gaps: [
        { text: "Unless you study, you will fail. = If you ___ study, you will fail.", bn: "না পড়লে ফেল।", options: ["do not", "do", "will not"], right: 0, why: { bn: "unless = if not।", en: "Unless equals if not." } },
        { text: "No other bowler is ___ Mustafiz.", bn: "আর কোনো বোলার মুস্তাফিজের মতো দ্রুত নয়।", options: ["faster than", "as fast as", "the fastest"], right: 1, why: { bn: "No other … as … as।", en: "No other … as … as." } },
        { text: "Mustafiz is ___ any other bowler.", bn: "মুস্তাফিজ অন্য যেকোনো বোলারের চেয়ে দ্রুত।", options: ["as fast as", "faster than", "the fastest"], right: 1, why: { bn: "… than any other।", en: "… than any other." } },
        { text: "What a great match it was! = It was ___ great match.", bn: "দারুণ ম্যাচ ছিল।", options: ["a", "such", "so"], right: 0, why: { bn: "assertive: a great match।", en: "Assertive: a great match." } },
        { text: "Who does not love his country? = ___ loves his country.", bn: "সবাই দেশকে ভালোবাসে।", options: ["Nobody", "Everybody", "Somebody"], right: 1, why: { bn: "Everybody।", en: "Everybody." } },
        { text: "Seeing the tiger, he ran. (complex) = ___ he saw the tiger, he ran.", bn: "বাঘ দেখে সে দৌড়াল।", options: ["When", "And", "But"], right: 0, why: { bn: "অধীন clause: When।", en: "A dependent clause: When." } },
      ],
      heart: {
        en: "Take 3 sentences from an old exam paper and transform each one two ways.",
        bn: "পুরনো একটা প্রশ্নপত্র থেকে তিনটা বাক্য নাও আর প্রতিটা দুই ভাবে বদলাও।",
      },
    },
    {
      n: 29,
      en: "narration and voice",
      bn: "পরীক্ষার হল: বহন আর উল্টানো",
      pattern: {
        shape: "said that + এক ধাপ পিছনে · asked if / wh + সোজা ক্রম · told + to · OBJECT + be + V3 + by",
        why: "narration: বলার ক্রিয়া, জোড়ার শব্দ, কাল পিছনে, pronoun আর সময় ঘোরাও। voice: কর্ম সামনে, be ক্রিয়ার কালে, V3, by কর্তা। দুটোই মেশিন, দুটোই ধাপে ধাপে।",
        examples: "He said that he was tired. · She asked me where I lived. · The window was broken by Rafi.",
        tip: "শেষে একবার পড়ো: প্রশ্নবোধক থেকে গেছে? V2 বসে গেছে?",
      },
      watch: [
        { en: "\"I am tired,\" he said. He said that he was tired.", bn: "সে বলল, আমি ক্লান্ত। সে বলল যে সে ক্লান্ত।" },
        { en: "\"Where do you live?\" she asked. She asked me where I lived.", bn: "সে জিজ্ঞেস করল আমি কোথায় থাকি।" },
        { en: "\"Don't be late,\" Coach said. Coach told us not to be late.", bn: "কোচ আমাদের দেরি না করতে বললেন।" },
        { en: "Rafi broke the window. The window was broken by Rafi.", bn: "রাফি জানালা ভাঙল। জানালাটা রাফির দ্বারা ভাঙা হলো।" },
        { en: "They are building a bridge. A bridge is being built.", bn: "তারা সেতু বানাচ্ছে। সেতু বানানো হচ্ছে।" },
      ],
      say: [
        { q: "সে বলল যে সে আসবে।", a: "She said that she would come." },
        { q: "সে জিজ্ঞেস করল আমি ব্যস্ত কি না।", a: "He asked if I was busy." },
        { q: "মা আমাকে দরজা বন্ধ করতে বললেন।", a: "Ma told me to close the door." },
        { q: "চিঠিটা লেখা হয়েছে।", a: "The letter has been written." },
        { q: "রাস্তা সারানো হচ্ছে।", a: "The road is being repaired." },
        { q: "দরজাটা খোলা হোক।", a: "Let the door be opened." },
      ],
      gaps: [
        { text: "He said, \"I will come.\" He said that he ___ come.", bn: "সে বলল যে সে আসবে।", options: ["will", "would", "can"], right: 1, why: { bn: "will → would।", en: "Will becomes would." } },
        { text: "She asked, \"Are you busy?\" She asked ___ I was busy.", bn: "সে জিজ্ঞেস করল আমি ব্যস্ত কি না।", options: ["that", "if", "when"], right: 1, why: { bn: "হ্যাঁ/না: if।", en: "Yes/no: if." } },
        { text: "Ma said, \"Close the door.\" Ma told me ___ the door.", bn: "মা আমাকে দরজা বন্ধ করতে বললেন।", options: ["close", "to close", "closing"], right: 1, why: { bn: "আদেশ: told + to।", en: "A command: told + to." } },
        { text: "Rafi broke the window. The window ___ by Rafi.", bn: "জানালাটা রাফি ভেঙেছে।", options: ["was broke", "was broken", "is broken"], right: 1, why: { bn: "অতীত, V3: was broken।", en: "Past, V3: was broken." } },
        { text: "They are building a bridge. A bridge ___.", bn: "একটা সেতু বানানো হচ্ছে।", options: ["is built", "is being built", "has been built"], right: 1, why: { bn: "-ing: being।", en: "-ing: being." } },
        { text: "Open the door. ___ the door be opened.", bn: "দরজাটা খোলা হোক।", options: ["Let", "Make", "Have"], right: 0, why: { bn: "আদেশের passive: Let।", en: "Passive of a command: Let." } },
      ],
      heart: {
        en: "Report a short conversation you had today (4 lines), then write 3 passive sentences about your school.",
        bn: "আজকের একটা ছোট কথোপকথন বহন করো (চার লাইন), তারপর নিজের স্কুল নিয়ে তিনটা passive বাক্য।",
      },
    },
    {
      n: 30,
      en: "The twenty-five traps",
      bn: "পঁচিশটা ফাঁদ, সব একসাথে",
      pattern: {
        shape: "I am a student · Are you ready? · for two days · Although …, … · enjoy playing · if it rains",
        why: "বেশিরভাগ ভুল বাংলার ছায়া: যা বাংলায় লুকায় ইংরেজিতে বলতে হয়, যা বাংলায় দুবার বসে ইংরেজিতে একবার। ছায়াটা চিনলেই সরানো যায়।",
        examples: "Rafi and I are good at English. · If it rains, we will stay. · I had my bat repaired.",
        tip: "পরীক্ষার আগের রাতে পুরো বই নয়, এই তালিকা।",
      },
      watch: [
        { en: "I am a student, and my sister is a doctor.", bn: "আমি ছাত্র, আর আমার বোন ডাক্তার।" },
        { en: "Rafi and I are good at English.", bn: "রাফি আর আমি ইংরেজিতে ভালো।" },
        { en: "She plays well, and she has played for two years.", bn: "সে ভালো খেলে, আর দুই বছর ধরে খেলছে।" },
        { en: "Does he play? He can play, but he doesn't play every day.", bn: "সে কি খেলে? পারে, কিন্তু রোজ খেলে না।" },
        { en: "If it rains, we will stay. Although it rained, we played.", bn: "বৃষ্টি হলে থাকব। যদিও বৃষ্টি হলো, খেললাম।" },
      ],
      say: [
        { q: "আমি ছাত্র।", a: "I am a student." },
        { q: "রাফি আর আমি গেলাম।", a: "Rafi and I went." },
        { q: "আমি তাকে কাল দেখেছি।", a: "I saw him yesterday." },
        { q: "সে দুই দিন ধরে অসুস্থ।", a: "She has been ill for two days." },
        { q: "যদিও সে গরিব, সে সৎ।", a: "Although he is poor, he is honest." },
        { q: "আমি খেলতে ভালোবাসি।", a: "I enjoy playing." },
      ],
      gaps: [
        { text: "I ___ a student.", bn: "আমি ছাত্র।", options: ["am", "is", "(nothing)"], right: 0, why: { bn: "লুকানো 'হয়' বলতে হয়: am। ফাঁদ ১।", en: "The hidden be must be said: am. Trap 1." } },
        { text: "Rafi and ___ went to the fair.", bn: "রাফি আর আমি মেলায় গেলাম।", options: ["me", "I", "my"], right: 1, why: { bn: "কর্তা: I। ফাঁদ ৩।", en: "Subject: I. Trap 3." } },
        { text: "I ___ him yesterday.", bn: "আমি তাকে কাল দেখেছি।", options: ["have seen", "saw", "see"], right: 1, why: { bn: "yesterday: saw। ফাঁদ ১২।", en: "Yesterday: saw. Trap 12." } },
        { text: "She has been ill ___ two days.", bn: "সে দুই দিন ধরে অসুস্থ।", options: ["since", "for", "from"], right: 1, why: { bn: "দৈর্ঘ্য: for। ফাঁদ ১৩।", en: "A length: for. Trap 13." } },
        { text: "Although he is poor, ___ he is honest.", bn: "যদিও গরিব, সে সৎ।", options: ["but", "(nothing)", "yet"], right: 1, why: { bn: "একটাই জোড়ার শব্দ। ফাঁদ ১৬।", en: "One joining word only. Trap 16." } },
        { text: "If it ___ tomorrow, we will stay home.", bn: "কাল বৃষ্টি হলে বাসায় থাকব।", options: ["will rain", "rains", "rained"], right: 1, why: { bn: "if-এর ঘরে will নয়। ফাঁদ ১৯।", en: "No will in the if clause. Trap 19." } },
      ],
      heart: {
        en: "Write a paragraph of 8 sentences about this month. Then read it as your own teacher and mark any trap you find.",
        bn: "এই মাস নিয়ে আট বাক্যের একটা অনুচ্ছেদ। তারপর নিজেই স্যার হয়ে পড়ো আর যে ফাঁদ পাও দাগ দাও।",
      },
    },
  ],
};
