/* ============================================================
   curriculum.js — the German school, in one file.

   THIS IS THE ONE FILE YOU EDIT to add, rename or reorder
   anything under /deutsch/. Everything else reads from it:

     /deutsch/index.html + hub.js     the ladder, the resume card
     /deutsch/<stufe>/index.html      generated by build-deutsch.mjs
     /deutsch/<stufe>/<teil>.html     generated by build-deutsch.mjs
     /crumbs.js                       the breadcrumb trail
     /content.js                      the Ctrl+K palette and the menu
     /build-meta.mjs                  sitemap.xml

   ------------------------------------------------------------
   WHY THIS IS NOT IN /learn/curriculum.js

   /learn/ is the money school: eight stages about investing in
   Bangladesh, with risk labels, broker warnings and a starter
   guide about opening a BO account. German shares none of that
   vocabulary. Mounting it there would have meant a reader
   looking for শেয়ার scrolling past Akkusativ, and a reader
   looking for Akkusativ scrolling past ব্রোকার.

   So it is a second school at its own mount, deliberately built
   from the same parts — the same ladder, the same lesson cards,
   the same tick-in-your-own-browser progress. Someone who has
   used the Learn area already knows how to use this one, and
   nothing here can break anything there.

   ------------------------------------------------------------
   THE SHAPE

   STUFEN[]              four stages, zero to speaking. A stage
                         is a folder and a page of its own.

     .sections[]         a heading inside a stage. Never a page.

       .teile[]          one page each. "Teil" is what the
                         course itself calls a chapter, so that
                         is what they are called here.

   Plus one thing the money school has no equivalent of: each
   Stufe has a WORKBOOK — thirty days of daily practice on a
   single page the learner writes into. See arbeitsbuch.data.js.

   ------------------------------------------------------------
   FIELDS

   stufe   slug     folder name, and the id progress is stored under
           kicker   the tiny label above the name ("Stufe 1")
           bn/en    the name, Bangla first
           de       the German name, because this is a German course
           icon     a key in /deutsch/icons.js
           who      who this stage is for, in one line
           blurb    what it teaches, two lines at most
           can      what you will be able to DO at the end of it —
                    the only promise a language course should make
           status   "live" | "soon"
           workbook { slug, days } when the stage has a practice book

   teil    slug     file name (no .html)
           bn/en    the title, Bangla first
           de       the German heading for it
           blurb    the one line on the card
           minutes  reading time
           status   "live" | "soon"
   ============================================================ */

/* ------------------------------------------------------------
   STUFE 1 — the deck that exists, chapter by chapter.
   ------------------------------------------------------------ */
const STUFE_1_SECTIONS = [
  {
    id: "anfangen",
    bn: "শুরুর আগে",
    en: "Before you begin",
    de: "Bevor wir anfangen",
    teile: [
      {
        slug: "anfang",
        bn: "শুরুর আগে: চারটা উপহার, ছয়টা নিয়ম",
        en: "Four gifts and six rules",
        de: "Bevor wir anfangen",
        icon: "gift",
        minutes: 8,
        blurb:
          "জার্মান ইংরেজির চেয়ে ভদ্র, আর সেটা কেন। ছয়টা নিয়ম যার একটা একদম নতুন, আর একটা ছাঁচ যেটা দিয়ে আজই হাজারটা বাক্য বলা যায়।",
      },
      {
        slug: "laute",
        bn: "ধ্বনি: যা লেখা, তাই বলা",
        en: "The sounds",
        de: "Die Laute",
        icon: "mouth",
        minutes: 11,
        blurb:
          "w মানে ভ, z মানে ৎস, ei মানে আই। এই এক পাতা শেখা হলে কোনোদিন না দেখা জার্মান শব্দও জোরে পড়তে পারবেন।",
      },
    ],
  },
  {
    id: "satz",
    bn: "বাক্যের কাঠামো",
    en: "Building a sentence",
    de: "Der Satz",
    teile: [
      {
        slug: "satzbau",
        bn: "বাক্যের ইঞ্জিন: ক্রিয়া দুই নম্বরে",
        en: "The verb sits in seat two",
        de: "Der Satzbau",
        icon: "engine",
        minutes: 8,
        blurb:
          "জার্মান বাক্যের একটাই আইন, আর সেটা শিখলে শব্দক্রমের অর্ধেক শেখা হয়ে যায়। সঙ্গে নয়জন কর্তা, বাংলার চেনা মুখসহ।",
      },
      {
        slug: "sein",
        bn: "sein: আমি হই",
        en: "sein, the hidden verb",
        de: "sein — ich bin",
        icon: "person",
        minutes: 9,
        blurb:
          "bin·bist·ist·sind·seid·sind। বাংলায় যে ক্রিয়াটা লুকিয়ে থাকে, জার্মানে সেটা বলতেই হয়। সঙ্গে nicht আর প্রশ্ন।",
      },
      {
        slug: "haben",
        bn: "haben: আমার আছে",
        en: "haben, and what you lack",
        de: "haben — ich habe",
        icon: "hand",
        minutes: 9,
        blurb:
          "পরিবার, জিনিস, সময়, খিদে: একটা ক্রিয়া সব বয়ে নেয়। আর 'নেই' বলার জার্মান অস্ত্র kein·keine।",
      },
    ],
  },
  {
    id: "woerter",
    bn: "শব্দ আর তার টুপি",
    en: "Words and their hats",
    de: "Die Wörter",
    teile: [
      {
        slug: "artikel",
        bn: "der · die · das: তিন টুপির রহস্য",
        en: "Every noun wears a hat",
        de: "Der Artikel",
        icon: "hat",
        minutes: 10,
        blurb:
          "ইংরেজি যেটা কখনো চায়নি। কেন চামচ der আর ছুরি das, তার কোনো যুক্তি নেই: রঙ দিয়ে মনে রাখুন। প্রথম ২৪টা শব্দ টুপিসহ।",
      },
      {
        slug: "verben",
        bn: "ক্রিয়া: এক মেশিন, ছয় পোশাক",
        en: "The endings machine",
        de: "Die Verben",
        icon: "gears",
        minutes: 10,
        blurb:
          "-e -st -t -en -t -en। এই একটা ছকে জার্মানের ৯০% ক্রিয়া চলে। সঙ্গে সারাদিনের ৩০টা ক্রিয়া আর রূপবদলকারীরা।",
      },
    ],
  },
  {
    id: "nein-frage",
    bn: "না বলা, প্রশ্ন করা",
    en: "Saying no, asking why",
    de: "Nein und Fragen",
    teile: [
      {
        slug: "negation",
        bn: "না বলার দুই অস্ত্র: nicht ও kein",
        en: "nicht vs kein",
        de: "Nein sagen",
        icon: "no",
        minutes: 7,
        blurb:
          "kein মারে বিশেষ্যকে, nicht মারে বাকি সব। কোনটা কখন, আর সবাই যে ছয়টা ভুল করে সেগুলো পাশাপাশি।",
      },
      {
        slug: "fragen",
        bn: "প্রশ্নের চাবি",
        en: "The seven question words",
        de: "Die Fragen",
        icon: "key",
        minutes: 8,
        blurb:
          "হ্যাঁ/না প্রশ্নে ক্রিয়া লাফ দিয়ে এক নম্বরে, কোনো do লাগে না। আর সাতটা W-চাবি, যা দিয়ে ভাষার প্রতিটা দরজা খোলে।",
      },
    ],
  },
  {
    id: "leben",
    bn: "ইচ্ছা, সংখ্যা, জীবন",
    en: "Wishes, numbers, real life",
    de: "Das echte Leben",
    teile: [
      {
        slug: "modalverben",
        bn: "möchte · kann · muss আর বিখ্যাত বন্ধনী",
        en: "The sentence bracket",
        de: "Die Modalverben",
        icon: "bracket",
        minutes: 10,
        blurb:
          "সাহায্যকারী দুই নম্বরে, আসল কাজ একদম শেষে। এটাই সবচেয়ে জার্মান জিনিস। সঙ্গে বেঁচে থাকার বাক্যগুলো।",
      },
      {
        slug: "zahlen-zeit",
        bn: "সংখ্যা, দিন ও ঘড়ি",
        en: "Numbers, days and the clock",
        de: "Zahlen & Zeit",
        icon: "clock",
        minutes: 8,
        blurb:
          "০ থেকে ১০০, আর সেই উল্টো প্যাঁচ: ২১ মানে 'এক-আর-বিশ'। সঙ্গে halb vier-এর ফাঁদ, যেটা মানে সাড়ে তিনটা।",
      },
      {
        slug: "satzbank",
        bn: "বাক্যব্যাংক: প্রথম সপ্তাহের কথা",
        en: "The sentence bank",
        de: "Die Satzbank",
        icon: "cup",
        minutes: 9,
        blurb:
          "পরিচয়, ঘর, ক্যাফে, বাজার, পথ আর বিপদ: প্রথম সপ্তাহে আপনি আসলে যে বাক্যগুলো বলবেন, চারটা তালিকায়।",
      },
    ],
  },
  {
    id: "eigene",
    bn: "নিজের ভাষা",
    en: "Your own words",
    de: "Von Herzen",
    teile: [
      {
        slug: "von-herzen",
        bn: "মন থেকে: এবার নিজের কথা",
        en: "Stop repeating, start creating",
        de: "Von Herzen",
        icon: "heart",
        minutes: 8,
        blurb:
          "পাঁচটা প্রশ্ন দিয়ে যেকোনো ছবি থেকে একটা অনুচ্ছেদ। নিজের দিনটা জার্মানে বলা, আর একা একা নিজের সাথে কথা বলার গোপন অস্ত্র।",
      },
      {
        slug: "plan",
        bn: "রোজকার এক ঘণ্টা ও ৩০ দিনের মানচিত্র",
        en: "The daily hour and the 30-day map",
        de: "Der Plan",
        icon: "map",
        minutes: 8,
        blurb:
          "দিনে এক ঘণ্টা কীভাবে ভাগ করবেন, ৩০ দিনে কোথায় পৌঁছাবেন, আর যে সাতটা ভুল সবাই করে তার ওষুধ।",
      },
    ],
  },
];

/* ------------------------------------------------------------
   THE LADDER — four Stufen.

   Stufe 1 is written. Stufen 2–4 are outlines: they are listed
   so a learner can see the whole road before starting one, and
   so the first day does not feel like a leap into fog. Their
   Teile carry status "soon" and get a proper "আসছে" page rather
   than a 404 — a listed thing must always be a place you can go.
   ------------------------------------------------------------ */
export const STUFEN = [
  {
    slug: "stufe-1",
    kicker: "Stufe 1",
    bn: "একদম শুরু থেকে",
    en: "Absolute beginner",
    de: "Der Anfang",
    icon: "seed",
    who: "যিনি জার্মানের একটা অক্ষরও চেনেন না, কিন্তু ইংরেজি একবার শিখে ফেলেছেন",
    blurb:
      "ধ্বনি থেকে শুরু, তারপর বাক্যের ইঞ্জিন, sein ও haben, তিন টুপি, ক্রিয়ার মেশিন, না-বলা, প্রশ্ন, বন্ধনী, সংখ্যা আর সত্যিকারের জীবনের বাক্য।",
    can:
      "৩০ দিন পরে: নিজের পরিচয় দিতে পারবেন, কিছু চাইতে পারবেন, প্রশ্ন করতে পারবেন, 'না' বলতে পারবেন, আর নিজের দিনটা জার্মানে বলতে পারবেন।",
    status: "live",
    workbook: { slug: "arbeitsbuch", days: 30 },
    sections: STUFE_1_SECTIONS,
  },

  {
    slug: "stufe-2",
    kicker: "Stufe 2",
    bn: "কারক ও অতীত",
    en: "Cases and the past",
    de: "Die Fälle",
    icon: "compass",
    who: "স্তর ১ শেষ, এখন বাক্যের ভেতরে কে কী করছে সেটা ঠিকভাবে বলতে চান",
    blurb:
      "den আর einen কেন আসে, dem আর der কোথা থেকে, আর কীভাবে গতকালের কথা বলতে হয়। স্তর ১-এ যেসব জিনিস 'তৈরি টুকরো' হিসেবে মুখস্থ করেছিলেন, এখানে সেগুলোর নিয়ম।",
    can: "শেষে: কে কাকে কী দিল সেটা বলতে পারবেন, জায়গা ও দিক আলাদা করতে পারবেন, আর গতকাল কী করেছেন সেটা বলতে পারবেন।",
    status: "soon",
    workbook: { slug: "arbeitsbuch", days: 30 },
    sections: [
      {
        id: "faelle",
        bn: "চার কারক",
        en: "The four cases",
        de: "Die vier Fälle",
        teile: [
          { slug: "akkusativ", bn: "Akkusativ: den ও einen", en: "The accusative", de: "Der Akkusativ", icon: "arrow", minutes: 10, status: "soon",
            blurb: "নীল দল বদলায়, বাকিরা বদলায় না। কর্ম হিসেবে বিশেষ্য কেমন দেখায়।" },
          { slug: "dativ", bn: "Dativ: dem, der, den", en: "The dative", de: "Der Dativ", icon: "hand", minutes: 12, status: "soon",
            blurb: "কাকে দিলাম, কার জন্য করলাম: তিন টুপিরই তৃতীয় চেহারা।" },
          { slug: "praepositionen", bn: "পূর্বসর্গ: in, auf, mit, zu", en: "Prepositions", de: "Die Präpositionen", icon: "map", minutes: 12, status: "soon",
            blurb: "কোন পূর্বসর্গ কোন কারক টানে, আর 'in der Küche' কেন der হলো।" },
          { slug: "possessiv", bn: "mein · dein · sein: আমার, তোমার", en: "Possessives", de: "Possessivartikel", icon: "person", minutes: 9, status: "soon",
            blurb: "kein-এর মতোই চলে, তাই একটা শিখলে আরেকটা বিনামূল্যে।" },
        ],
      },
      {
        id: "vergangenheit",
        bn: "গতকালের কথা",
        en: "Talking about yesterday",
        de: "Die Vergangenheit",
        teile: [
          { slug: "perfekt", bn: "Perfekt: ich habe gemacht", en: "The perfect tense", de: "Das Perfekt", icon: "clock", minutes: 12, status: "soon",
            blurb: "কথ্য জার্মানে অতীত মানেই এটা। haben না sein, সেটাই একমাত্র কঠিন প্রশ্ন।" },
          { slug: "trennbare-verben", bn: "ভাগ হওয়া ক্রিয়া: aufstehen", en: "Separable verbs", de: "Trennbare Verben", icon: "gears", minutes: 10, status: "soon",
            blurb: "'stehe … auf' — মাথাটা দুই নম্বরে, লেজটা বাক্যের শেষে।" },
          { slug: "plural", bn: "বহুবচনের পাঁচ পথ", en: "Making plurals", de: "Der Plural", icon: "hat", minutes: 10, status: "soon",
            blurb: "-e, -er, -n, -s আর উমলাউট। সুখবর: সব বহুবচনেই die।" },
        ],
      },
    ],
  },

  {
    slug: "stufe-3",
    kicker: "Stufe 3",
    bn: "কারণ, তুলনা ও গল্প",
    en: "Reasons, comparisons, stories",
    de: "Die Verbindung",
    icon: "scroll",
    who: "ছোট বাক্য হয়ে গেছে, এখন লম্বা কথা বলতে চান",
    blurb:
      "weil, dass, wenn দিয়ে বাক্য জোড়া দেওয়া, বিশেষণের লেজ, তুলনা, ভবিষ্যৎ, আর একটা গল্প শুরু থেকে শেষ পর্যন্ত বলা।",
    can: "শেষে: কেন কিছু করছেন সেটা ব্যাখ্যা করতে পারবেন, দুটো জিনিস তুলনা করতে পারবেন, আর একটা ঘটনা গুছিয়ে বলতে পারবেন।",
    status: "soon",
    workbook: { slug: "arbeitsbuch", days: 30 },
    sections: [
      {
        id: "nebensatz",
        bn: "বাক্য জোড়া দেওয়া",
        en: "Joining sentences",
        de: "Der Nebensatz",
        teile: [
          { slug: "weil-dass", bn: "weil · dass: ক্রিয়া একদম শেষে", en: "weil & dass", de: "Nebensätze", icon: "bracket", minutes: 12, status: "soon",
            blurb: "কারণ বলতে গেলে জার্মান ক্রিয়াকে বাক্যের শেষে পাঠিয়ে দেয়।" },
          { slug: "wenn-als", bn: "wenn · als: যখন", en: "wenn & als", de: "Zeitsätze", icon: "clock", minutes: 10, status: "soon",
            blurb: "একবারের 'যখন' আর বারবারের 'যখন' — জার্মানে দুটো আলাদা শব্দ।" },
          { slug: "relativsatz", bn: "যে লোকটা…: Relativsatz", en: "Relative clauses", de: "Der Relativsatz", icon: "key", minutes: 12, status: "soon",
            blurb: "der Mann, der … — টুপিটাই জোড়ার কাজ করে।" },
        ],
      },
      {
        id: "beschreiben",
        bn: "বর্ণনা ও তুলনা",
        en: "Describing and comparing",
        de: "Beschreiben",
        teile: [
          { slug: "adjektive", bn: "বিশেষণের লেজ", en: "Adjective endings", de: "Die Adjektive", icon: "hat", minutes: 14, status: "soon",
            blurb: "ein guter Mann, der gute Mann: কেন লেজটা বদলায়, ছকে নয় কানে।" },
          { slug: "vergleich", bn: "তুলনা: gut · besser · am besten", en: "Comparatives", de: "Der Vergleich", icon: "arrow", minutes: 9, status: "soon",
            blurb: "ইংরেজির চেয়ে সহজ, কারণ ব্যতিক্রম কম।" },
          { slug: "futur", bn: "ভবিষ্যৎ, আর কেন প্রায়ই লাগে না", en: "The future tense", de: "Das Futur", icon: "map", minutes: 8, status: "soon",
            blurb: "'কাল যাচ্ছি' বললেই চলে — werden লাগে কম।" },
        ],
      },
    ],
  },

  {
    slug: "stufe-4",
    kicker: "Stufe 4",
    bn: "মুক্তভাবে বলা",
    en: "Speaking freely",
    de: "Frei sprechen",
    icon: "mouth",
    who: "যিনি এখন মত দিতে, তর্ক করতে আর ভদ্রভাবে চিঠি লিখতে চান",
    blurb:
      "Konjunktiv II দিয়ে ভদ্রতা ও কল্পনা, কর্মবাচ্য, মতামত ও তর্কের কাঠামো, আনুষ্ঠানিক চিঠি ও ইমেইল, আর পরীক্ষার প্রস্তুতি।",
    can: "শেষে: নিজের মত যুক্তিসহ বলতে পারবেন, ভদ্রভাবে অনুরোধ ও অভিযোগ করতে পারবেন, আর একটা আনুষ্ঠানিক ইমেইল লিখতে পারবেন।",
    status: "soon",
    workbook: { slug: "arbeitsbuch", days: 30 },
    sections: [
      {
        id: "hoeflich",
        bn: "ভদ্রতা ও কল্পনা",
        en: "Politeness and what-if",
        de: "Höflichkeit",
        teile: [
          { slug: "konjunktiv", bn: "würde · könnte · hätte", en: "Konjunktiv II", de: "Der Konjunktiv II", icon: "heart", minutes: 12, status: "soon",
            blurb: "'পারতেন কি' — অনুরোধ, কল্পনা আর ভদ্রতার রূপ।" },
          { slug: "passiv", bn: "কর্মবাচ্য: werden", en: "The passive", de: "Das Passiv", icon: "gears", minutes: 10, status: "soon",
            blurb: "কে করেছে জানা না গেলে বা জরুরি না হলে।" },
        ],
      },
      {
        id: "ausdruecken",
        bn: "মত ও লেখা",
        en: "Opinion and writing",
        de: "Ausdrücken",
        teile: [
          { slug: "meinung", bn: "মত দেওয়া ও তর্ক করা", en: "Giving an opinion", de: "Die Meinung", icon: "mouth", minutes: 11, status: "soon",
            blurb: "একমত, দ্বিমত, উদাহরণ, উপসংহার — কথা বলার কাঠামো।" },
          { slug: "brief", bn: "আনুষ্ঠানিক চিঠি ও ইমেইল", en: "Formal letters & email", de: "Der Brief", icon: "scroll", minutes: 10, status: "soon",
            blurb: "Sehr geehrte Damen und Herren থেকে Mit freundlichen Grüßen পর্যন্ত।" },
          { slug: "pruefung", bn: "পরীক্ষা: A1 থেকে B1", en: "Sitting the exams", de: "Die Prüfung", icon: "cap", minutes: 12, status: "soon",
            blurb: "Goethe ও telc পরীক্ষায় আসলে কী দেখা হয়, আর কীভাবে প্রস্তুতি নেবেন।" },
        ],
      },
    ],
  },
];

/* ------------------------------------------------------------
   THE SCHOOL
   ------------------------------------------------------------ */
export const SCHOOL = {
  id: "deutsch",
  mount: "/deutsch/",
  bn: "জার্মান, বাংলায়",
  en: "German from Bangla",
  de: "Deutsch von Herzen",
  tagline: "শব্দ মুখস্থ নয় — কাঠামো। চার স্তর, রোজ একটা পাতা।",
};

/* ------------------------------------------------------------
   URLs and ids

   Nothing below assumes there are four Stufen or that Stufe 1 is
   the written one, so adding Stufe 5 is a matter of adding it to
   the array above and rerunning build-deutsch.mjs.
   ------------------------------------------------------------ */

/** A Stufe's folder URL. */
export const stufeUrl = (stufe) => `/deutsch/${stufe.slug}/index.html`;

/** A Teil's page URL. */
export const teilUrl = (stufe, teil) => `/deutsch/${stufe.slug}/${teil.slug}.html`;

/** A Stufe's practice book, or null.

    Null for a Stufe still marked "soon", even though the Stufe
    declares a workbook: the declaration is the plan, the page is
    the thing. Every caller links to whatever this returns, so
    letting it name a page that has not been generated is how a
    course ends up advertising a 404. */
export const workbookUrl = (stufe) =>
  stufe.workbook && stufe.status === "live"
    ? `/deutsch/${stufe.slug}/${stufe.workbook.slug}.html`
    : null;

/** Progress is stored per Teil under a stable id. */
export const teilId = (stufe, teil) => `${stufe.slug}/${teil.slug}`;

/** One day of a Stufe's workbook, as a progress id. */
export const dayId = (stufe, n) => `${stufe.slug}/tag-${n}`;

/** Teile of one Stufe, flattened, in order. */
export const stufeTeile = (stufe) =>
  stufe.sections.flatMap((section) =>
    section.teile.map((teil) => ({
      ...teil,
      stufe,
      section,
      id: teilId(stufe, teil),
      url: teilUrl(stufe, teil),
      status: teil.status ?? "live",
    }))
  );

/** Flat list of every Teil in the school. */
export const allTeile = () => STUFEN.flatMap(stufeTeile);

/** How many Teile a Stufe has, and how many are written. */
export const stufeCount = (stufe) => {
  const teile = stufeTeile(stufe);
  return { total: teile.length, live: teile.filter((t) => t.status === "live").length };
};

/** Total reading time of a Stufe, in minutes. */
export const stufeMinutes = (stufe) =>
  stufeTeile(stufe).reduce((sum, t) => sum + (t.minutes ?? 0), 0);

/** Find a Stufe by slug. */
export const findStufe = (slug) => STUFEN.find((s) => s.slug === slug);

/** Find a Teil (and its Stufe) from a URL path. */
export const findByPath = (path) =>
  allTeile().find((t) => t.url === path || t.url === `${path}.html`);
